"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { Activity, ArrowRight, Bot, CheckCircle2, FileClock, Fingerprint, LockKeyhole, RefreshCw, ShieldAlert, ShieldCheck, XCircle } from "lucide-react";
import { EnterprisePageHeader } from "@/components/enterprise/page-header";
import { MetricCard, SectionHeading, StatusPill } from "@/components/enterprise/dashboard";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";

interface AuditRecord { id: string; taskId: string; timestamp: string; actor: { id: string; role: string; type: string }; operation: { action: string; category: string; level: string; targetEntity: string; targetId?: string }; context: { dataSensitivity: string }; result: { status: string }; evidence: { summary: string; ai?: { agentCode?: string; agentName?: string } }; recordHash: string }
interface Agent { code: string; name: string; lifecycle: string; permissionMode: string }
interface Overview { generatedAt: string; role: string; summary: { total: number; success: number; denied: number; ai: number; security: number; p4p5: number }; categories: Array<{ category: string; count: number }>; levels: Array<{ level: string; count: number }>; recent: AuditRecord[]; agents: Agent[]; chain: { valid: boolean; total: number; headHash: string | null; verifiedAt: string; algorithm: string; storage: string }; compliance: { coverage: string; p4Evidence: string; updateDelete: string; retention: string } }
interface Envelope<T> { success: boolean; data?: T; error?: string }
const CATEGORY_LABELS: Record<string, string> = { AUTH: "身份认证", DATA_ACCESS: "数据访问", DATA_CHANGE: "数据变更", AI_OPERATION: "AI操作", PERMISSION: "权限变更", SYSTEM_CONFIG: "系统配置", SECURITY_EVENT: "安全事件", AI_WITHDRAW: "AI撤回", BUSINESS: "业务操作" };
const LEVEL_TONES: Record<string, "healthy" | "warning" | "danger" | "info" | "neutral"> = { INFO: "info", WARN: "warning", ERROR: "danger", SECURITY: "danger", CRITICAL: "danger" };
function authHeaders(): HeadersInit { const token = localStorage.getItem("token"); return token ? { Authorization: `Bearer ${token}` } : {}; }

export default function AuditCenterPage() {
  const [data, setData] = useState<Overview | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/audit-evidence/overview", { headers: authHeaders(), cache: "no-store" }); const body = await response.json() as Envelope<Overview>; if (!response.ok || !body.success || !body.data) throw new Error(body.error ?? "审计中心加载失败"); setData(body.data); } catch (reason) { setError(reason instanceof Error ? reason.message : "审计中心加载失败"); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  return <div className="space-y-6">
    <EnterprisePageHeader eyebrow="FULL-LINK AUDIT & EVIDENCE" title="全链路审计与法定证据中心" description="人类与Agent操作统一进入只追加证据链；保存操作者、前后值、九维权限上下文、P4最小证据、XAI摘要及SHA-256链式哈希。所有指标、Agent和事件均可下钻。" icon={ShieldCheck} badge="B3 · APPEND ONLY" actions={[{ label: "刷新证据", icon: RefreshCw, variant: "outline", onClick: () => void load(), disabled: loading }]} />
    {error && <div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700 dark:border-rose-900 dark:bg-rose-950/30 dark:text-rose-200">{error}</div>}
    {loading && !data && <div className="flex min-h-[360px] items-center justify-center text-sm text-muted-foreground"><RefreshCw className="mr-2 h-5 w-5 animate-spin text-blue-600" />正在验证证据链并加载角色授权数据…</div>}
    {data && <>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">
        <Link href="/audit-center/events"><MetricCard label="授权可见事件" value={data.summary.total.toString()} detail="进入完整事件流水" icon={Activity} tone="blue" /></Link>
        <Link href="/audit-center/events?outcome=SUCCESS"><MetricCard label="成功执行" value={data.summary.success.toString()} detail="含人工确认记录" icon={CheckCircle2} tone="emerald" /></Link>
        <Link href="/audit-center/events?outcome=DENIED"><MetricCard label="策略阻断" value={data.summary.denied.toString()} detail="查看拒绝与护栏证据" icon={XCircle} tone="amber" /></Link>
        <Link href="/audit-center/events?category=AI_OPERATION"><MetricCard label="AI/Agent证据" value={data.summary.ai.toString()} detail="模型、Skill与XAI快照" icon={Bot} tone="violet" /></Link>
        <Link href="/audit-center/events?level=SECURITY"><MetricCard label="安全级事件" value={data.summary.security.toString()} detail="SECURITY / CRITICAL" icon={ShieldAlert} tone="rose" /></Link>
        <Link href="/audit-center/events?sensitivity=high"><MetricCard label="P4/P5记录" value={data.summary.p4p5.toString()} detail="按最小必要原则取证" icon={LockKeyhole} tone="cyan" /></Link>
      </div>

      <div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]">
        <Card className="border-border shadow-sm"><CardHeader><SectionHeading title="审计类别覆盖" description="点击类别直接进入对应事件列表，不经过板块中转" /></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data.categories.map(item => <Link key={item.category} href={`/audit-center/events?category=${item.category}`} className="group rounded-xl border border-border bg-card p-4 transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md"><div className="flex items-center justify-between"><span className="rounded-lg bg-blue-50 px-2.5 py-1 text-[10px] font-semibold text-blue-700 dark:bg-blue-950/40 dark:text-blue-300">{item.category}</span><strong className="text-xl text-foreground">{item.count}</strong></div><div className="mt-4 flex items-center justify-between text-sm font-medium text-foreground"><span>{CATEGORY_LABELS[item.category] ?? item.category}</span><ArrowRight className="h-4 w-4 text-muted-foreground transition group-hover:translate-x-1 group-hover:text-blue-600" /></div></Link>)}</CardContent></Card>
        <Link href="/audit-center/integrity"><Card className={`h-full border-border shadow-sm transition hover:-translate-y-0.5 hover:shadow-md ${data.chain.valid ? "bg-gradient-to-br from-emerald-50/80 to-white dark:from-emerald-950/20 dark:to-card" : "bg-rose-50"}`}><CardHeader><SectionHeading title="证据链完整性" description="点击查看链式哈希、存储策略与校验结果" /></CardHeader><CardContent><div className="flex items-center gap-4"><span className={`flex h-14 w-14 items-center justify-center rounded-2xl ${data.chain.valid ? "bg-emerald-600 text-white" : "bg-rose-600 text-white"}`}><Fingerprint className="h-6 w-6" /></span><div><p className="text-2xl font-bold text-foreground">{data.chain.valid ? "完整" : "异常"}</p><p className="mt-1 text-xs text-muted-foreground">{data.chain.total} 个节点 · {data.chain.algorithm}</p></div></div><div className="mt-6 space-y-3 rounded-xl border border-border bg-card/80 p-4 text-xs"><Row label="存储模式" value="只追加 JSONL" /><Row label="链头哈希" value={data.chain.headHash ? `${data.chain.headHash.slice(0, 16)}…` : "暂无"} mono /><Row label="最近校验" value={new Date(data.chain.verifiedAt).toLocaleString("zh-CN")} /></div><p className="mt-4 flex items-center justify-end text-xs font-medium text-blue-700">进入完整性中心<ArrowRight className="ml-1 h-4 w-4" /></p></CardContent></Card></Link>
      </div>

      <Card className="border-border shadow-sm"><CardHeader><SectionHeading title={`${data.role} 专属Agent审计入口`} description="每张Agent卡片直接下钻到该Agent产生的审计证据；Agent权限始终取用户角色、Agent、工具、数据与护栏交集" /></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{data.agents.map((agent, index) => <Link key={agent.code} href={`/audit-center/events?agent=${encodeURIComponent(agent.code)}`} className="group rounded-xl border border-border p-4 transition hover:border-violet-300 hover:bg-violet-50/40 dark:hover:bg-violet-950/20"><div className="flex items-start justify-between"><span className="rounded-xl bg-violet-50 p-2.5 text-violet-700 dark:bg-violet-950/40 dark:text-violet-300"><Bot className="h-5 w-5" /></span><Badge variant="outline">AGENT {String(index + 1).padStart(2, "0")}</Badge></div><p className="mt-4 text-sm font-semibold text-foreground">{agent.name}</p><p className="mt-1 font-mono text-[9px] text-muted-foreground">{agent.code}</p><div className="mt-3 flex items-center justify-between text-[10px] text-muted-foreground"><span>已注册 · 角色交集权限</span><ArrowRight className="h-4 w-4 transition group-hover:translate-x-1 group-hover:text-violet-600" /></div></Link>)}</CardContent></Card>

      <Card className="overflow-hidden border-border shadow-sm"><CardHeader><SectionHeading title="最近审计事件" description="真实读取角色授权范围内的只追加证据；每一行均可打开独立详情页" action={<Link href="/audit-center/events"><Button variant="outline" size="sm">全部事件<ArrowRight className="ml-2 h-4 w-4" /></Button></Link>} /></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-y border-border bg-muted/50 text-[10px] uppercase tracking-wider text-muted-foreground"><tr><th className="px-5 py-3">事件 / 时间</th><th className="px-4 py-3">操作者</th><th className="px-4 py-3">操作对象</th><th className="px-4 py-3">级别</th><th className="px-4 py-3">结果</th><th className="px-5 py-3 text-right">证据</th></tr></thead><tbody>{data.recent.map(record => <tr key={record.id} className="border-b border-border last:border-0 hover:bg-muted/30"><td className="px-5 py-4"><p className="font-semibold text-foreground">{CATEGORY_LABELS[record.operation.category] ?? record.operation.category}</p><p className="mt-1 font-mono text-[9px] text-muted-foreground">{record.id}</p><p className="mt-1 text-[10px] text-muted-foreground">{new Date(record.timestamp).toLocaleString("zh-CN")}</p></td><td className="px-4 py-4"><p className="text-foreground">{record.actor.role}</p><p className="mt-1 text-[10px] text-muted-foreground">{record.actor.type} · {record.actor.id}</p></td><td className="px-4 py-4"><p className="font-medium text-foreground">{record.operation.action}</p><p className="mt-1 text-[10px] text-muted-foreground">{record.operation.targetEntity} · {record.operation.targetId ?? "-"} · {record.context.dataSensitivity}</p></td><td className="px-4 py-4"><StatusPill status={LEVEL_TONES[record.operation.level] ?? "neutral"} label={record.operation.level} /></td><td className="px-4 py-4"><StatusPill status={record.result.status === "DENIED" || record.result.status === "FAILURE" ? "danger" : "healthy"} label={record.result.status} /></td><td className="px-5 py-4 text-right"><Link href={`/audit-center/events/${record.id}`}><Button variant="ghost" size="sm">查看详情<ArrowRight className="ml-1 h-3.5 w-3.5" /></Button></Link></td></tr>)}</tbody></table></div></CardContent></Card>

      <Card className="border-border shadow-sm"><CardHeader><SectionHeading title="v2审计规范落实" description="不是展示性说明：以下策略由证据存储、接口权限与字段最小化程序实际执行" /></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Compliance icon={Activity} title="全覆盖" text={data.compliance.coverage} /><Compliance icon={LockKeyhole} title="P4最小证据" text={data.compliance.p4Evidence} /><Compliance icon={Fingerprint} title="不可修改" text={data.compliance.updateDelete} /><Compliance icon={FileClock} title="分级保留" text={data.compliance.retention} /></CardContent></Card>
    </>}
  </div>;
}
function Row({ label, value, mono = false }: { label: string; value: string; mono?: boolean }) { return <div className="flex items-center justify-between gap-4"><span className="text-muted-foreground">{label}</span><span className={`${mono ? "font-mono" : "font-medium"} text-foreground`}>{value}</span></div>; }
function Compliance({ icon: Icon, title, text }: { icon: typeof Activity; title: string; text: string }) { return <div className="rounded-xl border border-border p-4"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-200"><Icon className="h-4 w-4" /></span><p className="mt-3 text-sm font-semibold text-foreground">{title}</p><p className="mt-1 text-[11px] leading-5 text-muted-foreground">{text}</p></div>; }

