"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { AlertTriangle, ArrowLeft, CheckCircle2, Fingerprint, Loader2, ScanText, ShieldCheck } from "lucide-react";
import { EnterprisePageHeader } from "@/components/enterprise/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
interface Stage { code: string; name: string; status: string; detail: string }
interface Field { key: string; label: string; value: string; confidence: number; confirmed: boolean; source: string }
interface Payload { material: { id: string; applicationId?: string; name: string; mimeType: string; sizeBytes: number; sha256: string; uploadedAt: string }; processing: null | { id: string; status: string; parserAdapter: string; pageCount: number; extractedTextPreview: string; classification: { label: string; confidence: number }; extractedFields: Field[]; stages: Stage[]; version: number; confirmedAt?: string }; permission: { canConfirm: boolean; rawObjectDownload: boolean; reason: string } }
interface Envelope<T> { success: boolean; data?: T; error?: string; message?: string }
function headers(json = false): HeadersInit { const token = localStorage.getItem("token"); return { ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(json ? { "Content-Type": "application/json" } : {}) }; }
export default function MaterialProcessingDetailPage() {
  const params = useParams<{ id: string }>(); const id = String(params.id); const [data, setData] = useState<Payload | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [message, setMessage] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch(`/api/applications/materials/${encodeURIComponent(id)}`, { headers: headers(), cache: "no-store" }); const body = await response.json() as Envelope<Payload>; if (!response.ok || !body.success || !body.data) throw new Error(body.error ?? "材料解析详情加载失败"); setData(body.data); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "材料解析详情加载失败"); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  async function confirm() { setSubmitting(true); try { const response = await fetch(`/api/applications/materials/${encodeURIComponent(id)}/processing/actions`, { method: "POST", headers: headers(true), body: JSON.stringify({ action: "confirm", humanConfirmed: true }) }); const body = await response.json() as Envelope<unknown>; if (!response.ok || !body.success) throw new Error(body.error ?? "确认失败"); setMessage(body.message ?? "确认完成"); await load(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "确认失败"); } finally { setSubmitting(false); } }
  if (loading) return <div className="flex min-h-[60vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-blue-600" /></div>;
  if (error || !data) return <div className="enterprise-panel p-10 text-center"><AlertTriangle className="mx-auto h-8 w-8 text-rose-500" /><p className="mt-3">{error || "材料不存在"}</p></div>;
  const job = data.processing;
  return <div className="space-y-6 pb-10"><EnterprisePageHeader eyebrow="DOCUMENT PREPROCESSING PIPELINE" title="材料解析与人工确认" description="展示真实文件签名校验、恶意特征扫描、PDF文本抽取、版面分析、实体抽取和分类结果；系统不伪造无法识别的OCR文本。" icon={ScanText} badge={job?.status === "completed" ? "HITL CONFIRMED" : "REVIEW REQUIRED"} />
    <div className="flex flex-wrap items-center justify-between gap-3"><Button asChild variant="outline"><Link href={data.material.applicationId ? `/application/detail?id=${data.material.applicationId}` : "/application/create"}><ArrowLeft className="mr-2 h-4 w-4" />返回申请</Link></Button><div className="flex gap-2"><Badge variant="outline">{data.material.mimeType}</Badge><Badge variant="outline">{Math.ceil(data.material.sizeBytes / 1024)} KB</Badge></div></div>
    {message && <div className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-800">{message}</div>}
    <div className="grid gap-4 xl:grid-cols-[1fr_340px]"><div className="space-y-4"><Card><CardHeader><CardTitle className="text-base">预处理流水线</CardTitle></CardHeader><CardContent className="space-y-3">{job?.stages.map((stage) => <div key={stage.code} className="flex gap-3 rounded-xl border p-4"><span className={`mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg ${stage.status === "needs_confirmation" ? "bg-amber-50 text-amber-700" : stage.status === "blocked" ? "bg-rose-50 text-rose-700" : "bg-emerald-50 text-emerald-700"}`}>{stage.status === "needs_confirmation" ? <AlertTriangle className="h-4 w-4" /> : <CheckCircle2 className="h-4 w-4" />}</span><div><div className="flex items-center gap-2"><p className="text-sm font-semibold">{stage.name}</p><Badge variant="outline">{stage.status}</Badge></div><p className="mt-1 text-xs leading-5 text-muted-foreground">{stage.detail}</p></div></div>)}</CardContent></Card>
      <Card><CardHeader><CardTitle className="text-base">结构化实体（待确认区）</CardTitle></CardHeader><CardContent className="space-y-3">{job?.extractedFields.length ? job.extractedFields.map((field) => <div key={field.key} className="rounded-xl bg-muted/40 p-4"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold">{field.label}</p><Badge className={field.confidence < .7 ? "bg-amber-100 text-amber-800" : "bg-blue-100 text-blue-800"}>置信度 {(field.confidence * 100).toFixed(0)}%</Badge></div><p className="mt-2 text-sm">{field.value}</p><p className="mt-1 text-[10px] text-muted-foreground">{field.source} · {field.confirmed ? "已人工确认" : "尚未确认"}</p></div>) : <p className="py-8 text-center text-sm text-muted-foreground">未抽取到可安全展示的实体，保留人工核验。</p>}</CardContent></Card></div>
      <aside className="space-y-4"><Card><CardHeader><CardTitle className="text-base">文件证据</CardTitle></CardHeader><CardContent className="space-y-3"><Info label="材料名称" value={data.material.name} /><Info label="解析任务" value={job?.id ?? "未创建"} /><Info label="解析适配器" value={job?.parserAdapter ?? "—"} /><Info label="页数" value={`${job?.pageCount ?? 0}`} /><div className="rounded-xl bg-slate-950 p-3 font-mono text-[9px] leading-5 text-slate-300"><Fingerprint className="mb-2 h-4 w-4 text-cyan-300" />SHA256<br />{data.material.sha256}</div></CardContent></Card>
        <Card className="border-amber-200"><CardContent className="p-5"><ShieldCheck className="h-5 w-5 text-amber-700" /><p className="mt-3 text-xs leading-5 text-amber-900">{data.permission.reason}</p>{data.permission.canConfirm && <Button className="mt-4 w-full" onClick={() => void confirm()} disabled={submitting}>{submitting ? "确认中…" : "本人确认识别结果"}</Button>}{job?.status === "completed" && <div className="mt-4 flex items-center gap-2 rounded-lg bg-emerald-50 p-3 text-xs text-emerald-800"><CheckCircle2 className="h-4 w-4" />已完成预处理与人工回环</div>}</CardContent></Card>
        <Card><CardHeader><CardTitle className="text-base">文本预览</CardTitle></CardHeader><CardContent><p className="text-xs leading-6 text-muted-foreground">{job?.extractedTextPreview ?? "暂无文本"}</p></CardContent></Card></aside></div>
  </div>;
}
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-muted/40 p-3"><p className="text-[10px] text-muted-foreground">{label}</p><p className="mt-1 break-all text-xs font-medium">{value}</p></div>; }

