import { type NextRequest } from "next/server";
import { errorResponse, successResponse } from "@/lib/api-utils";
import { parseApplicationMutation, type ApplicationMutationBody } from "@/lib/platform/application-request";
import { bindMaterialProcessingJobs, buildApplicationPrecheck, createIntakeTicketId, enrichApplicationPrecheckWithAi, evaluateApplicationEligibility, findApplicationProject, processApplicationMaterial, registerIntakeTicket, saveApplicationEligibility, saveApplicationPrecheck, synchronizeIntakeTicket } from "@/lib/platform/application-intake-store";
import { getApplicationMaterialRecord, listApplicationMaterialRecords } from "@/lib/platform/application-material-store";
import { getVisibleApplication, listVisibleApplications, updateDemoApplicationDraft, writeAuditSnapshot } from "@/lib/platform/demo-store";
import { resolveRequestActor } from "@/lib/platform/request-actor";
export async function GET(request: NextRequest, context: { params: Promise<{ id: string }> }) {
  const actor = resolveRequestActor(request); if (!actor) return errorResponse("未完成身份认证", 401); if (actor.role !== "STUDENT") return errorResponse("只有学生本人可读取可编辑草稿", 403); const { id } = await context.params; const application = getVisibleApplication(actor, id);
  if (!application || !["草稿", "已退回补正"].includes(application.status)) return errorResponse("申请不存在或当前状态不可编辑", 404);
  const project = findApplicationProject(application.projectName); const materials = listApplicationMaterialRecords(application.id).map((record) => ({ ...record, processing: processApplicationMaterial(record) }));
  return successResponse({ application: { ...application, authorizationSources: [...(application.authorizationSources ?? [])], precheckWarnings: [...(application.precheckWarnings ?? [])] }, projectCode: project?.code ?? "", materials, editable: true });
}
export async function PATCH(request: NextRequest, context: { params: Promise<{ id: string }> }) {
  const actor = resolveRequestActor(request); if (!actor) return errorResponse("未完成身份认证", 401); if (actor.role !== "STUDENT") return errorResponse("只有学生本人可编辑申请草稿", 403); const idempotencyKey = request.headers.get("idempotency-key")?.trim(); if (!idempotencyKey || idempotencyKey.length < 8 || idempotencyKey.length > 100) return errorResponse("保存草稿必须提供有效的 Idempotency-Key");
  let body: ApplicationMutationBody; try { body = await request.json() as ApplicationMutationBody; } catch { return errorResponse("请求格式不正确"); } const parsed = parseApplicationMutation(body); if (!parsed.success) return errorResponse(parsed.error, parsed.status); if (!parsed.data.expectedVersion) return errorResponse("缺少有效的草稿数据版本号", 409);
  const { id } = await context.params; const current = getVisibleApplication(actor, id); if (!current || !["草稿", "已退回补正"].includes(current.status)) return errorResponse("申请不存在或当前状态不可编辑", 404);
  const allRecords = parsed.data.input.materialIds.map((materialId) => getApplicationMaterialRecord(materialId)); if (allRecords.some((record) => !record || record.ownerId !== actor.userId || (record.applicationId && record.applicationId !== id))) return errorResponse("材料不存在、已绑定其他申请或不属于当前用户", 409); if (allRecords.reduce((sum, record) => sum + (record?.sizeBytes ?? 0), 0) > 50 * 1024 * 1024) return errorResponse("单份申请材料总量不得超过50MB");
  const stagedIds = allRecords.filter((record) => record?.status === "staged").map((record) => record!.id); const allMaterialIds = allRecords.map((record) => record!.id);
  const eligibility = evaluateApplicationEligibility(actor, { project: parsed.data.projectCode, requestedAmount: parsed.data.input.requestedAmount, academicYear: parsed.data.input.academicYear, excludeApplicationId: id }, listVisibleApplications(actor));
  const evidenceCount = allMaterialIds.length + parsed.data.input.authorizationSources.length + (parsed.data.input.offlineReceiptNo ? 1 : 0); let precheck = buildApplicationPrecheck({ project: parsed.data.projectCode, materialIds: allMaterialIds, evidenceCount, waiverConfirmed: parsed.data.precheckWaiverConfirmed, applicationId: id });
  if (parsed.data.input.mode === "submit") precheck = await enrichApplicationPrecheckWithAi(precheck, { projectName: parsed.data.input.projectName, materialIds: allMaterialIds });
  if (parsed.data.input.mode === "submit" && !eligibility.allowed) return errorResponse(`资格校验未通过：${eligibility.checks.filter(item => item.status === "blocked").map(item => item.detail).join("；")}`, 409);
  if (parsed.data.input.mode === "submit" && precheck.blockers.length) return errorResponse(`材料预处理未完成：${precheck.blockers.join("；")}`, 409);
  if (parsed.data.input.mode === "submit" && precheck.requiresWaiver && !parsed.data.precheckWaiverConfirmed) return errorResponse(`材料预检提示：${precheck.warnings.join("；")}。如仍需提交，请勾选“已知悉并确认提交”。`, 409);
  const intakeTicketId = parsed.data.input.mode === "submit" ? current.intakeTicketId ?? createIntakeTicketId() : current.intakeTicketId;
  try {
    const result = updateDemoApplicationDraft(actor, { ...parsed.data.input, applicationId: id, idempotencyKey, expectedVersion: parsed.data.expectedVersion, materialIds: stagedIds, eligibilityReportId: eligibility.id, precheckReportId: parsed.data.input.mode === "submit" ? precheck.id : undefined, precheckScore: parsed.data.input.mode === "submit" ? precheck.score : undefined, precheckWarnings: parsed.data.input.mode === "submit" ? precheck.warnings : undefined, precheckWaiverConfirmed: parsed.data.input.mode === "submit" ? parsed.data.precheckWaiverConfirmed : undefined, intakeTicketId });
    if (!result.success || !result.application) return errorResponse(result.message, result.code === "VERSION_CONFLICT" ? 409 : result.code === "APPLICATION_NOT_FOUND" ? 404 : 403);
    eligibility.applicationId = id; saveApplicationEligibility(eligibility);
    bindMaterialProcessingJobs(stagedIds, id); let ticket = null;
    if (parsed.data.input.mode === "submit" && intakeTicketId) { saveApplicationPrecheck(precheck); writeAuditSnapshot({ taskId: precheck.id, actorId: actor.userId, actorRole: actor.role, action: "ai:application_material_precheck", outcome: precheck.aiAdvice?.status ?? "deterministic_only", evidenceSummary: `申请 ${id} 完成100%材料预检；规则评分 ${precheck.score}，AI状态 ${precheck.aiAdvice?.status ?? "not_run"}；仅输出建议，不形成拒绝或审批结论。`, resource: { type: "application", id, campusId: result.application.campusId, departmentId: result.application.departmentId, classId: result.application.classId, sensitivity: "P3", workflowState: result.application.status }, ai: { agentCode: "student-material-precheck-agent", agentName: "材料预检Agent", modelProvider: precheck.aiAdvice?.modelUsed ? "DeepSeek" : "deterministic-fallback", model: precheck.aiAdvice?.model, promptVersion: "application-precheck-v1", skillVersion: "material-completeness-v1", workflowVersion: "application-intake-v2", inputSummary: "脱敏项目清单、材料分类标签与确定性预检结果", outputSummary: precheck.aiAdvice?.summary ?? precheck.warnings.join("；"), xaiSummary: precheck.aiAdvice?.caution ?? precheck.disclaimer, advisoryOnly: true }, operationDetails: { modelUsed: Boolean(precheck.aiAdvice?.modelUsed), waiverConfirmed: precheck.waiverConfirmed, blockers: precheck.blockers.length, missingCount: precheck.missingCount } }); ticket = registerIntakeTicket({ id: intakeTicketId, applicationId: id, ownerId: result.application.ownerId, campusId: result.application.campusId, departmentId: result.application.departmentId, classId: result.application.classId, projectName: result.application.projectName, receiptNo: result.application.submissionReceiptNo ?? id, precheckReportId: precheck.id, priority: result.application.riskLevel === "高" ? "high" : "normal" }); if (current.status === "已退回补正") ticket = synchronizeIntakeTicket({ applicationId: id, action: "resubmit", fromStatus: "已退回补正", toStatus: result.application.status, actorId: actor.userId, actorRole: actor.role, comment: "学生已补充材料并确认预检提示，重新提交受理。" }); }
    writeAuditSnapshot({ taskId: eligibility.id, actorId: actor.userId, actorRole: actor.role, action: "application:eligibility_check", outcome: eligibility.allowed ? "passed" : "warning", evidenceSummary: `草稿 ${id} 资格确定性校验完成；报告 ${eligibility.id}。`, resource: { type: "application", id, campusId: result.application.campusId, departmentId: result.application.departmentId, classId: result.application.classId, sensitivity: "P2", workflowState: result.application.status }, after: { reportId: eligibility.id, allowed: eligibility.allowed, blockingCodes: eligibility.blockingCodes, warningCodes: eligibility.warningCodes }, operationDetails: { deterministicRules: true, modelUsed: false } });
    return successResponse({ ...result.application, eligibility, precheck: parsed.data.input.mode === "submit" ? precheck : null, intakeTicket: ticket }, result.message);
  } catch (reason) { if (reason instanceof Error && reason.message === "MATERIAL_NOT_FOUND_OR_ALREADY_CLAIMED") return errorResponse("部分新增材料不存在、已被其他申请绑定或不属于当前用户", 409); return errorResponse("草稿写入失败，请稍后重试", 500); }
}







