"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AppWindow, ArrowRight, Bot, CheckCircle2, CircleOff, CloudCog, Code2, Database, Download, FlaskConical, GitBranch, HardDrive, Loader2, MemoryStick, Network, Play, Plug, Plus, RefreshCw, Rocket, Search, ServerCog, ShieldCheck, Trash2, UploadCloud, Workflow } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { useHashTab } from "@/hooks/use-hash-tab";
import type { StudioIntegration, StudioSkill, StudioSnapshot, StudioWorkflow, WorkflowTemplate } from "@/lib/ai/studio-store";

type Envelope<T>={success:boolean;data?:T;error?:string;message?:string};
const initialSkill={name:"",slug:"",description:"",operation:"application_analysis" as const,riskLevel:"L1" as const};
const initialIntegration={type:"mcp" as const,name:"",description:"",endpoint:"mock://",authMode:"oauth2" as const,secretRef:"vault://",tools:""};
const initialMemory={name:"",description:"",scope:"role" as const,retentionDays:180};
const initialWorkflow:{name:string;description:string;template:WorkflowTemplate}={name:"",description:"",template:"analysis"};

export default function AiAssetStudioPage(){
 const{toast}=useToast();const[data,setData]=useState<StudioSnapshot|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[result,setResult]=useState<{title:string;value:unknown}|null>(null),[role,setRole]=useState("");
 const[tab,setTab]=useHashTab(["skills","integrations","memory","workflows"] as const,"skills");
 const[skillForm,setSkillForm]=useState(initialSkill),[integrationForm,setIntegrationForm]=useState(initialIntegration),[memoryForm,setMemoryForm]=useState(initialMemory),[workflowForm,setWorkflowForm]=useState(initialWorkflow);
 const[memoryInputs,setMemoryInputs]=useState<Record<string,{content:string;query:string}>>({});
 const headers=useCallback((json=true)=>{const token=localStorage.getItem("token");return{...(json?{"Content-Type":"application/json"}:{}),...(token?{Authorization:`Bearer ${token}`}:{})}},[]);
 const load=useCallback(async()=>{setLoading(true);try{const response=await fetch("/api/ai/studio",{headers:headers(false),cache:"no-store"});const payload=await response.json() as Envelope<StudioSnapshot>;if(!response.ok||!payload.success||!payload.data)throw new Error(payload.error??"AI资产工作室加载失败");setData(payload.data);try{const user=JSON.parse(localStorage.getItem("user")??"{}") as{role?:string;roles?:Array<{code?:string}>};setRole(user.role??user.roles?.[0]?.code??"")}catch{setRole("")}}catch(error){toast({title:"加载失败",description:error instanceof Error?error.message:"请稍后重试",variant:"destructive"})}finally{setLoading(false)}},[headers,toast]);
 useEffect(()=>{void load()},[load]);
 const manageable=role==="AI_OPS";
 async function post(title:string,body:Record<string,unknown>,key:string){setBusy(key);try{const response=await fetch("/api/ai/studio",{method:"POST",headers:{...headers(),"Idempotency-Key":`${key}-${Date.now()}-${crypto.randomUUID()}`},body:JSON.stringify(body)});const payload=await response.json() as Envelope<unknown>;if(!response.ok||!payload.success)throw new Error(payload.error??"操作失败");setResult({title,value:payload.data});toast({title,description:payload.message??"状态已更新并写入审计。"});await load();return true}catch(error){toast({title:`${title}失败`,description:error instanceof Error?error.message:"请稍后重试",variant:"destructive"});return false}finally{setBusy("")}}
 async function createSkill(){if(await post("创建 Skill",{action:"create_skill",...skillForm},"create-skill"))setSkillForm(initialSkill)}
 async function createIntegration(){if(await post(`创建 ${integrationForm.type.toUpperCase()}`,{action:"create_integration",...integrationForm,tools:integrationForm.tools.split(/[，,\n]/).map(item=>item.trim()).filter(Boolean)},"create-integration"))setIntegrationForm(initialIntegration)}
 async function createMemory(){if(await post("创建记忆空间",{action:"create_memory",...memoryForm},"create-memory"))setMemoryForm(initialMemory)}
 async function createWorkflow(){if(await post("创建工作流",{action:"create_workflow",...workflowForm},"create-workflow"))setWorkflowForm(initialWorkflow)}
 const stats=useMemo(()=>data?{installedSkills:data.skills.filter(item=>item.installed).length,activeIntegrations:data.integrations.filter(item=>item.enabled).length,memoryEntries:data.memories.reduce((sum,item)=>sum+item.entryCount,0),installedWorkflows:data.workflows.filter(item=>item.installed).length}:{installedSkills:0,activeIntegrations:0,memoryEntries:0,installedWorkflows:0},[data]);
 if(loading&&!data)return <Loading/>;
 if(!data)return <div className="enterprise-panel p-8 text-center"><CircleOff className="mx-auto h-8 w-8 text-rose-500"/><h1 className="mt-3 font-semibold">当前岗位无法访问 AI 资产工作室</h1><p className="mt-2 text-sm text-slate-500">请使用 AI 运维管理员账号进行资产管理。</p></div>;
 return <div className="space-y-6 pb-10">
  <section className="relative overflow-hidden rounded-[24px] bg-gradient-to-br from-[#071426] via-[#102b59] to-[#1646a2] px-6 py-7 text-white shadow-[0_24px_80px_rgba(10,46,116,.28)] lg:px-8"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_85%_20%,rgba(34,211,238,.25),transparent_30%)]"/><div className="relative flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex flex-wrap gap-2"><Badge className="border border-cyan-300/20 bg-cyan-300/10 text-cyan-100">AI ASSET STUDIO</Badge><Badge className="border border-white/10 bg-white/10 text-white">全生命周期可执行</Badge>{!data.capabilities.productionAdaptersConfigured&&<Badge className="border border-amber-300/20 bg-amber-300/10 text-amber-100">演示适配器</Badge>}</div><h1 className="mt-4 text-2xl font-bold tracking-tight lg:text-3xl">Skills、插件/MCP、记忆与工作流资产工作室</h1><p className="mt-3 max-w-4xl text-sm leading-6 text-blue-100/80">不是静态展示：支持创建、确定性校验、人工发布、安装启用和真实运行；每次变更都有版本、幂等键与审计证据。生产部署前仍需接入制品库、Vault、向量数据库和工作流执行集群。</p></div><Button variant="secondary" onClick={()=>void load()} disabled={loading} className="rounded-xl"><RefreshCw className={loading?"animate-spin":""}/>刷新资产运行态</Button></div></section>
  {!manageable&&<div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">当前为只读治理视图。依据职责分离原则，只有 AI 运维管理员可创建、发布、安装或运行 AI 资产。</div>}
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Code2} label="已安装 Skills" value={stats.installedSkills} detail={`${data.skills.length} 个资产版本`}/><Metric icon={Plug} label="已启用集成" value={stats.activeIntegrations} detail={`${data.integrations.length} 个插件/MCP`}/><Metric icon={MemoryStick} label="长期记忆条目" value={stats.memoryEntries} detail={`${data.memories.length} 个权限空间`}/><Metric icon={Workflow} label="已安装工作流" value={stats.installedWorkflows} detail={`${data.workflows.length} 个编排定义`}/></section>
  <Tabs value={tab} onValueChange={setTab} className="gap-5"><div className="overflow-x-auto"><TabsList className="h-12 min-w-max gap-1 rounded-2xl border border-slate-200 bg-white p-1 shadow-sm dark:border-slate-700 dark:bg-card"><TabsTrigger value="skills" className="h-10 rounded-xl px-4"><Code2/>Skills</TabsTrigger><TabsTrigger value="integrations" className="h-10 rounded-xl px-4"><Plug/>插件与 MCP</TabsTrigger><TabsTrigger value="memory" className="h-10 rounded-xl px-4"><MemoryStick/>记忆系统</TabsTrigger><TabsTrigger value="workflows" className="h-10 rounded-xl px-4"><GitBranch/>工作流编排</TabsTrigger></TabsList></div>
   <TabsContent value="skills" className="space-y-5"><CreateSkillPanel value={skillForm} onChange={setSkillForm} onCreate={createSkill} disabled={!manageable||busy==="create-skill"}/><div className="grid gap-4 xl:grid-cols-2">{data.skills.map(item=><SkillCard key={item.id} item={item} manageable={manageable} busy={busy} run={(action,humanConfirmed=false)=>post(`Skill ${actionLabel(action)}`,{action:"skill_action",id:item.id,lifecycleAction:action,expectedVersion:item.version,humanConfirmed},`skill-${item.id}-${action}`)}/>)}</div></TabsContent>
   <TabsContent value="integrations" className="space-y-5"><CreateIntegrationPanel value={integrationForm} onChange={setIntegrationForm} onCreate={createIntegration} disabled={!manageable||busy==="create-integration"}/><div className="grid gap-4 xl:grid-cols-2">{data.integrations.map(item=><IntegrationCard key={item.id} item={item} manageable={manageable} busy={busy} run={(action)=>post(`${item.type.toUpperCase()} ${actionLabel(action)}`,{action:"integration_action",id:item.id,lifecycleAction:action,expectedVersion:item.version,humanConfirmed:true,...(action==="call"?{tool:item.tools[0],arguments:{studentNo:"aggregate-demo"}}:{})},`integration-${item.id}-${action}`)}/>)}</div></TabsContent>
   <TabsContent value="memory" className="space-y-5"><CreateMemoryPanel value={memoryForm} onChange={setMemoryForm} onCreate={createMemory} disabled={!manageable||busy==="create-memory"}/><div className="grid gap-4 xl:grid-cols-2">{data.memories.map(item=>{const input=memoryInputs[item.id]??{content:"",query:""};return <Card key={item.id} className="rounded-2xl border-slate-200 shadow-sm dark:border-slate-700"><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2 text-base"><Database className="h-4 w-4 text-cyan-600"/>{item.name}</CardTitle><p className="mt-1 text-xs text-muted-foreground">{item.scope==="role"?"角色共享":"个人私有"} · {item.retentionDays} 天保留 · v{item.version}</p></div><Badge variant="outline">{item.entryCount} 条</Badge></div></CardHeader><CardContent className="space-y-4"><p className="text-sm leading-6 text-muted-foreground">{item.description}</p><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><p className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">最近记忆</p>{item.latestEntries.length?item.latestEntries.map(entry=><p key={entry.id} className="mt-2 line-clamp-2 text-xs leading-5 text-slate-600 dark:text-slate-300">{entry.content}</p>):<p className="mt-2 text-xs text-slate-400">暂无记忆条目</p>}</div><div className="space-y-2"><Label>写入经人工确认的经验</Label><Textarea value={input.content} onChange={event=>setMemoryInputs({...memoryInputs,[item.id]:{...input,content:event.target.value}})} placeholder="例如：一次成功处置模式或失败教训（不应包含敏感个人信息）"/><Button disabled={!manageable||!input.content.trim()||busy===`memory-write-${item.id}`} onClick={()=>void post("写入长期记忆",{action:"memory_write",namespaceId:item.id,content:input.content,tags:["人工确认","工作台录入"],sensitivity:"P1",source:"ai-studio-ui"},`memory-write-${item.id}`).then(ok=>ok&&setMemoryInputs({...memoryInputs,[item.id]:{...input,content:""}}))} className="rounded-xl"><HardDrive/>向量化并写入</Button></div><div className="space-y-2 border-t border-slate-100 pt-4 dark:border-slate-700"><Label>语义召回测试</Label><div className="flex gap-2"><Input value={input.query} onChange={event=>setMemoryInputs({...memoryInputs,[item.id]:{...input,query:event.target.value}})} placeholder="输入检索问题"/><Button variant="outline" disabled={!input.query.trim()||busy===`memory-search-${item.id}`} onClick={()=>void post("检索长期记忆",{action:"memory_search",namespaceId:item.id,query:input.query,topK:5},`memory-search-${item.id}`)}><Search/></Button></div></div></CardContent></Card>})}</div></TabsContent>
   <TabsContent value="workflows" className="space-y-5"><CreateWorkflowPanel value={workflowForm} onChange={setWorkflowForm} onCreate={createWorkflow} disabled={!manageable||busy==="create-workflow"}/><div className="space-y-4">{data.workflows.map(item=><WorkflowCard key={item.id} item={item} manageable={manageable} busy={busy} run={(action,humanConfirmed=false)=>post(`工作流${actionLabel(action)}`,{action:"workflow_action",id:item.id,lifecycleAction:action,expectedVersion:item.version,humanConfirmed},`workflow-${item.id}-${action}`)}/>)}</div></TabsContent>
  </Tabs>
  {result&&<section className="rounded-2xl border border-slate-200 bg-slate-950 p-5 text-slate-100 shadow-xl"><div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold tracking-[.16em] text-cyan-400">LAST EXECUTION RESULT</p><h2 className="mt-1 text-sm font-semibold">{result.title}</h2></div><button onClick={()=>setResult(null)} className="rounded-lg p-2 text-slate-500 hover:bg-white/5 hover:text-white" aria-label="关闭结果"><CircleOff className="h-4 w-4"/></button></div><pre className="mt-4 max-h-80 overflow-auto rounded-xl bg-black/30 p-4 text-[11px] leading-5 text-emerald-200">{JSON.stringify(result.value,null,2)}</pre></section>}
 </div>
}

function CreateShell({icon:Icon,title,description,children,onCreate,disabled}:{icon:typeof Plus;title:string;description:string;children:React.ReactNode;onCreate:()=>void;disabled:boolean}){return <Card className="rounded-[22px] border-dashed border-blue-200 bg-blue-50/40 shadow-none dark:border-blue-900 dark:bg-blue-950/20"><CardContent className="p-5 lg:p-6"><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-600 text-white"><Icon className="h-4 w-4"/></span><div><h2 className="text-sm font-semibold">{title}</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">{description}</p></div></div><div className="mt-5 grid gap-3 lg:grid-cols-4">{children}</div><Button onClick={onCreate} disabled={disabled} className="mt-4 rounded-xl"><Plus/>{disabled?"无管理权限或处理中":"创建草稿"}</Button></CardContent></Card>}
function CreateSkillPanel({value,onChange,onCreate,disabled}:{value:typeof initialSkill;onChange:(v:typeof initialSkill)=>void;onCreate:()=>void;disabled:boolean}){return <CreateShell icon={Code2} title="创建新 Skill" description="Skill 采用声明式能力与允许操作绑定，不能携带任意 Shell；创建后需依次通过沙盒、发布和安装。" onCreate={onCreate} disabled={disabled}><Field label="名称"><Input value={value.name} onChange={e=>onChange({...value,name:e.target.value})} placeholder="如：资格一致性分析"/></Field><Field label="英文标识"><Input value={value.slug} onChange={e=>onChange({...value,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"")})} placeholder="qualification-analysis"/></Field><Field label="能力绑定"><NativeSelect value={value.operation} onChange={operation=>onChange({...value,operation:operation as typeof value.operation})} options={[['application_analysis','申请态势分析'],['monthly_report','月报草稿'],['risk_summary','风险摘要']]}/></Field><Field label="风险等级"><NativeSelect value={value.riskLevel} onChange={riskLevel=>onChange({...value,riskLevel:riskLevel as typeof value.riskLevel})} options={[['L1','L1 只读'],['L2','L2 生成草稿']]}/></Field><div className="lg:col-span-4"><Field label="功能说明"><Textarea value={value.description} onChange={e=>onChange({...value,description:e.target.value})} placeholder="说明输入、输出、边界和禁止事项"/></Field></div></CreateShell>}
function CreateIntegrationPanel({value,onChange,onCreate,disabled}:{value:typeof initialIntegration;onChange:(v:typeof initialIntegration)=>void;onCreate:()=>void;disabled:boolean}){return <CreateShell icon={Plug} title="注册插件或 MCP Server" description="只保存 Vault 凭据引用；端点需先完成握手和工具发现，再由人工发布、安装和启用。" onCreate={onCreate} disabled={disabled}><Field label="类型"><NativeSelect value={value.type} onChange={type=>onChange({...value,type:type as typeof value.type})} options={[['mcp','MCP Server'],['plugin','业务插件']]}/></Field><Field label="名称"><Input value={value.name} onChange={e=>onChange({...value,name:e.target.value})} placeholder="如：学工系统 MCP"/></Field><Field label="端点"><Input value={value.endpoint} onChange={e=>onChange({...value,endpoint:e.target.value})} placeholder="mock://system/mcp"/></Field><Field label="凭据引用"><Input value={value.secretRef} onChange={e=>onChange({...value,secretRef:e.target.value})} placeholder="vault://mcp/system"/></Field><Field label="允许工具（逗号分隔）"><Input value={value.tools} onChange={e=>onChange({...value,tools:e.target.value})} placeholder="student.read, status.verify"/></Field><div className="lg:col-span-3"><Field label="功能说明"><Input value={value.description} onChange={e=>onChange({...value,description:e.target.value})} placeholder="连接范围、用途及禁止操作"/></Field></div></CreateShell>}
function CreateMemoryPanel({value,onChange,onCreate,disabled}:{value:typeof initialMemory;onChange:(v:typeof initialMemory)=>void;onCreate:()=>void;disabled:boolean}){return <CreateShell icon={MemoryStick} title="创建长期记忆空间" description="记忆按个人或角色隔离，写入时生成向量并设置到期时间；P2 数据不能进入角色共享记忆。" onCreate={onCreate} disabled={disabled}><Field label="空间名称"><Input value={value.name} onChange={e=>onChange({...value,name:e.target.value})} placeholder="如：材料审核经验"/></Field><Field label="权限范围"><NativeSelect value={value.scope} onChange={scope=>onChange({...value,scope:scope as typeof value.scope})} options={[['role','角色共享'],['private','个人私有']]}/></Field><Field label="保留周期"><NativeSelect value={String(value.retentionDays)} onChange={retentionDays=>onChange({...value,retentionDays:Number(retentionDays)})} options={[['30','30 天'],['90','90 天'],['180','180 天'],['365','365 天']]}/></Field><Field label="说明"><Input value={value.description} onChange={e=>onChange({...value,description:e.target.value})} placeholder="用途、来源和清理策略"/></Field></CreateShell>}
function CreateWorkflowPanel({value,onChange,onCreate,disabled}:{value:typeof initialWorkflow;onChange:(v:typeof initialWorkflow)=>void;onCreate:()=>void;disabled:boolean}){return <CreateShell icon={Workflow} title="创建可编排工作流" description="根据模板生成真实 DAG，发布前校验节点、环路和人工确认门；安装后才能运行。" onCreate={onCreate} disabled={disabled}><Field label="工作流名称"><Input value={value.name} onChange={e=>onChange({...value,name:e.target.value})} placeholder="如：周度风险分析"/></Field><Field label="编排模板"><NativeSelect value={value.template} onChange={template=>onChange({...value,template:template as typeof value.template})} options={[['analysis','数据分析（L1）'],['reminder','智能催办（L3）'],['knowledge_feedback','反馈学习（L2）'],['temporary_hardship_grant','临时困难补助全链路（L3）']]}/></Field><div className="lg:col-span-2"><Field label="业务说明"><Input value={value.description} onChange={e=>onChange({...value,description:e.target.value})} placeholder="说明触发条件、业务目标和人工责任"/></Field></div></CreateShell>}

function SkillCard({item,manageable,busy,run}:{item:StudioSkill;manageable:boolean;busy:string;run:(action:"sandbox"|"publish"|"install"|"uninstall"|"run",confirmed?:boolean)=>Promise<boolean>}){return <Card className="rounded-2xl border-slate-200 shadow-sm dark:border-slate-700"><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2 text-base"><Code2 className="h-4 w-4 text-blue-600"/>{item.name}</CardTitle><p className="mt-1 font-mono text-[10px] text-slate-400">{item.slug} · v{item.version}</p></div><Status status={item.status}/></div></CardHeader><CardContent><p className="text-sm leading-6 text-muted-foreground">{item.description}</p><div className="mt-4 grid grid-cols-3 gap-2"><Small label="风险" value={item.riskLevel}/><Small label="沙盒" value={item.sandbox.status}/><Small label="运行" value={item.runs}/></div>{item.sandbox.checks.length>0&&<div className="mt-3 flex flex-wrap gap-1">{item.sandbox.checks.map(check=><Badge key={check} variant="secondary" className="text-[10px]"><CheckCircle2 className="h-3 w-3 text-emerald-600"/>{check}</Badge>)}</div>}<div className="mt-4 flex flex-wrap gap-2">{item.status==="draft"&&<Action icon={FlaskConical} label="运行沙盒" onClick={()=>run("sandbox")} disabled={!manageable||busy.includes(item.id)}/>} {item.status==="validated"&&<Action icon={UploadCloud} label="人工确认发布" onClick={()=>run("publish",true)} disabled={!manageable||busy.includes(item.id)}/>} {item.status==="published"&&!item.installed&&<Action icon={Download} label="安装" onClick={()=>run("install")} disabled={!manageable||busy.includes(item.id)}/>} {item.installed&&<><Action icon={Play} label="运行 Skill" onClick={()=>run("run")} disabled={!manageable||busy.includes(item.id)}/><Action icon={Trash2} label="卸载" variant="outline" onClick={()=>run("uninstall")} disabled={!manageable||busy.includes(item.id)}/></>}</div></CardContent></Card>}
function IntegrationCard({item,manageable,busy,run}:{item:StudioIntegration;manageable:boolean;busy:string;run:(action:"test"|"publish"|"install"|"enable"|"disable"|"call")=>Promise<boolean>}){const Icon=item.type==="mcp"?Network:AppWindow;return <Card className="rounded-2xl border-slate-200 shadow-sm dark:border-slate-700"><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2 text-base"><Icon className="h-4 w-4 text-violet-600"/>{item.name}</CardTitle><p className="mt-1 font-mono text-[10px] text-slate-400">{item.type.toUpperCase()} · v{item.version} · {item.endpoint}</p></div><Status status={item.status}/></div></CardHeader><CardContent><p className="text-sm leading-6 text-muted-foreground">{item.description}</p><div className="mt-4 grid grid-cols-3 gap-2"><Small label="健康" value={item.health}/><Small label="启用" value={item.enabled?"是":"否"}/><Small label="调用" value={item.calls}/></div><div className="mt-3 flex flex-wrap gap-1">{item.tools.map(tool=><Badge key={tool} variant="outline" className="font-mono text-[10px]">{tool}</Badge>)}</div><p className="mt-3 font-mono text-[10px] text-slate-400">{item.secretRef??"无需凭据"}</p><div className="mt-4 flex flex-wrap gap-2">{item.status==="draft"&&<Action icon={CloudCog} label="握手测试" onClick={()=>run("test")} disabled={!manageable||busy.includes(item.id)}/>} {item.status==="validated"&&<Action icon={Rocket} label="人工发布" onClick={()=>run("publish")} disabled={!manageable||busy.includes(item.id)}/>} {item.status==="published"&&!item.installed&&<Action icon={Download} label="安装" onClick={()=>run("install")} disabled={!manageable||busy.includes(item.id)}/>} {item.installed&&!item.enabled&&<Action icon={ServerCog} label="启用" onClick={()=>run("enable")} disabled={!manageable||busy.includes(item.id)}/>} {item.enabled&&<><Action icon={Play} label="调用首个工具" onClick={()=>run("call")} disabled={!manageable||busy.includes(item.id)}/><Action icon={CircleOff} label="停用" variant="outline" onClick={()=>run("disable")} disabled={!manageable||busy.includes(item.id)}/></>}</div></CardContent></Card>}
function WorkflowCard({item,manageable,busy,run}:{item:StudioWorkflow;manageable:boolean;busy:string;run:(action:"validate"|"publish"|"install"|"uninstall"|"run",confirmed?:boolean)=>Promise<boolean>}){return <Card className="rounded-2xl border-slate-200 shadow-sm dark:border-slate-700"><CardHeader><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><CardTitle className="flex items-center gap-2 text-base"><GitBranch className="h-4 w-4 text-emerald-600"/>{item.name}</CardTitle><p className="mt-1 text-xs text-muted-foreground">{item.template} · {item.riskLevel} · v{item.version} · 已运行 {item.runs} 次</p></div><Status status={item.status}/></div></CardHeader><CardContent><p className="text-sm leading-6 text-muted-foreground">{item.description}</p><div className="mt-4 overflow-x-auto"><div className="flex min-w-max items-center gap-2">{item.nodes.map((node,index)=><div key={node.id} className="flex items-center gap-2"><div className={`rounded-xl border px-3 py-2 ${node.type==="human_gate"?"border-amber-200 bg-amber-50 text-amber-800":"border-slate-200 bg-slate-50 text-slate-700 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200"}`}><p className="text-[9px] uppercase text-slate-400">{node.type}</p><p className="mt-0.5 text-xs font-medium">{node.name}</p></div>{index<item.nodes.length-1&&<ArrowRight className="h-4 w-4 text-slate-300"/>}</div>)}</div></div>{item.lastRun&&<div className="mt-4 rounded-xl border border-emerald-100 bg-emerald-50/60 p-3 dark:border-emerald-900 dark:bg-emerald-950/20"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-emerald-800 dark:text-emerald-300">最近运行：{item.lastRun.status}</p><span className="text-[10px] text-slate-400">{item.lastRun.steps.length} 步</span></div><p className="mt-1 text-[10px] text-slate-500">{item.lastRun.steps.map(step=>step.name).join(" → ")}</p></div>}<div className="mt-4 flex flex-wrap gap-2">{item.status==="draft"&&<Action icon={ShieldCheck} label="校验 DAG 与护栏" onClick={()=>run("validate")} disabled={!manageable||busy.includes(item.id)}/>} {item.status==="validated"&&<Action icon={UploadCloud} label="人工发布" onClick={()=>run("publish",true)} disabled={!manageable||busy.includes(item.id)}/>} {item.status==="published"&&!item.installed&&<Action icon={Download} label="安装工作流" onClick={()=>run("install")} disabled={!manageable||busy.includes(item.id)}/>} {item.installed&&<><Action icon={Play} label={item.riskLevel==="L3"?"人工确认并运行":"运行工作流"} onClick={()=>run("run",item.riskLevel==="L3")} disabled={!manageable||busy.includes(item.id)}/><Action icon={Trash2} label="卸载" variant="outline" onClick={()=>run("uninstall")} disabled={!manageable||busy.includes(item.id)}/></>}</div></CardContent></Card>}

function Metric({icon:Icon,label,value,detail}:{icon:typeof Bot;label:string;value:number;detail:string}){return <Card className="rounded-2xl border-slate-200 shadow-sm dark:border-slate-700"><CardContent className="flex items-center gap-4 p-5"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-blue-50 text-blue-700 dark:bg-blue-500/10 dark:text-blue-300"><Icon className="h-5 w-5"/></span><div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-bold">{value}</p><p className="mt-1 text-[10px] text-slate-400">{detail}</p></div></CardContent></Card>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
function NativeSelect({value,onChange,options}:{value:string;onChange:(value:string)=>void;options:Array<[string,string]>}){return <select value={value} onChange={e=>onChange(e.target.value)} className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm outline-none focus:border-ring focus:ring-2 focus:ring-ring/20">{options.map(([v,label])=><option key={v} value={v}>{label}</option>)}</select>}
function Small({label,value}:{label:string;value:string|number}){return <div className="rounded-xl bg-slate-50 p-2.5 text-center dark:bg-slate-900"><p className="text-xs font-semibold">{value}</p><p className="mt-1 text-[9px] text-slate-400">{label}</p></div>}
function Status({status}:{status:string}){const style=status==="installed"?"bg-emerald-100 text-emerald-700":status==="published"?"bg-blue-100 text-blue-700":status==="validated"?"bg-violet-100 text-violet-700":"bg-slate-100 text-slate-600";return <Badge className={style}>{status}</Badge>}
function Action({icon:Icon,label,onClick,disabled,variant="default"}:{icon:typeof Play;label:string;onClick:()=>void;disabled:boolean;variant?:"default"|"outline"}){return <Button size="sm" variant={variant} onClick={onClick} disabled={disabled} className="rounded-lg">{disabled&&label.includes("处理")?<Loader2 className="animate-spin"/>:<Icon/>}{label}</Button>}
function Loading(){return <div className="flex min-h-[60vh] items-center justify-center"><div className="text-center"><Loader2 className="mx-auto h-8 w-8 animate-spin text-blue-600"/><p className="mt-3 text-sm text-slate-500">正在加载 AI 资产注册中心...</p></div></div>}
function actionLabel(action:string){return({sandbox:"沙盒测试",publish:"发布",install:"安装",uninstall:"卸载",run:"运行",test:"握手测试",enable:"启用",disable:"停用",call:"工具调用",validate:"校验"} as Record<string,string>)[action]??action}

