import { type NextRequest } from "next/server";
import { errorResponse, successResponse } from "@/lib/api-utils";
import { buildMonthlyFundingReport, listVisibleApplications, writeAuditSnapshot } from "@/lib/platform/demo-store";
import { resolveRequestActor } from "@/lib/platform/request-actor";
const ROLES = ["SCHOOL_LEADER","FUND_LEADER","STU_AFFAIRS","FUND_ADMIN","FINANCE","DEPT_ADMIN","EDU_BUREAU","AUDITOR","AUDIT_EXTERNAL","PUBLIC_OPINION"] as const;

function csvCell(value: unknown){const text=String(value??"");return /[",\n]/.test(text)?`"${text.replaceAll('"','""')}"`:text}
export async function GET(request:NextRequest){const actor=resolveRequestActor(request);if(!actor)return errorResponse("未完成身份认证",401);if(!(ROLES as readonly string[]).includes(actor.role))return errorResponse("当前岗位无报表导出权限",403);const report=buildMonthlyFundingReport(actor);return successResponse({generatedAt:new Date().toISOString(),summary:report,templates:[{id:"status-summary",name:"申请状态汇总",classification:"P1",formats:["csv","json"]},{id:"project-summary",name:"项目金额汇总",classification:"P1",formats:["csv","json"]}],controls:["按当前角色数据范围聚合","不导出学生个人明细","生成水印编号与审计证据","幂等防止重复任务"]})}
export async function POST(request:NextRequest){const actor=resolveRequestActor(request);if(!actor)return errorResponse("未完成身份认证",401);if(!(ROLES as readonly string[]).includes(actor.role))return errorResponse("当前岗位无报表导出权限",403);const key=request.headers.get("idempotency-key")?.trim();if(!key||key.length<8)return errorResponse("导出必须提供有效Idempotency-Key");let body:{templateId?:unknown;format?:unknown};try{body=await request.json()}catch{return errorResponse("请求格式不正确")};const templateId=body.templateId==="project-summary"?"project-summary":body.templateId==="status-summary"?"status-summary":null,format=body.format==="json"?"json":body.format==="csv"?"csv":null;if(!templateId||!format)return errorResponse("导出模板或格式无效");const apps=listVisibleApplications(actor),watermark=`EXP-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${key.slice(-8).toUpperCase()}`;let rows:Array<Record<string,unknown>>;if(templateId==="status-summary"){const counts=apps.reduce<Record<string,{count:number;amount:number}>>((r,item)=>{const v=r[item.status]??{count:0,amount:0};v.count++;v.amount+=item.requestedAmount;r[item.status]=v;return r},{});rows=Object.entries(counts).map(([status,value])=>({status,count:value.count,amount:value.amount}))}else{const projects=apps.reduce<Record<string,{count:number;amount:number}>>((r,item)=>{const v=r[item.projectName]??{count:0,amount:0};v.count++;v.amount+=item.requestedAmount;r[item.projectName]=v;return r},{});rows=Object.entries(projects).map(([project,value])=>({project,count:value.count,amount:value.amount}))}const content=format==="json"?JSON.stringify({watermark,generatedAt:new Date().toISOString(),role:actor.role,rows},null,2):[Object.keys(rows[0]??{status:"",count:"",amount:""}).join(","),...rows.map(row=>Object.values(row).map(csvCell).join(",")),`水印,${watermark}`].join("\n");writeAuditSnapshot({taskId:watermark,actorId:actor.userId,actorRole:actor.role,action:"data:export_report",outcome:"success",evidenceSummary:`生成${templateId}聚合报表，格式${format.toUpperCase()}，${rows.length}行；不含学生个人明细；水印${watermark}。`,resource:{type:"aggregate_report",id:watermark,campusId:actor.campusIds[0],sensitivity:"P1"},operationDetails:{templateId,format,rowCount:rows.length,aggregateOnly:true,watermark},after:{fileName:`${templateId}_${watermark}.${format}`,rowCount:rows.length,watermark},context:{purpose:"授权范围聚合报表导出"}});return successResponse({fileName:`${templateId}_${watermark}.${format}`,mimeType:format==="csv"?"text/csv;charset=utf-8":"application/json;charset=utf-8",content,watermark,rowCount:rows.length},"报表已生成并写入审计")}

