import type { NextRequest } from "next/server";
import { errorResponse, successResponse } from "@/lib/api-utils";
import { canAccessAuditCenter, listAuditEvidence } from "@/lib/platform/audit-evidence-store";
import { getApplicationEligibility, getApplicationPrecheck, getMaterialProcessingJob, getVisibleIntakeTicket } from "@/lib/platform/application-intake-store";
import { listApplicationMaterialRecords } from "@/lib/platform/application-material-store";
import { getVisibleApplication, type ApplicationAction, type ApplicationStatus } from "@/lib/platform/demo-store";
import { resolveRequestActor } from "@/lib/platform/request-actor";
import { getHardshipVideoMaterialProjections } from "@/lib/platform/hardship-video-business-store";
import { getHardshipVideoReviewProjections } from "@/lib/platform/hardship-video-review-store";
import { getHardshipVideoFinanceProjection } from "@/lib/platform/hardship-video-disbursement-store";
import { ROLE_PROFILES } from "@/lib/platform/roles";

const departments: Record<string, string> = { "dept-agri": "农学院", "dept-engineering": "工程学院", "dept-humanities": "人文学院", "dept-unassigned": "未分配院系" };
const stages = ["填写与材料提交", "辅导员初审", "院系复核", "校级复审", "校领导审批", "财务发放", "银行回盘与对账"];
const stageByStatus: Record<ApplicationStatus, number> = { "草稿": 0, "待辅导员初审": 1, "待院系复核": 2, "待校级复审": 3, "待领导审批": 4, "待公示": 4, "公示中": 4, "待发放": 5, "已完成": 7, "已退回补正": 1, "已驳回": 3, "申诉处理中": 3 };
const sourceLabels: Record<string, string> = { "student-status": "学籍状态授权核验", "low-income-registry": "低收入人口信息授权核验", "disability-registry": "残疾信息授权核验", "grade-transcript": "成绩单授权核验" };
interface AllowedAction { action: ApplicationAction; label: string; tone: "primary" | "warning" | "danger" }
function actions(role: string, status: ApplicationStatus): AllowedAction[] { const item = (action: ApplicationAction, label: string, tone: AllowedAction["tone"] = "primary") => ({ action, label, tone }); if (role === "STUDENT" && status === "草稿") return []; if (role === "COUNSELOR" && status === "待辅导员初审") return [item("approve", "初审通过"), item("return", "退回补正", "warning")]; if (role === "DEPT_ADMIN" && status === "待院系复核") return [item("approve", "院系复核通过"), item("return", "退回补正", "warning")]; if (["FUND_ADMIN", "FUND_LEADER"].includes(role) && status === "待校级复审") return [item("approve", "校级复审通过"), item("return", "退回补正", "warning"), ...(role === "FUND_LEADER" ? [item("reject", "驳回申请", "danger")] : [])]; if (role === "FUND_ADMIN" && status === "待公示") return [item("publish", "发布公示")]; if (role === "FUND_ADMIN" && status === "公示中") return [item("close_publicity", "结束公示")]; if (role === "STUDENT" && status === "已退回补正") return [item("appeal", "发起申诉", "warning")]; if (role === "STUDENT" && status === "已驳回") return [item("appeal", "发起申诉", "warning")]; if (role === "FUND_LEADER" && status === "申诉处理中") return [item("resolve_appeal", "申诉复核通过"), item("reject", "维持原结论", "danger")]; return []; }

export async function GET(request: NextRequest, context: { params: Promise<{ id: string }> }) {
  const actor = resolveRequestActor(request); if (!actor) return errorResponse("未完成身份认证", 401); const allowedRoles = ["FUND_LEADER", "STU_AFFAIRS", "FUND_ADMIN", "DEPT_ADMIN", "COUNSELOR", "STUDENT", "SCHOOL_LEADER", "FINANCE", "BANK", "AUDITOR", "AUDIT_EXTERNAL"] as const; if (!(allowedRoles as readonly string[]).includes(actor.role)) return errorResponse("当前岗位无权读取学生申请个体详情", 403);
  const { id } = await context.params; const application = getVisibleApplication(actor, id); if (!application) return errorResponse("申请不存在或不在当前授权范围", 404);
  const currentStage = stageByStatus[application.status]; const score = Math.max(45, 100 - (100 - application.materialCompleteness) * .7 - (application.riskLevel === "高" ? 24 : application.riskLevel === "中" ? 10 : 0) - (application.overdue ? 12 : 0));
  const storedMaterials = listApplicationMaterialRecords(application.id); const uploaded = storedMaterials.map(item => { const processing = getMaterialProcessingJob(item.id); return { id: item.id, name: item.name, type: item.mimeType, status: processing?.status === "completed" ? "verified" : "needs_review", completeness: processing?.status === "completed" ? 100 : 70, source: `${item.source} · SHA-256 ${item.sha256.slice(0, 12)}…`, sizeBytes: item.sizeBytes, sha256: item.sha256, submittedAt: item.submittedAt ?? item.uploadedAt, processingStatus: processing?.status ?? "processing", processingJobId: processing?.id, detailPath: `/application/materials/${item.id}` }; }); const authorized = (application.authorizationSources ?? []).map(source => ({ id: `AUTH-${source}`, name: sourceLabels[source] ?? source, type: "数据授权核验", status: "needs_review", completeness: 100, source: "学生明示授权 · 等待MCP回执" })); const offline = application.offlineReceiptNo ? [{ id: `OFFLINE-${application.id}`, name: "线下材料受理回执", type: "服务窗口核验", status: "needs_review", completeness: 100, source: `受理回执 ${application.offlineReceiptNo}` }] : [];
  const scenarioMaterials = getHardshipVideoMaterialProjections(application.id);
  const materials = scenarioMaterials.length ? scenarioMaterials : uploaded.length || authorized.length || offline.length ? [...uploaded, ...authorized, ...offline] : [{ id: "application-form", name: "资助申请表", type: "结构化表单", status: "verified", completeness: 100, source: "学生本人提交" }, { id: "identity-status", name: "学籍状态核验", type: "MCP核验结果", status: "verified", completeness: 100, source: "学工系统MCP（演示适配器）" }, { id: "supporting-documents", name: "困难或业绩佐证材料", type: "材料包", status: application.materialCompleteness === 100 ? "verified" : "needs_review", completeness: application.materialCompleteness, source: "OCR与版面解析流水线" }];
  const reviews = getHardshipVideoReviewProjections(application.id);
  const disbursement = application.scenarioId ? getHardshipVideoFinanceProjection() : null;
  const audits = listAuditEvidence(actor, { keyword: application.id, pageSize: 20 }).items.map(item => ({ id: item.id, actorRole: item.actor.role, actorType: item.actor.type, action: item.operation.action, category: item.operation.category, level: item.operation.level, outcome: item.result.status, evidenceSummary: item.evidence.summary, createdAt: item.timestamp, canDrill: canAccessAuditCenter(actor), detailPath: `/audit-center/events/${item.id}` }));
  const flow = stages.map((name, index) => { const review = index >= 1 && index <= 4 ? reviews.find(item => item.sequence === index + 3) : undefined; return { id: `stage-${index}`, name, status: index < currentStage ? "completed" : index === currentStage ? "current" : "pending", description: index === 0 ? (application.status === "草稿" ? "草稿已持久化，尚未进入审核队列" : `已通过${application.submissionChannel ?? "web"}渠道、${application.materialSubmissionMethod ?? "online-upload"}方式提交`) : index === 1 ? "辅导员核验材料原件、申请陈述与关怀事实" : index === 2 ? "院系执行组织范围、防重与上报口径复核" : index === 3 ? "校级资助中心执行政策、金额与证据一致性复审" : index === 4 ? "校领导基于脱敏摘要完成人工审批" : index === 5 ? "财务执行确定性校验与双人复核" : "银行回盘、银校对账、到账通知与审计归档", completedAt: index === 0 ? application.submittedAt : review?.completedAt ?? (index === 5 ? disbursement?.financeTask.completedAt : index === 6 ? disbursement?.completedAt : undefined) }; });
  const canReadP3 = actor.role === "STUDENT" && actor.userId === application.ownerId;
  const applicationView = { ...application, departmentName: departments[application.departmentId] ?? application.departmentId, className: application.classId, familyAnnualIncome: canReadP3 ? application.familyAnnualIncome : undefined, familyMembers: canReadP3 ? application.familyMembers : undefined, bankName: canReadP3 ? application.bankName : undefined, bankAccountLast4: canReadP3 ? application.bankAccountLast4 : application.bankAccountLast4 ? `****${application.bankAccountLast4}` : undefined, authorizationSources: [...(application.authorizationSources ?? [])] };
  return successResponse({ application: applicationView, permission: { roleCode: actor.role, roleName: ROLE_PROFILES[actor.role].name, dataScope: ROLE_PROFILES[actor.role].dataScope, p3FieldMode: canReadP3 ? "full" : "masked", allowedActions: application.scenarioId ? [] : actions(actor.role, application.status), editPath: !application.scenarioId && actor.role === "STUDENT" && ["草稿", "已退回补正"].includes(application.status) ? `/application/create?draft=${application.id}` : undefined }, materials, flow, submission: { channel: application.submissionChannel ?? "web", method: application.materialSubmissionMethod ?? "online-upload", receiptNo: application.submissionReceiptNo ?? `RCP-${application.id.toUpperCase()}`, materialCount: application.materialCount ?? materials.length, verifiedCount: application.materialVerifiedCount ?? materials.filter(item => item.status === "verified").length, authorizationSources: [...(application.authorizationSources ?? [])], offlineReceiptNo: application.offlineReceiptNo }, operations: { eligibility: getApplicationEligibility(application.id), precheck: getApplicationPrecheck(application.id), reviews, disbursement, intakeTicket: application.intakeTicketId ? getVisibleIntakeTicket(application.intakeTicketId, [application.id]) : null }, aiAnalysis: { score: Number(score.toFixed(1)), riskLevel: application.riskLevel, decisionBoundary: "AI仅提供材料、时效和风险标签解释，不形成资格、等级或审批决定。", findings: [application.materialCompleteness < 100 ? `材料完整度为 ${application.materialCompleteness}%，建议人工核对缺失项。` : "材料完整度规则检查通过。", application.overdue ? "当前节点已超过时效阈值，建议确认责任人后发起催办。" : "当前流程未触发超时规则。", application.riskLevel === "高" ? "存在高风险标签，必须优先人工复核原始证据。" : "未触发高风险人工升级规则。"], evidence: ["确定性材料完整度规则", "流程状态机与时效阈值", "岗位数据范围校验", "材料SHA-256摘要"], modelUsed: false }, audits, generatedAt: new Date().toISOString() });
}



