"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { AlertTriangle, Archive, BellRing, CheckCircle2, ClipboardCheck, FileCheck2, FolderArchive, ListTodo, MessageSquareText, RefreshCw, Send, Sparkles, UserRoundCheck, UsersRound } from "lucide-react";
import { useHashTab } from "@/hooks/use-hash-tab";
import { EnterprisePageHeader } from "@/components/enterprise/page-header";
import { MetricCard, SectionHeading, StatusPill } from "@/components/enterprise/dashboard";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
type Role = "FUND_ADMIN" | "DEPT_ADMIN" | "COUNSELOR";
interface Task { id:string;title:string;type:string;assignedRole:Role;scope:string;studentCount:number;dueAt:string;priority:"high"|"medium"|"normal";status:"pending"|"processing"|"completed";description:string;version:number;scenarioId?:string;applicationId?:string;externalActionRoute?:string }
interface StudentRow { id:string;studentCode:string;college:string;className:string;project:string;materialCompleteness:number;status:string;riskFlags:string[];lastContact:string;aidHistory:string;followUp:string }
interface QuotaPlan { id:string;project:string;totalQuota:number;allocatedQuota:number;rows:Array<{departmentId:string;department:string;applications:number;difficultyStudents:number;currentQuota:number;proposedQuota:number;ciac:number}>;status:"draft"|"published";version:number }
interface Interview { id:string;studentCode:string;template:string;summary:string;keyPoints:string[];followUpDate:string;signature:"pending"|"signed";status:"draft"|"completed";version:number }
interface Notice { id:string;name:string;assignedRole:Role;channel:string;recipients:number;template:string;status:"draft"|"sent";version:number;sentAt?:string }
interface ArchiveRow { id:string;department:string;period:string;applications:number;evidenceCompleteness:number;signedDocuments:number;totalDocuments:number;status:"preparing"|"ready"|"submitted";version:number }
interface Snapshot { tasks:Task[];students:StudentRow[];quotaPlans:QuotaPlan[];interviews:Interview[];notifications:Notice[];archives:ArchiveRow[];indicators:{pendingTasks:number;students:number;materialIssues:number;highRisk:number;overdue:number;archiveReadiness:number} }
interface Envelope<T>{success:boolean;data?:T;error?:string;message?:string}
type Pending={title:string;description:string;confirm:string;body:Record<string,unknown>};
function headers(){const token=localStorage.getItem("token");return{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}}function key(){return`frontline-${Date.now()}-${crypto.randomUUID()}`}function roleFromStorage():Role{try{const u=JSON.parse(localStorage.getItem("user")??"{}")as{role?:Role;roles?:Array<{code?:Role}>};return u.roles?.[0]?.code??u.role??"COUNSELOR"}catch{return"COUNSELOR"}}
const roleTitle:Record<Role,string>={FUND_ADMIN:"校级资助业务协同作战室",DEPT_ADMIN:"院系资助组织与复核中心",COUNSELOR:"辅导员一线资助服务工作台"};
export default function FrontlineCenterPage(){const[tab,setTab]=useHashTab(["tasks","students","quotas","interviews","notifications","archives"]as const,"tasks");const[data,setData]=useState<Snapshot|null>(null),[role,setRole]=useState<Role>("COUNSELOR"),[loading,setLoading]=useState(true),[pending,setPending]=useState<Pending|null>(null),[note,setNote]=useState(""),[working,setWorking]=useState(false),[message,setMessage]=useState<{type:"ok"|"error";text:string}|null>(null),[interview,setInterview]=useState<Interview|null>(null),[summary,setSummary]=useState(""),[followUpDate,setFollowUpDate]=useState("2026-08-15");
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/frontline-center",{headers:headers(),cache:"no-store"});const b=await r.json()as Envelope<Snapshot>;if(!r.ok||!b.success||!b.data)throw new Error(b.error??"协同工作台加载失败");setData(b.data)}catch(e){setMessage({type:"error",text:e instanceof Error?e.message:"协同工作台加载失败"})}finally{setLoading(false)}},[]);useEffect(()=>{setRole(roleFromStorage());void load()},[load]);const open=(p:Pending)=>{setPending(p);setNote("")};
 const post=async(body:Record<string,unknown>)=>{setWorking(true);try{const r=await fetch("/api/frontline-center",{method:"POST",headers:{...headers(),"Idempotency-Key":key()},body:JSON.stringify({...body,note:note.trim(),humanConfirmed:true})});const b=await r.json()as Envelope<unknown>;if(!r.ok||!b.success)throw new Error(b.error??"协同操作失败");setMessage({type:"ok",text:b.message??"操作已完成"});setPending(null);setInterview(null);setNote("");await load()}catch(e){setMessage({type:"error",text:e instanceof Error?e.message:"协同操作失败"})}finally{setWorking(false)}};const execute=()=>pending&&post(pending.body);const completeInterview=()=>interview&&post({action:"complete_interview",interviewId:interview.id,expectedVersion:interview.version,summary:summary.trim(),followUpDate});
 return <div className="space-y-6"><EnterprisePageHeader eyebrow="AID COLLABORATION" title={roleTitle[role]} description="按校级、院系、班级三层数据范围加载待办、学生脱敏画像、名额方案、谈心谈话、批量通知和电子归档；小海豚可生成草稿与检查问题，但提交、发送、签名均由人确认。" icon={UserRoundCheck} badge={`${role} · 岗位范围已隔离`} actions={[{label:"刷新协同态",icon:RefreshCw,variant:"outline",onClick:()=>void load(),disabled:loading}]} />
 {message&&<div className={`rounded-xl border px-4 py-3 text-sm ${message.type==="ok"?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-rose-200 bg-rose-50 text-rose-700"}`}>{message.text}</div>}{data&&<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="岗位待办" value={data.indicators.pendingTasks.toString()} detail={`${data.indicators.overdue}项高优先级`} icon={ListTodo} tone="blue"/><MetricCard label="授权学生范围" value={data.indicators.students.toString()} detail="仅显示脱敏编码" icon={UsersRound} tone="cyan"/><MetricCard label="材料问题" value={data.indicators.materialIssues.toString()} detail="有效期、缺失项与一致性" icon={FileCheck2} tone="amber"/><MetricCard label="风险标记" value={data.indicators.highRisk.toString()} detail="必须人工核验说明" icon={AlertTriangle} tone="rose"/><MetricCard label="档案就绪度" value={`${data.indicators.archiveReadiness}%`} detail="证据、签名与流程快照" icon={FolderArchive} tone="emerald"/></div>
 <Tabs value={tab} onValueChange={setTab} className="space-y-5"><TabsList className="h-auto flex-wrap rounded-xl border border-slate-200 bg-white p-1"><TabsTrigger value="tasks">岗位待办</TabsTrigger><TabsTrigger value="students">学生与材料</TabsTrigger><TabsTrigger value="quotas">名额组织</TabsTrigger>{role==="COUNSELOR"&&<TabsTrigger value="interviews">谈心谈话</TabsTrigger>}<TabsTrigger value="notifications">通知沟通</TabsTrigger><TabsTrigger value="archives">电子归档</TabsTrigger></TabsList>
 <TabsContent value="tasks" className="grid gap-4 xl:grid-cols-2">{data.tasks.map(item=><Card key={item.id} className="border-slate-200 shadow-sm"><CardContent className="p-5"><div className="flex items-start justify-between"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${item.priority==="high"?"bg-rose-50 text-rose-600":item.priority==="medium"?"bg-amber-50 text-amber-600":"bg-blue-50 text-blue-700"}`}><ClipboardCheck className="h-4 w-4"/></span><StatusPill status={item.status==="completed"?"healthy":item.priority==="high"?"danger":"warning"} label={item.status==="completed"?"已完成":item.status==="processing"?"处理中":"待处理"}/></div><div className="mt-4 flex flex-wrap items-center gap-2"><h3 className="text-sm font-semibold text-slate-800">{item.title}</h3><Badge variant="outline">{item.type}</Badge></div><p className="mt-1 text-[10px] text-slate-400">{item.scope} · {item.studentCount}人 · 截止 {item.dueAt}</p><p className="mt-3 text-[11px] leading-5 text-slate-600">{item.description}</p>{item.status!=="completed"&&(item.externalActionRoute?<Button asChild className="mt-4 w-full"><Link href={item.externalActionRoute}><Sparkles className="mr-2 h-4 w-4"/>进入Agent人工闸门</Link></Button>:<Button className="mt-4 w-full" variant="outline" onClick={()=>open({title:"确认完成岗位任务",description:"系统将冻结当前处理快照并写入审计；请确保关联业务记录已完成。",confirm:"人工确认完成",body:{action:"complete_task",taskId:item.id,expectedVersion:item.version}})}><CheckCircle2 className="mr-2 h-4 w-4"/>完成任务</Button>)}</CardContent></Card>)}</TabsContent>
 <TabsContent value="students"><Card className="border-slate-200 shadow-sm"><CardHeader><SectionHeading title="学生资助画像与材料问题" description="P3字段不在本页展示；风险标记不等同于否决结论"/></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-y border-slate-100 bg-slate-50 text-[10px] text-slate-400"><tr><th className="px-5 py-3">学生/班级</th><th className="px-4 py-3">项目与状态</th><th className="px-4 py-3">材料</th><th className="px-4 py-3">风险说明</th><th className="px-5 py-3">后续跟踪</th></tr></thead><tbody>{data.students.map(item=><tr key={item.id} className="border-b border-slate-100 last:border-0"><td className="px-5 py-4"><p className="font-semibold text-slate-800">{item.studentCode}</p><p className="mt-1 text-[10px] text-slate-400">{item.college} · {item.className}</p></td><td className="px-4 py-4"><p className="text-slate-700">{item.project}</p><Badge variant="outline" className="mt-1 text-[9px]">{item.status}</Badge></td><td className="px-4 py-4"><p className={`font-bold ${item.materialCompleteness<90?"text-rose-600":item.materialCompleteness<100?"text-amber-600":"text-emerald-600"}`}>{item.materialCompleteness}%</p><p className="mt-1 text-[9px] text-slate-400">完整度</p></td><td className="max-w-[260px] px-4 py-4">{item.riskFlags.length?item.riskFlags.map(flag=><p key={flag} className="mb-1 text-[10px] text-rose-600">• {flag}</p>):<span className="text-[10px] text-emerald-600">未发现规则异常</span>}</td><td className="px-5 py-4"><p className="text-[11px] text-slate-600">{item.followUp}</p><p className="mt-1 text-[9px] text-slate-400">最近联系 {item.lastContact} · {item.aidHistory}</p></td></tr>)}</tbody></table></div></CardContent></Card></TabsContent>
 <TabsContent value="quotas" className="space-y-4">{data.quotaPlans.map(plan=><Card key={plan.id} className="border-slate-200 shadow-sm"><CardHeader><SectionHeading title={plan.project} description={`总名额 ${plan.totalQuota} · 拟分配 ${plan.rows.reduce((s,row)=>s+row.proposedQuota,0)} · ${plan.status==="published"?"已发布":"待人工发布"}`} action={role==="FUND_ADMIN"&&plan.status==="draft"?<Button onClick={()=>open({title:"发布全校名额方案",description:"确定性规则将校验院系名额合计必须等于总名额。发布后院系可见。",confirm:"确认发布",body:{action:"publish_quota_plan",planId:plan.id,expectedVersion:plan.version}})}><Send className="mr-2 h-4 w-4"/>发布方案</Button>:<StatusPill status={plan.status==="published"?"healthy":"warning"} label={plan.status==="published"?"已发布":"草稿"}/>} /></CardHeader><CardContent className="grid gap-3 lg:grid-cols-2 xl:grid-cols-3">{plan.rows.map(row=><div key={row.departmentId} className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-slate-700">{row.department}</p><Badge variant="outline">CIAC {row.ciac.toFixed(2)}</Badge></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><Tiny label="申请" value={row.applications}/><Tiny label="困难生" value={row.difficultyStudents}/><Tiny label="拟分配" value={row.proposedQuota}/></div><p className="mt-2 text-[9px] text-slate-400">原名额 {row.currentQuota} · 调整 {row.proposedQuota-row.currentQuota>=0?"+":""}{row.proposedQuota-row.currentQuota}</p></div>)}</CardContent></Card>)}</TabsContent>
 {role==="COUNSELOR"&&<TabsContent value="interviews" className="grid gap-4 xl:grid-cols-2">{data.interviews.map(item=><Card key={item.id} className="border-slate-200 shadow-sm"><CardContent className="p-5"><div className="flex items-start justify-between"><MessageSquareText className="h-5 w-5 text-violet-700"/><StatusPill status={item.status==="completed"?"healthy":"warning"} label={item.status==="completed"?"已签名归档":"待完成"}/></div><h3 className="mt-4 text-sm font-semibold text-slate-800">{item.studentCode} · {item.template}</h3><div className="mt-3 flex flex-wrap gap-1.5">{item.keyPoints.map(point=><Badge key={point} variant="secondary" className="text-[9px]">{point}</Badge>)}</div><p className="mt-3 min-h-12 text-[11px] leading-5 text-slate-600">{item.summary||"尚未填写谈话纪要；可由AI生成结构草稿，但需辅导员核对后签名。"}</p><p className="mt-2 text-[10px] text-slate-400">跟进日期 {item.followUpDate} · 电子签名 {item.signature}</p>{item.status==="draft"&&<Button className="mt-4 w-full" variant="outline" onClick={()=>{setInterview(item);setSummary("");setFollowUpDate(item.followUpDate);setNote("")}}><Sparkles className="mr-2 h-4 w-4"/>填写并签名纪要</Button>}</CardContent></Card>)}</TabsContent>}
 <TabsContent value="notifications" className="grid gap-4 xl:grid-cols-2">{data.notifications.map(item=><Card key={item.id} className="border-slate-200 shadow-sm"><CardContent className="p-5"><div className="flex items-start justify-between"><BellRing className="h-5 w-5 text-blue-700"/><StatusPill status={item.status==="sent"?"healthy":"warning"} label={item.status==="sent"?"已发送":"待确认"}/></div><h3 className="mt-4 text-sm font-semibold text-slate-800">{item.name}</h3><p className="mt-1 text-[10px] text-slate-400">{item.channel} · {item.recipients}人{item.sentAt?` · ${item.sentAt}`:""}</p><p className="mt-3 rounded-lg bg-slate-50 p-3 text-[11px] leading-5 text-slate-600">{item.template}</p>{item.status==="draft"&&<Button className="mt-4 w-full" onClick={()=>open({title:"确认发送批量通知",description:`将通过${item.channel}发送给${item.recipients}人。请核对对象和话术，AI不能自动发送。`,confirm:"人工确认发送",body:{action:"send_notification",notificationId:item.id,expectedVersion:item.version}})}><Send className="mr-2 h-4 w-4"/>确认发送</Button>}</CardContent></Card>)}</TabsContent>
 <TabsContent value="archives" className="grid gap-4 xl:grid-cols-2">{data.archives.map(item=><Card key={item.id} className="border-slate-200 shadow-sm"><CardContent className="p-5"><div className="flex items-start justify-between"><Archive className="h-5 w-5 text-emerald-700"/><StatusPill status={item.status==="submitted"?"healthy":item.status==="ready"?"info":"warning"} label={item.status==="submitted"?"已提交":item.status==="ready"?"可归档":"准备中"}/></div><h3 className="mt-4 text-sm font-semibold text-slate-800">{item.department} · {item.period}</h3><p className="mt-1 text-[10px] text-slate-400">申请档案 {item.applications} 份</p><div className="mt-4 grid grid-cols-2 gap-2"><Tiny label="证据完整度" value={`${item.evidenceCompleteness}%`}/><Tiny label="电子签名" value={`${item.signedDocuments}/${item.totalDocuments}`}/></div>{role==="DEPT_ADMIN"&&item.status==="ready"&&<Button className="mt-4 w-full" variant="outline" onClick={()=>open({title:"提交院系电子归档",description:"系统将再次校验证据完整度、电子签名和流程快照阈值。",confirm:"确认提交学校",body:{action:"submit_archive",archiveId:item.id,expectedVersion:item.version}})}><FolderArchive className="mr-2 h-4 w-4"/>提交学校</Button>}</CardContent></Card>)}</TabsContent>
 </Tabs></>}
 <AlertDialog open={Boolean(pending)} onOpenChange={value=>{if(!value&&!working)setPending(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{pending?.title}</AlertDialogTitle><AlertDialogDescription>{pending?.description}</AlertDialogDescription></AlertDialogHeader><Textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="请输入处理依据、核验结果或发送理由（至少4个字）" maxLength={800}/><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction disabled={working||note.trim().length<4} onClick={e=>{e.preventDefault();void execute()}}>{working?"提交中…":pending?.confirm}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={Boolean(interview)} onOpenChange={value=>{if(!value&&!working)setInterview(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>完成谈心谈话纪要</AlertDialogTitle><AlertDialogDescription>{interview?.studentCode} · {interview?.template}。AI草稿不得直接归档，须辅导员核对事实并签名。</AlertDialogDescription></AlertDialogHeader><Textarea value={summary} onChange={e=>setSummary(e.target.value)} placeholder="请输入核对后的谈话纪要（至少10个字）" rows={5}/><div className="grid grid-cols-2 gap-3"><label className="space-y-2 text-xs text-slate-600">后续跟进日期<Input type="date" value={followUpDate} onChange={e=>setFollowUpDate(e.target.value)}/></label><label className="space-y-2 text-xs text-slate-600">人工签名依据<Input value={note} onChange={e=>setNote(e.target.value)} placeholder="如：本人已核对纪要"/></label></div><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction disabled={working||summary.trim().length<10||note.trim().length<4} onClick={e=>{e.preventDefault();void completeInterview()}}>{working?"提交中…":"核对并电子签名"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>}
function Tiny({label,value}:{label:string;value:string|number}){return <div className="rounded-lg bg-slate-50 p-2 text-center"><p className="text-xs font-bold text-slate-800">{value}</p><p className="mt-1 text-[9px] text-slate-400">{label}</p></div>}

