"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { AlertTriangle, ArrowLeft, CheckCircle2, CloudUpload, Database, FileCheck2, FileText, Loader2, Save, ScanText, Send, ShieldCheck, Smartphone, Store, Trash2, UploadCloud } from "lucide-react";
import { EnterprisePageHeader } from "@/components/enterprise/page-header";
import { SectionHeading } from "@/components/enterprise/dashboard";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

type SubmissionMethod = "online-upload" | "data-authorization" | "mixed" | "offline-verification";
type SubmissionChannel = "web" | "mobile" | "service-counter";
interface ProjectDefinition { code: string; name: string; maximumAmount: number; defaultAmount: number; requiredDocuments: string[]; criteria: string; applicationStart: string; applicationEnd: string; policyRef: string }
interface ProcessingSummary { id: string; status: "processing" | "completed" | "needs_confirmation" | "blocked"; parserAdapter: string }
interface UploadedMaterial { id: string; applicationId?: string; name: string; mimeType: string; sizeBytes: number; sha256: string; status: string; uploadedAt: string; processing?: ProcessingSummary | null }
interface EligibilityReport { id: string; allowed: boolean; checks: Array<{ code: string; label: string; status: "passed" | "warning" | "blocked"; detail: string; source: string }>; blockingCodes: string[]; warningCodes: string[]; disclaimer: string }
interface DraftPayload { application: { id: string; projectName: string; requestedAmount: number; version: number; academicYear?: string; semester?: string; applicantStatement?: string; familyAnnualIncome?: number; familyMembers?: number; specialCircumstance?: string; bankName?: string; submissionChannel?: SubmissionChannel; materialSubmissionMethod?: SubmissionMethod; offlineReceiptNo?: string; authorizationSources?: string[] }; projectCode: string; materials: UploadedMaterial[] }
interface CreatedApplication { id: string; status: string; version?: number; submissionReceiptNo?: string }
interface Envelope<T> { success: boolean; data?: T; error?: string; message?: string }
const fallbackProjects: ProjectDefinition[] = [
  { code: "national_scholarship", name: "国家奖学金", maximumAmount: 8000, defaultAmount: 8000, requiredDocuments: ["成绩单", "获奖证书", "家庭经济情况说明"], criteria: "全日制在籍且学业表现达到项目要求。", applicationStart: "2026-08-01", applicationEnd: "2026-09-15", policyRef: "POL-NATIONAL-SCHOLARSHIP-2026" },
  { code: "national_grant", name: "国家助学金", maximumAmount: 4500, defaultAmount: 3300, requiredDocuments: ["家庭经济情况调查表", "困难情况佐证", "本人承诺书"], criteria: "全日制在籍并完成家庭经济困难认定。", applicationStart: "2026-08-01", applicationEnd: "2026-09-20", policyRef: "POL-NATIONAL-GRANT-2026" },
  { code: "school_scholarship", name: "校内奖学金", maximumAmount: 5000, defaultAmount: 3000, requiredDocuments: ["成绩单", "获奖证书", "综合素质证明"], criteria: "学业与综合表现由评审组织人工核定。", applicationStart: "2026-08-01", applicationEnd: "2026-10-15", policyRef: "POL-SCHOOL-SCHOLARSHIP-2026" },
  { code: "work_study", name: "勤工助学", maximumAmount: 0, defaultAmount: 0, requiredDocuments: ["家庭经济情况调查表", "本人承诺书"], criteria: "薪酬按岗位工时核定。", applicationStart: "2026-08-01", applicationEnd: "2027-07-31", policyRef: "POL-WORK-STUDY-2026" },
  { code: "temporary_aid", name: "临时困难补助", maximumAmount: 5000, defaultAmount: 2000, requiredDocuments: ["家庭困难说明", "突发情况佐证"], criteria: "发生疾病、灾害或家庭突发变故。", applicationStart: "2026-01-01", applicationEnd: "2026-12-31", policyRef: "POL-EMERGENCY-AID-2026" },
  { code: "tuition_waiver", name: "学费减免", maximumAmount: 10000, defaultAmount: 6000, requiredDocuments: ["家庭经济情况调查表", "困难情况佐证", "学费信息核验"], criteria: "符合学校学费减免政策。", applicationStart: "2026-08-01", applicationEnd: "2026-10-31", policyRef: "POL-TUITION-WAIVER-2026" },
  { code: "student_loan", name: "生源地信用助学贷款", maximumAmount: 16000, defaultAmount: 12000, requiredDocuments: ["家庭经济情况调查表", "身份与学籍核验", "录取或在籍证明"], criteria: "额度以银行资格核验回执为准。", applicationStart: "2026-07-01", applicationEnd: "2026-10-20", policyRef: "POL-STUDENT-LOAN-2026" },
];
const authorizationOptions = [{ id: "student-status", label: "授权核验学籍状态" }, { id: "low-income-registry", label: "授权核验低收入人口信息" }, { id: "disability-registry", label: "授权核验残疾信息" }, { id: "grade-transcript", label: "授权读取成绩单" }];
const methodOptions: Array<{ id: SubmissionMethod; name: string; detail: string; icon: typeof CloudUpload }> = [{ id: "online-upload", name: "在线上传", detail: "真实保存文件、计算摘要并运行预处理流水线", icon: CloudUpload }, { id: "data-authorization", name: "数据授权", detail: "明示授权MCP核验，避免重复提交证明", icon: Database }, { id: "mixed", name: "混合提交", detail: "上传材料与授权数据共同组成证据包", icon: FileCheck2 }, { id: "offline-verification", name: "线下核验", detail: "服务窗口收件后绑定受理回执", icon: Store }];
function authHeaders(json = false): HeadersInit { const token = localStorage.getItem("token"); return { ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(json ? { "Content-Type": "application/json" } : {}) }; }
function formatBytes(value: number) { return value > 1024 * 1024 ? `${(value / 1024 / 1024).toFixed(2)} MB` : `${Math.ceil(value / 1024)} KB`; }

export default function CreateApplicationPage() {
  const router = useRouter(); const params = useSearchParams(); const draftId = params.get("draft");
  const [projects, setProjects] = useState<ProjectDefinition[]>(fallbackProjects); const [draftVersion, setDraftVersion] = useState<number | null>(null); const [initializing, setInitializing] = useState(Boolean(draftId));
  const [step, setStep] = useState(1); const [materials, setMaterials] = useState<UploadedMaterial[]>([]); const [uploading, setUploading] = useState(false); const [submitting, setSubmitting] = useState(false); const [eligibilityLoading, setEligibilityLoading] = useState(false); const [eligibility, setEligibility] = useState<EligibilityReport | null>(null); const [waiverConfirmed, setWaiverConfirmed] = useState(false); const [message, setMessage] = useState<{ type: "ok" | "error"; text: string } | null>(null);
  const [form, setForm] = useState({ projectCode: "", academicYear: "2026-2027", semester: "第一学期", amount: "", statement: "", familyAnnualIncome: "", familyMembers: "", specialCircumstance: "", bankName: "", bankAccount: "", channel: "web" as SubmissionChannel, method: "online-upload" as SubmissionMethod, offlineReceiptNo: "" }); const [authorizationSources, setAuthorizationSources] = useState<string[]>([]);
  const selectedProject = projects.find(item => item.code === form.projectCode); const required = selectedProject?.requiredDocuments ?? []; const evidenceUnits = materials.length + authorizationSources.length + (form.offlineReceiptNo.trim() ? 1 : 0); const completeness = required.length ? Math.min(100, Math.round(evidenceUnits / required.length * 100)) : 0; const unresolved = materials.filter(item => item.processing?.status === "needs_confirmation" || item.processing?.status === "processing");
  useEffect(() => { let active = true; void (async () => { try {
    const [projectsResponse, stagedResponse, draftResponse] = await Promise.all([fetch("/api/applications/eligibility", { headers: authHeaders(), cache: "no-store" }), fetch("/api/applications/materials", { headers: authHeaders(), cache: "no-store" }), draftId ? fetch(`/api/applications/${encodeURIComponent(draftId)}/draft`, { headers: authHeaders(), cache: "no-store" }) : Promise.resolve(null)]);
    const projectsBody = await projectsResponse.json() as Envelope<{ projects: ProjectDefinition[] }>; const stagedBody = await stagedResponse.json() as Envelope<UploadedMaterial[]>; if (active && projectsResponse.ok && projectsBody.data?.projects.length) setProjects(projectsBody.data.projects);
    const staged = stagedResponse.ok && stagedBody.success ? stagedBody.data ?? [] : [];
    if (draftResponse) { const draftBody = await draftResponse.json() as Envelope<DraftPayload>; if (!draftResponse.ok || !draftBody.success || !draftBody.data) throw new Error(draftBody.error ?? "草稿加载失败"); const draft = draftBody.data; if (!active) return; setDraftVersion(draft.application.version); setForm({ projectCode: draft.projectCode, academicYear: draft.application.academicYear ?? "2026-2027", semester: draft.application.semester ?? "第一学期", amount: String(draft.application.requestedAmount), statement: draft.application.applicantStatement ?? "", familyAnnualIncome: draft.application.familyAnnualIncome === undefined ? "" : String(draft.application.familyAnnualIncome), familyMembers: draft.application.familyMembers === undefined ? "" : String(draft.application.familyMembers), specialCircumstance: draft.application.specialCircumstance ?? "", bankName: draft.application.bankName ?? "", bankAccount: "", channel: draft.application.submissionChannel ?? "web", method: draft.application.materialSubmissionMethod ?? "online-upload", offlineReceiptNo: draft.application.offlineReceiptNo ?? "" }); setAuthorizationSources(draft.application.authorizationSources ?? []); setMaterials(uniqueMaterials([...draft.materials, ...staged]));
    } else if (active) setMaterials(staged);
  } catch (reason) { if (active) setMessage({ type: "error", text: reason instanceof Error ? reason.message : "申请初始化失败" }); } finally { if (active) setInitializing(false); } })(); return () => { active = false; }; }, [draftId]);
  const update = <K extends keyof typeof form>(key: K, value: typeof form[K]) => { setForm(current => ({ ...current, [key]: value })); if (["projectCode", "amount", "academicYear"].includes(key)) setEligibility(null); };
  function selectProject(project: ProjectDefinition) { setForm(current => ({ ...current, projectCode: project.code, amount: String(project.defaultAmount) })); setEligibility(null); setWaiverConfirmed(false); }
  async function runEligibility(): Promise<boolean> { if (!selectedProject) { setMessage({ type: "error", text: "请先选择资助项目。" }); return false; } setEligibilityLoading(true); try { const amount = selectedProject.maximumAmount === 0 ? 0 : Number(form.amount); const response = await fetch("/api/applications/eligibility", { method: "POST", headers: authHeaders(true), body: JSON.stringify({ project: selectedProject.code, requestedAmount: amount, academicYear: form.academicYear, excludeApplicationId: draftId ?? undefined }) }); const body = await response.json() as Envelope<EligibilityReport>; if (!response.ok || !body.success || !body.data) throw new Error(body.error ?? "资格校验失败"); setEligibility(body.data); if (!body.data.allowed) { setMessage({ type: "error", text: "项目资格存在阻断项，请查看确定性校验报告。" }); return false; } setMessage({ type: "ok", text: "项目资格确定性校验通过；提示项仍由后续人工审核确认。" }); return true; } catch (reason) { setMessage({ type: "error", text: reason instanceof Error ? reason.message : "资格校验失败" }); return false; } finally { setEligibilityLoading(false); } }
  async function uploadFiles(files: FileList | null) { if (!files?.length) return; setUploading(true); setMessage(null); try { for (const file of Array.from(files).slice(0, 12 - materials.length)) { const data = new FormData(); data.set("file", file); const response = await fetch("/api/applications/materials", { method: "POST", headers: authHeaders(), body: data }); const body = await response.json() as Envelope<UploadedMaterial>; if (!response.ok || !body.success || !body.data) throw new Error(body.error ?? `${file.name} 上传失败`); setMaterials(current => uniqueMaterials([body.data!, ...current])); } setMessage({ type: "ok", text: "材料已写入对象存储并运行安全扫描、OCR/文本抽取、版面分析和实体分类。" }); } catch (reason) { setMessage({ type: "error", text: reason instanceof Error ? reason.message : "材料上传失败" }); } finally { setUploading(false); } }
  async function removeMaterial(item: UploadedMaterial) { const query = item.applicationId ? `?applicationId=${encodeURIComponent(item.applicationId)}` : ""; const response = await fetch(`/api/applications/materials/${encodeURIComponent(item.id)}${query}`, { method: "DELETE", headers: authHeaders() }); const body = await response.json() as Envelope<unknown>; if (!response.ok || !body.success) { setMessage({ type: "error", text: body.error ?? "材料移除失败" }); return; } setMaterials(current => current.filter(material => material.id !== item.id)); }
  async function confirmMaterial(item: UploadedMaterial) { const response = await fetch(`/api/applications/materials/${encodeURIComponent(item.id)}/processing/actions`, { method: "POST", headers: authHeaders(true), body: JSON.stringify({ action: "confirm", humanConfirmed: true }) }); const body = await response.json() as Envelope<ProcessingSummary>; if (!response.ok || !body.success || !body.data) { setMessage({ type: "error", text: body.error ?? "确认失败" }); return; } setMaterials(current => current.map(material => material.id === item.id ? { ...material, processing: body.data! } : material)); setMessage({ type: "ok", text: `${item.name} 的低可信识别结果已由本人确认。` }); }
  const toggleAuthorization = (id: string, checked: boolean) => setAuthorizationSources(current => checked ? [...new Set([...current, id])] : current.filter(item => item !== id));
  async function submit(mode: "draft" | "submit") { if (!selectedProject) { setMessage({ type: "error", text: "请先选择资助项目。" }); setStep(1); return; } if (mode === "submit" && form.statement.trim().length < 10) { setMessage({ type: "error", text: "正式提交前请填写至少10个字符的申请理由。" }); setStep(2); return; } if (mode === "submit" && unresolved.length) { setMessage({ type: "error", text: `仍有 ${unresolved.length} 份材料需要确认OCR/分类结果。` }); return; } if (mode === "submit" && completeness < 100 && !waiverConfirmed) { setMessage({ type: "error", text: "材料预检存在缺失提示；如仍需提交，请明确勾选知悉确认。" }); return; } if (mode === "submit" && !(await runEligibility())) { setStep(1); return; }
    setSubmitting(true); setMessage(null); try { const amount = selectedProject.maximumAmount === 0 ? 0 : Number(form.amount); const endpoint = draftId ? `/api/applications/${encodeURIComponent(draftId)}/draft` : "/api/applications"; const response = await fetch(endpoint, { method: draftId ? "PATCH" : "POST", headers: { ...authHeaders(true), "Idempotency-Key": `application-${mode}-${crypto.randomUUID()}` }, body: JSON.stringify({ projectCode: selectedProject.code, projectName: selectedProject.name, requestedAmount: amount, mode, expectedVersion: draftVersion ?? undefined, submissionChannel: form.channel, materialSubmissionMethod: form.method, materialIds: materials.map(item => item.id), requiredMaterialCount: Math.max(1, required.length), authorizationSources, offlineReceiptNo: form.offlineReceiptNo, academicYear: form.academicYear, semester: form.semester, applicantStatement: form.statement, familyAnnualIncome: form.familyAnnualIncome ? Number(form.familyAnnualIncome) : undefined, familyMembers: form.familyMembers ? Number(form.familyMembers) : undefined, specialCircumstance: form.specialCircumstance, bankName: form.bankName, bankAccount: form.bankAccount, precheckWaiverConfirmed: waiverConfirmed }) }); const body = await response.json() as Envelope<CreatedApplication>; if (!response.ok || !body.success || !body.data) throw new Error(body.error ?? "申请提交失败"); router.push(`/application/detail?id=${encodeURIComponent(body.data.id)}`); } catch (reason) { setMessage({ type: "error", text: reason instanceof Error ? reason.message : "申请提交失败" }); } finally { setSubmitting(false); } }
  const methodNeedsUpload = form.method === "online-upload" || form.method === "mixed"; const methodNeedsAuthorization = form.method === "data-authorization" || form.method === "mixed";
  if (initializing) return <div className="flex min-h-[60vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-blue-600" /></div>;
  return <div className="space-y-6 pb-10"><EnterprisePageHeader eyebrow="ONLINE AID APPLICATION" title={draftId ? "编辑申请草稿与补正材料" : "在线资助申请与材料提交"} description="项目资格、材料预处理、AI/规则预检、人工确认、受理工单和通知回执已打通；缺失材料只提示，AI不自动拒绝。" icon={FileText} badge={draftId ? `DRAFT v${draftVersion ?? 1}` : "PERSISTED · AUDITED"} />
    <div className="flex items-center justify-between"><Link href="/application/all" className="inline-flex items-center text-xs font-medium text-muted-foreground hover:text-foreground"><ArrowLeft className="mr-1 h-4 w-4" />返回申请列表</Link><Badge variant="outline">材料完整度 {completeness}%</Badge></div>
    {message && <div className={`rounded-xl border px-4 py-3 text-sm ${message.type === "ok" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-rose-200 bg-rose-50 text-rose-700"}`}>{message.text}</div>}
    <Card><CardContent className="p-5"><div className="grid gap-4 md:grid-cols-3">{[{ n: 1, title: "项目与资格", detail: "项目选择和确定性资格校验" }, { n: 2, title: "申请信息", detail: "申请理由与必要信息" }, { n: 3, title: "材料与受理", detail: "预处理、预检、确认并提交" }].map(item => <button key={item.n} onClick={() => setStep(item.n)} className={`flex items-center gap-3 rounded-xl border p-3 text-left transition ${step === item.n ? "border-blue-300 bg-blue-50 dark:bg-blue-950/30" : "hover:bg-muted/40"}`}><span className={`flex h-9 w-9 items-center justify-center rounded-xl text-sm font-bold ${step >= item.n ? "bg-blue-600 text-white" : "bg-muted text-muted-foreground"}`}>{step > item.n ? <CheckCircle2 className="h-4 w-4" /> : item.n}</span><span><strong className="block text-sm">{item.title}</strong><span className="mt-1 block text-[10px] text-muted-foreground">{item.detail}</span></span></button>)}</div></CardContent></Card>
    {step === 1 && <Card><CardHeader><SectionHeading title="选择资助项目并校验资格" description="项目范围、金额、时间窗、身份与同类在途申请全部由服务端确定性规则复核" /></CardHeader><CardContent className="space-y-6"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{projects.map(project => <button key={project.code} onClick={() => selectProject(project)} className={`rounded-xl border p-4 text-left transition ${form.projectCode === project.code ? "border-blue-400 bg-blue-50 ring-1 ring-blue-200 dark:bg-blue-950/30" : "hover:border-blue-300"}`}><div className="flex items-start justify-between"><div><p className="text-sm font-semibold">{project.name}</p><p className="mt-1 text-[10px] text-muted-foreground">{project.maximumAmount ? `最高 ¥${project.maximumAmount.toLocaleString("zh-CN")}` : "按核定工时结算"} · 截止 {project.applicationEnd}</p></div>{form.projectCode === project.code && <CheckCircle2 className="h-5 w-5 text-blue-600" />}</div><p className="mt-3 text-[10px] leading-5 text-muted-foreground">{project.criteria}</p></button>)}</div>
      <div className="grid gap-4 lg:grid-cols-2"><Field label="提交渠道"><Select value={form.channel} onValueChange={value => update("channel", value as SubmissionChannel)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="web"><UploadCloud className="mr-2 inline h-4 w-4" />网页端</SelectItem><SelectItem value="mobile"><Smartphone className="mr-2 inline h-4 w-4" />移动端</SelectItem><SelectItem value="service-counter"><Store className="mr-2 inline h-4 w-4" />资助服务窗口</SelectItem></SelectContent></Select></Field><Field label="学年 / 学期"><div className="grid grid-cols-2 gap-2"><Select value={form.academicYear} onValueChange={value => update("academicYear", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="2026-2027">2026-2027学年</SelectItem><SelectItem value="2025-2026">2025-2026学年</SelectItem></SelectContent></Select><Select value={form.semester} onValueChange={value => update("semester", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="第一学期">第一学期</SelectItem><SelectItem value="第二学期">第二学期</SelectItem></SelectContent></Select></div></Field></div>
      {selectedProject?.maximumAmount !== 0 && <Field label="申请金额（元）"><Input type="number" min={0} max={selectedProject?.maximumAmount} value={form.amount} onChange={event => update("amount", event.target.value)} /></Field>}
      <div><p className="mb-3 text-xs font-medium">材料提交方式</p><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{methodOptions.map(item => { const Icon = item.icon; return <button key={item.id} onClick={() => update("method", item.id)} className={`rounded-xl border p-4 text-left ${form.method === item.id ? "border-blue-400 bg-blue-50 dark:bg-blue-950/30" : "hover:border-blue-300"}`}><Icon className="h-5 w-5 text-blue-600" /><p className="mt-3 text-sm font-semibold">{item.name}</p><p className="mt-1 text-[10px] leading-5 text-muted-foreground">{item.detail}</p></button>; })}</div></div>
      {eligibility && <Card className={eligibility.allowed ? "border-emerald-200" : "border-rose-200"}><CardContent className="space-y-2 p-4">{eligibility.checks.map(check => <div key={check.code} className="flex gap-3 rounded-lg bg-muted/40 p-3"><span className={check.status === "blocked" ? "text-rose-600" : check.status === "warning" ? "text-amber-600" : "text-emerald-600"}>{check.status === "blocked" ? <AlertTriangle className="h-4 w-4" /> : <CheckCircle2 className="h-4 w-4" />}</span><div><p className="text-xs font-semibold">{check.label}</p><p className="mt-1 text-[10px] leading-5 text-muted-foreground">{check.detail} · {check.source}</p></div></div>)}<p className="text-[10px] text-muted-foreground">{eligibility.disclaimer}</p></CardContent></Card>}
      <div className="flex justify-end gap-2"><Button variant="outline" onClick={() => void runEligibility()} disabled={!selectedProject || eligibilityLoading}>{eligibilityLoading ? "校验中…" : "执行资格校验"}</Button><Button onClick={async () => { if (await runEligibility()) setStep(2); }} disabled={!selectedProject || eligibilityLoading}>下一步：填写信息</Button></div></CardContent></Card>}
    {step === 2 && <Card><CardHeader><SectionHeading title={`${selectedProject?.name ?? "资助项目"}申请信息`} description="银行卡完整号码仅参与本次格式校验，服务端只持久化末四位，审计日志不记录原值" /></CardHeader><CardContent className="space-y-5"><div className="grid gap-4 md:grid-cols-2"><Field label="开户银行（可选）"><Input value={form.bankName} onChange={event => update("bankName", event.target.value)} placeholder="如：中国建设银行" /></Field><Field label="银行卡号（可选）"><Input value={form.bankAccount} onChange={event => update("bankAccount", event.target.value)} placeholder={draftId ? "留空表示保持原末四位" : "仅保存末四位"} inputMode="numeric" /></Field><Field label="家庭年收入（可选）"><Input type="number" min={0} max={5000000} value={form.familyAnnualIncome} onChange={event => update("familyAnnualIncome", event.target.value)} /></Field><Field label="家庭成员人数（可选）"><Input type="number" min={1} value={form.familyMembers} onChange={event => update("familyMembers", event.target.value)} /></Field></div><Field label="申请理由（正式提交至少10字）"><Textarea value={form.statement} onChange={event => update("statement", event.target.value)} rows={5} maxLength={2000} placeholder="请说明申请事项和需要资助的原因。AI不会替您编造事实。" /><p className="mt-1 text-right text-[10px] text-muted-foreground">{form.statement.length}/2000</p></Field><Field label="特殊情况说明（可选）"><Textarea value={form.specialCircumstance} onChange={event => update("specialCircumstance", event.target.value)} rows={3} maxLength={1000} /></Field><div className="flex justify-between"><Button variant="outline" onClick={() => setStep(1)}>上一步</Button><Button onClick={() => setStep(3)}>下一步：提交材料</Button></div></CardContent></Card>}
    {step === 3 && <div className="grid gap-5 xl:grid-cols-[1fr_360px]"><div className="space-y-5"><Card><CardHeader><SectionHeading title="所需证据与预处理" description={`${selectedProject?.name ?? "当前项目"}建议提交 ${required.length} 类材料；缺失项由预检提示但不由AI自动拒绝`} /></CardHeader><CardContent><div className="mb-5 grid gap-2 sm:grid-cols-2">{required.map((item, index) => <div key={item} className="flex items-center gap-2 rounded-lg bg-muted/40 p-3 text-xs"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-blue-100 text-[10px] font-bold text-blue-700">{index + 1}</span>{item}</div>)}</div>
      {methodNeedsUpload && <><label className="flex min-h-[145px] cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-blue-200 bg-blue-50/40 p-6 text-center hover:border-blue-400 dark:border-blue-900 dark:bg-blue-950/20"><input type="file" multiple accept="application/pdf,image/jpeg,image/png" className="hidden" onChange={event => { void uploadFiles(event.target.files); event.target.value = ""; }} disabled={uploading} />{uploading ? <Loader2 className="h-9 w-9 animate-spin text-blue-600" /> : <CloudUpload className="h-9 w-9 text-blue-600" />}<p className="mt-3 text-sm font-semibold">{uploading ? "正在保存并运行预处理…" : "选择PDF、JPG或PNG材料"}</p><p className="mt-1 text-[10px] text-muted-foreground">单文件≤10MB，总量≤50MB；命中恶意特征将阻断且不落盘</p></label><div className="mt-4 space-y-2">{materials.map(item => <div key={item.id} className="flex flex-col gap-3 rounded-xl border p-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-3"><span className={`rounded-lg p-2 ${item.processing?.status === "completed" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}><ScanText className="h-4 w-4" /></span><div className="min-w-0"><p className="truncate text-xs font-semibold">{item.name}</p><p className="mt-1 truncate font-mono text-[9px] text-muted-foreground">{formatBytes(item.sizeBytes)} · SHA256 {item.sha256.slice(0, 16)}…</p><p className="mt-1 text-[10px] text-muted-foreground">预处理：{item.processing?.status ?? "processing"} · {item.applicationId ? "已绑定草稿" : "暂存区"}</p></div></div><div className="flex gap-2"><Button asChild size="sm" variant="outline"><Link href={`/application/materials/${item.id}`}>解析详情</Link></Button>{item.processing?.status === "needs_confirmation" && <Button size="sm" onClick={() => void confirmMaterial(item)}>本人确认</Button>}<Button variant="ghost" size="icon" onClick={() => void removeMaterial(item)} aria-label="移除材料"><Trash2 className="h-4 w-4 text-rose-600" /></Button></div></div>)}</div></>}
      {methodNeedsAuthorization && <div className="space-y-3 rounded-xl border p-4"><p className="text-xs font-semibold">明示授权数据源</p>{authorizationOptions.map(item => <label key={item.id} className="flex cursor-pointer items-center gap-3 rounded-lg bg-muted/40 p-3 text-xs"><Checkbox checked={authorizationSources.includes(item.id)} onCheckedChange={checked => toggleAuthorization(item.id, checked === true)} />{item.label}</label>)}</div>}{form.method === "offline-verification" && <Field label="服务窗口材料受理回执号"><Input value={form.offlineReceiptNo} onChange={event => update("offlineReceiptNo", event.target.value)} placeholder="如：FW-20260805-001" /></Field>}</CardContent></Card></div>
      <aside className="space-y-4"><Card><CardHeader><SectionHeading title="提交前受理网关" /></CardHeader><CardContent className="space-y-4"><div><div className="mb-2 flex justify-between text-xs"><span className="text-muted-foreground">材料完整度</span><strong>{completeness}%</strong></div><Progress value={completeness} /></div><Check label="资格规则" value={eligibility?.allowed ? "通过" : "待复核"} ok={Boolean(eligibility?.allowed)} /><Check label="材料预处理" value={unresolved.length ? `${unresolved.length}份待确认` : "已完成"} ok={!unresolved.length} /><Check label="上传文件" value={`${materials.length}份`} ok={!methodNeedsUpload || materials.length > 0} /><Check label="授权数据" value={`${authorizationSources.length}项`} ok={!methodNeedsAuthorization || authorizationSources.length > 0} />{completeness < 100 && <label className="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-[10px] leading-5 text-amber-900"><Checkbox checked={waiverConfirmed} onCheckedChange={checked => setWaiverConfirmed(checked === true)} className="mt-0.5" /><span>我已阅读材料缺失提示，确认当前材料真实，并选择继续提交；最终由人工审核决定是否需要补正。</span></label>}<div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-[10px] leading-5 text-blue-900"><ShieldCheck className="mr-1 inline h-4 w-4" />正式提交将生成受理工单、站内通知、预检报告和不可篡改审计证据。</div><Button variant="outline" className="w-full" disabled={submitting} onClick={() => void submit("draft")}><Save className="mr-2 h-4 w-4" />保存持久化草稿</Button><Button className="w-full" disabled={submitting || unresolved.length > 0} onClick={() => void submit("submit")}><Send className="mr-2 h-4 w-4" />{submitting ? "正在受理…" : "确认提交并生成工单"}</Button><Button variant="ghost" className="w-full" onClick={() => setStep(2)}>返回修改信息</Button></CardContent></Card></aside></div>}
  </div>;
}
function uniqueMaterials(items: UploadedMaterial[]) { return [...new Map(items.map(item => [item.id, item])).values()]; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><p className="mb-2 text-xs font-medium">{label}</p>{children}</div>; }
function Check({ label, value, ok }: { label: string; value: string; ok: boolean }) { return <div className="flex items-center justify-between gap-3 text-xs"><span className="text-muted-foreground">{label}</span><span className={`flex items-center font-medium ${ok ? "text-emerald-700" : "text-rose-700"}`}>{ok && <CheckCircle2 className="mr-1 h-3.5 w-3.5" />}{value}</span></div>; }

