"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Bell, CheckCircle2, ClipboardCheck, Loader2, RefreshCw, Search } from "lucide-react";
import { EnterprisePageHeader } from "@/components/enterprise/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
interface Notice { id: string; applicationId: string; ticketId: string; type: "announcement" | "receipt" | "correction" | "progress"; title: string; content: string; channels: string[]; deliveryStatus: string; createdAt: string; readAt?: string; actionRoute?: string; actionLabel?: string; scenarioId?: string }
interface Payload { notices: Notice[]; unread: number }
interface Envelope<T> { success: boolean; data?: T; error?: string }
function headers(json = false): HeadersInit { const token = localStorage.getItem("token"); return { ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(json ? { "Content-Type": "application/json" } : {}) }; }
export default function NotificationCenterPage() {
  const [data, setData] = useState<Payload>({ notices: [], unread: 0 }); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [keyword, setKeyword] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/application-intake/notifications", { headers: headers(), cache: "no-store" }); const body = await response.json() as Envelope<Payload>; if (!response.ok || !body.success || !body.data) throw new Error(body.error ?? "通知加载失败"); setData(body.data); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "通知加载失败"); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => data.notices.filter(item => `${item.title}${item.content}${item.applicationId}${item.ticketId}`.toLocaleLowerCase().includes(keyword.trim().toLocaleLowerCase())), [data.notices, keyword]);
  async function markRead(notice: Notice) { if (notice.readAt) return; const response = await fetch(`/api/application-intake/notifications/${encodeURIComponent(notice.id)}/actions`, { method: "POST", headers: headers(true), body: JSON.stringify({ action: "mark_read" }) }); if (response.ok) await load(); }
  return <div className="space-y-6 pb-10"><EnterprisePageHeader eyebrow="DELIVERY & ACKNOWLEDGEMENT" title="业务通知中心" description="展示由申请受理、补正和流程状态真实触发的站内通知；消息与申请、受理工单保持可追溯关联。" icon={Bell} badge={`${data.unread} UNREAD`} />
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="relative w-full sm:max-w-md"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input value={keyword} onChange={event => setKeyword(event.target.value)} placeholder="搜索通知、申请或工单" className="pl-9" /></div><Button variant="outline" onClick={() => void load()} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading ? "animate-spin" : ""}`} />刷新</Button></div>
    {error && <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{error}。本业务通知中心当前仅向学生本人返回申请通知。</div>}
    <div className="space-y-3">{loading ? <Card><CardContent className="flex h-32 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-blue-600" /></CardContent></Card> : visible.length ? visible.map(notice => <Card key={notice.id} className={!notice.readAt ? "border-blue-300 bg-blue-50/30" : ""}><CardContent className="flex flex-col gap-4 p-5 lg:flex-row lg:items-start lg:justify-between"><div className="flex gap-3"><span className={`mt-0.5 flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${notice.type === "correction" ? "bg-amber-100 text-amber-800" : "bg-blue-100 text-blue-800"}`}>{notice.type === "correction" ? <ClipboardCheck className="h-5 w-5" /> : <CheckCircle2 className="h-5 w-5" />}</span><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-semibold">{notice.title}</h2>{!notice.readAt && <Badge className="bg-blue-600 text-white">未读</Badge>}<Badge variant="outline">{notice.deliveryStatus}</Badge>{notice.scenarioId && <Badge className="bg-violet-100 text-violet-700">视频场景</Badge>}</div><p className="mt-2 text-xs leading-6 text-muted-foreground">{notice.content}</p><p className="mt-2 font-mono text-[9px] text-muted-foreground">{notice.applicationId} · {notice.ticketId} · {new Date(notice.createdAt).toLocaleString("zh-CN")} · {notice.channels.join(" / ")}</p></div></div><div className="flex shrink-0 flex-wrap gap-2"><Button asChild size="sm" variant={notice.type === "announcement" ? "default" : "outline"}><Link href={notice.actionRoute ?? `/application/detail?id=${notice.applicationId}`}>{notice.actionLabel ?? "申请详情"}</Link></Button>{notice.ticketId !== "VIDEO-TICKET-PENDING" && <Button asChild size="sm" variant="outline"><Link href={`/application/intake/${notice.ticketId}`}>工单详情</Link></Button>}{!notice.readAt && <Button size="sm" onClick={() => void markRead(notice)}>标记已读</Button>}</div></CardContent></Card>) : <Card><CardContent className="py-16 text-center text-sm text-muted-foreground">暂无由真实业务流程触发的通知</CardContent></Card>}</div>
  </div>;
}
