"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, Database, FileLock2, Fingerprint, HardDrive, Link2, RefreshCw, ShieldAlert } from "lucide-react";
import { EnterprisePageHeader } from "@/components/enterprise/page-header";
import { MetricCard, SectionHeading, StatusPill } from "@/components/enterprise/dashboard";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";

interface Integrity { valid: boolean; total: number; verifiedAt: string; genesisHash: string | null; headHash: string | null; brokenAt?: string; storage: string; algorithm: string }
interface Envelope<T> { success: boolean; data?: T; error?: string }
function authHeaders(): HeadersInit { const token = localStorage.getItem("token"); return token ? { Authorization: `Bearer ${token}` } : {}; }
export default function AuditIntegrityPage() {
  const [data, setData] = useState<Integrity | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const verify = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/audit-evidence/integrity", { headers: authHeaders(), cache: "no-store" }); const body = await response.json() as Envelope<Integrity>; if (!response.ok || !body.success || !body.data) throw new Error(body.error ?? "证据链校验失败"); setData(body.data); } catch (reason) { setError(reason instanceof Error ? reason.message : "证据链校验失败"); } finally { setLoading(false); } }, []);
  useEffect(() => { void verify(); }, [verify]);
  return <div className="space-y-6"><EnterprisePageHeader eyebrow="EVIDENCE CHAIN INTEGRITY" title="审计证据链完整性中心" description="从GENESIS节点开始逐条重算SHA-256记录哈希并验证previousHash引用。存储层只提供追加接口，不提供更新和删除API。" icon={Fingerprint} badge={data ? (data.valid ? "VERIFIED" : "BROKEN") : "VERIFYING"} actions={[{ label: "重新校验", icon: RefreshCw, variant: "outline", onClick: () => void verify(), disabled: loading }]} />
    <Link href="/audit-center" className="inline-flex items-center text-xs font-medium text-muted-foreground hover:text-foreground"><ArrowLeft className="mr-1 h-4 w-4" />返回审计总览</Link>
    {error && <div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}
    {loading && !data && <div className="flex min-h-[360px] items-center justify-center text-sm text-muted-foreground"><RefreshCw className="mr-2 h-5 w-5 animate-spin text-blue-600" />正在重算全部链式哈希…</div>}
    {data && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="链节点数量" value={data.total.toString()} detail="每个人类与AI操作一个节点" icon={Link2} tone="blue" /><MetricCard label="完整性状态" value={data.valid ? "通过" : "失败"} detail={data.valid ? "未发现断链或字段篡改" : `断点 ${data.brokenAt ?? "未知"}`} icon={data.valid ? CheckCircle2 : ShieldAlert} tone={data.valid ? "emerald" : "rose"} /><MetricCard label="摘要算法" value={data.algorithm} detail="稳定键序列化后计算" icon={FileLock2} tone="violet" /><MetricCard label="物理存储" value="只追加" detail="JSONL演示适配器；生产映射WORM" icon={HardDrive} tone="cyan" /></div>
      <Card className={`border-border shadow-sm ${data.valid ? "bg-gradient-to-br from-emerald-50/70 to-card dark:from-emerald-950/20" : "bg-rose-50"}`}><CardContent className="p-7"><div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-4"><span className={`flex h-16 w-16 items-center justify-center rounded-2xl text-white shadow-lg ${data.valid ? "bg-emerald-600" : "bg-rose-600"}`}>{data.valid ? <CheckCircle2 className="h-7 w-7" /> : <ShieldAlert className="h-7 w-7" />}</span><div><StatusPill status={data.valid ? "healthy" : "danger"} label={data.valid ? "CHAIN VERIFIED" : "CHAIN BROKEN"} /><h2 className="mt-3 text-2xl font-bold text-foreground">{data.valid ? "证据链校验通过" : "检测到证据链异常"}</h2><p className="mt-1 text-xs text-muted-foreground">校验时间 {new Date(data.verifiedAt).toLocaleString("zh-CN")}</p></div></div><Link href="/audit-center/events"><Button>查看全部链节点</Button></Link></div></CardContent></Card>
      <div className="grid gap-5 xl:grid-cols-2"><Card className="border-border shadow-sm"><CardHeader><SectionHeading title="GENESIS / 首节点哈希" description="第一个证据节点引用固定GENESIS标识" /></CardHeader><CardContent><Hash value={data.genesisHash ?? "暂无节点"} /></CardContent></Card><Card className="border-border shadow-sm"><CardHeader><SectionHeading title="HEAD / 当前链头哈希" description="任何新事件只能在当前链头之后追加" /></CardHeader><CardContent><Hash value={data.headHash ?? "暂无节点"} /></CardContent></Card></div>
      <Card className="border-border shadow-sm"><CardHeader><SectionHeading title="不可篡改控制实现" description="界面、API和存储三层同时约束；生产部署时映射PostgreSQL只读触发器和WORM对象存储" /></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Control icon={Link2} title="链式绑定" text="每条记录的recordHash覆盖全部证据字段与previousHash，字段变化立即断链。" /><Control icon={Database} title="只追加接口" text="核心存储仅暴露append/list/get/verify；系统没有UPDATE或DELETE审计接口。" /><Control icon={FileLock2} title="P4最小证据" text="自动屏蔽完整Prompt、Response、RAG全文与高敏个人字段，只存摘要与摘要哈希。" /><Control icon={HardDrive} title="分级保留" text="P0-P3保留3年，P4保留10年，P5与AI撤回保留50年并要求主管部门审批。" /></CardContent></Card></>}
  </div>;
}
function Hash({ value }: { value: string }) { return <div className="rounded-xl border border-slate-800 bg-slate-950 p-5"><p className="break-all font-mono text-[11px] leading-6 text-emerald-300">{value}</p></div>; }
function Control({ icon: Icon, title, text }: { icon: typeof Link2; title: string; text: string }) { return <div className="rounded-xl border border-border p-4"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-blue-50 text-blue-700 dark:bg-blue-950/40 dark:text-blue-300"><Icon className="h-4 w-4" /></span><p className="mt-3 text-sm font-semibold text-foreground">{title}</p><p className="mt-1 text-[11px] leading-5 text-muted-foreground">{text}</p></div>; }
