"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Activity, ArrowRight, Bot, CheckCircle2, Clock3, Filter, Fingerprint, GitBranch, Globe2, LockKeyhole, Play, RefreshCw, Search, ShieldCheck, UserRoundCog, XCircle } from "lucide-react";
import { EnterprisePageHeader } from "@/components/enterprise/page-header";
import { MetricCard, SectionHeading, StatusPill } from "@/components/enterprise/dashboard";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

interface DimensionResult { code: string; name: string; status: string; reason: string; policyRef: string }
interface DecisionRecord { id: string; scenarioId: string; scenarioName: string; actorRole: string; actorType: "human" | "agent"; permission: string; operation: string; resourceId: string; resourceType: string; sensitiveLevel: string; geographicLevel: string; decision: { status: string; reason: string; deniedBy: string[]; pendingBy: string[]; dimensions: DimensionResult[]; formula: unknown }; createdAt: string; initiatedBy: string }
interface DimensionSummary { code: string; name: string; category: string; description: string; policyRef: string; total: number; allowed: number; denied: number; pending: number }
interface Scenario { id: string; name: string; category: string; description: string; actorId: string; actorRole: string; expectedStatus: string }
interface OverviewPayload { generatedAt: string; summary: { total: number; allowed: number; denied: number; pending: number; agent: number; dimensions: number }; byDimension: DimensionSummary[]; decisions: DecisionRecord[]; scenarios: Scenario[]; engine: { version: string; mode: string; persistence: string; agentFormula: string } }
interface Envelope<T> { success: boolean; data?: T; error?: string; message?: string }
interface SimulationResponse { record: DecisionRecord; replayed: boolean }

const STATUS_LABELS: Record<string, string> = { ALLOW: "允许", DENY: "拒绝", PENDING_APPROVAL: "待审批", ESCALATE: "升级处置" };
const DIMENSION_ICONS = [UserRoundCog, Fingerprint, Filter, Clock3, Globe2, GitBranch, Bot, LockKeyhole, Activity];
function headers(json = false): HeadersInit { const token = localStorage.getItem("token"); return { ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(json ? { "Content-Type": "application/json" } : {}) }; }
function decisionTone(status: string): "healthy" | "danger" | "warning" { return status === "ALLOW" ? "healthy" : status === "DENY" ? "danger" : "warning"; }

export default function AccessControlPage() {
  const [data, setData] = useState<OverviewPayload | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [status, setStatus] = useState("all"); const [keyword, setKeyword] = useState("");
  const [scenarioId, setScenarioId] = useState(""); const [geo, setGeo] = useState("default");
  const [trusted, setTrusted] = useState(true); const [mfa, setMfa] = useState(true); const [confirmations, setConfirmations] = useState("default"); const [purpose, setPurpose] = useState("");
  const [running, setRunning] = useState(false); const [simulation, setSimulation] = useState<DecisionRecord | null>(null);

  const load = useCallback(async () => {
    setLoading(true); setError("");
    try { const response = await fetch("/api/access-control/overview", { headers: headers(), cache: "no-store" }); const body = await response.json() as Envelope<OverviewPayload>; if (!response.ok || !body.success || !body.data) throw new Error(body.error ?? "权限控制中心加载失败"); setData(body.data); setScenarioId(current => current || body.data?.scenarios[0]?.id || ""); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "权限控制中心加载失败"); } finally { setLoading(false); }
  }, []);
  useEffect(() => { void load(); }, [load]);

  const decisions = useMemo(() => { const term = keyword.trim().toLocaleLowerCase(); return data?.decisions.filter(item => (status === "all" || item.decision.status === status) && (!term || `${item.scenarioName}${item.actorRole}${item.permission}${item.resourceId}`.toLocaleLowerCase().includes(term))) ?? []; }, [data, keyword, status]);
  const selectedScenario = data?.scenarios.find(item => item.id === scenarioId);

  const runSimulation = async () => {
    if (!scenarioId) return; setRunning(true); setError("");
    const overrides: Record<string, unknown> = { deviceTrusted: trusted, mfaVerified: mfa };
    if (geo !== "default") overrides.geographicLevel = geo;
    if (confirmations !== "default") overrides.confirmations = Number(confirmations);
    if (purpose.trim()) overrides.purpose = purpose.trim();
    try { const response = await fetch("/api/access-control/simulate", { method: "POST", headers: { ...headers(true), "Idempotency-Key": `permission-ui-${crypto.randomUUID()}` }, body: JSON.stringify({ scenarioId, overrides }) }); const body = await response.json() as Envelope<SimulationResponse>; if (!response.ok || !body.success || !body.data?.record) throw new Error(body.error ?? "权限模拟失败"); setSimulation(body.data.record); await load(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "权限模拟失败"); } finally { setRunning(false); }
  };

  return <div className="space-y-6">
    <EnterprisePageHeader eyebrow="ZERO TRUST ACCESS CONTROL" title="九维权限与Agent执行控制中心" description="每次操作同时验证角色、组织、数据范围、时间、地理、流程、AI等级、敏感度和操作类型；Agent还必须通过工具注册与安全护栏交集。指标可下钻、决策可查看完整证据，策略模拟不会写入业务数据。" icon={ShieldCheck} badge="9 DIMENSION · DETERMINISTIC" actions={[{ label: "刷新决策流水", icon: RefreshCw, variant: "outline", onClick: () => void load(), disabled: loading }]} />
    {error && <div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700 dark:border-rose-900/70 dark:bg-rose-950/30 dark:text-rose-200">{error}</div>}
    {loading && !data && <div className="flex min-h-[360px] items-center justify-center text-sm text-muted-foreground"><RefreshCw className="mr-2 h-5 w-5 animate-spin text-blue-600" />正在加载确定性策略与决策证据…</div>}

    {data && <>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
        <button className="text-left" onClick={() => setStatus("all")}><MetricCard label="决策总数" value={data.summary.total.toString()} detail="点击查看全部决策流水" icon={Activity} tone="blue" /></button>
        <button className="text-left" onClick={() => setStatus("ALLOW")}><MetricCard label="已允许" value={data.summary.allowed.toString()} detail="九个维度全部通过" icon={CheckCircle2} tone="emerald" /></button>
        <button className="text-left" onClick={() => setStatus("DENY")}><MetricCard label="已阻断" value={data.summary.denied.toString()} detail="任一维度拒绝即阻断" icon={XCircle} tone="amber" /></button>
        <button className="text-left" onClick={() => setStatus("PENDING_APPROVAL")}><MetricCard label="待审批" value={data.summary.pending.toString()} detail="条件未满足，操作挂起" icon={Clock3} tone="cyan" /></button>
        <MetricCard label="Agent判定" value={data.summary.agent.toString()} detail="附带完整交集公式证据" icon={Bot} tone="violet" />
      </div>

      <Card className="border-border shadow-sm"><CardHeader><SectionHeading title="九维策略健康与详情下钻" description="每张卡片进入独立维度详情页，查看规则、统计和命中记录" /></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.byDimension.map((item, index) => { const Icon = DIMENSION_ICONS[index] ?? ShieldCheck; const pass = item.total ? Math.round(item.allowed / item.total * 100) : 100; return <Link key={item.code} href={`/access-control/dimensions/${item.code}`} className="group rounded-xl border border-border bg-card p-4 transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md dark:hover:border-blue-700"><div className="flex items-start justify-between gap-3"><span className="rounded-xl bg-blue-50 p-2.5 text-blue-700 dark:bg-blue-950/40 dark:text-blue-300"><Icon className="h-5 w-5" /></span><div className="text-right"><p className="text-xl font-bold text-foreground">{pass}%</p><p className="text-[9px] text-muted-foreground">本批通过率</p></div></div><div className="mt-4 flex items-center justify-between"><div><p className="text-sm font-semibold text-foreground">{item.name}</p><p className="mt-1 text-[10px] text-muted-foreground">拒绝 {item.denied} · 待审批 {item.pending}</p></div><ArrowRight className="h-4 w-4 text-muted-foreground transition group-hover:translate-x-1 group-hover:text-blue-600" /></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-blue-500" style={{ width: `${pass}%` }} /></div></Link>; })}</CardContent></Card>

      <Tabs defaultValue="decisions" className="space-y-5"><TabsList className="h-auto rounded-xl border border-border bg-card p-1"><TabsTrigger value="decisions">决策流水与详情</TabsTrigger><TabsTrigger value="simulator">策略模拟器</TabsTrigger><TabsTrigger value="formula">Agent权限公式</TabsTrigger></TabsList>
        <TabsContent value="decisions"><Card className="overflow-hidden border-border shadow-sm"><CardHeader><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><SectionHeading title="权限决策流水" description={`${decisions.length} 条结果；列表行可进入九维证据详情`} /><div className="flex flex-col gap-2 sm:flex-row"><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input value={keyword} onChange={event => setKeyword(event.target.value)} placeholder="检索场景、角色、权限或资源" className="w-full pl-9 sm:w-72" /></div><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-full sm:w-40"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">全部结果</SelectItem><SelectItem value="ALLOW">允许</SelectItem><SelectItem value="DENY">拒绝</SelectItem><SelectItem value="PENDING_APPROVAL">待审批</SelectItem></SelectContent></Select></div></div></CardHeader><CardContent className="p-0"><DecisionTable decisions={decisions} /></CardContent></Card></TabsContent>

        <TabsContent value="simulator" className="grid gap-5 xl:grid-cols-[1fr_1.1fr]"><Card className="border-border shadow-sm"><CardHeader><SectionHeading title="确定性策略模拟器" description="从服务器预置回归场景运行，只记录权限结果，不执行任何业务动作" /></CardHeader><CardContent className="space-y-4"><div><Label text="测试场景" /><Select value={scenarioId} onValueChange={value => { setScenarioId(value); setSimulation(null); }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{data.scenarios.map(item => <SelectItem key={item.id} value={item.id}>{item.name} · {item.actorRole}</SelectItem>)}</SelectContent></Select>{selectedScenario && <div className="mt-2 rounded-lg bg-muted/50 p-3 text-xs leading-5 text-muted-foreground">{selectedScenario.description}<span className="ml-2 font-medium text-foreground">基准预期：{STATUS_LABELS[selectedScenario.expectedStatus]}</span></div>}</div><div className="grid gap-3 sm:grid-cols-2"><div><Label text="地理位置覆盖" /><Select value={geo} onValueChange={setGeo}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="default">使用场景默认值</SelectItem><SelectItem value="L1">L1 校内核心区</SelectItem><SelectItem value="L2">L2 校内非核心</SelectItem><SelectItem value="L3">L3 外勤地址</SelectItem><SelectItem value="L4">L4 国内异地</SelectItem><SelectItem value="L5">L5 境外/未知</SelectItem></SelectContent></Select></div><div><Label text="人工确认次数" /><Select value={confirmations} onValueChange={setConfirmations}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="default">使用场景默认值</SelectItem><SelectItem value="0">0 次</SelectItem><SelectItem value="1">1 次</SelectItem><SelectItem value="2">2 次</SelectItem></SelectContent></Select></div></div><div className="grid gap-3 sm:grid-cols-2"><Toggle label="可信设备" value={trusted} onChange={setTrusted} /><Toggle label="已完成MFA" value={mfa} onChange={setMfa} /></div><div><Label text="查阅/导出用途" /><Input value={purpose} onChange={event => setPurpose(event.target.value)} placeholder="留空则沿用场景用途；输入内容用于测试用途登记规则" maxLength={200} /></div><Button className="w-full" onClick={() => void runSimulation()} disabled={running || !scenarioId}><Play className="mr-2 h-4 w-4" />{running ? "正在执行九维判定…" : "运行策略模拟"}</Button></CardContent></Card>
          <Card className="border-border shadow-sm"><CardHeader><SectionHeading title="本次模拟结果" description="显示整体结果与九维逐项状态，可继续下钻完整证据" /></CardHeader><CardContent>{simulation ? <div className="space-y-5"><div className={`rounded-xl border p-5 ${simulation.decision.status === "ALLOW" ? "border-emerald-200 bg-emerald-50 dark:border-emerald-900 dark:bg-emerald-950/25" : simulation.decision.status === "DENY" ? "border-rose-200 bg-rose-50 dark:border-rose-900 dark:bg-rose-950/25" : "border-amber-200 bg-amber-50 dark:border-amber-900 dark:bg-amber-950/25"}`}><div className="flex items-center justify-between"><div><p className="text-xs text-muted-foreground">{simulation.scenarioName}</p><p className="mt-2 text-2xl font-bold text-foreground">{STATUS_LABELS[simulation.decision.status]}</p></div><StatusPill status={decisionTone(simulation.decision.status)} label={STATUS_LABELS[simulation.decision.status]} /></div><p className="mt-3 text-xs leading-5 text-muted-foreground">{simulation.decision.reason}</p></div><div className="grid grid-cols-3 gap-2">{simulation.decision.dimensions.map(item => <div key={item.code} className="rounded-lg border border-border p-2 text-center"><p className="truncate text-[10px] text-muted-foreground">{item.name.replace("维度", "")}</p><p className={`mt-1 text-[10px] font-semibold ${item.status === "ALLOW" ? "text-emerald-600" : item.status === "DENY" ? "text-rose-600" : "text-amber-600"}`}>{STATUS_LABELS[item.status]}</p></div>)}</div><Link href={`/access-control/decisions/${simulation.id}`}><Button variant="outline" className="w-full">查看完整判定证据<ArrowRight className="ml-2 h-4 w-4" /></Button></Link></div> : <div className="flex min-h-[360px] flex-col items-center justify-center text-center text-sm text-muted-foreground"><ShieldCheck className="mb-3 h-10 w-10 text-blue-500" /><p>选择场景并运行后，这里会展示真实判定结果。</p><p className="mt-2 text-xs">模拟器不会修改申请、审批、资金或账号状态。</p></div>}</CardContent></Card></TabsContent>

        <TabsContent value="formula"><Card className="border-border shadow-sm"><CardContent className="p-6"><div className="rounded-2xl border border-blue-200 bg-gradient-to-br from-blue-50 to-cyan-50 p-6 dark:border-blue-900 dark:from-blue-950/40 dark:to-cyan-950/20"><Badge className="bg-blue-600 text-white">AND / INTERSECTION</Badge><p className="mt-4 font-mono text-sm font-semibold leading-7 text-foreground">Agent可执行操作 = {data.engine.agentFormula}</p><p className="mt-3 max-w-4xl text-xs leading-6 text-muted-foreground">所有分量均由服务器注册表和确定性程序计算，模型不能修改判定结果。任一分量拒绝即整体阻断，阻断结果进入权限决策流水和审计日志。</p></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{["用户角色权限是执行上限", "Agent必须属于角色专属团队", "工具必须在服务器注册", "L4只建议、L5禁止AI执行", "P3以上登记用途", "流程节点与处理人必须匹配", "时间和地理实时参与判定", "阻断与待审批均保留证据"].map((item, index) => <div key={item} className="rounded-xl border border-border p-4"><span className="text-[10px] font-bold text-blue-600">RULE {String(index + 1).padStart(2, "0")}</span><p className="mt-2 text-xs leading-5 text-foreground/80">{item}</p></div>)}</div></CardContent></Card></TabsContent>
      </Tabs>
      <p className="text-right text-[10px] text-muted-foreground">引擎 {data.engine.version} · {new Date(data.generatedAt).toLocaleString("zh-CN")}</p>
    </>}
  </div>;
}

function DecisionTable({ decisions }: { decisions: DecisionRecord[] }) { return decisions.length ? <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-y border-border bg-muted/50 text-[10px] uppercase tracking-wider text-muted-foreground"><tr><th className="px-5 py-3">判定场景</th><th className="px-4 py-3">主体</th><th className="px-4 py-3">操作与资源</th><th className="px-4 py-3">条件</th><th className="px-4 py-3">结果</th><th className="px-5 py-3 text-right">详情</th></tr></thead><tbody>{decisions.map(item => <tr key={item.id} className="border-b border-border last:border-0 hover:bg-muted/30"><td className="px-5 py-4"><p className="font-semibold text-foreground">{item.scenarioName}</p><p className="mt-1 font-mono text-[9px] text-muted-foreground">{item.id}</p></td><td className="px-4 py-4"><p className="text-foreground">{item.actorRole}</p><p className="mt-1 text-[10px] text-muted-foreground">{item.actorType === "agent" ? "Agent代理" : "人工操作"}</p></td><td className="px-4 py-4"><p className="font-medium text-foreground">{item.operation} · {item.resourceType}</p><p className="mt-1 font-mono text-[9px] text-muted-foreground">{item.permission} · {item.resourceId}</p></td><td className="px-4 py-4"><Badge variant="outline">{item.sensitiveLevel}</Badge><Badge variant="outline" className="ml-1">{item.geographicLevel}</Badge></td><td className="px-4 py-4"><StatusPill status={decisionTone(item.decision.status)} label={STATUS_LABELS[item.decision.status]} /></td><td className="px-5 py-4 text-right"><Link href={`/access-control/decisions/${item.id}`}><Button size="sm" variant="ghost">查看证据<ArrowRight className="ml-1 h-3.5 w-3.5" /></Button></Link></td></tr>)}</tbody></table></div> : <div className="py-16 text-center text-sm text-muted-foreground">没有符合筛选条件的决策记录。</div>; }
function Label({ text }: { text: string }) { return <p className="mb-2 text-xs font-medium text-foreground">{text}</p>; }
function Toggle({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <div className="flex items-center justify-between rounded-xl border border-border p-3"><span className="text-xs text-foreground">{label}</span><Switch checked={value} onCheckedChange={onChange} /></div>; }

