"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Activity, AlertTriangle, ArrowRight, Bot, BrainCircuit, CheckCircle2, ChevronRight, CirclePause, CirclePlay, Clock3, Database, ExternalLink, FileCheck2, Fingerprint, GitBranch, Landmark, Loader2, LockKeyhole, MessageSquareText, Network, Pause, Play, Plug, RefreshCw, RotateCcw, Send, ShieldCheck, Sparkles, UserCheck, UsersRound, Workflow, Zap } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import type { CollaborationMessage, CollaborationRun, CollaborationRunStatus, CollaborationSnapshot, CollaborationStage, CollaborationTraceKind } from "@/lib/ai/hardship-collaboration-store";

interface Envelope<T> { success: boolean; data?: T; error?: string; message?: string }
const VIDEO_HARDSHIP_SCENARIO_ID = "VIDEO-HARDSHIP-2026-001";
const DEFAULT_COMMAND = "小海豚，请协调各岗位完成一笔临时困难补助，从发布通知、学生申请、分层审核到财务、银行到账和审计归档。";
const STATUS_NAMES: Record<CollaborationRunStatus, string> = { ready: "场景就绪", running: "运行中", paused: "已暂停", awaiting_human: "等待人工", completed: "已完成", failed: "执行失败" };
const TRACE_STYLES: Record<CollaborationTraceKind, string> = { WORKFLOW: "text-blue-200 bg-blue-400/10 border-blue-300/15", MODEL: "text-violet-200 bg-violet-400/10 border-violet-300/15", RAG: "text-cyan-200 bg-cyan-400/10 border-cyan-300/15", SKILL: "text-fuchsia-200 bg-fuchsia-400/10 border-fuchsia-300/15", PLUGIN: "text-indigo-200 bg-indigo-400/10 border-indigo-300/15", MCP: "text-amber-200 bg-amber-400/10 border-amber-300/15", PERMISSION: "text-emerald-200 bg-emerald-400/10 border-emerald-300/15", AUDIT: "text-slate-200 bg-slate-400/10 border-slate-300/15" };

function headers(json = true): HeadersInit {
  const token = localStorage.getItem("token");
  return { ...(json ? { "Content-Type": "application/json" } : {}), ...(token ? { Authorization: `Bearer ${token}` } : {}) };
}
function mutationKey(prefix: string) { return `${prefix}-${Date.now()}-${crypto.randomUUID()}`; }
function progress(run: CollaborationRun) { return Math.round(run.stages.filter(stage => stage.status === "completed").length / run.stages.length * 100); }
function activeStage(run: CollaborationRun) { return run.stages.find(stage => stage.status !== "completed") ?? run.stages.at(-1)!; }

export function CollaborationCommandCenter({ initialRunId, initialScenarioId = VIDEO_HARDSHIP_SCENARIO_ID }: { initialRunId?: string; initialScenarioId?: string }) {
  const router = useRouter();
  const [snapshot, setSnapshot] = useState<CollaborationSnapshot | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState("");
  const [autoRun, setAutoRun] = useState(false);
  const [messageText, setMessageText] = useState<{ type: "success" | "error"; text: string } | null>(null);
  const [createOpen, setCreateOpen] = useState(false);
  const [resetOpen, setResetOpen] = useState(false);
  const [gateOpen, setGateOpen] = useState(false);
  const [command, setCommand] = useState(DEFAULT_COMMAND);
  const [comment, setComment] = useState("已核对模拟业务对象、权限范围与证据摘要，同意进入下一节点。");
  const [resetComment, setResetComment] = useState("为下一次视频录制恢复固定初始场景，并保留旧实例审计记录。");
  const chatRef = useRef<HTMLDivElement>(null);

  const load = useCallback(async (runId?: string, scenarioId = initialScenarioId) => {
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (runId) params.set("runId", runId); else if (scenarioId) params.set("scenario", scenarioId);
      const response = await fetch(`/api/ai/collaboration?${params.toString()}`, { headers: headers(false), cache: "no-store" });
      const body = await response.json() as Envelope<CollaborationSnapshot>;
      if (!response.ok || !body.success || !body.data) throw new Error(body.error ?? "协同运行加载失败");
      setSnapshot(body.data);
    } catch (error) { setMessageText({ type: "error", text: error instanceof Error ? error.message : "协同运行加载失败" }); }
    finally { setLoading(false); }
  }, [initialScenarioId]);
  useEffect(() => { void load(initialRunId, initialScenarioId); }, [initialRunId, initialScenarioId, load]);
  useEffect(() => { if (chatRef.current) chatRef.current.scrollTop = chatRef.current.scrollHeight; }, [snapshot?.selectedRun.messages.length]);

  const post = useCallback(async (body: Record<string, unknown>, prefix: string) => {
    setBusy(prefix); setMessageText(null);
    try {
      const response = await fetch("/api/ai/collaboration", { method: "POST", headers: { ...headers(), "Idempotency-Key": mutationKey(prefix) }, body: JSON.stringify(body) });
      const payload = await response.json() as Envelope<CollaborationRun>;
      if (!response.ok || !payload.success) throw new Error(payload.error ?? "协同操作失败");
      const runId = payload.data?.id;
      await load(runId);
      setMessageText({ type: "success", text: payload.message ?? "运行状态已更新并写入审计。" });
      return payload.data ?? null;
    } catch (error) { setMessageText({ type: "error", text: error instanceof Error ? error.message : "协同操作失败" }); return null; }
    finally { setBusy(""); }
  }, [load]);

  const run = snapshot?.selectedRun;
  useEffect(() => {
    if (!autoRun || !run || run.status !== "running" || busy) return;
    const timer = window.setTimeout(() => { void post({ action: "advance", runId: run.id, expectedVersion: run.version }, `advance-${run.id}-${run.version}`); }, 1050);
    return () => window.clearTimeout(timer);
  }, [autoRun, busy, post, run]);
  useEffect(() => { if (run && run.status !== "running") setAutoRun(false); }, [run]);

  async function createRun() {
    if (!run || !snapshot?.scenario) return;
    const created = await post({ action: "start_scenario", scenarioId: snapshot.scenario.id, expectedVersion: run.version, command }, "start-video-scenario");
    if (created) { setCreateOpen(false); setAutoRun(true); router.replace(`/agent/monitor/collaboration/${created.id}`); }
  }
  async function resetScenario() {
    if (!run || !snapshot?.scenario) return;
    const reset = await post({ action: "reset_scenario", scenarioId: snapshot.scenario.id, expectedVersion: run.version, comment: resetComment, humanConfirmed: true }, "reset-video-scenario");
    if (reset) { setResetOpen(false); setAutoRun(false); router.replace(`/agent/monitor/collaboration/${reset.id}`); }
  }
  async function advance() { if (run) await post({ action: "advance", runId: run.id, expectedVersion: run.version }, `advance-${run.id}-${run.version}`); }
  async function control(action: "pause" | "resume" | "retry") { if (run) await post({ action: "control", controlAction: action, runId: run.id, expectedVersion: run.version }, `${action}-${run.id}-${run.version}`); }
  async function confirmGate() {
    if (!run) return;
    const confirmed = await post({ action: "confirm_gate", runId: run.id, expectedVersion: run.version, comment, humanConfirmed: true }, `confirm-${run.id}-${run.version}`);
    if (confirmed) { setGateOpen(false); setAutoRun(true); }
  }

  if (loading && !snapshot) return <div className="flex min-h-[70vh] items-center justify-center"><div className="text-center"><Loader2 className="mx-auto h-8 w-8 animate-spin text-blue-600" /><p className="mt-3 text-sm text-muted-foreground">正在连接工作流运行时与Agent OS…</p></div></div>;
  if (!snapshot || !run) return <div className="enterprise-panel p-10 text-center"><AlertTriangle className="mx-auto h-8 w-8 text-rose-500" /><p className="mt-3 font-semibold">协同运行暂时不可用</p><Button className="mt-4" onClick={() => void load(initialRunId)}>重新加载</Button></div>;

  const current = activeStage(run);
  const completed = run.stages.filter(stage => stage.status === "completed").length;
  return <div className="space-y-5 pb-10 text-slate-100">
    <section className="relative overflow-hidden rounded-[26px] border border-slate-800 bg-[#06101e] p-6 shadow-[0_28px_80px_rgba(2,6,23,.28)] lg:p-7">
      <div className="pointer-events-none absolute inset-0 opacity-45" style={{ backgroundImage: "linear-gradient(rgba(56,189,248,.055) 1px,transparent 1px),linear-gradient(90deg,rgba(56,189,248,.055) 1px,transparent 1px)", backgroundSize: "34px 34px" }} />
      <div className="pointer-events-none absolute -right-20 -top-32 h-96 w-96 rounded-full bg-blue-600/25 blur-[120px]" />
      <div className="relative flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex flex-wrap gap-2"><Badge className="border border-cyan-300/20 bg-cyan-400/10 text-cyan-100">VIDEO SCENARIO · LIVE</Badge><Badge className="border border-emerald-300/20 bg-emerald-400/10 text-emerald-100">固定场景单一真值</Badge><Badge className="border border-amber-300/20 bg-amber-400/10 text-amber-100">模拟数据 · 真实交互</Badge>{snapshot.scenario && <Badge className="border border-violet-300/20 bg-violet-400/10 text-violet-100">REV {snapshot.scenario.revision}</Badge>}</div><h1 className="mt-4 text-2xl font-bold tracking-tight lg:text-3xl">小海豚多Agent协作指挥台</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">固定视频场景由服务器单一状态源驱动。每次推进必须同时满足角色闸门、版本校验和业务适配器真实性门禁，禁止用动画或Trace替代业务写入。</p></div><div className="flex flex-wrap gap-2"><select value={run.id} onChange={event => router.push(`/agent/monitor/collaboration/${event.target.value}`)} className="h-9 max-w-64 rounded-lg border border-slate-700 bg-slate-900 px-3 text-[10px] text-slate-300 outline-none"><option value={run.id}>{run.runNo} · {STATUS_NAMES[run.status]}</option>{snapshot.runs.filter(item => item.id !== run.id).map(item => <option key={item.id} value={item.id}>{item.runNo} · {STATUS_NAMES[item.status]}</option>)}</select><Link href={`/agent/monitor/collaboration/${run.id}`} className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-slate-700 bg-slate-900 px-3 text-[10px] font-semibold text-slate-300 transition hover:bg-slate-800 hover:text-white">运行详情<ExternalLink className="h-3.5 w-3.5" /></Link>{run.status === "completed" && <Link href={`/agent/monitor/collaboration/${run.id}/report`} className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-emerald-500/30 bg-emerald-500/10 px-3 text-[10px] font-semibold text-emerald-200 transition hover:bg-emerald-500/20"><FileCheck2 className="h-3.5 w-3.5" />运行证据报告</Link>}<Button variant="outline" onClick={() => void load(run.id)} disabled={loading} className="border-slate-700 bg-slate-900 text-slate-200 hover:bg-slate-800 hover:text-white"><RefreshCw className={loading ? "animate-spin" : ""} />刷新</Button>{snapshot.viewer.canReset && <Button variant="outline" onClick={() => setResetOpen(true)} className="border-amber-700/50 bg-amber-950/20 text-amber-200 hover:bg-amber-900/30"><RotateCcw />复位场景</Button>}{snapshot.viewer.canStart && <Button onClick={() => setCreateOpen(true)} className="bg-blue-600 hover:bg-blue-500"><Sparkles />启动视频场景</Button>}</div></div>
      <div className="relative mt-6 grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 sm:grid-cols-2 xl:grid-cols-6"><HeaderMetric label="固定场景" value={snapshot.scenario?.id ?? run.runNo} /><HeaderMetric label="工作流" value={`v${run.workflowVersion} · ${run.stages.length}节点`} /><HeaderMetric label="节点进度" value={`${completed} / ${run.stages.length}`} /><HeaderMetric label="场景修订" value={`REV ${snapshot.scenario?.revision ?? "-"}`} /><HeaderMetric label="计划来源" value={run.status === "ready" ? "等待启动" : run.planning.source === "deepseek" ? "DeepSeek真实调用" : "安全降级"} /><HeaderMetric label="状态" value={STATUS_NAMES[run.status]} highlight /></div>
    </section>

    {snapshot.scenario && <section className={`rounded-2xl border px-4 py-3 text-xs leading-5 ${snapshot.scenario.syncStatus === "awaiting_business_adapter" ? "border-amber-500/30 bg-amber-950/45 text-amber-100" : "border-cyan-500/20 bg-cyan-950/30 text-cyan-100"}`}><div className="flex flex-wrap items-center gap-2"><ShieldCheck className="h-4 w-4" /><span className="font-bold">{snapshot.scenario.implementationStage} 真实性状态</span><span className="font-mono text-[10px] opacity-70">STATE {snapshot.scenario.stateHash}</span></div><p className="mt-1 opacity-75">当前已实现到节点 {snapshot.scenario.implementedThroughStage}/10。未接通原业务适配器的节点会被强制阻断，不能显示为业务完成。</p></section>}

    {run.status === "completed" && run.summary && <section className="overflow-hidden rounded-2xl border border-emerald-400/20 bg-[linear-gradient(110deg,rgba(6,78,59,.42),rgba(8,47,73,.36))] p-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div className="flex items-start gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-emerald-400/15 text-emerald-300"><CheckCircle2 className="h-5 w-5" /></span><div><p className="text-sm font-bold text-emerald-100">业务闭环与AI证据均已封存</p><p className="mt-1 text-[11px] leading-5 text-slate-400">{run.summary.result} 模型、Agent、Skill、插件、MCP、九维权限、人工闸门和审计证据可在同一报告逐项核验。</p></div></div><div className="flex flex-wrap items-center gap-2"><span className="rounded-lg border border-white/8 bg-black/15 px-3 py-2 text-[9px] text-slate-400"><strong className="text-slate-100">{run.summary.modelCalls}</strong> 模型</span><span className="rounded-lg border border-white/8 bg-black/15 px-3 py-2 text-[9px] text-slate-400"><strong className="text-slate-100">{run.summary.skillCalls}</strong> Skill</span><span className="rounded-lg border border-white/8 bg-black/15 px-3 py-2 text-[9px] text-slate-400"><strong className="text-slate-100">{run.summary.mcpCalls}</strong> MCP调用</span><span className="rounded-lg border border-white/8 bg-black/15 px-3 py-2 text-[9px] text-slate-400"><strong className="text-slate-100">{run.summary.evidenceCount}</strong> 节点证据</span><Button asChild className="bg-emerald-500 text-slate-950 hover:bg-emerald-400"><Link href={`/agent/monitor/collaboration/${run.id}/report`}><FileCheck2 />打开运行证据报告</Link></Button></div></div></section>}

    {messageText && <div className={`rounded-xl border px-4 py-3 text-sm ${messageText.type === "success" ? "border-emerald-700/50 bg-emerald-950/70 text-emerald-200" : "border-rose-700/50 bg-rose-950/70 text-rose-200"}`}>{messageText.text}</div>}

    <section className="rounded-2xl border border-slate-800 bg-slate-950 p-4 shadow-xl"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2"><Workflow className="h-4 w-4 text-cyan-300" /><h2 className="text-sm font-bold">工作流执行图</h2><Badge className="bg-white/5 text-slate-400">{progress(run)}%</Badge></div><p className="mt-1 text-[10px] text-slate-500">点击节点可进入对应正式业务页面</p></div><RunControls run={run} snapshot={snapshot} busy={busy} autoRun={autoRun} onAuto={setAutoRun} onAdvance={advance} onControl={control} /></div><div className="mt-4 overflow-x-auto pb-2"><div className="flex min-w-max items-center">{run.stages.map((stage, index) => <div key={stage.id} className="flex items-center"><StageNode stage={stage} active={stage.id === current.id && run.status !== "completed"} />{index < run.stages.length - 1 && <div className={`relative h-px w-7 ${stage.status === "completed" ? "bg-cyan-400/70" : "bg-slate-800"}`}><span className={`absolute -right-0.5 -top-0.5 h-1.5 w-1.5 rounded-full ${stage.status === "completed" ? "bg-cyan-300" : "bg-slate-700"}`} /></div>}</div>)}</div></div></section>

    <div className="grid gap-5 2xl:grid-cols-[1.38fr_.72fr]">
      <ChatPanel run={run} containerRef={chatRef} />
      <ControlPanel run={run} current={current} snapshot={snapshot} onConfirm={() => setGateOpen(true)} />
    </div>

    <section className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><TracePanel run={run} /><AssetPanel snapshot={snapshot} run={run} /></section>
    <section className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><AgentRoster run={run} /><BusinessObjects run={run} /></section>

    <Dialog open={createOpen} onOpenChange={open => { if (!busy) setCreateOpen(open); }}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>启动固定视频场景</DialogTitle><DialogDescription>小海豚将调用模型网关进行受控任务分解，加载工作流v6。没有原业务适配器返回成功的节点绝不会被标记完成。</DialogDescription></DialogHeader><Textarea value={command} onChange={event => setCommand(event.target.value)} className="min-h-28" maxLength={500} /><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs leading-5 text-emerald-800">仅使用模拟数据；模型只接收场景摘要和固定流程，不接收姓名、证件号、银行卡或原始材料。</div><DialogFooter><Button variant="outline" onClick={() => setCreateOpen(false)} disabled={Boolean(busy)}>取消</Button><Button onClick={() => void createRun()} disabled={Boolean(busy) || command.trim().length < 10}>{busy.startsWith("start-video") ? <Loader2 className="animate-spin" /> : <Send />}小海豚开始调度</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={resetOpen} onOpenChange={open => { if (!busy) setResetOpen(open); }}><DialogContent><DialogHeader><DialogTitle>复位固定视频场景</DialogTitle><DialogDescription>当前实例将只读归档，并创建一个新的就绪修订。复位仅处理本场景数据，不影响其他模拟业务。</DialogDescription></DialogHeader><Textarea value={resetComment} onChange={event => setResetComment(event.target.value)} className="min-h-24" maxLength={300} /><div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-800">复位操作需要人工确认、幂等键和版本匹配，并写入审计证据链。</div><DialogFooter><Button variant="outline" onClick={() => setResetOpen(false)} disabled={Boolean(busy)}>取消</Button><Button onClick={() => void resetScenario()} disabled={Boolean(busy) || resetComment.trim().length < 6} className="bg-amber-600 hover:bg-amber-500">{busy.startsWith("reset-video") ? <Loader2 className="animate-spin" /> : <RotateCcw />}确认复位</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={gateOpen} onOpenChange={open => { if (!busy) setGateOpen(open); }}><DialogContent><DialogHeader><DialogTitle>人工确认：{current.title}</DialogTitle><DialogDescription>当前责任岗位为{current.requiredRole ? current.roleName : "系统节点"}。确认意见、身份、时间和证据引用将冻结写入审计链。</DialogDescription></DialogHeader><Textarea value={comment} onChange={event => setComment(event.target.value)} className="min-h-24" maxLength={300} /><DialogFooter><Button variant="outline" onClick={() => setGateOpen(false)} disabled={Boolean(busy)}>取消</Button><Button onClick={() => void confirmGate()} disabled={Boolean(busy) || comment.trim().length < 6}>{busy.startsWith("confirm") ? <Loader2 className="animate-spin" /> : <Fingerprint />}人工签名并继续</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function HeaderMetric({ label, value, highlight = false }: { label: string; value: string; highlight?: boolean }) { return <div className="bg-slate-950/75 px-4 py-3"><p className="text-[9px] uppercase tracking-wider text-slate-600">{label}</p><p className={`mt-1 truncate text-xs font-bold ${highlight ? "text-emerald-300" : "text-slate-200"}`}>{value}</p></div>; }

function RunControls({ run, snapshot, busy, autoRun, onAuto, onAdvance, onControl }: { run: CollaborationRun; snapshot: CollaborationSnapshot; busy: string; autoRun: boolean; onAuto: (value: boolean) => void; onAdvance: () => Promise<void>; onControl: (action: "pause" | "resume" | "retry") => Promise<void> }) {
  const waiting = run.status === "ready" || run.status === "awaiting_human" || run.status === "completed";
  return <div className="flex flex-wrap gap-2">{run.status === "running" && <><Button size="sm" onClick={() => onAuto(!autoRun)} className={autoRun ? "bg-cyan-600 hover:bg-cyan-500" : "bg-blue-600 hover:bg-blue-500"}>{autoRun ? <Pause /> : <Play />}{autoRun ? "暂停自动推进" : "自动运行至闸门"}</Button><Button size="sm" variant="outline" onClick={() => void onAdvance()} disabled={Boolean(busy)} className="border-slate-700 bg-slate-900 text-slate-200 hover:bg-slate-800 hover:text-white"><ChevronRight />单步执行</Button></>}{run.status === "paused" && <Button size="sm" onClick={() => void onControl("resume")} disabled={!snapshot.viewer.canControl || Boolean(busy)}><CirclePlay />恢复运行</Button>}{run.status === "failed" && <Button size="sm" onClick={() => void onControl("retry")} disabled={!snapshot.viewer.canControl || Boolean(busy)}><RotateCcw />重试失败节点</Button>}{snapshot.viewer.canControl && run.status === "running" && <Button size="sm" variant="outline" onClick={() => void onControl("pause")} disabled={Boolean(busy)} className="border-amber-700/50 bg-amber-950/20 text-amber-200 hover:bg-amber-900/30"><CirclePause />安全暂停</Button>}{waiting && <span className="inline-flex items-center gap-2 rounded-lg border border-slate-800 bg-slate-900 px-3 py-2 text-[10px] text-slate-500"><LockKeyhole className="h-3.5 w-3.5" />{run.status === "completed" ? "运行已封存" : run.status === "ready" ? "等待场景启动" : "自动执行已锁定"}</span>}</div>;
}
function StageNode({ stage, active }: { stage: CollaborationStage; active: boolean }) {
  const style = stage.status === "completed" ? "border-emerald-400/25 bg-emerald-400/8" : stage.status === "awaiting_human" ? "border-amber-400/40 bg-amber-400/10 shadow-[0_0_24px_rgba(251,191,36,.1)]" : stage.status === "failed" ? "border-rose-400/40 bg-rose-400/10" : active ? "border-blue-400/40 bg-blue-400/10 shadow-[0_0_24px_rgba(59,130,246,.12)]" : "border-white/8 bg-white/[.025]";
  return <Link href={stage.businessRoute} className={`group w-36 rounded-2xl border p-3 transition hover:border-cyan-300/30 hover:bg-white/[.05] ${style}`}><div className="flex items-center justify-between"><span className={`flex h-7 w-7 items-center justify-center rounded-lg font-mono text-[9px] font-bold ${stage.status === "completed" ? "bg-emerald-500/15 text-emerald-300" : stage.status === "awaiting_human" ? "bg-amber-500/15 text-amber-300" : active ? "bg-blue-500 text-white" : "bg-slate-800 text-slate-500"}`}>{String(stage.sequence).padStart(2, "0")}</span>{stage.status === "completed" ? <CheckCircle2 className="h-3.5 w-3.5 text-emerald-400" /> : stage.status === "awaiting_human" ? <UserCheck className="h-3.5 w-3.5 text-amber-300" /> : <Clock3 className="h-3.5 w-3.5 text-slate-600" />}</div><p className="mt-3 truncate text-xs font-semibold text-slate-200">{stage.phase}</p><p className="mt-1 truncate text-[9px] text-slate-600">{stage.roleName}</p></Link>;
}
function ChatPanel({ run, containerRef }: { run: CollaborationRun; containerRef: React.RefObject<HTMLDivElement | null> }) {
  return <section className="overflow-hidden rounded-2xl border border-slate-800 bg-[#07111f] shadow-xl"><header className="flex items-center justify-between border-b border-white/8 px-5 py-4"><div><div className="flex items-center gap-2"><MessageSquareText className="h-4 w-4 text-cyan-300" /><h2 className="text-sm font-bold">多Agent协作群聊</h2><span className="h-1.5 w-1.5 rounded-full bg-emerald-400 shadow-[0_0_8px_#34d399]" /></div><p className="mt-1 text-[10px] text-slate-600">任务分配、执行汇报、人工确认与交接全部来自服务器运行轨迹</p></div><Badge className="bg-white/5 text-slate-400">{run.messages.length} 条消息</Badge></header><div ref={containerRef} className="h-[570px] space-y-3 overflow-y-auto p-4 lg:p-5">{run.messages.map(item => <ChatMessage key={item.id} item={item} />)}</div></section>;
}
function ChatMessage({ item }: { item: CollaborationMessage }) {
  const isDolphin = item.senderType === "dolphin", isHuman = item.senderType === "human", isSystem = item.senderType === "system";
  return <div className={`flex gap-3 ${isHuman ? "flex-row-reverse" : ""}`}><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl text-xs font-bold ${isDolphin ? "bg-gradient-to-br from-blue-500 to-cyan-400 text-white shadow-[0_0_20px_rgba(56,189,248,.2)]" : isHuman ? "bg-amber-500/15 text-amber-200" : isSystem ? "bg-rose-500/15 text-rose-200" : "bg-violet-500/15 text-violet-200"}`}>{item.avatar}</span><div className={`max-w-[86%] ${isHuman ? "text-right" : ""}`}><div className={`mb-1 flex items-center gap-2 text-[9px] text-slate-600 ${isHuman ? "justify-end" : ""}`}><span className="font-semibold text-slate-400">{item.senderName}</span><span>{item.senderRole ?? item.type}</span><span>{new Date(item.createdAt).toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit", second: "2-digit" })}</span></div><div className={`rounded-2xl border px-3.5 py-3 text-[11px] leading-5 ${isDolphin ? "border-blue-400/15 bg-blue-500/8 text-blue-100" : isHuman ? "border-amber-400/15 bg-amber-500/8 text-amber-100" : isSystem ? "border-rose-400/15 bg-rose-500/8 text-rose-100" : "border-white/8 bg-white/[.035] text-slate-300"}`}>{item.content}{item.evidenceRefs.length > 0 && <div className={`mt-2 flex flex-wrap gap-1 ${isHuman ? "justify-end" : ""}`}>{item.evidenceRefs.slice(0, 4).map(ref => <span key={ref} className="rounded-md border border-white/8 bg-black/15 px-1.5 py-0.5 font-mono text-[8px] text-slate-500">{ref}</span>)}</div>}</div></div></div>;
}
function ControlPanel({ run, current, snapshot, onConfirm }: { run: CollaborationRun; current: CollaborationStage; snapshot: CollaborationSnapshot; onConfirm: () => void }) {
  const permission = current.permission;
  return <div className="space-y-4"><section className="rounded-2xl border border-slate-800 bg-slate-950 p-5 shadow-xl"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[9px] font-bold uppercase tracking-wider text-cyan-300">CURRENT TASK · {String(current.sequence).padStart(2, "0")}</p><h2 className="mt-2 text-lg font-bold">{current.title}</h2><p className="mt-1 text-[10px] text-slate-600">{current.agentName} · {current.roleName}</p></div><StatusBadge status={current.status} /></div><p className="mt-4 text-xs leading-6 text-slate-400">{current.actionSummary}</p><div className="mt-4 rounded-xl border border-white/8 bg-white/[.025] p-3"><p className="text-[9px] font-bold uppercase tracking-wider text-slate-600">业务状态</p><p className="mt-1 text-xs font-semibold text-slate-300">{current.businessState}</p><Link href={current.businessRoute} className="mt-2 inline-flex items-center gap-1.5 text-[10px] font-semibold text-cyan-300 hover:text-cyan-200">进入对应业务页面<ExternalLink className="h-3 w-3" /></Link></div>{run.status === "awaiting_human" && <div className="mt-4 rounded-xl border border-amber-400/20 bg-amber-400/8 p-4"><div className="flex items-center gap-2 text-amber-200"><UserCheck className="h-4 w-4" /><p className="text-xs font-bold">等待{current.roleName}人工确认</p></div><p className="mt-2 text-[10px] leading-5 text-amber-100/65">AI分析已完成，但没有权限替代当前岗位作出业务决定。</p>{snapshot.viewer.canConfirmCurrentGate ? <Button onClick={onConfirm} className="mt-3 w-full bg-amber-500 text-slate-950 hover:bg-amber-400"><Fingerprint />核对证据并人工确认</Button> : <div className="mt-3 rounded-lg border border-amber-300/10 bg-black/15 p-2.5 text-[10px] text-amber-200/70">当前登录岗位：{snapshot.viewer.roleName}。请由责任岗位登录本页面处理。</div>}</div>}</section>
    <section className="rounded-2xl border border-slate-800 bg-slate-950 p-5 shadow-xl"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-emerald-300" /><h2 className="text-sm font-bold">权限与安全护栏</h2></div><Badge className={permission?.allowed ? "bg-emerald-400/10 text-emerald-300" : "bg-slate-800 text-slate-500"}>{permission ? `${permission.dimensions.filter(item => item.status === "ALLOW").length}/9` : "待校验"}</Badge></div><div className="mt-4 grid grid-cols-3 gap-2">{["角色", "组织", "数据", "时间", "地理", "流程", "AI风险", "敏感度", "操作"].map((label, index) => { const item = permission?.dimensions[index]; return <div key={label} className={`rounded-lg border p-2 text-center ${item?.status === "ALLOW" ? "border-emerald-400/15 bg-emerald-400/7" : item ? "border-rose-400/15 bg-rose-400/7" : "border-white/6 bg-white/[.02]"}`}><span className={`mx-auto block h-1.5 w-1.5 rounded-full ${item?.status === "ALLOW" ? "bg-emerald-400" : item ? "bg-rose-400" : "bg-slate-700"}`} /><p className="mt-1.5 text-[9px] text-slate-500">{label}</p></div>; })}</div><div className="mt-3 rounded-xl border border-white/8 bg-white/[.025] p-3"><p className="text-[9px] text-slate-600">AGENT PERMISSION FORMULA</p><p className="mt-1 text-[10px] leading-5 text-slate-400">角色权限 ∩ Agent工具 ∩ 九维校验 ∩ Guardrails ∩ 流程 ∩ 时间 ∩ 地理</p></div></section>
  </div>;
}

function TracePanel({ run }: { run: CollaborationRun }) {
  return <section className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-950 shadow-xl"><header className="flex items-center justify-between border-b border-white/8 px-5 py-4"><div><div className="flex items-center gap-2"><Activity className="h-4 w-4 text-blue-300" /><h2 className="text-sm font-bold">执行链路与资产调用</h2></div><p className="mt-1 text-[10px] text-slate-600">模型、RAG、Skill、插件、MCP、权限与审计均来自运行记录</p></div><Badge className="bg-white/5 text-slate-400">{run.traces.length} spans</Badge></header><div className="max-h-[430px] overflow-auto"><table className="w-full text-left"><thead className="sticky top-0 bg-slate-950 text-[9px] uppercase tracking-wider text-slate-600"><tr><th className="px-5 py-3">类型/资产</th><th className="px-4 py-3">状态</th><th className="px-4 py-3">耗时</th><th className="px-5 py-3">证据摘要</th></tr></thead><tbody>{run.traces.slice().reverse().map(item => <tr key={item.id} className="border-t border-white/6"><td className="px-5 py-3"><span className={`inline-flex rounded-md border px-1.5 py-0.5 text-[8px] font-bold ${TRACE_STYLES[item.kind]}`}>{item.kind}</span><p className="mt-1.5 max-w-52 truncate text-[10px] font-semibold text-slate-300">{item.name}</p><p className="mt-0.5 font-mono text-[8px] text-slate-700">{item.version}</p></td><td className="px-4 py-3"><span className={`inline-flex items-center gap-1 text-[9px] ${item.status === "success" ? "text-emerald-300" : item.status === "blocked" ? "text-rose-300" : "text-amber-300"}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{item.status}</span></td><td className="px-4 py-3 font-mono text-[9px] text-slate-500">{item.latencyMs}ms</td><td className="px-5 py-3"><p className="max-w-xl text-[10px] leading-5 text-slate-500">{item.detail}</p>{item.evidenceId && item.evidenceId.startsWith("AUD-") && !item.evidenceId.startsWith("AUD-SEED") && <Link href={`/audit-center/events/${item.evidenceId}`} className="mt-1 inline-flex items-center gap-1 text-[9px] text-cyan-400">查看证据<ArrowRight className="h-3 w-3" /></Link>}</td></tr>)}</tbody></table></div></section>;
}
function AssetPanel({ snapshot, run }: { snapshot: CollaborationSnapshot; run: CollaborationRun }) {
  const icons = { workflow: GitBranch, skill: Zap, plugin: Plug, mcp: Network } as const;
  const mcpObject = run.businessObjects.find(item => item.type === "mcp_session");
  const mcpActual = Number(mcpObject?.status.match(/(\d+)次/)?.[1] ?? 0);
  return <section className="rounded-2xl border border-slate-800 bg-slate-950 p-5 shadow-xl"><div className="flex items-center justify-between"><div><div className="flex items-center gap-2"><BrainCircuit className="h-4 w-4 text-violet-300" /><h2 className="text-sm font-bold">AI资产：注册态 × 本次执行态</h2></div><p className="mt-1 text-[10px] text-slate-600">健康绿点只代表已安装；卡片中的执行次数、耗时和输出来自当前运行Trace</p></div><Link href="/agent/studio?view=workflows" className="text-[10px] font-semibold text-cyan-300">资产工作室 →</Link></div><div className="mt-4 space-y-2.5">{snapshot.assets.map(asset => { const Icon = icons[asset.kind]; const spans = run.traces.filter(item => item.name === asset.id && item.status === "success"); const latest = spans.at(-1); const actual = asset.kind === "mcp" ? mcpActual : spans.length; return <div key={asset.id} className={`rounded-xl border p-3 ${actual > 0 ? "border-emerald-400/15 bg-emerald-400/[.035]" : "border-white/8 bg-white/[.025]"}`}><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-violet-400/10 text-violet-200"><Icon className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-semibold text-slate-300">{asset.name}</p><p className="mt-0.5 font-mono text-[8px] text-slate-700">{asset.id} · v{asset.version}</p></div><div className="text-right"><span className={`inline-flex items-center gap-1 text-[9px] ${actual > 0 ? "text-emerald-300" : "text-amber-300"}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{actual > 0 ? `本次执行 ${actual}` : "本次未执行"}</span><p className="mt-1 font-mono text-[8px] text-slate-700">{latest ? `${latest.latencyMs}ms` : asset.status}</p></div></div>{latest && <p className="mt-2 line-clamp-2 text-[9px] leading-4 text-slate-600">{latest.detail}</p>}<div className="mt-2 flex flex-wrap gap-1">{asset.tools.slice(0, 3).map(tool => <span key={tool} className="rounded-md bg-black/20 px-1.5 py-0.5 font-mono text-[8px] text-slate-600">{tool}</span>)}</div></div>; })}</div><div className="mt-4 grid grid-cols-2 gap-2"><Tiny icon={Database} label="持久化" value="JSON Runtime" /><Tiny icon={ShieldCheck} label="Guardrails" value="确定性开启" /></div></section>;
}
function AgentRoster({ run }: { run: CollaborationRun }) {
  const agents = useMemo(() => Array.from(new Map(run.stages.map(stage => [stage.agentCode, stage])).values()), [run.stages]);
  return <section className="rounded-2xl border border-slate-800 bg-slate-950 p-5 shadow-xl"><div className="flex items-center justify-between"><div><div className="flex items-center gap-2"><UsersRound className="h-4 w-4 text-cyan-300" /><h2 className="text-sm font-bold">本次Agent团队</h2></div><p className="mt-1 text-[10px] text-slate-600">7个岗位团队按工作流动态组队，权限不合并</p></div><Badge className="bg-cyan-400/10 text-cyan-300">{agents.length} Agent</Badge></div><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{agents.map(stage => <div key={stage.agentCode} className="rounded-xl border border-white/8 bg-white/[.025] p-3"><div className="flex items-center gap-2.5"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-400/10 text-blue-200"><Bot className="h-4 w-4" /></span><div className="min-w-0"><p className="truncate text-[11px] font-semibold text-slate-300">{stage.agentName}</p><p className="mt-0.5 truncate text-[8px] text-slate-700">{stage.roleName}</p></div><span className={`ml-auto h-1.5 w-1.5 rounded-full ${stage.status === "completed" ? "bg-emerald-400" : stage.status === "awaiting_human" ? "bg-amber-400" : "bg-blue-400"}`} /></div><p className="mt-2 font-mono text-[8px] text-slate-700">{stage.agentCode}</p></div>)}</div></section>;
}
function BusinessObjects({ run }: { run: CollaborationRun }) {
  return <section className="rounded-2xl border border-slate-800 bg-slate-950 p-5 shadow-xl"><div className="flex items-center gap-2"><Landmark className="h-4 w-4 text-amber-300" /><h2 className="text-sm font-bold">关联业务对象</h2></div><p className="mt-1 text-[10px] text-slate-600">由固定场景真值源统一绑定；尚未生成的业务对象明确标记为待同步</p><div className="mt-4 space-y-2">{run.businessObjects.map(item => <Link key={`${item.type}-${item.id}`} href={item.route} className="group flex items-center gap-3 rounded-xl border border-white/8 bg-white/[.025] p-3 transition hover:border-cyan-300/20 hover:bg-white/[.045]"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-amber-400/10 text-amber-200">{item.type === "application" ? <FileCheck2 className="h-4 w-4" /> : item.type === "grant_batch" ? <Landmark className="h-4 w-4" /> : <Database className="h-4 w-4" />}</span><div className="min-w-0"><p className="truncate text-[11px] font-semibold text-slate-300">{item.label}</p><p className="mt-0.5 font-mono text-[8px] text-slate-700">{item.id} · {item.sensitivity}</p></div><div className="ml-auto text-right"><p className="text-[9px] text-emerald-300">{item.status}</p><ExternalLink className="ml-auto mt-1 h-3 w-3 text-slate-700 transition group-hover:text-cyan-300" /></div></Link>)}</div></section>;
}
function Tiny({ icon: Icon, label, value }: { icon: typeof Database; label: string; value: string }) { return <div className="rounded-xl border border-white/8 bg-white/[.025] p-3"><Icon className="h-4 w-4 text-slate-500" /><p className="mt-2 text-[10px] font-semibold text-slate-300">{value}</p><p className="mt-1 text-[8px] text-slate-700">{label}</p></div>; }
function StatusBadge({ status }: { status: CollaborationStage["status"] }) { const style = status === "completed" ? "bg-emerald-400/10 text-emerald-300" : status === "awaiting_human" ? "bg-amber-400/10 text-amber-300" : status === "failed" ? "bg-rose-400/10 text-rose-300" : status === "working" ? "bg-blue-400/10 text-blue-300" : "bg-white/5 text-slate-500"; const name = { pending: "待执行", working: "执行中", awaiting_human: "待人工", completed: "已完成", failed: "失败" }[status]; return <Badge className={style}>{name}</Badge>; }





