"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { BadgeCheck, Database, Fingerprint, HardDrive, Loader2, RefreshCw, RotateCcw, ServerCog, ShieldCheck } from "lucide-react";
import type { HardshipPersistenceProof } from "@/lib/ai/hardship-persistence-proof";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";

interface Envelope<T> { success: boolean; data?: T; error?: string }
function authHeaders(): HeadersInit { const token = localStorage.getItem("token"); return token ? { Authorization: `Bearer ${token}` } : {}; }
function short(value?: string | null, start = 12, end = 8) { if (!value) return "—"; return value.length > start + end + 2 ? `${value.slice(0, start)}…${value.slice(-end)}` : value; }
function size(value: number) { return value >= 1024 * 1024 ? `${(value / 1024 / 1024).toFixed(2)} MB` : `${(value / 1024).toFixed(1)} KB`; }
function time(value?: string | null) { if (!value) return "?"; return `${new Intl.DateTimeFormat("zh-CN", { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false, timeZone: "UTC" }).format(new Date(value))} UTC`; }

export function CollaborationPersistenceProofView({ runId }: { runId: string }) {
  const [data, setData] = useState<HardshipPersistenceProof | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const load = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const response = await fetch(`/api/ai/collaboration/persistence?runId=${encodeURIComponent(runId)}&t=${Date.now()}`, { headers: authHeaders(), cache: "no-store" });
      const body = await response.json() as Envelope<HardshipPersistenceProof>;
      if (!response.ok || !body.success || !body.data) throw new Error(body.error ?? "持久化证据加载失败");
      setData(body.data);
    } catch (reason) { setError(reason instanceof Error ? reason.message : "持久化证据加载失败"); }
    finally { setLoading(false); }
  }, [runId]);
  useEffect(() => { void load(); }, [load]);
  const directPass = data?.directDiskRead.verified === true;
  const restartPass = data?.restart.verified === true;
  const overall = directPass && restartPass && data?.audit.valid === true;
  const checkEntries = useMemo(() => data ? Object.entries(data.directDiskRead.checks) : [], [data]);
  if (loading && !data) return <div className="flex min-h-[75vh] items-center justify-center bg-[#030a14] text-slate-300"><Loader2 className="mr-3 h-6 w-6 animate-spin text-cyan-300"/>正在绕过前端缓存，从服务器持久化介质读取证据…</div>;
  if (error || !data) return <div className="min-h-[70vh] bg-[#030a14] p-8 text-center text-slate-200"><ShieldCheck className="mx-auto h-10 w-10 text-rose-300"/><h1 className="mt-4 text-lg font-bold">持久化核验不可用</h1><p className="mt-2 text-sm text-slate-500">{error}</p><Button asChild variant="outline" className="mt-5"><Link href={`/agent/monitor/collaboration/${runId}/report`}>返回运行报告</Link></Button></div>;
  return <div className="min-h-screen space-y-5 bg-[#030a14] pb-12 text-slate-100">
    <section className="relative overflow-hidden rounded-[28px] border border-slate-800 bg-[linear-gradient(135deg,#071426_0%,#081a30_55%,#061a1d_100%)] p-6 shadow-[0_30px_90px_rgba(0,0,0,.35)] lg:p-8">
      <div className="pointer-events-none absolute inset-0 opacity-40" style={{backgroundImage:"linear-gradient(rgba(56,189,248,.05) 1px,transparent 1px),linear-gradient(90deg,rgba(56,189,248,.05) 1px,transparent 1px)",backgroundSize:"32px 32px"}}/>
      <div className="relative flex flex-col gap-6 xl:flex-row xl:items-start xl:justify-between"><div><div className="flex flex-wrap gap-2"><Badge className="border border-cyan-300/20 bg-cyan-400/10 text-cyan-100">PERSISTENCE EVIDENCE · LIVE</Badge><Badge className={overall?"border border-emerald-300/20 bg-emerald-400/10 text-emerald-100":"border border-amber-300/20 bg-amber-400/10 text-amber-100"}>{overall?"COLD RESTART VERIFIED":"CHECK REQUIRED"}</Badge><Badge className="border border-amber-300/20 bg-amber-400/10 text-amber-100">演示存储边界已披露</Badge></div><h1 className="mt-4 text-2xl font-bold tracking-tight lg:text-4xl">持久化、刷新与服务重启核验</h1><p className="mt-3 max-w-4xl text-sm leading-7 text-slate-400">本页不读取浏览器LocalStorage中的业务结果，而是由服务器重新打开持久化文件、计算文件摘要，并与同一运行实例、业务对象版本和审计链交叉比对。</p><p className="mt-3 font-mono text-[10px] text-cyan-300">{data.run.id} · REV {data.run.revision} · STATE v{data.run.version} · {data.mode}</p></div><div className="flex shrink-0 flex-wrap gap-2"><Button asChild className="bg-cyan-500 text-slate-950 hover:bg-cyan-400"><Link href={`/agent/monitor/collaboration/${runId}/report`}>返回运行报告</Link></Button><Button variant="outline" onClick={() => void load()} className="border-slate-700 bg-slate-900/70 text-slate-200 hover:bg-slate-800 hover:text-white"><RefreshCw className={loading?"animate-spin":""}/>从磁盘重读</Button><Button variant="outline" onClick={() => window.location.reload()} className="border-slate-700 bg-slate-900/70 text-slate-200 hover:bg-slate-800 hover:text-white"><RotateCcw/>强制刷新</Button></div></div>
      <div className="relative mt-7 grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 sm:grid-cols-2 xl:grid-cols-5"><Metric label="服务器磁盘回读" value={directPass?"PASS":"CHECK"} detail="绕过前端缓存" highlight={directPass}/><Metric label="服务冷启动" value={restartPass?"PASS":"CHECK"} detail="进程重启后同源" highlight={restartPass}/><Metric label="持久化存储" value={`${data.stores.filter(item=>item.exists).length}/${data.stores.length}`} detail="运行/业务/审核/发放/审计"/><Metric label="状态版本" value={`v${data.run.version}`} detail={`申请v${data.versions.finalApplication} · 批次v${data.versions.grantBatch.version}`}/><Metric label="审计链" value={data.audit.valid?"VERIFIED":"BROKEN"} detail={`${data.audit.algorithm} · ${data.audit.total}节点`} highlight={data.audit.valid}/></div>
    </section>

    <section className={`rounded-2xl border p-5 ${overall?"border-emerald-400/25 bg-emerald-400/8":"border-amber-400/25 bg-amber-400/8"}`}><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-start gap-3"><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${overall?"bg-emerald-400/15 text-emerald-300":"bg-amber-400/15 text-amber-200"}`}><BadgeCheck className="h-5 w-5"/></span><div><p className={`text-sm font-bold ${overall?"text-emerald-200":"text-amber-200"}`}>{overall?"不是预设动画：落盘、刷新、重启三类证据均通过":"持久化证据仍有缺口"}</p><p className="mt-1 text-xs leading-6 text-slate-400">最近服务器回读：{time(data.generatedAt)}；冷启动复核：{"verifiedAt" in data.restart?time(data.restart.verifiedAt):"未生成"}。</p></div></div><div className="flex flex-wrap gap-2">{checkEntries.map(([name, passed])=><span key={name} className={`rounded-lg border px-2.5 py-1.5 font-mono text-[9px] ${passed?"border-emerald-400/15 bg-emerald-400/8 text-emerald-300":"border-rose-400/20 bg-rose-400/8 text-rose-300"}`}>{name} · {passed?"PASS":"FAIL"}</span>)}</div></div></section>

    <div className="grid gap-5 xl:grid-cols-[1.18fr_.82fr]">
      <Card className="border-slate-800 bg-slate-950 text-slate-100 shadow-xl"><CardHeader className="border-b border-white/6"><Title icon={HardDrive} title="服务器端持久化介质" description="每次点击“从磁盘重读”都会重新计算大小、修改时间与SHA-256摘要"/></CardHeader><CardContent className="grid gap-3 p-5 lg:grid-cols-2">{data.stores.map(store=><div key={store.logicalName} className="rounded-2xl border border-white/8 bg-white/[.025] p-4"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-cyan-400/10 text-cyan-200"><Database className="h-4 w-4"/></span><div><p className="text-xs font-bold text-slate-300">{store.logicalName}</p><p className="mt-1 font-mono text-[8px] text-slate-600">{store.adapter} · {store.writeMode}</p></div></div><span className={`text-[9px] ${store.exists?"text-emerald-300":"text-rose-300"}`}>{store.exists?"ON DISK":"MISSING"}</span></div><div className="mt-4 grid grid-cols-2 gap-2 text-[9px]"><Value label="大小" value={size(store.sizeBytes)}/><Value label="更新时间" value={time(store.updatedAt)}/></div><div className="mt-3 rounded-xl bg-[#020617] p-3"><p className="text-[8px] text-slate-700">SHA-256</p><p className="mt-2 break-all font-mono text-[9px] text-emerald-300">{short(store.sha256,16,12)}</p></div></div>)}</CardContent></Card>

      <div className="space-y-5"><Card className="border-slate-800 bg-slate-950 text-slate-100 shadow-xl"><CardHeader className="border-b border-white/6"><Title icon={ServerCog} title="冷启动同源证明" description="停止服务进程后重新启动，再次调用报告API"/></CardHeader><CardContent className="space-y-3 p-5">{"checks" in data.restart?Object.entries(data.restart.checks).map(([name,passed])=><Value key={name} label={name} value={passed?"PASS":"FAIL"} good={passed}/>):<p className="text-xs text-amber-200">{"reason" in data.restart?data.restart.reason:"冷启动证据不可用"}</p>}{"before" in data.restart&&<><Value label="重启前" value={`HTTP ${data.restart.before.status} · v${data.restart.before.runVersion}`}/><Value label="重启后" value={`HTTP ${data.restart.after.status} · v${data.restart.after.runVersion}`}/><Value label="审计HEAD" value={short(data.restart.after.auditHeadHash)} good={data.restart.checks.sameAuditHead}/></>}</CardContent></Card>
      <Card className="border-slate-800 bg-slate-950 text-slate-100 shadow-xl"><CardHeader className="border-b border-white/6"><Title icon={Fingerprint} title="透明边界声明" description="真实性不靠把演示环境包装成生产环境"/></CardHeader><CardContent className="space-y-3 p-5"><Value label="当前演示" value={data.storageBoundary.demoAdapter}/><Value label="浏览器业务存储" value={data.storageBoundary.browserStorageUsedForBusinessState?"使用":"未使用"} good={!data.storageBoundary.browserStorageUsedForBusinessState}/><Value label="生产目标" value={data.storageBoundary.productionTarget}/><p className="rounded-xl border border-amber-400/15 bg-amber-400/6 p-3 text-[10px] leading-6 text-amber-100/80">{data.storageBoundary.statement}</p></CardContent></Card></div>
    </div>

    <Card className="border-slate-800 bg-slate-950 text-slate-100 shadow-xl"><CardHeader className="border-b border-white/6"><Title icon={Database} title="同一对象版本链" description="运行、申请、审核、批次、银行回盘与对账全部使用同一revision和对象编号"/></CardHeader><CardContent className="grid gap-3 p-5 sm:grid-cols-2 xl:grid-cols-6"><Version label="工作流运行" value={`STATE v${data.versions.workflowRun}`} detail={data.run.id}/><Version label="申请状态" value={`APP v${data.versions.finalApplication}`} detail={`${data.versions.baseApplication} → ${data.versions.reviewedApplication} → ${data.versions.finalApplication}`}/><Version label="四级审核" value={`${data.versions.reviewConfirmed}/${data.versions.reviewTotal}`} detail="人工签名已冻结"/><Version label="财务批次" value={`BATCH v${data.versions.grantBatch.version}`} detail={data.versions.grantBatch.id}/><Version label="银行任务" value={`BANK v${data.versions.bankTask.version}`} detail={data.versions.bankTask.id}/><Version label="回盘/对账" value="MATCHED · ¥0" detail={`${data.versions.receipt.receiptNo} · ${data.versions.arrivalNotice.status}`}/></CardContent></Card>
  </div>;
}

function Title({icon:Icon,title,description}:{icon:typeof Database;title:string;description:string}){return <div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-400/10 text-blue-200"><Icon className="h-5 w-5"/></span><div><h2 className="text-sm font-bold">{title}</h2><p className="mt-1 text-[9px] text-slate-600">{description}</p></div></div>}
function Metric({label,value,detail,highlight=false}:{label:string;value:string;detail:string;highlight?:boolean}){return <div className="bg-slate-950/75 px-4 py-4"><p className="text-[9px] uppercase tracking-wider text-slate-600">{label}</p><p className={`mt-1 truncate text-lg font-bold ${highlight?"text-emerald-300":"text-slate-100"}`}>{value}</p><p className="mt-1 truncate text-[8px] text-slate-600">{detail}</p></div>}
function Value({label,value,good=false}:{label:string;value:string;good?:boolean}){return <div className="flex items-center justify-between gap-4 rounded-xl border border-white/8 bg-white/[.025] p-3"><p className="text-[9px] text-slate-600">{label}</p><p className={`max-w-[70%] truncate text-right text-[9px] font-semibold ${good?"text-emerald-300":"text-slate-300"}`}>{value}</p></div>}
function Version({label,value,detail}:{label:string;value:string;detail:string}){return <div className="rounded-2xl border border-white/8 bg-white/[.025] p-4"><p className="text-[9px] uppercase tracking-wider text-slate-600">{label}</p><p className="mt-2 text-base font-bold text-emerald-300">{value}</p><p className="mt-2 truncate font-mono text-[8px] text-slate-600">{detail}</p></div>}
