"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ClipboardCheck, Clock3, Eye, Loader2, RefreshCw, RotateCcw, ShieldCheck } from "lucide-react";
import { EnterprisePageHeader } from "@/components/enterprise/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
interface Ticket { id: string; applicationId: string; projectName: string; receiptNo: string; status: string; priority: string; handlerRole: string; dueAt: string; issues: string[]; version: number; updatedAt: string }
interface Payload { tickets: Ticket[]; summary: { total: number; queued: number; correction: number; highPriority: number } }
interface Envelope<T> { success: boolean; data?: T; error?: string }
function headers(): HeadersInit { const token = localStorage.getItem("token"); return token ? { Authorization: `Bearer ${token}` } : {}; }
export default function ApplicationIntakePage() {
  const [data, setData] = useState<Payload | null>(null); const [filter, setFilter] = useState("all"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/application-intake/tickets", { headers: headers(), cache: "no-store" }); const body = await response.json() as Envelope<Payload>; if (!response.ok || !body.success || !body.data) throw new Error(body.error ?? "受理工单加载失败"); setData(body.data); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "受理工单加载失败"); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  const tickets = useMemo(() => (data?.tickets ?? []).filter((ticket) => filter === "all" || (filter === "queued" ? ["queued", "resubmitted"].includes(ticket.status) : filter === "high" ? ticket.priority === "high" : ticket.status === filter)), [data, filter]);
  return <div className="space-y-6 pb-10"><EnterprisePageHeader eyebrow="APPLICATION INTAKE QUEUE" title="申请受理与补正工单" description="每一份正式申请自动生成受理工单、回执、处理时限和状态通知；列表严格复用当前岗位组织数据范围。" icon={ClipboardCheck} badge="PERSISTED · VERSIONED" />
    <div className="flex justify-end"><Button variant="outline" onClick={() => void load()} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading ? "animate-spin" : ""}`} />刷新工单</Button></div>
    {error && <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="授权范围工单" value={data?.summary.total ?? 0} icon={ClipboardCheck} active={filter === "all"} onClick={() => setFilter("all")} /><Metric label="待受理" value={data?.summary.queued ?? 0} icon={Clock3} active={filter === "queued"} onClick={() => setFilter("queued")} /><Metric label="待补正" value={data?.summary.correction ?? 0} icon={RotateCcw} active={filter === "correction_required"} onClick={() => setFilter("correction_required")} /><Metric label="高优先级" value={data?.summary.highPriority ?? 0} icon={AlertTriangle} active={filter === "high"} onClick={() => setFilter("high")} /></div>
    <Card><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>工单 / 申请</TableHead><TableHead>项目与回执</TableHead><TableHead>受理状态</TableHead><TableHead>当前岗位</TableHead><TableHead>处理时限</TableHead><TableHead className="text-right">下钻</TableHead></TableRow></TableHeader><TableBody>{loading ? <TableRow><TableCell colSpan={6} className="h-28 text-center"><Loader2 className="mx-auto h-5 w-5 animate-spin" /></TableCell></TableRow> : tickets.length ? tickets.map(ticket => <TableRow key={ticket.id}><TableCell><p className="font-mono text-xs font-semibold text-blue-700">{ticket.id}</p><p className="mt-1 font-mono text-[10px] text-muted-foreground">{ticket.applicationId} · v{ticket.version}</p></TableCell><TableCell><p className="text-sm font-medium">{ticket.projectName}</p><p className="mt-1 font-mono text-[10px] text-muted-foreground">{ticket.receiptNo}</p></TableCell><TableCell><Badge className={ticket.status === "correction_required" ? "bg-amber-100 text-amber-800" : ticket.status === "closed" ? "bg-slate-100 text-slate-700" : "bg-blue-100 text-blue-800"}>{ticket.status}</Badge>{ticket.priority === "high" && <Badge className="ml-1 bg-rose-100 text-rose-700">高优先</Badge>}</TableCell><TableCell><Badge variant="outline">{ticket.handlerRole}</Badge></TableCell><TableCell className="text-xs">{new Date(ticket.dueAt).toLocaleString("zh-CN")}</TableCell><TableCell className="text-right"><Button asChild size="sm" variant="outline"><Link href={`/application/intake/${ticket.id}`}><Eye className="mr-1 h-3.5 w-3.5" />详情</Link></Button></TableCell></TableRow>) : <TableRow><TableCell colSpan={6} className="h-28 text-center text-muted-foreground">当前筛选下暂无工单</TableCell></TableRow>}</TableBody></Table></div></CardContent></Card>
    <div className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-xs leading-6 text-blue-900"><ShieldCheck className="mr-2 inline h-4 w-4" />工单处理执行角色、组织范围、状态机、乐观锁、幂等键与人工确认六重校验；AI只能提出补正建议，不能自动退回或通过。</div>
  </div>;
}
function Metric({ label, value, icon: Icon, active, onClick }: { label: string; value: number; icon: typeof ClipboardCheck; active: boolean; onClick: () => void }) { return <button onClick={onClick} className="text-left"><Card className={active ? "border-blue-300 ring-1 ring-blue-100" : ""}><CardContent className="flex items-center gap-4 p-5"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-700"><Icon className="h-5 w-5" /></span><div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div></CardContent></Card></button>; }
