"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, Bot, CheckCircle2, ClipboardCheck, RefreshCw, Scale, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";

type DifficultyStatus = "pending_democratic_review" | "pending_department_review" | "pending_school_confirmation" | "confirmed" | "returned";
type DifficultyLevel = "一般困难" | "困难" | "特别困难" | "不予认定";
type DifficultyAction = "submit_democratic_review" | "department_approve" | "department_return" | "school_confirm" | "school_return" | "restart_review";
interface Assessment { id: string; applicationId: string; studentName: string; studentNo: string; householdIncomePerCapita: number; burdenScore: number; specialFactors: string[]; democraticVotesAgree: number; democraticVotesTotal: number; ruleScore: number; aiSuggestedLevel: DifficultyLevel; finalLevel?: DifficultyLevel; status: DifficultyStatus; riskFlags: string[]; lastComment?: string; version: number; updatedAt: string }
interface Envelope<T> { success: boolean; data?: T; error?: string; message?: string }
interface PendingAction { assessment: Assessment; action: DifficultyAction; title: string }

const STATUS: Record<DifficultyStatus, { label: string; style: string; step: number }> = {
  pending_democratic_review: { label: "待民主评议", style: "border-blue-200 bg-blue-50 text-blue-700", step: 1 },
  pending_department_review: { label: "待院系复核", style: "border-violet-200 bg-violet-50 text-violet-700", step: 2 },
  pending_school_confirmation: { label: "待校级确认", style: "border-amber-200 bg-amber-50 text-amber-700", step: 3 },
  confirmed: { label: "已认定", style: "border-emerald-200 bg-emerald-50 text-emerald-700", step: 4 },
  returned: { label: "已退回评议", style: "border-rose-200 bg-rose-50 text-rose-700", step: 1 },
};
const LEVELS: DifficultyLevel[] = ["一般困难", "困难", "特别困难", "不予认定"];
function authHeaders(extra?: Record<string, string>): HeadersInit { const token = window.localStorage.getItem("token"); return { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}), ...extra }; }
function currentRole() { try { const user = JSON.parse(window.localStorage.getItem("user") ?? "{}") as { role?: string; roles?: Array<{ code?: string }> }; return user.roles?.[0]?.code ?? user.role ?? ""; } catch { return ""; } }
function actionsFor(role: string, assessment: Assessment): PendingAction[] { const make = (action: DifficultyAction, title: string) => ({ assessment, action, title }); if (role === "COUNSELOR" && assessment.status === "pending_democratic_review") return [make("submit_democratic_review", "录入并提交民主评议")]; if (role === "COUNSELOR" && assessment.status === "returned") return [make("restart_review", "重新发起民主评议")]; if (role === "DEPT_ADMIN" && assessment.status === "pending_department_review") return [make("department_approve", "院系复核通过"), make("department_return", "退回民主评议")]; if (role === "FUND_ADMIN" && assessment.status === "pending_school_confirmation") return [make("school_confirm", "人工确认困难等级"), make("school_return", "退回院系复核")]; return []; }

export default function DifficultyPage() {
  const router = useRouter();
  const [items, setItems] = useState<Assessment[]>([]); const [role, setRole] = useState(""); const [loading, setLoading] = useState(true); const [message, setMessage] = useState<{ type: "success" | "error"; text: string } | null>(null); const [pending, setPending] = useState<PendingAction | null>(null); const [comment, setComment] = useState(""); const [votesAgree, setVotesAgree] = useState(""); const [votesTotal, setVotesTotal] = useState(""); const [finalLevel, setFinalLevel] = useState<DifficultyLevel>("困难"); const [submitting, setSubmitting] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/funding/difficulty", { headers: authHeaders(), cache: "no-store" }); const body = await response.json() as Envelope<Assessment[]>; if (!response.ok || !body.success) throw new Error(body.error ?? "困难认定数据加载失败"); setItems(body.data ?? []); } catch (reason) { setMessage({ type: "error", text: reason instanceof Error ? reason.message : "困难认定数据加载失败" }); } finally { setLoading(false); } }, []);
  useEffect(() => { setRole(currentRole()); void load(); }, [load]);
  const metrics = useMemo(() => ({ pending: items.filter((item) => item.status !== "confirmed").length, confirmed: items.filter((item) => item.status === "confirmed").length, highRisk: items.filter((item) => item.riskFlags.length > 0).length, average: items.length ? Math.round(items.reduce((sum, item) => sum + item.ruleScore, 0) / items.length) : 0 }), [items]);
  const openAction = (action: PendingAction) => { setPending(action); setComment(""); setVotesAgree(action.assessment.democraticVotesAgree ? String(action.assessment.democraticVotesAgree) : ""); setVotesTotal(action.assessment.democraticVotesTotal ? String(action.assessment.democraticVotesTotal) : ""); setFinalLevel(action.assessment.aiSuggestedLevel); };
  const execute = async () => { if (!pending || comment.trim().length < 2) return; setSubmitting(true); try { const response = await fetch(`/api/funding/difficulty/${pending.assessment.id}/actions`, { method: "POST", headers: authHeaders({ "Idempotency-Key": `difficulty-${pending.action}-${pending.assessment.id}-v${pending.assessment.version}` }), body: JSON.stringify({ action: pending.action, expectedVersion: pending.assessment.version, comment: comment.trim(), humanConfirmed: true, ...(pending.action === "submit_democratic_review" ? { votesAgree: Number(votesAgree), votesTotal: Number(votesTotal) } : {}), ...(pending.action === "school_confirm" ? { finalLevel } : {}) }) }); const body = await response.json() as Envelope<Assessment>; if (!response.ok || !body.success) throw new Error(body.error ?? "认定流程处理失败"); setMessage({ type: "success", text: body.message ?? "认定流程已更新" }); setPending(null); await load(); } catch (reason) { setMessage({ type: "error", text: reason instanceof Error ? reason.message : "认定流程处理失败" }); } finally { setSubmitting(false); } };
  return <div className="space-y-6"><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-2 flex items-center gap-2 text-xs font-medium text-blue-700"><ShieldCheck className="h-4 w-4" />规则评分与民主评议并行 · AI建议不替代认定</div><h1 className="text-2xl font-bold text-slate-900">家庭经济困难认定工作台</h1><p className="mt-1 text-sm text-slate-500">班级民主评议、院系复核、校级确认三级流程；最终等级只能由有权人员人工选择。</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => void load()}><RefreshCw className={`mr-2 h-4 w-4 ${loading ? "animate-spin" : ""}`} />刷新</Button><Button onClick={() => router.push("/ai-assistant/chat?scene=difficulty-review")}><Bot className="mr-2 h-4 w-4" />AI材料核验</Button></div></div>
  {message && <div className={`rounded-xl border px-4 py-3 text-sm ${message.type === "success" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-rose-200 bg-rose-50 text-rose-700"}`}>{message.text}</div>}
  <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric icon={ClipboardCheck} label="待认定" value={metrics.pending} detail="按当前数据范围" tone="blue" /><Metric icon={CheckCircle2} label="已确认" value={metrics.confirmed} detail="人工最终认定" tone="emerald" /><Metric icon={AlertTriangle} label="需核验风险" value={metrics.highRisk} detail="AI不自动处置" tone="rose" /><Metric icon={Scale} label="平均规则分" value={metrics.average} detail="仅作辅助依据" tone="violet" /></div>
  <Card className="border-slate-200 shadow-sm"><CardHeader className="border-b border-slate-100"><CardTitle className="text-base">认定案件清单</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow className="bg-slate-50"><TableHead>学生 / 案件</TableHead><TableHead>家庭与特殊因素</TableHead><TableHead>规则评分</TableHead><TableHead>民主评议</TableHead><TableHead>AI建议 / 最终结果</TableHead><TableHead>流程</TableHead><TableHead className="text-right">当前操作</TableHead></TableRow></TableHeader><TableBody>{loading ? <TableRow><TableCell colSpan={7} className="h-32 text-center text-slate-500">加载授权范围内案件…</TableCell></TableRow> : items.map((item) => { const actions = actionsFor(role, item); const voteRate = item.democraticVotesTotal ? Math.round(item.democraticVotesAgree / item.democraticVotesTotal * 100) : 0; return <TableRow key={item.id}><TableCell><p className="font-medium text-slate-900">{item.studentName}</p><p className="mt-1 text-xs text-slate-400">{item.studentNo} · {item.id} · v{item.version}</p>{item.riskFlags.map((flag) => <p key={flag} className="mt-1 flex items-center gap-1 text-xs text-rose-600"><AlertTriangle className="h-3 w-3" />{flag}</p>)}</TableCell><TableCell className="max-w-xs"><p className="text-sm text-slate-700">人均月收入 ¥{item.householdIncomePerCapita.toLocaleString("zh-CN")}</p><div className="mt-2 flex flex-wrap gap-1">{item.specialFactors.map((factor) => <Badge key={factor} variant="secondary" className="font-normal">{factor}</Badge>)}</div></TableCell><TableCell><div className="w-28"><div className="mb-1 flex justify-between text-xs"><span>规则分</span><strong>{item.ruleScore}</strong></div><Progress value={item.ruleScore} className="h-1.5" /><p className="mt-1 text-xs text-slate-400">负担指数 {item.burdenScore}</p></div></TableCell><TableCell><p className="text-sm font-medium text-slate-700">{item.democraticVotesTotal ? `${item.democraticVotesAgree}/${item.democraticVotesTotal}` : "尚未评议"}</p>{item.democraticVotesTotal > 0 && <p className="mt-1 text-xs text-slate-400">同意率 {voteRate}%</p>}</TableCell><TableCell><p className="flex items-center gap-1 text-xs text-violet-700"><Sparkles className="h-3 w-3" />建议：{item.aiSuggestedLevel}</p><p className="mt-2 text-sm font-semibold text-slate-900">结果：{item.finalLevel ?? "待人工确认"}</p></TableCell><TableCell><Badge variant="outline" className={STATUS[item.status].style}>{STATUS[item.status].label}</Badge><div className="mt-2 flex gap-1">{[1,2,3,4].map((step) => <span key={step} className={`h-1.5 w-6 rounded ${step <= STATUS[item.status].step ? "bg-blue-500" : "bg-slate-200"}`} />)}</div></TableCell><TableCell><div className="flex max-w-56 flex-wrap justify-end gap-2">{actions.length ? actions.map((action) => <Button key={action.action} size="sm" variant="outline" onClick={() => openAction(action)}>{action.title}</Button>) : <span className="text-xs text-slate-400">只读</span>}</div></TableCell></TableRow>; })}</TableBody></Table></div></CardContent></Card>
  <AlertDialog open={Boolean(pending)} onOpenChange={(open) => { if (!open && !submitting) setPending(null); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{pending?.title}</AlertDialogTitle><AlertDialogDescription>案件：{pending?.assessment.studentName}（{pending?.assessment.id}）。AI给出的“{pending?.assessment.aiSuggestedLevel}”仅是建议，处理人必须独立判断。</AlertDialogDescription></AlertDialogHeader>{pending?.action === "submit_democratic_review" && <div className="grid grid-cols-2 gap-3"><Field label="同意票"><Input type="number" value={votesAgree} onChange={(event) => setVotesAgree(event.target.value)} /></Field><Field label="总票数"><Input type="number" value={votesTotal} onChange={(event) => setVotesTotal(event.target.value)} /></Field></div>}{pending?.action === "school_confirm" && <Field label="人工最终等级"><Select value={finalLevel} onValueChange={(value) => setFinalLevel(value as DifficultyLevel)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{LEVELS.map((level) => <SelectItem key={level} value={level}>{level}</SelectItem>)}</SelectContent></Select></Field>}<Field label="处理意见"><Textarea value={comment} onChange={(event) => setComment(event.target.value)} placeholder="请输入明确的评议、核验或认定依据" maxLength={500} /></Field><AlertDialogFooter><AlertDialogCancel disabled={submitting}>取消</AlertDialogCancel><AlertDialogAction onClick={(event) => { event.preventDefault(); void execute(); }} disabled={submitting || comment.trim().length < 2}>{submitting ? "处理中…" : "人工确认并提交"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
function Metric({ icon: Icon, label, value, detail, tone }: { icon: typeof ClipboardCheck; label: string; value: number; detail: string; tone: "blue" | "emerald" | "rose" | "violet" }) { const color = { blue: "bg-blue-50 text-blue-700", emerald: "bg-emerald-50 text-emerald-700", rose: "bg-rose-50 text-rose-700", violet: "bg-violet-50 text-violet-700" }; return <Card className="border-slate-200 shadow-sm"><CardContent className="flex items-center gap-4 p-5"><span className={`rounded-xl p-3 ${color[tone]}`}><Icon className="h-5 w-5" /></span><div><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-400">{detail}</p></div></CardContent></Card>; }


