"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, Building2, CheckCircle2, GitBranch, KeyRound, LockKeyhole, Network, RefreshCw, ScanSearch, ServerCog, ShieldCheck, Users, Workflow, XCircle } from "lucide-react";
import { useHashTab } from "@/hooks/use-hash-tab";
import { EnterprisePageHeader } from "@/components/enterprise/page-header";
import { MetricCard, SectionHeading, StatusPill } from "@/components/enterprise/dashboard";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";

type AccountStatus = "active" | "frozen" | "disabled";
interface Account { id: string; username: string; name: string; role: string; department: string; campus: string; status: AccountStatus; mfa: boolean; lastActive: string; version: number }
interface Org { id: string; name: string; type: string; children?: Org[] }
interface Session { id: string; accountId: string; user: string; role: string; ip: string; device: string; signedInAt: string; lastSeenAt: string; risk: "normal" | "attention"; status: "online" | "terminated"; version: number }
interface Conflict { id: string; severity: "high" | "medium" | "low"; subject: string; rule: string; detail: string; suggestion: string; status: "open" | "resolved"; detectedAt: string }
interface WorkflowItem { id: string; name: string; versionName: string; nodes: string[]; timeoutHours: number; rollbackEnabled: boolean; status: "active" | "draft"; version: number }
interface Snapshot { organizations: Org[]; accounts: Account[]; sessions: Session[]; conflicts: Conflict[]; workflows: WorkflowItem[]; policy: { mfaRequiredForAdmins: boolean; passwordValidityDays: number; idleSessionMinutes: number; draftRetentionDays: number; graduateArchiveYears: number; caseRetentionYears: number; logLevel: string; version: number }; integrations: Array<{ id: string; name: string; protocol: string; auth: string; status: "healthy" | "degraded"; calls24h: number; successRate: number; latencyMs: number }>; auditEvents: Array<{ id: string; time: string; actor: string; action: string; result: string; ip: string }> }
interface Envelope<T> { success: boolean; data?: T; error?: string; message?: string }
type Pending = { title: string; description: string; body: Record<string, unknown>; confirm: string };

function requestHeaders() { const token = localStorage.getItem("token"); return { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }; }
function idempotencyKey() { return `platform-${Date.now()}-${crypto.randomUUID()}`; }
function countOrg(nodes: Org[]): number { return nodes.reduce((sum, node) => sum + 1 + countOrg(node.children ?? []), 0); }

export default function PlatformGovernancePage() {
  const [tab, setTab] = useHashTab(["identity", "permissions", "workflow", "integrations"] as const, "identity");
  const [data, setData] = useState<Snapshot | null>(null); const [loading, setLoading] = useState(true); const [pending, setPending] = useState<Pending | null>(null); const [reason, setReason] = useState(""); const [submitting, setSubmitting] = useState(false); const [notice, setNotice] = useState<{ tone: "ok" | "error"; text: string } | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/platform/operations", { headers: requestHeaders(), cache: "no-store" }); const body = await response.json() as Envelope<Snapshot>; if (!response.ok || !body.success || !body.data) throw new Error(body.error ?? "平台治理数据加载失败"); setData(body.data); } catch (error) { setNotice({ tone: "error", text: error instanceof Error ? error.message : "平台治理数据加载失败" }); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const metrics = useMemo(() => ({ orgs: data ? countOrg(data.organizations) : 0, online: data?.sessions.filter(item => item.status === "online").length ?? 0, conflicts: data?.conflicts.filter(item => item.status === "open").length ?? 0, health: data ? data.integrations.filter(item => item.status === "healthy").length / data.integrations.length * 100 : 0 }), [data]);
  const open = (item: Pending) => { setPending(item); setReason(""); };
  const execute = async () => { if (!pending || reason.trim().length < 4) return; setSubmitting(true); try { const response = await fetch("/api/platform/operations", { method: "POST", headers: { ...requestHeaders(), "Idempotency-Key": idempotencyKey() }, body: JSON.stringify({ ...pending.body, reason: reason.trim() }) }); const body = await response.json() as Envelope<unknown>; if (!response.ok || !body.success) throw new Error(body.error ?? "平台治理操作失败"); setNotice({ tone: "ok", text: body.message ?? "操作已完成" }); setPending(null); await load(); } catch (error) { setNotice({ tone: "error", text: error instanceof Error ? error.message : "平台治理操作失败" }); } finally { setSubmitting(false); } };
  return <div className="space-y-6">
    <EnterprisePageHeader eyebrow="PLATFORM CONTROL PLANE" title="平台治理与安全控制中心" description="覆盖 v6 规划中的组织树、账号生命周期、RBAC冲突、九维权限、流程模板、会话、数据保留、MCP接入与全量审计。所有变更均要求人工理由、幂等校验并写入审计证据。" icon={ServerCog} badge="SYS_ADMIN · 平台范围" actions={[{ label: "刷新运行态", icon: RefreshCw, variant: "outline", onClick: () => void load(), disabled: loading }, { label: "运行权限冲突扫描", icon: ScanSearch, onClick: () => open({ title: "运行全量权限冲突扫描", description: "扫描 RBAC、字段权限、流程职责分离、时间与地理约束，结果将进入审计日志。", confirm: "开始扫描", body: { action: "run_conflict_scan" } }) }]} />
    {notice && <div className={`rounded-xl border px-4 py-3 text-sm ${notice.tone === "ok" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-rose-200 bg-rose-50 text-rose-700"}`}>{notice.text}</div>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="组织与隔离节点" value={metrics.orgs.toString()} detail={`${data?.organizations.length ?? 0} 个校区根节点，按校区/院系/专业/班级隔离`} icon={Building2} tone="blue" /><MetricCard label="在线安全会话" value={metrics.online.toString()} detail="支持风险识别与强制下线" icon={Users} tone="cyan" /><MetricCard label="待处置权限冲突" value={metrics.conflicts.toString()} detail="AI辅助发现，最终由管理员人工处置" icon={AlertTriangle} tone={metrics.conflicts > 0 ? "amber" : "emerald"} /><MetricCard label="外部连接健康度" value={`${metrics.health.toFixed(0)}%`} detail="教务、银行、教育厅接口实时状态" icon={Network} tone="emerald" /></div>
    {data && <Tabs value={tab} onValueChange={setTab} className="space-y-5"><TabsList className="h-auto flex-wrap rounded-xl border border-slate-200 bg-white p-1"><TabsTrigger value="identity">组织与账号</TabsTrigger><TabsTrigger value="permissions">权限冲突</TabsTrigger><TabsTrigger value="workflow">流程与策略</TabsTrigger><TabsTrigger value="integrations">接入与审计</TabsTrigger></TabsList>
      <TabsContent value="identity" className="grid gap-5 xl:grid-cols-[.8fr_1.8fr]">
        <Card className="border-slate-200 shadow-sm"><CardHeader><SectionHeading title="多校区组织树" description="数据隔离边界随组织节点继承" /></CardHeader><CardContent className="space-y-2">{data.organizations.map(node => <OrgNode key={node.id} node={node} depth={0} />)}</CardContent></Card>
        <Card className="border-slate-200 shadow-sm"><CardHeader><SectionHeading title="账号生命周期" description="开通、启用、冻结、停用与强认证状态" /></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-y border-slate-100 bg-slate-50/80 text-[10px] uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3">账号/岗位</th><th className="px-4 py-3">组织范围</th><th className="px-4 py-3">MFA</th><th className="px-4 py-3">状态</th><th className="px-5 py-3 text-right">操作</th></tr></thead><tbody>{data.accounts.map(account => <tr key={account.id} className="border-b border-slate-100 last:border-0"><td className="px-5 py-4"><p className="font-semibold text-slate-800">{account.name}</p><p className="mt-1 text-[10px] text-slate-400">{account.username} · {account.role}</p></td><td className="px-4 py-4"><p className="text-slate-600">{account.department}</p><p className="mt-1 text-[10px] text-slate-400">{account.campus}</p></td><td className="px-4 py-4">{account.mfa ? <StatusPill status="healthy" label="已启用" /> : <StatusPill status="warning" label="未启用" />}</td><td className="px-4 py-4"><StatusPill status={account.status === "active" ? "healthy" : account.status === "frozen" ? "warning" : "danger"} label={account.status === "active" ? "正常" : account.status === "frozen" ? "冻结" : "停用"} /></td><td className="px-5 py-4 text-right"><Button size="sm" variant="outline" disabled={account.id === "u-sys"} onClick={() => open({ title: account.status === "active" ? "冻结账号" : "恢复账号", description: `${account.name}（${account.role}）的权限与在线状态将立即变化。`, confirm: account.status === "active" ? "确认冻结" : "确认恢复", body: { action: "set_account_status", accountId: account.id, status: account.status === "active" ? "frozen" : "active", expectedVersion: account.version } })}>{account.status === "active" ? "冻结" : "恢复"}</Button></td></tr>)}</tbody></table></div></CardContent></Card>
        <Card className="border-slate-200 shadow-sm xl:col-span-2"><CardHeader><SectionHeading title="在线会话与风险终端" description="支持查看在线用户、终端、IP与强制踢出" /></CardHeader><CardContent className="grid gap-3 lg:grid-cols-3">{data.sessions.map(session => <div key={session.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-slate-800">{session.user}</p><p className="mt-1 text-[10px] text-slate-400">{session.role}</p></div><StatusPill status={session.status === "terminated" ? "neutral" : session.risk === "attention" ? "warning" : "healthy"} label={session.status === "terminated" ? "已下线" : session.risk === "attention" ? "需关注" : "在线"} /></div><div className="mt-4 space-y-1.5 text-[11px] text-slate-500"><p>{session.device}</p><p className="font-mono">{session.ip}</p><p>登录 {session.signedInAt} · {session.lastSeenAt}</p></div><Button className="mt-4 w-full" size="sm" variant="outline" disabled={session.status !== "online" || session.accountId === "u-sys"} onClick={() => open({ title: "强制终止在线会话", description: `将立即终止 ${session.user} 在 ${session.ip} 的会话，并记录操作证据。`, confirm: "强制下线", body: { action: "terminate_session", sessionId: session.id, expectedVersion: session.version } })}>强制下线</Button></div>)}</CardContent></Card>
      </TabsContent>
      <TabsContent value="permissions" className="space-y-4">{data.conflicts.map(conflict => <Card key={conflict.id} className="border-slate-200 shadow-sm"><CardContent className="flex flex-col gap-4 p-5 lg:flex-row lg:items-center"><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${conflict.severity === "high" ? "bg-rose-50 text-rose-600" : conflict.severity === "medium" ? "bg-amber-50 text-amber-600" : "bg-blue-50 text-blue-600"}`}><AlertTriangle className="h-5 w-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-slate-800">{conflict.subject}</p><Badge variant="outline">{conflict.rule}</Badge><StatusPill status={conflict.status === "resolved" ? "healthy" : conflict.severity === "high" ? "danger" : "warning"} label={conflict.status === "resolved" ? "已处置" : "待处置"} /></div><p className="mt-2 text-xs text-slate-600">{conflict.detail}</p><p className="mt-1.5 text-[11px] text-blue-700">建议：{conflict.suggestion}</p></div><Button variant="outline" disabled={conflict.status === "resolved"} onClick={() => open({ title: "确认权限冲突处置", description: conflict.suggestion, confirm: "完成处置", body: { action: "resolve_conflict", conflictId: conflict.id } })}>标记已处置</Button></CardContent></Card>)}</TabsContent>
      <TabsContent value="workflow" className="grid gap-5 xl:grid-cols-[1.5fr_1fr]">
        <Card className="border-slate-200 shadow-sm"><CardHeader><SectionHeading title="审批流模板" description="节点、处理人、超时、动态路由与回退策略" /></CardHeader><CardContent className="space-y-4">{data.workflows.map(flow => <div key={flow.id} className={`rounded-xl border p-4 ${flow.status === "active" ? "border-blue-200 bg-blue-50/35" : "border-slate-200"}`}><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><p className="text-sm font-semibold text-slate-800">{flow.name}</p><Badge variant="outline">{flow.versionName}</Badge></div><p className="mt-1 text-[10px] text-slate-400">超时 {flow.timeoutHours}h · {flow.rollbackEnabled ? "允许受控回退" : "禁止回退"}</p></div><StatusPill status={flow.status === "active" ? "healthy" : "neutral"} label={flow.status === "active" ? "当前生效" : "草稿"} /></div><div className="mt-4 flex flex-wrap items-center gap-1.5">{flow.nodes.map((node, index) => <div key={node} className="flex items-center gap-1.5"><span className="rounded-lg border border-slate-200 bg-white px-2.5 py-1.5 text-[10px] text-slate-600">{node}</span>{index < flow.nodes.length - 1 && <span className="text-slate-300">→</span>}</div>)}</div>{flow.status === "draft" && <Button className="mt-4" size="sm" onClick={() => open({ title: "发布审批流模板", description: "发布后将成为新申请的默认流程；在途实例仍使用原流程快照。", confirm: "人工确认并发布", body: { action: "activate_workflow", workflowId: flow.id, expectedVersion: flow.version } })}><GitBranch className="mr-2 h-3.5 w-3.5" />发布流程</Button>}</div>)}</CardContent></Card>
        <Card className="border-slate-200 shadow-sm"><CardHeader><SectionHeading title="确定性安全策略" description="这些校验由程序执行，不交给模型判断" /></CardHeader><CardContent className="space-y-3"><Policy label="管理岗位强制MFA" value={data.policy.mfaRequiredForAdmins ? "已启用" : "已关闭"} icon={LockKeyhole} /><Policy label="密码有效期" value={`${data.policy.passwordValidityDays} 天`} icon={KeyRound} /><Policy label="空闲会话超时" value={`${data.policy.idleSessionMinutes} 分钟`} icon={Activity} /><Policy label="毕业记录脱敏归档" value={`${data.policy.graduateArchiveYears} 年`} icon={ShieldCheck} /><Policy label="案件材料保留" value={`${data.policy.caseRetentionYears} 年`} icon={Workflow} /><Button className="mt-2 w-full" variant="outline" onClick={() => open({ title: data.policy.mfaRequiredForAdmins ? "关闭强制MFA策略" : "启用强制MFA策略", description: "该变更将影响所有管理岗位的下一次登录，必须保留审计理由。", confirm: "确认变更", body: { action: "update_mfa_policy", required: !data.policy.mfaRequiredForAdmins, expectedVersion: data.policy.version } })}>变更MFA策略</Button></CardContent></Card>
      </TabsContent>
      <TabsContent value="integrations" className="grid gap-5 xl:grid-cols-[1.2fr_1fr]">
        <Card className="border-slate-200 shadow-sm"><CardHeader><SectionHeading title="MCP / API 接入健康" description="密钥由 Vault 引用，页面不展示真实凭据" /></CardHeader><CardContent className="space-y-3">{data.integrations.map(item => <div key={item.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-slate-800">{item.name}</p><p className="mt-1 text-[10px] text-slate-400">{item.protocol} · {item.auth}</p></div><StatusPill status={item.status === "healthy" ? "healthy" : "warning"} label={item.status === "healthy" ? "健康" : "降级"} /></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><Tiny label="24h调用" value={item.calls24h.toLocaleString()} /><Tiny label="成功率" value={`${item.successRate}%`} /><Tiny label="平均延迟" value={`${item.latencyMs}ms`} /></div></div>)}</CardContent></Card>
        <Card className="border-slate-200 shadow-sm"><CardHeader><SectionHeading title="最新审计事件" description="登录、业务操作、AI调用统一留痕" /></CardHeader><CardContent className="space-y-1">{data.auditEvents.map(event => <div key={event.id} className="flex items-start gap-3 border-b border-slate-100 py-3 last:border-0"><span className="mt-1 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-slate-100">{event.result === "成功" || event.result === "通过" || event.result === "允许" ? <CheckCircle2 className="h-3.5 w-3.5 text-emerald-600" /> : <XCircle className="h-3.5 w-3.5 text-rose-600" />}</span><div className="min-w-0"><p className="text-xs font-medium text-slate-700">{event.action}</p><p className="mt-1 text-[10px] text-slate-400">{event.time} · {event.actor} · {event.ip} · {event.result}</p></div></div>)}</CardContent></Card>
      </TabsContent>
    </Tabs>}
    <AlertDialog open={Boolean(pending)} onOpenChange={openState => { if (!openState && !submitting) setPending(null); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{pending?.title}</AlertDialogTitle><AlertDialogDescription>{pending?.description}</AlertDialogDescription></AlertDialogHeader><Textarea value={reason} onChange={event => setReason(event.target.value)} placeholder="请输入变更原因、依据或回滚说明（至少4个字）" maxLength={500} /><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction disabled={submitting || reason.trim().length < 4} onClick={event => { event.preventDefault(); void execute(); }}>{submitting ? "提交中…" : pending?.confirm}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
function OrgNode({ node, depth }: { node: Org; depth: number }) { const icons = { campus: Building2, college: Network, major: GitBranch, class: Users }; const Icon = icons[node.type as keyof typeof icons] ?? Building2; return <div><div className="flex items-center gap-2 rounded-lg py-2" style={{ paddingLeft: depth * 18 }}><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-slate-100 text-slate-500"><Icon className="h-3.5 w-3.5" /></span><div><p className="text-xs font-medium text-slate-700">{node.name}</p><p className="text-[9px] uppercase text-slate-400">{node.type}</p></div></div>{node.children?.map(child => <OrgNode key={child.id} node={child} depth={depth + 1} />)}</div>; }
function Policy({ label, value, icon: Icon }: { label: string; value: string; icon: typeof LockKeyhole }) { return <div className="flex items-center justify-between rounded-xl border border-slate-100 bg-slate-50/70 p-3"><div className="flex items-center gap-2.5"><Icon className="h-4 w-4 text-slate-500" /><span className="text-xs text-slate-600">{label}</span></div><span className="text-xs font-semibold text-slate-800">{value}</span></div>; }
function Tiny({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-slate-50 p-2"><p className="text-xs font-bold text-slate-800">{value}</p><p className="mt-1 text-[9px] text-slate-400">{label}</p></div>; }

