"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, Award, BarChart3, BookHeart, Brain, CalendarDays, CheckCircle2, FileText, HeartHandshake, RefreshCw, Sparkles, TrendingUp, UserRoundCheck, UsersRound } from "lucide-react";
import { useHashTab } from "@/hooks/use-hash-tab";
import { EnterprisePageHeader } from "@/components/enterprise/page-header";
import { MetricCard, SectionHeading, StatusPill } from "@/components/enterprise/dashboard";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";

type GrowthStatus = "tracking" | "intervening" | "closed";
interface GrowthCase { id: string; studentCode: string; college: string; grade: string; project: string; growthScore: number; growthDelta: number; academicDelta: number; serviceHours: number; keyEvent: string; risk: "stable" | "attention" | "priority"; status: GrowthStatus; nextFollowUp: string; version: number }
interface Project { id: string; name: string; category: string; participants: number; completionRate: number; growthGain: number; costPerStudent: number; roi: number; status: "running" | "evaluating" | "completed" }
interface Typical { id: string; title: string; studentCode: string; tags: string[]; highlights: string; evidenceCount: number; consent: boolean; status: "draft" | "approved" | "published"; version: number }
interface EducationActivity { id: string; name: string; type: string; date: string; audience: string; enrolled: number; completed: number; satisfaction: number; status: "draft" | "open" | "completed"; version: number }
interface Report { id: string; title: string; content: string; model: string; generatedAt: string; aggregateOnly: true }
interface Snapshot { cases: GrowthCase[]; projects: Project[]; typicalCases: Typical[]; activities: EducationActivity[]; reports: Report[]; indicators: { supportedStudents: number; averageGrowthGain: number; volunteerHours: number; projectCompletionRate: number; highPriorityCases: number; consentCoverage: number } }
interface Envelope<T> { success: boolean; data?: T; error?: string; message?: string }
type Pending = { title: string; description: string; body: Record<string, unknown>; confirm: string };
function headers() { const token = localStorage.getItem("token"); return { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }; }
function key() { return `affairs-${Date.now()}-${crypto.randomUUID()}`; }
export default function StudentAffairsPage() {
 const [tab, setTab] = useHashTab(["dashboard", "growth", "cases", "activities", "reports"] as const, "dashboard");
 const [data, setData] = useState<Snapshot | null>(null); const [loading, setLoading] = useState(true); const [pending, setPending] = useState<Pending | null>(null); const [note, setNote] = useState(""); const [working, setWorking] = useState(false); const [message, setMessage] = useState<{ type: "ok" | "error"; text: string } | null>(null);
 const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/student-affairs/operations", { headers: headers(), cache: "no-store" }); const body = await response.json() as Envelope<Snapshot>; if (!response.ok || !body.success || !body.data) throw new Error(body.error ?? "育人工作台加载失败"); setData(body.data); } catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "育人工作台加载失败" }); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
 const open = (item: Pending) => { setPending(item); setNote(""); };
 const runAction = async () => { if (!pending || note.trim().length < 4) return; setWorking(true); try { const response = await fetch("/api/student-affairs/operations", { method: "POST", headers: { ...headers(), "Idempotency-Key": key() }, body: JSON.stringify({ ...pending.body, note: note.trim() }) }); const body = await response.json() as Envelope<unknown>; if (!response.ok || !body.success) throw new Error(body.error ?? "操作失败"); setMessage({ type: "ok", text: body.message ?? "操作已完成" }); setPending(null); await load(); } catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "操作失败" }); } finally { setWorking(false); } };
 const generateReport = async () => { setWorking(true); try { const response = await fetch("/api/student-affairs/operations", { method: "POST", headers: headers(), body: JSON.stringify({ action: "generate_report" }) }); const body = await response.json() as Envelope<Report>; if (!response.ok || !body.success) throw new Error(body.error ?? "AI报告生成失败"); setMessage({ type: "ok", text: body.message ?? "AI报告草稿已生成" }); await load(); } catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "AI报告生成失败" }); } finally { setWorking(false); } };
 const priority = useMemo(() => data?.cases.filter(item => item.risk !== "stable").length ?? 0, [data]);
 return <div className="space-y-6"><EnterprisePageHeader eyebrow="STUDENT DEVELOPMENT" title="资助育人成效与成长追踪中心" description="落实 v6 规划中的成长轨迹、关键事件、项目效果与ROI、典型案例、励志教育、感恩教育和舆情协同；分析只使用脱敏汇总数据，个体干预由人工负责。" icon={BookHeart} badge="STU_AFFAIRS · 全校育人数据" actions={[{ label: "刷新数据", icon: RefreshCw, variant: "outline", onClick: () => void load(), disabled: loading }, { label: "生成AI成效报告", icon: Sparkles, onClick: () => void generateReport(), disabled: working }]} />
 {message && <div className={`rounded-xl border px-4 py-3 text-sm ${message.type === "ok" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-rose-200 bg-rose-50 text-rose-700"}`}>{message.text}</div>}
 {data && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="受助学生覆盖" value={data.indicators.supportedStudents.toLocaleString()} detail="当前学年已进入成长支持体系" icon={UsersRound} tone="blue" trend="同比 +6.8%" /><MetricCard label="平均成长增益" value={`+${data.indicators.averageGrowthGain}`} detail="综合学业、实践、发展与参与度" icon={TrendingUp} tone="emerald" /><MetricCard label="志愿服务时长" value={data.indicators.volunteerHours.toLocaleString()} detail="受助学生累计服务小时" icon={HeartHandshake} tone="violet" /><MetricCard label="项目完成率" value={`${data.indicators.projectCompletionRate}%`} detail="育人项目平均结项进度" icon={CheckCircle2} tone="cyan" /><MetricCard label="重点干预个案" value={data.indicators.highPriorityCases.toString()} detail={`当前列表 ${priority} 项需关注`} icon={UserRoundCheck} tone="amber" /></div>
 <Tabs value={tab} onValueChange={setTab} className="space-y-5"><TabsList className="h-auto flex-wrap rounded-xl border border-slate-200 bg-white p-1"><TabsTrigger value="dashboard">育人驾驶舱</TabsTrigger><TabsTrigger value="growth">成长追踪</TabsTrigger><TabsTrigger value="cases">典型案例库</TabsTrigger><TabsTrigger value="activities">教育活动</TabsTrigger><TabsTrigger value="reports">AI报告草稿</TabsTrigger></TabsList>
 <TabsContent value="dashboard" className="grid gap-5 xl:grid-cols-[1.25fr_1fr]"><Card className="border-slate-200 shadow-sm"><CardHeader><SectionHeading title="资助项目效果对比" description="成长增益、完成率与投入产出同时评估，不以单一指标替代育人判断" /></CardHeader><CardContent className="space-y-4">{data.projects.map(project => <div key={project.id}><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold text-slate-700">{project.name}</p><p className="mt-1 text-[10px] text-slate-400">{project.category} · {project.participants}人 · 人均¥{project.costPerStudent}</p></div><div className="text-right"><p className="text-sm font-bold text-blue-700">ROI {project.roi}</p><p className="text-[9px] text-slate-400">成长增益 +{project.growthGain}</p></div></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-blue-600 to-cyan-400" style={{ width: `${project.completionRate}%` }} /></div><p className="mt-1 text-right text-[9px] text-slate-400">完成率 {project.completionRate}%</p></div>)}</CardContent></Card><Card className="border-slate-200 shadow-sm"><CardHeader><SectionHeading title="重点关注信号" description="AI只做群体画像与提醒，不自动形成处分或资助结论" /></CardHeader><CardContent className="space-y-3">{data.cases.filter(item => item.risk !== "stable").map(item => <div key={item.id} className={`rounded-xl border p-4 ${item.risk === "priority" ? "border-rose-200 bg-rose-50/40" : "border-amber-200 bg-amber-50/40"}`}><div className="flex items-center justify-between"><p className="text-xs font-semibold text-slate-800">{item.studentCode}</p><StatusPill status={item.risk === "priority" ? "danger" : "warning"} label={item.risk === "priority" ? "重点干预" : "持续关注"} /></div><p className="mt-2 text-[11px] leading-5 text-slate-600">{item.keyEvent}</p><p className="mt-2 text-[10px] text-slate-400">下次跟进：{item.nextFollowUp}</p></div>)}</CardContent></Card></TabsContent>
 <TabsContent value="growth"><Card className="border-slate-200 shadow-sm"><CardHeader><SectionHeading title="受助学生成长轨迹" description="页面使用脱敏编码；敏感字段由数据权限层隔离" /></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-y border-slate-100 bg-slate-50 text-[10px] text-slate-400"><tr><th className="px-5 py-3">学生/项目</th><th className="px-4 py-3">成长表现</th><th className="px-4 py-3">关键事件</th><th className="px-4 py-3">跟进状态</th><th className="px-5 py-3 text-right">人工操作</th></tr></thead><tbody>{data.cases.map(item => <tr key={item.id} className="border-b border-slate-100 last:border-0"><td className="px-5 py-4"><p className="font-semibold text-slate-800">{item.studentCode}</p><p className="mt-1 text-[10px] text-slate-400">{item.college} · {item.grade}</p><p className="mt-1 text-[10px] text-blue-600">{item.project}</p></td><td className="px-4 py-4"><p className="text-lg font-bold text-slate-900">{item.growthScore}</p><p className={`text-[10px] ${item.growthDelta >= 0 ? "text-emerald-600" : "text-rose-600"}`}>成长 {item.growthDelta >= 0 ? "+" : ""}{item.growthDelta} · 绩点 {item.academicDelta >= 0 ? "+" : ""}{item.academicDelta}</p><p className="mt-1 text-[10px] text-slate-400">志愿 {item.serviceHours}h</p></td><td className="max-w-[320px] px-4 py-4 text-[11px] leading-5 text-slate-600">{item.keyEvent}</td><td className="px-4 py-4"><StatusPill status={item.status === "closed" ? "healthy" : item.status === "intervening" ? "warning" : "info"} label={item.status === "closed" ? "已结项" : item.status === "intervening" ? "干预中" : "追踪中"} /><p className="mt-2 text-[9px] text-slate-400">{item.nextFollowUp}</p></td><td className="px-5 py-4 text-right"><Button size="sm" variant="outline" onClick={() => open({ title: "登记成长跟进", description: "请记录本次人工访谈或协同跟进结果。AI不得替代辅导员或学工人员做个体决定。", confirm: "保存跟进", body: { action: "record_follow_up", caseId: item.id, status: item.risk === "priority" ? "intervening" : "tracking", nextFollowUp: "2026-09-01", expectedVersion: item.version } })}>登记跟进</Button></td></tr>)}</tbody></table></div></CardContent></Card></TabsContent>
 <TabsContent value="cases" className="grid gap-4 xl:grid-cols-3">{data.typicalCases.map(item => <Card key={item.id} className="border-slate-200 shadow-sm"><CardContent className="p-5"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-50 text-violet-700"><Award className="h-4 w-4" /></span><StatusPill status={item.status === "published" ? "healthy" : item.status === "approved" ? "info" : "neutral"} label={item.status === "published" ? "已发布" : item.status === "approved" ? "已审核" : "草稿"} /></div><h3 className="mt-4 text-sm font-semibold leading-6 text-slate-800">{item.title}</h3><p className="mt-1 text-[10px] text-slate-400">{item.studentCode} · 证据 {item.evidenceCount} 项 · {item.consent ? "已授权" : "未取得授权"}</p><p className="mt-3 text-[11px] leading-5 text-slate-600">{item.highlights}</p><div className="mt-3 flex flex-wrap gap-1.5">{item.tags.map(tag => <Badge key={tag} variant="secondary" className="text-[9px]">{tag}</Badge>)}</div>{item.status === "draft" && <Button className="mt-4 w-full" size="sm" variant="outline" disabled={!item.consent} onClick={() => open({ title: "审核典型学生案例", description: item.consent ? "审核通过后进入案例复用流程，发布前仍需隐私检查。" : "未取得学生授权，确定性规则禁止提交。", confirm: "审核通过", body: { action: "approve_typical_case", caseId: item.id, expectedVersion: item.version } })}>{item.consent ? "人工审核" : "等待学生授权"}</Button>}</CardContent></Card>)}</TabsContent>
 <TabsContent value="activities" className="grid gap-4 xl:grid-cols-3">{data.activities.map(item => <Card key={item.id} className="border-slate-200 shadow-sm"><CardContent className="p-5"><div className="flex items-start justify-between"><CalendarDays className="h-5 w-5 text-blue-600" /><StatusPill status={item.status === "completed" ? "healthy" : item.status === "open" ? "info" : "neutral"} label={item.status === "completed" ? "已完成" : item.status === "open" ? "报名中" : "草稿"} /></div><h3 className="mt-4 text-sm font-semibold text-slate-800">{item.name}</h3><p className="mt-1 text-[10px] text-slate-400">{item.type} · {item.date}</p><p className="mt-3 text-[11px] text-slate-500">对象：{item.audience}</p><div className="mt-4 grid grid-cols-3 gap-2"><Tiny label="报名" value={item.enrolled.toString()} /><Tiny label="完成" value={item.completed.toString()} /><Tiny label="满意度" value={item.satisfaction ? `${item.satisfaction}%` : "—"} /></div>{item.status === "open" && <Button className="mt-4 w-full" size="sm" variant="outline" onClick={() => open({ title: "活动结项确认", description: "演示环境将按当前报名数的95%记录完成人数，并保存人工说明。", confirm: "确认结项", body: { action: "close_activity", activityId: item.id, completed: Math.floor(item.enrolled * .95), satisfaction: 94.6, expectedVersion: item.version } })}>登记结项</Button>}</CardContent></Card>)}</TabsContent>
 <TabsContent value="reports"><Card className="border-slate-200 shadow-sm"><CardHeader><SectionHeading title="AI育人成效报告草稿" description="通过真实模型网关生成；仅输入脱敏汇总指标，所有内容需人工复核" action={<Button onClick={() => void generateReport()} disabled={working}><Brain className="mr-2 h-4 w-4" />生成新草稿</Button>} /></CardHeader><CardContent>{data.reports.length ? <div className="space-y-4">{data.reports.map(report => <article key={report.id} className="rounded-xl border border-slate-200 p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="text-sm font-semibold text-slate-800">{report.title}</h3><p className="mt-1 text-[10px] text-slate-400">{report.model} · {new Date(report.generatedAt).toLocaleString("zh-CN")} · 仅汇总数据</p></div><Badge className="bg-amber-50 text-amber-700 hover:bg-amber-50">待人工复核</Badge></div><div className="mt-4 whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-xs leading-6 text-slate-600">{report.content}</div></article>)}</div> : <div className="py-14 text-center"><FileText className="mx-auto h-9 w-9 text-slate-300" /><p className="mt-3 text-sm font-medium text-slate-600">尚未生成AI报告</p><p className="mt-1 text-[11px] text-slate-400">点击“生成新草稿”调用模型网关</p></div>}</CardContent></Card></TabsContent>
 </Tabs></>}
 <AlertDialog open={Boolean(pending)} onOpenChange={value => { if (!value && !working) setPending(null); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{pending?.title}</AlertDialogTitle><AlertDialogDescription>{pending?.description}</AlertDialogDescription></AlertDialogHeader><Textarea value={note} onChange={event => setNote(event.target.value)} placeholder="请输入人工跟进记录、证据或处置依据（至少4个字）" maxLength={800} /><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction disabled={working || note.trim().length < 4} onClick={event => { event.preventDefault(); void runAction(); }}>{working ? "提交中…" : pending?.confirm}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
function Tiny({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-slate-50 p-2 text-center"><p className="text-xs font-bold text-slate-800">{value}</p><p className="mt-1 text-[9px] text-slate-400">{label}</p></div>; }

