"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, BarChart3, Building2, CheckCircle2, Download, FileBarChart, FlaskConical, Gauge, Landmark, RefreshCw, Scale, ShieldCheck, Sparkles, TrendingUp, UsersRound, WalletCards, XCircle } from "lucide-react";
import { useHashTab } from "@/hooks/use-hash-tab";
import { EnterprisePageHeader } from "@/components/enterprise/page-header";
import { MetricCard, SectionHeading, StatusPill } from "@/components/enterprise/dashboard";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
interface Department { id: string; name: string; applications: number; supported: number; coverageRate: number; budget: number; paid: number; executionRate: number; ciac: number; highRisk: number; overdue: number }
interface ExceptionCase { id: string; caseNo: string; type: string; title: string; department: string; studentCode: string; requestedAmount: number; standardAmount: number; reason: string; evidence: string[]; aiRisk: "低" | "中" | "高"; aiSuggestion: string; requiredRole: "FUND_LEADER" | "SCHOOL_LEADER"; status: "pending" | "approved" | "rejected"; version: number; submittedAt: string; scenarioId?: string; applicationId?: string; externalActionRoute?: string }
interface Scenario { id: string; name: string; project: string; deltaAmount: number; baselineCoverage: number; predictedCoverage: number; baselineExecution: number; predictedExecution: number; additionalStudents: number; riskNote: string; createdBy: string; createdAt: string }
interface PolicyEffect { id: string; policy: string; year: string; target: string; coverageChange: number; completionRate: number; outcomeGain: number; equityChange: number; evidenceLevel: "高" | "中"; recommendation: string }
interface Brief { id: string; title: string; period: string; generatedAt: string; status: "draft" | "reviewed"; sections: string[] }
interface Snapshot { departments: Department[]; exceptions: ExceptionCase[]; scenarios: Scenario[]; policyEffects: PolicyEffect[]; briefs: Brief[]; indicators: { supportedStudents: number; coverageRate: number; totalBudget: number; paidAmount: number; executionRate: number; pendingDecisions: number; highRisk: number; ciac: number } }
interface Envelope<T> { success: boolean; data?: T; error?: string; message?: string }
type Pending = { item: ExceptionCase; decision: "approved" | "rejected" };
function headers() { const token = localStorage.getItem("token"); return { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }; }
function key() { return `decision-${Date.now()}-${crypto.randomUUID()}`; }
function money(value: number) { return value >= 10000 ? `¥${(value / 10000).toFixed(1)}万` : `¥${value.toLocaleString()}`; }
function currentRole() { try { const user = JSON.parse(localStorage.getItem("user") ?? "{}") as { role?: string; roles?: Array<{ code?: string }> }; return user.roles?.[0]?.code ?? user.role ?? ""; } catch { return ""; } }
export default function DecisionCenterPage() {
 const [tab, setTab] = useHashTab(["overview", "exceptions", "simulation", "policy", "briefs"] as const, "overview"); const [data, setData] = useState<Snapshot | null>(null); const [role, setRole] = useState(""); const [loading, setLoading] = useState(true); const [pending, setPending] = useState<Pending | null>(null); const [comment, setComment] = useState(""); const [scenarioOpen, setScenarioOpen] = useState(false); const [project, setProject] = useState("国家助学金"); const [deltaAmount, setDeltaAmount] = useState("1000000"); const [working, setWorking] = useState(false); const [message, setMessage] = useState<{ type: "ok" | "error"; text: string } | null>(null);
 const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/decision-center", { headers: headers(), cache: "no-store" }); const body = await response.json() as Envelope<Snapshot>; if (!response.ok || !body.success || !body.data) throw new Error(body.error ?? "决策中心加载失败"); setData(body.data); } catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "决策中心加载失败" }); } finally { setLoading(false); } }, []); useEffect(() => { setRole(currentRole()); void load(); }, [load]);
 const post = async (body: Record<string, unknown>) => { setWorking(true); try { const response = await fetch("/api/decision-center", { method: "POST", headers: { ...headers(), "Idempotency-Key": key() }, body: JSON.stringify(body) }); const payload = await response.json() as Envelope<unknown>; if (!response.ok || !payload.success) throw new Error(payload.error ?? "决策操作失败"); setMessage({ type: "ok", text: payload.message ?? "操作已完成" }); setPending(null); setScenarioOpen(false); setComment(""); await load(); } catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "决策操作失败" }); } finally { setWorking(false); } };
 const decide = () => pending && post({ action: "decide_exception", caseId: pending.item.id, expectedVersion: pending.item.version, decision: pending.decision, comment: comment.trim(), humanConfirmed: true }); const simulate = () => post({ action: "run_budget_scenario", project: project.trim(), deltaAmount: Number(deltaAmount), comment: comment.trim(), humanConfirmed: true });
 const maxApps = useMemo(() => Math.max(...(data?.departments.map(item => item.applications) ?? [1])), [data]); const exportBrief = () => { if (!data) return; const text = [`冀慧学途校级资助决策摘要`, `覆盖学生：${data.indicators.supportedStudents}`, `覆盖率：${data.indicators.coverageRate}%`, `预算执行率：${data.indicators.executionRate}%`, `待决策事项：${data.indicators.pendingDecisions}`, `CIAC：${data.indicators.ciac}`, "", ...data.departments.map(item => `${item.name}：覆盖率${item.coverageRate}%，执行率${item.executionRate}%，风险${item.highRisk}项`)]; const blob = new Blob([text.join("\n")], { type: "text/plain;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `校级资助决策摘要_${new Date().toISOString().slice(0,10)}.txt`; anchor.click(); URL.revokeObjectURL(url); };
 return <div className="space-y-6"><EnterprisePageHeader eyebrow="EXECUTIVE DECISION" title="校级资助决策与风险指挥中心" description="面向校领导与资助中心领导，落实 v6 中全校总览、例外终审、预算沙盒、政策效果、风险热力图和汇报材料；只展示宏观与脱敏数据，不介入一般业务经办。" icon={Landmark} badge={`${role || "LEADER"} · 全校决策范围`} actions={[{ label: "刷新决策态", icon: RefreshCw, variant: "outline", onClick: () => void load(), disabled: loading }, { label: "导出决策摘要", icon: Download, variant: "outline", onClick: exportBrief, disabled: !data }, ...(role === "SCHOOL_LEADER" ? [{ label: "新建预算情景", icon: FlaskConical, onClick: () => { setScenarioOpen(true); setComment(""); } }] : [])]} />
 {message && <div className={`rounded-xl border px-4 py-3 text-sm ${message.type === "ok" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-rose-200 bg-rose-50 text-rose-700"}`}>{message.text}</div>}
 {data && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="受助学生" value={data.indicators.supportedStudents.toLocaleString()} detail={`全校覆盖率 ${data.indicators.coverageRate}%`} icon={UsersRound} tone="blue" /><MetricCard label="年度资助预算" value={money(data.indicators.totalBudget)} detail={`累计实发 ${money(data.indicators.paidAmount)}`} icon={WalletCards} tone="emerald" /><MetricCard label="资金执行率" value={`${data.indicators.executionRate}%`} detail="按校区、院系、项目可下钻" icon={TrendingUp} tone="cyan" /><MetricCard label="待裁定事项" value={data.indicators.pendingDecisions.toString()} detail="例外、破格、申诉与紧急通道" icon={Scale} tone="amber" /><MetricCard label="公平性 CIAC" value={data.indicators.ciac.toFixed(2)} detail={`${data.indicators.highRisk}项高风险信号`} icon={Gauge} tone="violet" /></div>
 <Tabs value={tab} onValueChange={setTab} className="space-y-5"><TabsList className="h-auto flex-wrap rounded-xl border border-slate-200 bg-white p-1"><TabsTrigger value="overview">领导驾驶舱</TabsTrigger><TabsTrigger value="exceptions">重大与例外事项</TabsTrigger><TabsTrigger value="simulation">预算沙盒模拟</TabsTrigger><TabsTrigger value="policy">政策效果评估</TabsTrigger><TabsTrigger value="briefs">汇报材料</TabsTrigger></TabsList>
 <TabsContent value="overview" className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><Card className="border-slate-200 shadow-sm"><CardHeader><SectionHeading title="院系覆盖、资金与公平性" description="可比较，不自动排名或形成惩罚性结论" /></CardHeader><CardContent className="space-y-4">{data.departments.map(item => <div key={item.id}><div className="flex items-center justify-between"><div><p className="text-xs font-semibold text-slate-700">{item.name}</p><p className="mt-1 text-[10px] text-slate-400">申请{item.applications} · 受助{item.supported} · 实发{money(item.paid)}</p></div><div className="flex items-center gap-4 text-right"><div><p className="text-xs font-bold text-blue-700">{item.coverageRate}%</p><p className="text-[9px] text-slate-400">覆盖率</p></div><div><p className={`text-xs font-bold ${item.ciac > .25 ? "text-rose-600" : "text-emerald-600"}`}>{item.ciac.toFixed(2)}</p><p className="text-[9px] text-slate-400">CIAC</p></div></div></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-blue-600 to-cyan-400" style={{ width: `${item.applications / maxApps * 100}%` }} /></div></div>)}</CardContent></Card><Card className="border-slate-200 shadow-sm"><CardHeader><SectionHeading title="风险热力信号" description="高风险与超时按院系聚合" /></CardHeader><CardContent className="grid grid-cols-2 gap-3">{data.departments.map(item => <div key={item.id} className={`rounded-xl border p-4 ${item.highRisk >= 15 ? "border-rose-200 bg-rose-50" : item.highRisk >= 9 ? "border-amber-200 bg-amber-50" : "border-emerald-200 bg-emerald-50"}`}><p className="text-[10px] font-medium text-slate-600">{item.name}</p><p className={`mt-2 text-2xl font-bold ${item.highRisk >= 15 ? "text-rose-700" : item.highRisk >= 9 ? "text-amber-700" : "text-emerald-700"}`}>{item.highRisk}</p><p className="mt-1 text-[9px] text-slate-400">高风险 · 超时{item.overdue}</p></div>)}</CardContent></Card></TabsContent>
 <TabsContent value="exceptions" className="space-y-4">{data.exceptions.map(item => <Card key={item.id} className={`border-slate-200 shadow-sm ${item.aiRisk === "高" && item.status === "pending" ? "ring-1 ring-rose-200" : ""}`}><CardContent className="flex flex-col gap-4 p-5 xl:flex-row xl:items-center"><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${item.aiRisk === "高" ? "bg-rose-50 text-rose-600" : item.aiRisk === "中" ? "bg-amber-50 text-amber-600" : "bg-blue-50 text-blue-700"}`}><AlertTriangle className="h-5 w-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-slate-800">{item.title}</p><Badge variant="outline">{item.type}</Badge><Badge variant="secondary" className="font-mono text-[9px]">{item.caseNo}</Badge><StatusPill status={item.status === "approved" ? "healthy" : item.status === "rejected" ? "danger" : "warning"} label={item.status === "approved" ? "已批准" : item.status === "rejected" ? "已驳回" : "待终审"} /></div><p className="mt-2 text-[11px] text-slate-500">{item.department} · {item.studentCode} · 申请{money(item.requestedAmount)} / 标准{money(item.standardAmount)} · {item.submittedAt}</p>{item.scenarioId&&<p className="mt-1 font-mono text-[9px] text-blue-600">{item.id} · {item.applicationId} · {item.scenarioId}</p>}<p className="mt-2 text-[11px] leading-5 text-slate-600">{item.reason}</p><div className="mt-2 rounded-lg bg-violet-50 px-3 py-2 text-[10px] leading-5 text-violet-800"><Sparkles className="mr-1.5 inline h-3.5 w-3.5" />AI建议：{item.aiSuggestion}</div><div className="mt-2 flex flex-wrap gap-1.5">{item.evidence.map(value => <Badge key={value} variant="outline" className="text-[9px]">{value}</Badge>)}</div></div>{item.status === "pending" && item.requiredRole === role && item.externalActionRoute ? <Button asChild><Link href={item.externalActionRoute}><Sparkles className="mr-2 h-4 w-4" />进入Agent人工闸门</Link></Button> : item.status === "pending" && item.requiredRole === role ? <div className="flex shrink-0 gap-2"><Button variant="outline" onClick={() => { setPending({ item, decision: "rejected" }); setComment(""); }}><XCircle className="mr-2 h-4 w-4" />驳回</Button><Button onClick={() => { setPending({ item, decision: "approved" }); setComment(""); }}><CheckCircle2 className="mr-2 h-4 w-4" />批准</Button></div> : item.status === "pending" ? <Badge variant="outline">等待 {item.requiredRole} 终审</Badge> : null}</CardContent></Card>)}</TabsContent>
 <TabsContent value="simulation"><Card className="border-slate-200 shadow-sm"><CardHeader><SectionHeading title="预算与政策情景模拟" description="数字孪生辅助比较，不直接修改真实预算" action={role === "SCHOOL_LEADER" ? <Button onClick={() => { setScenarioOpen(true); setComment(""); }}><FlaskConical className="mr-2 h-4 w-4" />运行新情景</Button> : undefined} /></CardHeader><CardContent className="grid gap-4 xl:grid-cols-2">{data.scenarios.map(item => <div key={item.id} className="rounded-xl border border-slate-200 p-5"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-slate-800">{item.name}</p><p className="mt-1 text-[10px] text-slate-400">{item.project} · {item.createdAt}</p></div><Badge className={item.deltaAmount >= 0 ? "bg-emerald-50 text-emerald-700" : "bg-rose-50 text-rose-700"}>{item.deltaAmount ? `${item.deltaAmount > 0 ? "+" : ""}${money(item.deltaAmount)}` : "基线"}</Badge></div><div className="mt-4 grid grid-cols-3 gap-2"><Compare label="覆盖率" before={`${item.baselineCoverage}%`} after={`${item.predictedCoverage}%`} /><Compare label="执行率" before={`${item.baselineExecution}%`} after={`${item.predictedExecution}%`} /><Compare label="覆盖学生" before="基线" after={`${item.additionalStudents >= 0 ? "+" : ""}${item.additionalStudents}人`} /></div><p className="mt-4 rounded-lg bg-slate-50 p-3 text-[10px] leading-5 text-slate-600">{item.riskNote}</p></div>)}</CardContent></Card></TabsContent>
 <TabsContent value="policy" className="grid gap-4 xl:grid-cols-3">{data.policyEffects.map(item => <Card key={item.id} className="border-slate-200 shadow-sm"><CardContent className="p-5"><div className="flex items-start justify-between"><BarChart3 className="h-5 w-5 text-blue-700" /><Badge variant="outline">证据强度 {item.evidenceLevel}</Badge></div><h3 className="mt-4 text-sm font-semibold text-slate-800">{item.policy}</h3><p className="mt-1 text-[10px] text-slate-400">{item.year} · {item.target}</p><div className="mt-4 grid grid-cols-2 gap-2"><Tiny label="覆盖变化" value={`+${item.coverageChange}%`} /><Tiny label="完成率" value={`${item.completionRate}%`} /><Tiny label="成长增益" value={`+${item.outcomeGain}`} /><Tiny label="公平性变化" value={item.equityChange.toFixed(2)} /></div><p className="mt-4 rounded-lg bg-blue-50 p-3 text-[10px] leading-5 text-blue-800">建议：{item.recommendation}</p></CardContent></Card>)}</TabsContent>
 <TabsContent value="briefs" className="grid gap-4 xl:grid-cols-2">{data.briefs.map(item => <Card key={item.id} className="border-slate-200 shadow-sm"><CardContent className="p-5"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-950 text-white"><FileBarChart className="h-4 w-4" /></span><StatusPill status={item.status === "reviewed" ? "healthy" : "warning"} label={item.status === "reviewed" ? "已复核" : "AI草稿待复核"} /></div><h3 className="mt-4 text-sm font-semibold text-slate-800">{item.title}</h3><p className="mt-1 text-[10px] text-slate-400">{item.period} · {item.generatedAt}</p><ol className="mt-4 space-y-2">{item.sections.map((section, index) => <li key={section} className="flex items-center gap-2 text-[11px] text-slate-600"><span className="flex h-5 w-5 items-center justify-center rounded bg-slate-100 text-[9px]">{index + 1}</span>{section}</li>)}</ol></CardContent></Card>)}</TabsContent>
 </Tabs></>}
 <AlertDialog open={Boolean(pending)} onOpenChange={value => { if (!value && !working) setPending(null); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{pending?.decision === "approved" ? "批准重大/例外事项" : "驳回重大/例外事项"}</AlertDialogTitle><AlertDialogDescription>{pending ? `${pending.item.caseNo} · ${pending.item.title}。AI建议只作为参考，最终责任由当前终审人承担。` : ""}</AlertDialogDescription></AlertDialogHeader><Textarea value={comment} onChange={event => setComment(event.target.value)} placeholder="请输入政策依据、事实判断与风险控制意见（至少4个字）" maxLength={800} /><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction disabled={working || comment.trim().length < 4} onClick={event => { event.preventDefault(); void decide(); }}>{working ? "提交中…" : "本人确认并提交裁定"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={scenarioOpen} onOpenChange={value => { if (!value && !working) setScenarioOpen(false); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>运行资助预算沙盒情景</AlertDialogTitle><AlertDialogDescription>该模拟不写入真实预算，只生成覆盖率、执行率和风险预测快照。</AlertDialogDescription></AlertDialogHeader><div className="grid gap-3 sm:grid-cols-2"><label className="space-y-2 text-xs font-medium text-slate-700">项目<Input value={project} onChange={event => setProject(event.target.value)} /></label><label className="space-y-2 text-xs font-medium text-slate-700">预算调整金额（元）<Input type="number" value={deltaAmount} onChange={event => setDeltaAmount(event.target.value)} /></label></div><Textarea value={comment} onChange={event => setComment(event.target.value)} placeholder="请输入情景假设与决策目标（至少4个字）" maxLength={500} /><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction disabled={working || !project.trim() || comment.trim().length < 4 || !Number.isFinite(Number(deltaAmount))} onClick={event => { event.preventDefault(); void simulate(); }}>{working ? "计算中…" : "运行模拟"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
function Tiny({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-slate-50 p-2 text-center"><p className="text-xs font-bold text-slate-800">{value}</p><p className="mt-1 text-[9px] text-slate-400">{label}</p></div>; }
function Compare({ label, before, after }: { label: string; before: string; after: string }) { return <div className="rounded-lg bg-slate-50 p-3 text-center"><p className="text-[9px] text-slate-400">{label}</p><p className="mt-1 text-[10px] text-slate-400 line-through">{before}</p><p className="mt-1 text-sm font-bold text-blue-700">{after}</p></div>; }
