import { type NextRequest } from "next/server";
import { errorResponse, successResponse } from "@/lib/api-utils";
import { listVisibleApplications } from "@/lib/platform/demo-store";
import { resolveRequestActor } from "@/lib/platform/request-actor";
export async function GET(request: NextRequest, context: { params: Promise<{ id: string }> }) {
  const actor = resolveRequestActor(request); if (!actor) return errorResponse("未完成身份认证", 401); if (actor.role !== "DATA_ADMIN") return errorResponse("仅数据管理员可读取质量问题详情", 403); const { id } = await context.params; const applications = listVisibleApplications(actor);
  const incomplete = applications.map(item => ({ id: `DQ-${item.id}`, objectRefs: [item.id], type: "材料完整性", severity: item.materialCompleteness < 75 ? "high" : "medium", detectedValue: `${item.materialCompleteness}%`, expectedValue: ">= 90%", evidence: { materialCompleteness: item.materialCompleteness, materialCount: item.materialCount ?? null, submissionMethod: item.materialSubmissionMethod ?? "legacy" }, policy: "STD-APP-001 / 材料完整性规则", recommendation: "由业务经办人核对缺失材料；数据管理员只能创建治理建议，不得代为补材料或作审批结论。" })).filter(item => Number.parseInt(item.detectedValue, 10) < 90);
  const groups = Object.values(applications.reduce<Record<string, string[]>>((result, item) => { const key = `${item.studentNo}::${item.projectName}`; (result[key] ??= []).push(item.id); return result; }, {})).filter(items => items.length > 1).map((items, index) => ({ id: `DQ-DUP-${index + 1}`, objectRefs: items, type: "重复主体引用", severity: "high", detectedValue: `${items.length}条记录`, expectedValue: "同学生同项目同周期不得重复", evidence: { applicationIds: items }, policy: "STD-APP-001 / 业务唯一键", recommendation: "发起重复记录人工核验；合并或作废必须由资助业务角色确认并全程审计。" }));
  const missing = applications.filter(item => !item.campusId || !item.departmentId || !item.classId).map(item => ({ id: `DQ-ORG-${item.id}`, objectRefs: [item.id], type: "组织字段缺失", severity: "high", detectedValue: "组织字段不完整", expectedValue: "campusId/departmentId/classId齐全", evidence: { campusId: item.campusId || null, departmentId: item.departmentId || null, classId: item.classId || null }, policy: "STD-ORG-002 / 组织编码完整性", recommendation: "从统一组织目录重新映射；禁止手工填写未注册组织编码。" }));
  const issue = [...incomplete, ...groups, ...missing].find(item => item.id === id); if (!issue) return errorResponse("质量问题不存在或已在最新扫描中消除", 404);
  return successResponse({ generatedAt: new Date().toISOString(), issue: { ...issue, status: "open", ownerRole: "DATA_ADMIN", decisionBoundary: "数据管理员负责治理建议与标准校验，无资助业务修改和审批权。" }, trace: [{ time: new Date().toISOString(), stage: "detected", actor: "数据质量Agent", result: "确定性规则命中" }, { time: null, stage: "business_verification", actor: "授权业务经办人", result: "待人工核验" }], relatedApplications: issue.objectRefs.map(ref => { const item = applications.find(application => application.id === ref); return item ? { id: item.id, projectName: item.projectName, departmentId: item.departmentId, classId: item.classId, materialCompleteness: item.materialCompleteness, status: item.status, version: item.version } : { id: ref }; }) });
}
