"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { AlertTriangle, Banknote, Calculator, CheckCircle2, CircleDollarSign, Download, FileCheck2, FileSpreadsheet, Landmark, ListTodo, ReceiptText, RefreshCw, Send, ShieldCheck, Sparkles, WalletCards } from "lucide-react";
import { useHashTab } from "@/hooks/use-hash-tab";
import { EnterprisePageHeader } from "@/components/enterprise/page-header";
import { MetricCard, SectionHeading, StatusPill } from "@/components/enterprise/dashboard";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
interface Budget { id: string; project: string; budget: number; occupied: number; paid: number; adjustment: number; source: string; executionRate: number; risk: "normal" | "attention" }
type BatchStatus = "draft" | "blocked" | "validated" | "double_confirmed" | "sent" | "partially_failed" | "completed";
interface Batch { id: string; batchNo: string; project: string; students: number; amount: number; validAccounts: number; invalidAccounts: number; duplicateRecords: number; status: BatchStatus; confirmations: string[]; bankFileHash?: string; version: number; createdAt: string }
interface Reconciliation { id: string; batchNo: string; expectedCount: number; actualCount: number; expectedAmount: number; actualAmount: number; difference: number; reason: string; status: "matched" | "exception" | "resolved"; version: number }
interface Voucher { id: string; voucherNo: string; batchNo: string; debit: string; credit: string; amount: number; attachments: number; status: "draft" | "reviewed" | "archived"; version: number }
interface ScenarioTask { id:string;title:string;applicationId:string;project:string;studentCode:string;amount:number;status:"pending"|"completed";dueAt:string;completedAt?:string;checks:string[];description:string;scenarioId:string;externalActionRoute:string }
interface Risk { id: string; level: "high" | "medium" | "low"; type: string; target: string; description: string; control: string; status: "open" | "controlled" }
interface Snapshot { tasks: ScenarioTask[]; budgets: Budget[]; batches: Batch[]; reconciliations: Reconciliation[]; vouchers: Voucher[]; risks: Risk[]; indicators: { totalBudget: number; occupied: number; paid: number; executionRate: number; pendingAmount: number; exceptionCount: number } }
interface Envelope<T> { success: boolean; data?: T; error?: string; message?: string }
type Pending = { title: string; description: string; confirm: string; body: Record<string, unknown> };
function headers() { const token = localStorage.getItem("token"); return { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }; }
function key() { return `finance-${Date.now()}-${crypto.randomUUID()}`; }
function money(value: number) { if (value >= 10000000) return `¥${(value / 10000000).toFixed(2)}千万`; if (value >= 10000) return `¥${(value / 10000).toFixed(1)}万`; return `¥${value.toLocaleString()}`; }
const batchLabel: Record<BatchStatus, string> = { draft: "草稿", blocked: "校验阻断", validated: "待双确认", double_confirmed: "已双确认", sent: "银行处理中", partially_failed: "部分失败", completed: "发放完成" };
export default function FinanceWorkbenchPage() {
 const [tab, setTab] = useHashTab(["tasks", "budget", "batches", "reconciliation", "vouchers", "risks"] as const, "budget");
 const [data, setData] = useState<Snapshot | null>(null); const [loading, setLoading] = useState(true); const [pending, setPending] = useState<Pending | null>(null); const [note, setNote] = useState(""); const [working, setWorking] = useState(false); const [message, setMessage] = useState<{ type: "ok" | "error"; text: string } | null>(null);
 const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/finance/operations", { headers: headers(), cache: "no-store" }); const body = await response.json() as Envelope<Snapshot>; if (!response.ok || !body.success || !body.data) throw new Error(body.error ?? "财务工作台加载失败"); setData(body.data); } catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "财务工作台加载失败" }); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]); const open = (item: Pending) => { setPending(item); setNote(""); };
 const execute = async () => { if (!pending || note.trim().length < 4) return; setWorking(true); try { const response = await fetch("/api/finance/operations", { method: "POST", headers: { ...headers(), "Idempotency-Key": key() }, body: JSON.stringify({ ...pending.body, note: note.trim() }) }); const body = await response.json() as Envelope<unknown>; if (!response.ok || !body.success) throw new Error(body.error ?? "财务操作失败"); setMessage({ type: "ok", text: body.message ?? "操作已完成" }); setPending(null); await load(); } catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "财务操作失败" }); } finally { setWorking(false); } };
 const exportReport = () => { if (!data) return; const rows = ["项目,预算,占用,已发,执行率", ...data.budgets.map(item => `${item.project},${item.budget},${item.occupied},${item.paid},${item.executionRate}%`)]; const blob = new Blob(["\ufeff" + rows.join("\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `资助资金执行报表_${new Date().toISOString().slice(0, 10)}.csv`; anchor.click(); URL.revokeObjectURL(url); };
 return <div className="space-y-6"><EnterprisePageHeader eyebrow="FINANCIAL CONTROL" title="资助资金执行与银校对账中心" description="覆盖 v6 规划中的预算编制与占用、项目调剂、发放批次、确定性校验、双人确认、银行文件、回盘对账、失败重发、凭证草稿和资金风险监控。AI只分析与生成草稿，资金动作始终由人执行。" icon={Landmark} badge="FINANCE · 全校资金范围" actions={[{ label: "刷新资金态", icon: RefreshCw, variant: "outline", onClick: () => void load(), disabled: loading }, { label: "导出执行报表", icon: Download, onClick: exportReport, variant: "outline", disabled: !data }]} />
 {message && <div className={`rounded-xl border px-4 py-3 text-sm ${message.type === "ok" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-rose-200 bg-rose-50 text-rose-700"}`}>{message.text}</div>}
 {data && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="年度资助预算" value={money(data.indicators.totalBudget)} detail="中央、省级与校内资金合计" icon={WalletCards} tone="blue" /><MetricCard label="预算占用" value={money(data.indicators.occupied)} detail="已审批项目及在途批次占用" icon={Calculator} tone="cyan" /><MetricCard label="累计实发" value={money(data.indicators.paid)} detail={`预算执行率 ${data.indicators.executionRate}%`} icon={CircleDollarSign} tone="emerald" /><MetricCard label="待发金额" value={money(data.indicators.pendingAmount)} detail="校验、复核或银行处理中" icon={Send} tone="violet" /><MetricCard label="待处置差异" value={data.indicators.exceptionCount.toString()} detail="对账异常与账户退票" icon={AlertTriangle} tone="amber" /></div>
 <Tabs value={tab} onValueChange={setTab} className="space-y-5"><TabsList className="h-auto flex-wrap rounded-xl border border-slate-200 bg-white p-1"><TabsTrigger value="tasks">财务待办{data.tasks.length ? ` (${data.tasks.length})` : ""}</TabsTrigger><TabsTrigger value="budget">预算执行</TabsTrigger><TabsTrigger value="batches">发放批次</TabsTrigger><TabsTrigger value="reconciliation">银行对账</TabsTrigger><TabsTrigger value="vouchers">凭证管理</TabsTrigger><TabsTrigger value="risks">资金风险</TabsTrigger></TabsList>
 <TabsContent value="tasks" className="space-y-4">{data.tasks.length ? data.tasks.map(task => <Card key={task.id} className="border-blue-200 shadow-sm"><CardContent className="flex flex-col gap-5 p-5 xl:flex-row xl:items-center"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-blue-700"><ListTodo className="h-5 w-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-slate-800">{task.title}</p><Badge variant="outline">视频场景</Badge><StatusPill status={task.status === "completed" ? "healthy" : "warning"} label={task.status === "completed" ? "双人复核完成" : "待财务处理"} /></div><p className="mt-2 font-mono text-[9px] text-blue-600">{task.id} · {task.scenarioId}</p><p className="mt-2 text-[11px] text-slate-500">{task.applicationId} · {task.studentCode} · {money(task.amount)} · 截止 {new Date(task.dueAt).toLocaleString("zh-CN")}</p><p className="mt-2 text-[11px] leading-5 text-slate-600">{task.description}</p><div className="mt-3 flex flex-wrap gap-2">{task.checks.map(check => <Badge key={check} variant="secondary" className="text-[9px]">{check}</Badge>)}</div></div><Button asChild variant={task.status === "completed" ? "outline" : "default"}><Link href={task.externalActionRoute}>{task.status === "completed" ? <CheckCircle2 className="mr-2 h-4 w-4" /> : <Sparkles className="mr-2 h-4 w-4" />}{task.status === "completed" ? "查看协作证据" : "进入Agent人工闸门"}</Link></Button></CardContent></Card>) : <Card className="border-slate-200"><CardContent className="py-16 text-center text-sm text-slate-400">当前没有由审批链生成的财务任务</CardContent></Card>}</TabsContent>
  <TabsContent value="budget"><Card className="border-slate-200 shadow-sm"><CardHeader><SectionHeading title="项目预算占用与执行分析" description="预算、占用、实发和调剂全口径联动" /></CardHeader><CardContent className="space-y-5">{data.budgets.map(item => <div key={item.id}><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2"><p className="text-sm font-semibold text-slate-800">{item.project}</p>{item.risk === "attention" && <StatusPill status="warning" label="进度偏差" />}</div><p className="mt-1 text-[10px] text-slate-400">{item.source}{item.adjustment ? ` · 调剂 ${item.adjustment > 0 ? "+" : ""}${money(item.adjustment)}` : ""}</p></div><div className="grid grid-cols-3 gap-6 text-right"><Amount label="年度预算" value={money(item.budget)} /><Amount label="已占用" value={money(item.occupied)} /><Amount label="已实发" value={money(item.paid)} /></div></div><div className="mt-3 h-2.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${item.risk === "attention" ? "bg-gradient-to-r from-amber-500 to-orange-400" : "bg-gradient-to-r from-blue-600 to-cyan-400"}`} style={{ width: `${item.executionRate}%` }} /></div><p className="mt-1 text-right text-[9px] text-slate-400">执行率 {item.executionRate}%</p></div>)}</CardContent></Card></TabsContent>
 <TabsContent value="batches" className="space-y-4">{data.batches.map(batch => { const status: "healthy" | "warning" | "danger" | "neutral" | "info" = batch.status === "completed" ? "healthy" : batch.status === "blocked" || batch.status === "partially_failed" ? "danger" : batch.status === "validated" ? "warning" : "info"; return <Card key={batch.id} className="border-slate-200 shadow-sm"><CardContent className="flex flex-col gap-5 p-5 xl:flex-row xl:items-center"><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${batch.status === "blocked" || batch.status === "partially_failed" ? "bg-rose-50 text-rose-600" : "bg-blue-50 text-blue-700"}`}><Banknote className="h-5 w-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-slate-800">{batch.batchNo}</p><Badge variant="outline">{batch.project}</Badge><StatusPill status={status} label={batchLabel[batch.status]} /></div><p className="mt-2 text-[11px] text-slate-500">{batch.students}人 · {money(batch.amount)} · 创建于 {batch.createdAt}</p><div className="mt-3 flex flex-wrap gap-2"><Check label={`账号通过 ${batch.validAccounts}`} ok={batch.invalidAccounts === 0} /><Check label={`账号异常 ${batch.invalidAccounts}`} ok={batch.invalidAccounts === 0} /><Check label={`重复记录 ${batch.duplicateRecords}`} ok={batch.duplicateRecords === 0} /><Check label={`双人确认 ${batch.confirmations.length}/2`} ok={batch.confirmations.length === 2} /></div>{batch.bankFileHash && <p className="mt-2 font-mono text-[9px] text-slate-400">{batch.bankFileHash}</p>}</div><div className="flex shrink-0 flex-wrap gap-2">{batch.id.startsWith("VIDEO-")&&<Button asChild variant="outline"><Link href="/bank/portal#task"><FileCheck2 className="mr-2 h-4 w-4"/>查看批次证据</Link></Button>}{["draft", "blocked"].includes(batch.status) && <Button variant="outline" onClick={() => open({ title: "执行发放清单确定性校验", description: "程序将校验总人数、金额、账户有效性及重复记录。存在任何异常都将阻断后续发放。", confirm: "运行校验", body: { action: "validate_batch", batchId: batch.id, expectedVersion: batch.version } })}><ShieldCheck className="mr-2 h-4 w-4" />运行校验</Button>}{batch.status === "validated" && <Button onClick={() => open({ title: "发放批次双人确认", description: "该操作属于L4资金动作。演示复核岗将作为第二复核身份，确认后生成带哈希的银行文件；系统不会自动发送资金。", confirm: "双人确认并生成文件", body: { action: "double_confirm_batch", batchId: batch.id, expectedVersion: batch.version, secondApproverId: "finance-reviewer-002", humanConfirmed: true } })}><FileCheck2 className="mr-2 h-4 w-4" />双人确认</Button>}{["completed", "partially_failed", "double_confirmed"].includes(batch.status) && !data.vouchers.some(item => item.batchNo === batch.batchNo) && <Button variant="outline" onClick={() => open({ title: "生成会计凭证草稿", description: "仅生成可复核的凭证草稿，不自动记账。若批次已有凭证，确定性校验会拒绝重复生成。", confirm: "生成草稿", body: { action: "create_voucher", batchId: batch.id, expectedVersion: batch.version } })}><ReceiptText className="mr-2 h-4 w-4" />凭证草稿</Button>}</div></CardContent></Card>; })}</TabsContent>
 <TabsContent value="reconciliation" className="grid gap-4 xl:grid-cols-3">{data.reconciliations.map(item => <Card key={item.id} className={`border-slate-200 shadow-sm ${item.status === "exception" ? "ring-1 ring-rose-200" : ""}`}><CardContent className="p-5"><div className="flex items-start justify-between"><FileSpreadsheet className={`h-5 w-5 ${item.status === "exception" ? "text-rose-600" : "text-emerald-600"}`} /><StatusPill status={item.status === "matched" ? "healthy" : item.status === "resolved" ? "info" : "danger"} label={item.status === "matched" ? "账实相符" : item.status === "resolved" ? "已核销" : "存在差异"} /></div><h3 className="mt-4 font-semibold text-slate-800">{item.batchNo}</h3><div className="mt-4 grid grid-cols-2 gap-2"><Tiny label="应发" value={`${item.expectedCount}人 / ${money(item.expectedAmount)}`} /><Tiny label="实发" value={`${item.actualCount}人 / ${money(item.actualAmount)}`} /></div><p className={`mt-3 text-sm font-bold ${item.difference ? "text-rose-600" : "text-emerald-600"}`}>差额 {money(item.difference)}</p><p className="mt-2 text-[11px] leading-5 text-slate-500">{item.reason}</p>{item.status === "exception" && <Button className="mt-4 w-full" variant="outline" onClick={() => open({ title: "人工处置对账差异", description: "请在说明中记录退票原因、重发结果或核销依据。系统不会让AI自动核销资金差异。", confirm: "确认核销", body: { action: "resolve_reconciliation", reconciliationId: item.id, expectedVersion: item.version, resolution: "账户异常已核实，5笔退票转入次批重发，差异挂账待回盘。" } })}>处置差异</Button>}</CardContent></Card>)}</TabsContent>
 <TabsContent value="vouchers"><Card className="border-slate-200 shadow-sm"><CardHeader><SectionHeading title="会计凭证与财务归档" description="AI可生成草稿，人负责复核、记账与归档" /></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-y border-slate-100 bg-slate-50 text-[10px] text-slate-400"><tr><th className="px-5 py-3">凭证/批次</th><th className="px-4 py-3">借方</th><th className="px-4 py-3">贷方</th><th className="px-4 py-3">金额</th><th className="px-5 py-3">状态</th></tr></thead><tbody>{data.vouchers.map(item => <tr key={item.id} className="border-b border-slate-100 last:border-0"><td className="px-5 py-4"><p className="font-semibold text-slate-800">{item.voucherNo}</p><p className="mt-1 text-[10px] text-slate-400">{item.batchNo} · 附件{item.attachments}份</p></td><td className="px-4 py-4 text-slate-600">{item.debit}</td><td className="px-4 py-4 text-slate-600">{item.credit}</td><td className="px-4 py-4 font-semibold text-slate-800">{money(item.amount)}</td><td className="px-5 py-4"><StatusPill status={item.status === "archived" ? "healthy" : item.status === "reviewed" ? "info" : "warning"} label={item.status === "archived" ? "已归档" : item.status === "reviewed" ? "已复核" : "待复核草稿"} /></td></tr>)}</tbody></table></div></CardContent></Card></TabsContent>
 <TabsContent value="risks" className="grid gap-4 xl:grid-cols-3">{data.risks.map(item => <Card key={item.id} className="border-slate-200 shadow-sm"><CardContent className="p-5"><div className="flex items-start justify-between"><AlertTriangle className={`h-5 w-5 ${item.level === "high" ? "text-rose-600" : item.level === "medium" ? "text-amber-600" : "text-blue-600"}`} /><StatusPill status={item.status === "controlled" ? "healthy" : item.level === "high" ? "danger" : "warning"} label={item.status === "controlled" ? "已控制" : item.level === "high" ? "高风险" : item.level === "medium" ? "中风险" : "低风险"} /></div><h3 className="mt-4 text-sm font-semibold text-slate-800">{item.type}</h3><p className="mt-1 text-[10px] text-slate-400">{item.target}</p><p className="mt-3 text-[11px] leading-5 text-slate-600">{item.description}</p><div className="mt-3 rounded-lg bg-slate-50 p-3 text-[10px] leading-5 text-blue-700">控制措施：{item.control}</div></CardContent></Card>)}</TabsContent>
 </Tabs></>}
 <AlertDialog open={Boolean(pending)} onOpenChange={value => { if (!value && !working) setPending(null); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{pending?.title}</AlertDialogTitle><AlertDialogDescription>{pending?.description}</AlertDialogDescription></AlertDialogHeader><Textarea value={note} onChange={event => setNote(event.target.value)} placeholder="请输入业务依据、复核意见或差异处置说明（至少4个字）" maxLength={800} /><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction disabled={working || note.trim().length < 4} onClick={event => { event.preventDefault(); void execute(); }}>{working ? "提交中…" : pending?.confirm}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
function Amount({ label, value }: { label: string; value: string }) { return <div><p className="text-[9px] text-slate-400">{label}</p><p className="mt-1 text-xs font-semibold text-slate-700">{value}</p></div>; }
function Tiny({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-slate-50 p-2 text-center"><p className="text-[10px] font-semibold text-slate-700">{value}</p><p className="mt-1 text-[9px] text-slate-400">{label}</p></div>; }
function Check({ label, ok }: { label: string; ok: boolean }) { return <span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-[9px] ${ok ? "bg-emerald-50 text-emerald-700" : "bg-rose-50 text-rose-700"}`}>{ok ? <CheckCircle2 className="h-3 w-3" /> : <AlertTriangle className="h-3 w-3" />}{label}</span>; }

