"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, CheckCircle2, ClipboardCheck, FileWarning, Loader2, ShieldCheck } from "lucide-react";
import { EnterprisePageHeader } from "@/components/enterprise/page-header";


import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
interface Timeline { id: string; title: string; detail: string; actorRole: string; createdAt: string }
interface Payload { ticket: { id: string; applicationId: string; projectName: string; receiptNo: string; status: string; priority: string; dueAt: string; issues: string[]; version: number; timeline: Timeline[] }; application: { id: string; studentName: string; studentNo: string; projectName: string; status: string; materialCompleteness: number; version: number; requestedAmount: number }; precheck: null | { id: string; score: number; status: string; warnings: string[]; blockers: string[]; disclaimer: string }; permission: { canHandle: boolean; actions: Array<{ id: string; label: string }> } }
interface Envelope<T> { success: boolean; data?: T; error?: string; message?: string }
function headers(json = false, key?: string): HeadersInit { const token = localStorage.getItem("token"); return { ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(json ? { "Content-Type": "application/json" } : {}), ...(key ? { "Idempotency-Key": key } : {}) }; }
export default function IntakeTicketDetailPage() {
  const params = useParams<{ id: string }>(); const id = String(params.id); const [data, setData] = useState<Payload | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [action, setAction] = useState(""); const [comment, setComment] = useState(""); const [submitting, setSubmitting] = useState(false); const [message, setMessage] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch(`/api/application-intake/tickets/${encodeURIComponent(id)}`, { headers: headers(), cache: "no-store" }); const body = await response.json() as Envelope<Payload>; if (!response.ok || !body.success || !body.data) throw new Error(body.error ?? "工单详情加载失败"); setData(body.data); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "工单详情加载失败"); } finally { setLoading(false); } }, [id]); useEffect(() => { void load(); }, [load]);
  async function submit() { if (!data || !action || comment.trim().length < 2) return; setSubmitting(true); try { const response = await fetch(`/api/application-intake/tickets/${encodeURIComponent(id)}/actions`, { method: "POST", headers: headers(true, `intake-${id}-${data.ticket.version}-${action}`), body: JSON.stringify({ action, comment: comment.trim(), expectedTicketVersion: data.ticket.version, expectedApplicationVersion: data.application.version, humanConfirmed: true }) }); const body = await response.json() as Envelope<unknown>; if (!response.ok || !body.success) throw new Error(body.error ?? "工单处理失败"); setMessage(body.message ?? "工单已处理"); setAction(""); setComment(""); await load(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "工单处理失败"); } finally { setSubmitting(false); } }
  if (loading) return <div className="flex min-h-[60vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-blue-600" /></div>; if (error || !data) return <div className="enterprise-panel p-10 text-center text-rose-700">{error || "工单不存在"}</div>;
  return <div className="space-y-6 pb-10"><EnterprisePageHeader eyebrow="INTAKE TICKET EVIDENCE" title={`受理工单 ${data.ticket.id}`} description="工单、申请、预检报告、补正通知和人工处理轨迹使用同一业务主键关联。" icon={ClipboardCheck} badge={`v${data.ticket.version} · ${data.ticket.status}`} />
    <div className="flex flex-wrap items-center justify-between gap-3"><Button asChild variant="outline"><Link href="/application/intake"><ArrowLeft className="mr-2 h-4 w-4" />返回工单队列</Link></Button><Button asChild><Link href={`/application/detail?id=${data.application.id}`}>查看关联申请</Link></Button></div>{message && <div className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-800">{message}</div>}
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Info label="申请人" value={`${data.application.studentName} · ${data.application.studentNo}`} /><Info label="资助项目" value={data.application.projectName} /><Info label="申请状态" value={data.application.status} /><Info label="材料完整度" value={`${data.application.materialCompleteness}%`} /></div>
    <div className="grid gap-5 xl:grid-cols-[1fr_360px]"><div className="space-y-4"><Card><CardHeader><CardTitle className="text-base">受理轨迹</CardTitle></CardHeader><CardContent className="space-y-0">{data.ticket.timeline.map((item, index) => <div key={item.id} className="relative flex gap-4 pb-6 last:pb-0">{index < data.ticket.timeline.length - 1 && <span className="absolute left-4 top-8 h-[calc(100%-1rem)] w-px bg-border" />}<span className="relative z-10 flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-blue-100 text-blue-700"><CheckCircle2 className="h-4 w-4" /></span><div><p className="text-sm font-semibold">{item.title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{item.detail}</p><p className="mt-1 text-[10px] text-muted-foreground">{item.actorRole} · {new Date(item.createdAt).toLocaleString("zh-CN")}</p></div></div>)}</CardContent></Card>
      <Card><CardHeader><CardTitle className="text-base">AI / 规则材料预检</CardTitle></CardHeader><CardContent>{data.precheck ? <div className="space-y-3"><div className="flex items-center justify-between rounded-xl bg-blue-50 p-4"><span className="text-sm font-medium">预检评分</span><strong className="text-2xl text-blue-700">{data.precheck.score}</strong></div>{data.precheck.warnings.map(item => <div key={item} className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900"><FileWarning className="mr-2 inline h-4 w-4" />{item}</div>)}<p className="text-[10px] leading-5 text-muted-foreground">{data.precheck.disclaimer}</p></div> : <p className="py-8 text-center text-sm text-muted-foreground">历史申请未绑定新版本预检报告</p>}</CardContent></Card></div>
      <aside className="space-y-4"><Card><CardHeader><CardTitle className="text-base">工单上下文</CardTitle></CardHeader><CardContent className="space-y-3"><Info label="申请回执" value={data.ticket.receiptNo} /><Info label="优先级" value={data.ticket.priority} /><Info label="处理时限" value={new Date(data.ticket.dueAt).toLocaleString("zh-CN")} />{data.ticket.issues.map(issue => <div key={issue} className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">补正项：{issue}</div>)}</CardContent></Card>
        {data.permission.canHandle ? <Card><CardHeader><CardTitle className="text-base">人工受理操作</CardTitle></CardHeader><CardContent className="space-y-3"><div className="grid gap-2">{data.permission.actions.map(item => <Button key={item.id} variant={action === item.id ? "default" : "outline"} onClick={() => setAction(item.id)}>{item.label}</Button>)}</div><Textarea value={comment} onChange={event => setComment(event.target.value)} placeholder="请输入明确、可审计的受理依据" maxLength={500} /><Button className="w-full" disabled={!action || comment.trim().length < 2 || submitting} onClick={() => void submit()}>{submitting ? "处理中…" : "人工确认并执行"}</Button><p className="text-[10px] leading-5 text-muted-foreground"><ShieldCheck className="mr-1 inline h-3.5 w-3.5" />AI不自动执行通过或退回。</p></CardContent></Card> : <Card><CardContent className="p-5 text-center"><ShieldCheck className="mx-auto h-6 w-6 text-muted-foreground" /><p className="mt-2 text-sm font-medium">当前为只读工单</p></CardContent></Card>}</aside></div>
  </div>;
}
function Info({ label, value }: { label: string; value: string }) { return <Card><CardContent className="p-4"><p className="text-[10px] text-muted-foreground">{label}</p><p className="mt-1 break-all text-sm font-semibold">{value}</p></CardContent></Card>; }


