"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { BadgeCheck, Bot, CheckCircle2, Clapperboard, Clock3, Download, ExternalLink, Gauge, Loader2, Play, RefreshCw, ShieldCheck, Workflow } from "lucide-react";
import type { CollaborationEvidenceReport } from "@/lib/ai/hardship-collaboration-report";
import { EnterprisePageHeader } from "@/components/enterprise/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
interface Envelope<T>{success:boolean;data?:T;error?:string}
interface Shot{id:string;time:string;duration:number;title:string;purpose:string;role:string;route:string;proof:string;ready:(report:CollaborationEvidenceReport)=>boolean}
const SHOTS:Shot[]=[
 {id:"S01",time:"00:00—00:12",duration:12,title:"项目登录与模拟数据声明",purpose:"建立项目名称、企业级视觉与敏感数据边界",role:"公共入口",route:"/login",proof:"登录页、17角色入口、模拟数据声明",ready:()=>true},
 {id:"S02",time:"00:12—00:35",duration:23,title:"高校资助体系总览",purpose:"先解释资助是什么、覆盖哪些类型和生命周期",role:"小海豚旁白",route:"/platform-tour?mode=video",proof:"八类资助工具、六段生命周期",ready:()=>true},
 {id:"S03",time:"00:35—00:50",duration:15,title:"17角色与Agent团队",purpose:"展示17角色、17支团队和68个Agent的准备度",role:"平台全景",route:"/platform-tour/roles?mode=video",proof:"统一角色注册表与Agent团队",ready:()=>true},
 {id:"S04",time:"00:50—01:05",duration:15,title:"现实痛点与核心流程",purpose:"说明链路长、重复劳动、敏感数据和银校对账难",role:"小海豚旁白",route:"/platform-tour/process?mode=video",proof:"10节点临时困难补助流程",ready:r=>r.stages.length===10},
 {id:"S05",time:"01:05—02:45",duration:100,title:"小海豚多Agent角色接力",purpose:"通知、申请、预检、四级审核、财务、银行、对账连续执行",role:"8个责任岗位",route:"/agent/monitor/collaboration",proof:"真实运行、群聊、人工闸门、业务对象",ready:r=>r.result.completedStages===10&&r.result.confirmedGates===8},
 {id:"S06",time:"02:45—03:20",duration:35,title:"AI技术证据逐项显影",purpose:"模型、RAG、Skill、插件、MCP从注册态下钻到执行态",role:"AI运行治理",route:"/agent/monitor/collaboration/report?mode=video",proof:"实际次数、耗时、输入输出与证据ID",ready:r=>r.model.executionCount===1&&r.assets.every(asset=>asset.executionCount>0)},
 {id:"S07",time:"03:20—03:45",duration:25,title:"权限、安全与审计",purpose:"展示九维权限、越权阻断、脱敏、人工闸门和SHA-256",role:"审计员",route:"/audit-center/integrity",proof:"10×9权限矩阵、21条任务证据、完整性通过",ready:r=>r.consistency.audits.valid&&r.audit.valid},
 {id:"S08",time:"03:45—04:10",duration:25,title:"到账结果与价值总结",purpose:"以到账、对账平衡、效率和全链证据完成收束",role:"小海豚总调度",route:"/agent/monitor/collaboration/report?mode=video&scene=final",proof:"已完成、2000元、差额0、到账通知",ready:r=>r.result.applicationStatus==="已完成"&&r.result.reconciliation==="matched"},
];
function authHeaders():HeadersInit{const token=localStorage.getItem("token");return token?{Authorization:`Bearer ${token}`}:{}}
export function VideoProductionStudio({runId}:{runId:string}){
 const[data,setData]=useState<CollaborationEvidenceReport|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch(`/api/ai/collaboration/report?runId=${encodeURIComponent(runId)}`,{headers:authHeaders(),cache:"no-store"});const body=await response.json() as Envelope<CollaborationEvidenceReport>;if(!response.ok||!body.success||!body.data)throw new Error(body.error??"视频就绪状态加载失败");setData(body.data)}catch(reason){setError(reason instanceof Error?reason.message:"视频就绪状态加载失败")}finally{setLoading(false)}},[runId]);useEffect(()=>{void load()},[load]);
 const ready=useMemo(()=>data?SHOTS.filter(shot=>shot.ready(data)).length:0,[data]);const totalDuration=SHOTS.reduce((sum,item)=>sum+item.duration,0);
 function route(shot:Shot){if(shot.id==="S05")return `/agent/monitor/collaboration/${runId}`;if(shot.id==="S06")return `/agent/monitor/collaboration/${runId}/report?mode=video`;if(shot.id==="S08")return `/agent/monitor/collaboration/${runId}/report?mode=video`;return shot.route}
 function download(){if(!data)return;const manifest={project:"冀慧学途：校园资助数智化协同护航平台",version:"video-production-v4",runId,dataMode:"simulated",resolution:"1920x1080",fps:30,targetDurationSeconds:totalDuration,consistency:data.consistency,shots:SHOTS.map(shot=>({...shot,route:route(shot),ready:shot.ready(data)}))};const blob=new Blob([JSON.stringify(manifest,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`jihuixuetu-video-manifest-${runId}.json`;a.click();URL.revokeObjectURL(url)}
 return <div className="space-y-6 pb-12"><EnterprisePageHeader eyebrow="VIDEO PRODUCTION CONTROL" title="小海豚演示视频导演台" description="在原系统内检查3—5分钟成片所需的业务、AI与审计证据。导演台只组织镜头，不创建旁路数据；所有业务画面继续读取固定场景和同一运行实例。" icon={Clapperboard} badge="V4 · 1920×1080" actions={[{label:"刷新就绪态",icon:RefreshCw,variant:"outline",onClick:()=>void load(),disabled:loading},{label:"导出镜头清单",icon:Download,variant:"outline",onClick:download,disabled:!data}]}/>
  {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}
  {data&&<><section className="overflow-hidden rounded-[24px] border border-slate-800 bg-[linear-gradient(135deg,#06101e,#0b1c31_60%,#08242b)] p-6 text-white shadow-[0_24px_70px_rgba(15,23,42,.18)]"><div className="flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between"><div><div className="flex flex-wrap gap-2"><Badge className="border border-cyan-300/20 bg-cyan-400/10 text-cyan-100">DIRECTOR MODE · V4</Badge><Badge className="border border-emerald-300/20 bg-emerald-400/10 text-emerald-100">{data.consistency.overall?"SAME-RUN VERIFIED":"EVIDENCE CHECK"}</Badge><Badge className="border border-amber-300/20 bg-amber-400/10 text-amber-100">模拟数据 · 真实机制</Badge></div><h2 className="mt-4 text-2xl font-bold">录制基准已锁定：{runId}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">目标成片4分10秒；镜头按“认知—痛点—角色接力—AI证据—安全审计—结果”展开。重新录制单个镜头不会修改业务状态。</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Hero label="就绪镜头" value={`${ready}/${SHOTS.length}`}/><Hero label="目标时长" value={`${Math.floor(totalDuration/60)}:${String(totalDuration%60).padStart(2,"0")}`}/><Hero label="分辨率" value="1080p"/><Hero label="帧率" value="30 FPS"/></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/8"><div className="h-full rounded-full bg-gradient-to-r from-blue-500 via-cyan-400 to-emerald-400" style={{width:`${ready/SHOTS.length*100}%`}}/></div></section>
   <div className="grid gap-4 xl:grid-cols-4"><ReadyCard icon={Workflow} label="业务链" value={`${data.result.completedStages}/${data.result.totalStages}`} detail="通知至到账完整闭环"/><ReadyCard icon={Bot} label="AI资产" value={String(data.assets.reduce((sum,item)=>sum+item.executionCount,0)+data.model.executionCount)} detail="模型、RAG、Skill、插件、MCP"/><ReadyCard icon={ShieldCheck} label="一致性" value={data.consistency.overall?"VERIFIED":"CHECK"} detail="群聊、Trace、审计、业务同源"/><ReadyCard icon={Gauge} label="资金结果" value="差额 ¥0" detail={`${data.result.batchNo} · ${data.result.receiptNo}`}/></div>
   <Card className="border-slate-200 shadow-sm"><CardHeader><div className="flex items-center justify-between"><div><h2 className="text-base font-bold text-slate-900">3—5分钟成片镜头时间线</h2><p className="mt-1 text-xs text-slate-500">点击镜头直接进入原系统正式页面；录制身份与证据要求已锁定。</p></div><Button asChild><Link href={route(SHOTS[0])}><Play/>进入首镜头</Link></Button></div></CardHeader><CardContent className="space-y-3">{SHOTS.map(shot=>{const ok=shot.ready(data);return <div key={shot.id} className="grid gap-4 rounded-2xl border border-slate-200 p-4 lg:grid-cols-[110px_1fr_230px_130px] lg:items-center"><div><div className="flex items-center gap-2"><span className={`flex h-9 w-9 items-center justify-center rounded-xl font-mono text-xs font-bold ${ok?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{shot.id}</span><span className="font-mono text-[9px] text-slate-400">{shot.time}</span></div></div><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-semibold text-slate-800">{shot.title}</h3>{ok?<Badge className="bg-emerald-100 text-emerald-700"><CheckCircle2 className="mr-1 h-3 w-3"/>就绪</Badge>:<Badge className="bg-amber-100 text-amber-700"><Clock3 className="mr-1 h-3 w-3"/>待补齐</Badge>}</div><p className="mt-1 text-[11px] leading-5 text-slate-500">{shot.purpose}</p><p className="mt-1 text-[9px] text-blue-600">画面证据：{shot.proof}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-[9px] text-slate-400">录制身份</p><p className="mt-1 text-xs font-semibold text-slate-700">{shot.role}</p><p className="mt-1 truncate font-mono text-[8px] text-slate-400">{route(shot)}</p></div><Button asChild variant="outline"><Link href={route(shot)}>打开镜头<ExternalLink/></Link></Button></div>})}</CardContent></Card>
   <div className="grid gap-5 xl:grid-cols-2"><Card className="border-slate-200 shadow-sm"><CardHeader><h2 className="text-base font-bold">录制技术参数</h2></CardHeader><CardContent className="grid grid-cols-2 gap-3"><Spec label="画布" value="1920×1080"/><Spec label="帧率" value="30 FPS"/><Spec label="浏览器" value="Chromium / DPR 1"/><Spec label="素材容器" value="WebM → MP4"/><Spec label="页面稳定" value="networkidle + 定点等待"/><Spec label="数据基准" value={`REV ${data.run.scenario?.revision}`}/></CardContent></Card><Card className="border-slate-200 shadow-sm"><CardHeader><h2 className="text-base font-bold">真实性拍摄规则</h2></CardHeader><CardContent className="space-y-3"><Rule text="业务操作镜头必须从场景复位后通过真实API、角色闸门和状态机执行。"/><Rule text="证据回放镜头必须明确标注“非重新执行”，并保证回放前后运行版本和状态哈希不变。"/><Rule text="银行镜头明确显示模拟适配器、外部资金移动关闭，不暗示真实转账。"/><Rule text="模型、Skill、插件和MCP以实际执行次数和证据ID为准，不以已安装状态代替。"/></CardContent></Card></div>
  </>}{loading&&!data&&<Card><CardContent className="flex h-48 items-center justify-center text-sm text-slate-500"><Loader2 className="mr-3 h-5 w-5 animate-spin"/>正在检查视频镜头依赖…</CardContent></Card>}
 </div>}
function Hero({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-white/10 bg-black/15 p-3"><p className="text-[9px] text-slate-500">{label}</p><p className="mt-1 text-lg font-bold">{value}</p></div>}
function ReadyCard({icon:Icon,label,value,detail}:{icon:typeof Workflow;label:string;value:string;detail:string}){return <Card className="border-slate-200 shadow-sm"><CardContent className="flex items-center gap-4 p-5"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-blue-700"><Icon className="h-5 w-5"/></span><div><p className="text-[10px] text-slate-400">{label}</p><p className="mt-1 text-xl font-bold text-slate-900">{value}</p><p className="mt-1 text-[9px] text-slate-500">{detail}</p></div></CardContent></Card>}
function Spec({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[9px] text-slate-400">{label}</p><p className="mt-1 text-xs font-semibold text-slate-700">{value}</p></div>}
function Rule({text}:{text:string}){return <div className="flex gap-3 rounded-xl border border-emerald-100 bg-emerald-50/60 p-3 text-[11px] leading-5 text-emerald-800"><BadgeCheck className="mt-0.5 h-4 w-4 shrink-0"/>{text}</div>}

