"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, Bot, CheckCircle2, Clock3, Fingerprint, RefreshCw, ShieldCheck, XCircle } from "lucide-react";
import { EnterprisePageHeader } from "@/components/enterprise/page-header";
import { SectionHeading, StatusPill } from "@/components/enterprise/dashboard";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";

interface Dimension { code: string; name: string; status: string; reason: string; evidence: string[]; policyRef: string; requiredApprovals: number; fieldMode?: string }
interface Formula { expression: string; effective: boolean; components: Array<{ code: string; name: string; status: string; detail: string }> }
interface RecordPayload { id: string; scenarioId: string; scenarioName: string; actorId: string; actorRole: string; actorType: "human" | "agent"; permission: string; operation: string; resourceId: string; resourceType: string; sensitiveLevel: string; geographicLevel: string; decision: { status: string; allowed: boolean; code: string; reason: string; deniedBy: string[]; pendingBy: string[]; requiredApprovals: number; fieldMode: string; dimensions: Dimension[]; formula: Formula | null; evaluatedAt: string }; createdAt: string; initiatedBy: string }
interface Envelope<T> { success: boolean; data?: T; error?: string }
const LABELS: Record<string, string> = { ALLOW: "允许", DENY: "拒绝", PENDING_APPROVAL: "待审批", ESCALATE: "升级处置" };
function headers(): HeadersInit { const token = localStorage.getItem("token"); return token ? { Authorization: `Bearer ${token}` } : {}; }
function tone(status: string): "healthy" | "danger" | "warning" { return status === "ALLOW" ? "healthy" : status === "DENY" ? "danger" : "warning"; }
function icon(status: string) { return status === "ALLOW" ? CheckCircle2 : status === "DENY" ? XCircle : Clock3; }

export default function DecisionDetailPage() {
  const { id } = useParams<{ id: string }>(); const [data, setData] = useState<RecordPayload | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch(`/api/access-control/decisions/${encodeURIComponent(id)}`, { headers: headers(), cache: "no-store" }); const body = await response.json() as Envelope<RecordPayload>; if (!response.ok || !body.success || !body.data) throw new Error(body.error ?? "权限决策详情加载失败"); setData(body.data); } catch (reason) { setError(reason instanceof Error ? reason.message : "权限决策详情加载失败"); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  return <div className="space-y-6"><EnterprisePageHeader eyebrow="ACCESS DECISION EVIDENCE" title={data ? `${data.scenarioName} · 判定证据` : "权限决策证据详情"} description="展示请求主体、资源、动态上下文、九维逐项结果和Agent交集公式。该快照用于安全复核与审计追溯，页面不可修改原判定。" icon={Fingerprint} badge={data ? `${data.decision.code} · ${data.id}` : "LOADING"} actions={[{ label: "刷新证据", icon: RefreshCw, variant: "outline", onClick: () => void load(), disabled: loading }]} />
    <Link href="/access-control"><Button size="sm" variant="ghost"><ArrowLeft className="mr-2 h-4 w-4" />返回权限控制中心</Button></Link>
    {error && <div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700 dark:border-rose-900 dark:bg-rose-950/30 dark:text-rose-200">{error}</div>}
    {loading && !data && <div className="flex min-h-[360px] items-center justify-center text-sm text-muted-foreground"><RefreshCw className="mr-2 h-5 w-5 animate-spin" />正在读取九维权限证据快照…</div>}
    {data && <><Card className={`border shadow-sm ${data.decision.status === "ALLOW" ? "border-emerald-200 bg-emerald-50/50 dark:border-emerald-900 dark:bg-emerald-950/20" : data.decision.status === "DENY" ? "border-rose-200 bg-rose-50/50 dark:border-rose-900 dark:bg-rose-950/20" : "border-amber-200 bg-amber-50/50 dark:border-amber-900 dark:bg-amber-950/20"}`}><CardContent className="grid gap-5 p-6 xl:grid-cols-[.7fr_1.7fr_1fr]"><div><p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">综合结果</p><div className="mt-3 flex items-center gap-3"><StatusPill status={tone(data.decision.status)} label={LABELS[data.decision.status]} /><span className="font-mono text-[10px] text-muted-foreground">{data.decision.code}</span></div></div><div><p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">首要判定依据</p><p className="mt-3 text-sm leading-6 text-foreground">{data.decision.reason}</p></div><div className="grid grid-cols-2 gap-2"><Tiny label="字段模式" value={data.decision.fieldMode} /><Tiny label="所需审批" value={`${data.decision.requiredApprovals} 人`} /></div></CardContent></Card>

      <div className="grid gap-5 xl:grid-cols-[.85fr_1.65fr]"><Card className="h-fit border-border shadow-sm"><CardHeader><SectionHeading title="请求上下文快照" description="不展示密码、密钥、证件号或完整个人敏感字段" /></CardHeader><CardContent className="space-y-1"><Context label="主体ID" value={data.actorId} /><Context label="主体角色" value={data.actorRole} /><Context label="执行主体" value={data.actorType === "agent" ? "Agent代理" : "人工操作"} /><Context label="权限点" value={data.permission} mono /><Context label="操作类型" value={data.operation} /><Context label="资源类型" value={data.resourceType} /><Context label="资源引用" value={data.resourceId} mono /><Context label="敏感等级" value={data.sensitiveLevel} /><Context label="地理等级" value={data.geographicLevel} /><Context label="发起来源" value={data.initiatedBy} mono /><Context label="判定时间" value={new Date(data.decision.evaluatedAt).toLocaleString("zh-CN")} /></CardContent></Card>
        <Card className="border-border shadow-sm"><CardHeader><SectionHeading title="九维逐项判定链" description="任一维度拒绝则整体阻断；待审批条件使操作保持挂起" /></CardHeader><CardContent className="space-y-3">{data.decision.dimensions.map((dimension, index) => { const Icon = icon(dimension.status); return <div key={dimension.code} className="rounded-xl border border-border p-4"><div className="flex items-start gap-3"><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl ${dimension.status === "ALLOW" ? "bg-emerald-50 text-emerald-600 dark:bg-emerald-950/40" : dimension.status === "DENY" ? "bg-rose-50 text-rose-600 dark:bg-rose-950/40" : "bg-amber-50 text-amber-600 dark:bg-amber-950/40"}`}><Icon className="h-4 w-4" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-[10px] font-bold text-muted-foreground">DIM {index + 1}</span><p className="text-sm font-semibold text-foreground">{dimension.name}</p><StatusPill status={tone(dimension.status)} label={LABELS[dimension.status]} /><Link href={`/access-control/dimensions/${dimension.code}`}><Badge variant="outline" className="cursor-pointer hover:border-blue-300">{dimension.policyRef}</Badge></Link></div><p className="mt-2 text-xs leading-5 text-muted-foreground">{dimension.reason}</p><div className="mt-2 flex flex-wrap gap-1.5">{dimension.evidence.map(item => <code key={item} className="rounded-md bg-muted px-2 py-1 text-[9px] text-muted-foreground">{item}</code>)}</div>{dimension.fieldMode && <p className="mt-2 text-[10px] font-medium text-blue-700 dark:text-blue-300">字段输出模式：{dimension.fieldMode}</p>}</div></div></div>; })}</CardContent></Card></div>

      {data.decision.formula && <Card className="border-blue-200 shadow-sm dark:border-blue-900"><CardHeader><SectionHeading title="Agent权限交集公式证据" description="角色、工具、九维和护栏缺一不可；模型无法覆盖该结果" /></CardHeader><CardContent><div className="rounded-xl bg-blue-50 p-4 font-mono text-xs font-semibold leading-6 text-blue-900 dark:bg-blue-950/30 dark:text-blue-100">{data.decision.formula.expression}</div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{data.decision.formula.components.map(component => <div key={component.code} className="rounded-xl border border-border p-4"><div className="flex items-center justify-between"><Bot className="h-4 w-4 text-blue-600" /><StatusPill status={tone(component.status)} label={LABELS[component.status]} /></div><p className="mt-3 text-xs font-semibold text-foreground">{component.name}</p><p className="mt-2 text-[10px] leading-5 text-muted-foreground">{component.detail}</p></div>)}</div></CardContent></Card>}

      <div className="rounded-xl border border-border bg-muted/30 px-4 py-3 text-[10px] leading-5 text-muted-foreground"><ShieldCheck className="mr-2 inline h-4 w-4 text-blue-600" />证据快照编号 {data.id}。当前开发阶段持久化于本机运行目录；生产部署必须迁移至不可篡改审计存储并启用签名、时间戳和保留策略。</div>
    </>}
  </div>;
}
function Context({ label, value, mono = false }: { label: string; value: string; mono?: boolean }) { return <div className="flex items-start justify-between gap-4 border-b border-border py-3 last:border-0"><span className="text-xs text-muted-foreground">{label}</span><span className={`max-w-[65%] break-all text-right text-xs font-medium text-foreground ${mono ? "font-mono text-[10px]" : ""}`}>{value}</span></div>; }
function Tiny({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-border bg-card p-3 text-center"><p className="text-sm font-bold text-foreground">{value}</p><p className="mt-1 text-[9px] text-muted-foreground">{label}</p></div>; }
