import { type ActorContext } from '@/lib/platform/authorization';
import { writeAuditSnapshot } from '@/lib/platform/demo-store';

export type AgentRuntimeStatus = 'active' | 'paused' | 'degraded';
export type AgentAction = 'pause' | 'resume' | 'reset_breaker';
export interface AgentDefinition {
  id: string; name: string; team: string; description: string; modelRoute: string; tools: string[]; riskCeiling: 'L1'|'L2'|'L3'; status: AgentRuntimeStatus; trustScore: number; successRate: number; averageLatencyMs: number; executions24h: number; breakerFailures: number; version: number; updatedAt: string;
}
export type SkillStatus = 'draft'|'sandbox_passed'|'pending_approval'|'published'|'elite'|'rejected';
export type SkillAction = 'run_sandbox'|'submit_approval'|'approve_technical'|'approve_security'|'approve_business'|'evaluate_pareto';
export interface SkillMetrics { quality: number; successRate: number; costEfficiency: number; latencyScore: number; safetyScore: number }
export interface SkillDefinition { id:string; name:string; category:string; versionName:string; description:string; status:SkillStatus; source:'official'|'human-feedback'|'self-evolution'; approvals:{technical:boolean;security:boolean;business:boolean}; sandbox:{security:boolean;performance:boolean;permission:boolean}; metrics:SkillMetrics; parentSkillId?:string; eliteDecision?:string; version:number; updatedAt:string }
export interface ModelEndpoint { id:string; provider:string; model:string; expertType:'light'|'reasoning'|'embedding'|'ocr'; status:'active'|'standby'|'local'; configured:boolean; priority:number; contextWindow:number; inputCostPerMillion:number; outputCostPerMillion:number; requests24h:number; tokens24h:number; estimatedCost24h:number; successRate:number; p95LatencyMs:number }
export interface EvaluationRun { id:string; suite:string; model:string; cases:number; passed:number; accuracy:number; hallucinationRate:number; biasGap:number; status:'passed'|'blocked'; createdAt:string }
export interface AiTrace { id:string; requestType:string; actorRole:string; modelRoute:string; riskLevel:string; status:'completed'|'blocked'|'failed'; totalLatencyMs:number; tokens:number; estimatedCost:number; steps:Array<{name:string;status:string;latencyMs:number}>; createdAt:string }
export interface McpConnector { id:string; name:string; system:string; authMode:string; status:'healthy'|'degraded'|'disabled'; allowlistedTools:string[]; calls24h:number; successRate:number; secretRef:string }
export interface PromptTemplate { id:string; name:string; scope:string; versionName:string; variables:string[]; riskLevel:'L0'|'L1'|'L2'|'L3'; status:'draft'|'active'|'retired'; lastEvaluation:number; version:number; updatedAt:string }
export interface GuardrailRule { id:string; name:string; type:'prompt_injection'|'sensitive_data'|'compliance'|'tool_policy'; severity:'critical'|'high'|'medium'; status:'active'|'disabled'; hits24h:number; action:'block'|'redact'|'human_review'; core:boolean; version:number }
export interface HitlTask { id:string; title:string; requestedBy:string; assigneeRole:string; riskLevel:'L3'|'L4'|'L5'; tool:string; reason:string; status:'pending'|'approved'|'rejected'; createdAt:string; version:number }
export interface SandboxRuntime { id:string; name:string; type:'file_shell'|'browser'|'skill_test'; status:'healthy'|'degraded'; isolation:string; network:string; fileWrite:string; cpuLimit:string; executions24h:number; failures24h:number }
export interface AiBudget { monthlyLimit:number; used:number; warningThreshold:number; tokenLimit:number; tokensUsed:number }
interface Store { agents:AgentDefinition[]; skills:SkillDefinition[]; models:ModelEndpoint[]; evaluations:EvaluationRun[]; traces:AiTrace[]; connectors:McpConnector[]; prompts:PromptTemplate[]; guardrails:GuardrailRule[]; hitlTasks:HitlTask[]; sandboxes:SandboxRuntime[]; budget:AiBudget; idempotency:Map<string,AgentDefinition|SkillDefinition|EvaluationRun|PromptTemplate|GuardrailRule|HitlTask> }
const now='2026-08-03T09:00:00+08:00';
function createStore():Store{return{
 agents:[
  {id:'agent-orchestrator',name:'小海豚总调度',team:'统一调度团队',description:'意图识别、任务拆解、风险分级与多Agent协作。',modelRoute:'moe-router',tools:['intent_gateway','workflow_dispatch','human_handoff'],riskCeiling:'L3',status:'active',trustScore:96,successRate:98.7,averageLatencyMs:820,executions24h:1268,breakerFailures:0,version:4,updatedAt:now},
  {id:'agent-material-review',name:'材料预检Agent',team:'资助审核团队',description:'OCR结果核验、材料完整度与一致性检查，仅输出建议。',modelRoute:'light-expert',tools:['document_parse','rule_check','risk_flag'],riskCeiling:'L2',status:'active',trustScore:92,successRate:96.4,averageLatencyMs:1420,executions24h:486,breakerFailures:1,version:3,updatedAt:now},
  {id:'agent-policy-rag',name:'政策知识Agent',team:'知识服务团队',description:'基于权限过滤的混合检索、图RAG和引用回答。',modelRoute:'light-expert',tools:['hybrid_search','graph_rag','citation_verify'],riskCeiling:'L1',status:'active',trustScore:95,successRate:97.8,averageLatencyMs:960,executions24h:834,breakerFailures:0,version:5,updatedAt:now},
  {id:'agent-risk',name:'风险评估Agent',team:'风险治理团队',description:'异常模式与跨流程风险提示，不自动形成审批结论。',modelRoute:'reasoning-expert',tools:['risk_score','xai_summary','bias_guard'],riskCeiling:'L2',status:'degraded',trustScore:88,successRate:91.2,averageLatencyMs:2860,executions24h:219,breakerFailures:4,version:2,updatedAt:now},
  {id:'agent-notification',name:'智能催办Agent',team:'业务协同团队',description:'经人工确认后发送系统内催办并跟踪回执。',modelRoute:'rule-engine',tools:['overdue_query','notification_send'],riskCeiling:'L3',status:'active',trustScore:93,successRate:99.1,averageLatencyMs:410,executions24h:173,breakerFailures:0,version:2,updatedAt:now},
 ],
 skills:[
  {id:'skill-material-check-v2',name:'资助材料一致性检查',category:'material-review',versionName:'v2.3',description:'检查材料有效期、字段一致性与缺失项。',status:'elite',source:'official',approvals:{technical:true,security:true,business:true},sandbox:{security:true,performance:true,permission:true},metrics:{quality:94,successRate:97,costEfficiency:86,latencyScore:82,safetyScore:98},eliteDecision:'当前Pareto精英池基线。',version:5,updatedAt:now},
  {id:'skill-material-check-candidate',name:'材料一致性检查·反馈增强版',category:'material-review',versionName:'v2.4-rc1',description:'从42条人工修正中提炼的有效期识别与跨页字段比对能力。',status:'pending_approval',source:'self-evolution',parentSkillId:'skill-material-check-v2',approvals:{technical:true,security:true,business:true},sandbox:{security:true,performance:true,permission:true},metrics:{quality:96,successRate:98,costEfficiency:84,latencyScore:80,safetyScore:98},version:3,updatedAt:now},
  {id:'skill-policy-citation',name:'政策引用核验',category:'knowledge-rag',versionName:'v1.8',description:'验证答案中的政策版本、条款号与权限范围。',status:'published',source:'official',approvals:{technical:true,security:true,business:true},sandbox:{security:true,performance:true,permission:true},metrics:{quality:97,successRate:98,costEfficiency:91,latencyScore:88,safetyScore:99},version:4,updatedAt:now},
  {id:'skill-appeal-summary',name:'申诉材料摘要草稿',category:'appeal',versionName:'v0.9',description:'汇总申诉事实与证据目录，不生成裁定结论。',status:'draft',source:'human-feedback',approvals:{technical:false,security:false,business:false},sandbox:{security:false,performance:false,permission:false},metrics:{quality:85,successRate:88,costEfficiency:90,latencyScore:92,safetyScore:86},version:1,updatedAt:now},
 ],
 models:[
  {id:'model-deepseek-chat',provider:'DeepSeek',model:'deepseek-chat',expertType:'light',status:'active',configured:Boolean(process.env.DEEPSEEK_API_KEY),priority:10,contextWindow:64000,inputCostPerMillion:2,outputCostPerMillion:8,requests24h:1824,tokens24h:2864000,estimatedCost24h:14.62,successRate:99.2,p95LatencyMs:1840},
  {id:'model-deepseek-reasoner',provider:'DeepSeek',model:'deepseek-reasoner',expertType:'reasoning',status:'standby',configured:Boolean(process.env.DEEPSEEK_API_KEY),priority:20,contextWindow:64000,inputCostPerMillion:4,outputCostPerMillion:16,requests24h:196,tokens24h:782000,estimatedCost24h:8.74,successRate:97.6,p95LatencyMs:4620},
  {id:'model-bge-m3',provider:'Local',model:'bge-m3',expertType:'embedding',status:'local',configured:true,priority:5,contextWindow:8192,inputCostPerMillion:0,outputCostPerMillion:0,requests24h:5620,tokens24h:0,estimatedCost24h:0,successRate:99.8,p95LatencyMs:92},
  {id:'model-paddle-ocr',provider:'Local',model:'PaddleOCR',expertType:'ocr',status:'local',configured:true,priority:5,contextWindow:0,inputCostPerMillion:0,outputCostPerMillion:0,requests24h:386,tokens24h:0,estimatedCost24h:0,successRate:96.9,p95LatencyMs:680},
 ],
 evaluations:[
  {id:'eval-2026-08-03',suite:'校园资助核心回归集 v5',model:'deepseek-chat + RAG',cases:128,passed:121,accuracy:94.5,hallucinationRate:1.6,biasGap:3.2,status:'passed',createdAt:now},
  {id:'eval-2026-08-02-bias',suite:'困难认定公平性集 v3',model:'risk-agent',cases:240,passed:219,accuracy:91.3,hallucinationRate:0.8,biasGap:6.1,status:'blocked',createdAt:'2026-08-02T14:00:00+08:00'},
 ],
 traces:[
  {id:'trace-001',requestType:'材料预检',actorRole:'FUND_ADMIN',modelRoute:'light-expert',riskLevel:'L2',status:'completed',totalLatencyMs:1842,tokens:1280,estimatedCost:.014,steps:[{name:'意图网关',status:'completed',latencyMs:92},{name:'权限与脱敏',status:'completed',latencyMs:38},{name:'OCR/版面解析',status:'completed',latencyMs:610},{name:'规则检查',status:'completed',latencyMs:284},{name:'模型摘要',status:'completed',latencyMs:818}],createdAt:now},
  {id:'trace-002',requestType:'越权导出敏感数据',actorRole:'COUNSELOR',modelRoute:'none',riskLevel:'L5',status:'blocked',totalLatencyMs:24,tokens:0,estimatedCost:0,steps:[{name:'意图网关',status:'completed',latencyMs:11},{name:'九维权限校验',status:'blocked',latencyMs:13}],createdAt:'2026-08-03T08:40:00+08:00'},
 ],
 prompts:[
  {id:'prompt-assistant-role',name:'角色智能助手系统模板',scope:'全角色助手',versionName:'v4.2',variables:['role','data_scope','permissions'],riskLevel:'L1',status:'active',lastEvaluation:96.8,version:4,updatedAt:now},
  {id:'prompt-material-review',name:'材料预检解释模板',scope:'资助审核团队',versionName:'v2.1',variables:['application','evidence','policy_citations'],riskLevel:'L2',status:'active',lastEvaluation:94.2,version:3,updatedAt:now},
  {id:'prompt-finance-exception',name:'回盘失败原因分析模板',scope:'校级财务',versionName:'v1.3-rc',variables:['receipt_summary','error_codes'],riskLevel:'L2',status:'draft',lastEvaluation:91.6,version:2,updatedAt:now},
 ],
 guardrails:[
  {id:'guard-injection',name:'Prompt注入与越狱防护',type:'prompt_injection',severity:'critical',status:'active',hits24h:18,action:'block',core:true,version:5},
  {id:'guard-sensitive',name:'P3-P5敏感字段脱敏',type:'sensitive_data',severity:'critical',status:'active',hits24h:46,action:'redact',core:true,version:6},
  {id:'guard-discipline',name:'纪检合规红线',type:'compliance',severity:'high',status:'active',hits24h:3,action:'human_review',core:true,version:3},
  {id:'guard-tool-risk',name:'高风险工具确定性拦截',type:'tool_policy',severity:'critical',status:'active',hits24h:7,action:'block',core:true,version:8},
  {id:'guard-public-tone',name:'公示期舆情话术复核',type:'compliance',severity:'medium',status:'active',hits24h:12,action:'human_review',core:false,version:2},
 ],
 hitlTasks:[
  {id:'hitl-001',title:'发布材料预检Prompt v2.2',requestedBy:'AI运维工作流',assigneeRole:'AI_OPS',riskLevel:'L3',tool:'prompt.publish',reason:'核心回归集96.1分，需人工确认发布影响范围。',status:'pending',createdAt:'2026-08-03T08:52:00+08:00',version:1},
  {id:'hitl-002',title:'批量发送超时催办 37 条',requestedBy:'智能催办Agent',assigneeRole:'FUND_ADMIN',riskLevel:'L3',tool:'notification.batch_send',reason:'对外发送前需业务经办人确认对象和话术。',status:'pending',createdAt:'2026-08-03T09:03:00+08:00',version:1},
  {id:'hitl-003',title:'生成资助发放银行文件',requestedBy:'资金助手Agent',assigneeRole:'FINANCE',riskLevel:'L4',tool:'finance.bank_file.prepare',reason:'仅生成草稿，仍需财务双人复核后方可发送。',status:'rejected',createdAt:'2026-08-02T16:40:00+08:00',version:2},
 ],
 sandboxes:[
  {id:'sandbox-skill',name:'Skill三项测试沙盒',type:'skill_test',status:'healthy',isolation:'gVisor容器/任务级',network:'默认禁网，域名白名单',fileWrite:'临时卷，任务后销毁',cpuLimit:'2 vCPU / 2GB',executions24h:64,failures24h:2},
  {id:'sandbox-shell',name:'文件与Shell执行沙盒',type:'file_shell',status:'healthy',isolation:'只读基础镜像',network:'完全禁网',fileWrite:'工作目录白名单',cpuLimit:'1 vCPU / 1GB',executions24h:28,failures24h:1},
  {id:'sandbox-browser',name:'浏览器自动化沙盒',type:'browser',status:'degraded',isolation:'独立浏览器上下文',network:'业务域名白名单',fileWrite:'禁止下载可执行文件',cpuLimit:'2 vCPU / 3GB',executions24h:17,failures24h:3},
 ],
 connectors:[
  {id:'mcp-student-system',name:'学工系统MCP',system:'学生工作管理系统',authMode:'OAuth2 + 服务身份',status:'healthy',allowlistedTools:['student_status.read','enrollment.verify'],calls24h:1284,successRate:99.6,secretRef:'vault://mcp/student-system'},
  {id:'mcp-finance',name:'财务系统MCP',system:'高校财务平台',authMode:'mTLS + 签名',status:'healthy',allowlistedTools:['budget.balance.read','voucher.status.read'],calls24h:362,successRate:99.1,secretRef:'vault://mcp/finance'},
  {id:'mcp-bank',name:'银校协同MCP',system:'合作银行批量代发',authMode:'mTLS + IP白名单',status:'degraded',allowlistedTools:['batch.status.read','receipt.download'],calls24h:87,successRate:96.2,secretRef:'vault://mcp/bank'},
 ],
 budget:{monthlyLimit:3000,used:1184.62,warningThreshold:80,tokenLimit:180000000,tokensUsed:82460000},idempotency:new Map()}}
type Global=typeof globalThis&{__jhxtAiGovernance?:Store};const g=globalThis as Global;const store=g.__jhxtAiGovernance??createStore();g.__jhxtAiGovernance=store;store.idempotency??=new Map();const defaults=createStore();store.prompts??=defaults.prompts;store.guardrails??=defaults.guardrails;store.hitlTasks??=defaults.hitlTasks;store.sandboxes??=defaults.sandboxes;
function canOperate(actor:ActorContext){return actor.role==='AI_OPS'}
export function getAiOperationsSnapshot(actor:ActorContext){if(!['AI_OPS','SYS_ADMIN','AUDITOR','DISCIPLINE'].includes(actor.role))return null;return{agents:store.agents.map(x=>({...x,tools:[...x.tools]})),skills:store.skills.map(x=>({...x,approvals:{...x.approvals},sandbox:{...x.sandbox},metrics:{...x.metrics}})),models:store.models.map(x=>({...x})),evaluations:store.evaluations.map(x=>({...x})),traces:store.traces.map(x=>({...x,steps:x.steps.map(s=>({...s}))})),connectors:store.connectors.map(x=>({...x,allowlistedTools:[...x.allowlistedTools]})),prompts:store.prompts.map(x=>({...x,variables:[...x.variables]})),guardrails:store.guardrails.map(x=>({...x})),hitlTasks:store.hitlTasks.map(x=>({...x})),sandboxes:store.sandboxes.map(x=>({...x})),budget:{...store.budget}}}
export function processAgentAction(actor:ActorContext,input:{agentId:string;action:AgentAction;expectedVersion:number;comment:string;idempotencyKey:string}){if(!canOperate(actor))return{success:false,code:'ROLE_DENIED',message:'只有AI运维管理员可变更Agent运行状态。'};const scope=`${actor.userId}:agent:${input.idempotencyKey}`;const replay=store.idempotency.get(scope);if(replay&&'trustScore'in replay)return{success:true,code:'IDEMPOTENT_REPLAY',message:'操作已完成，本次返回原结果。',agent:{...replay,tools:[...replay.tools]}};const item=store.agents.find(x=>x.id===input.agentId);if(!item)return{success:false,code:'AGENT_NOT_FOUND',message:'Agent不存在。'};if(item.version!==input.expectedVersion)return{success:false,code:'VERSION_CONFLICT',message:'Agent配置已更新。',agent:{...item,tools:[...item.tools]}};if(input.action==='pause'){if(item.status==='paused')return{success:false,code:'ACTION_DENIED',message:'Agent已暂停。'};item.status='paused'}else if(input.action==='resume'){if(item.status!=='paused')return{success:false,code:'ACTION_DENIED',message:'只有已暂停Agent可恢复。'};item.status='active'}else{item.breakerFailures=0;if(item.status==='degraded')item.status='active'}item.version+=1;item.updatedAt=new Date().toISOString();store.idempotency.set(scope,{...item,tools:[...item.tools]});writeAuditSnapshot({taskId:item.id,actorId:actor.userId,actorRole:actor.role,action:`agent:${input.action}`,outcome:'success',evidenceSummary:`Agent ${item.id} 状态变为 ${item.status}；意见：${input.comment.slice(0,100)}。`});return{success:true,code:'ACTION_COMPLETED',message:'Agent运行状态已更新。',agent:{...item,tools:[...item.tools]}}}
function dominates(a:SkillMetrics,b:SkillMetrics){const av=Object.values(a),bv=Object.values(b);return av.every((v,i)=>v>=bv[i])&&av.some((v,i)=>v>bv[i])}
export function processSkillAction(actor:ActorContext,input:{skillId:string;action:SkillAction;expectedVersion:number;comment:string;idempotencyKey:string}){if(!canOperate(actor))return{success:false,code:'ROLE_DENIED',message:'只有AI运维管理员可执行Skill治理。'};const scope=`${actor.userId}:skill:${input.idempotencyKey}`;const replay=store.idempotency.get(scope);if(replay&&'metrics'in replay)return{success:true,code:'IDEMPOTENT_REPLAY',message:'操作已完成，本次返回原结果。',skill:{...replay}};const item=store.skills.find(x=>x.id===input.skillId);if(!item)return{success:false,code:'SKILL_NOT_FOUND',message:'Skill不存在。'};if(item.version!==input.expectedVersion)return{success:false,code:'VERSION_CONFLICT',message:'Skill已更新。',skill:{...item}};if(input.action==='run_sandbox'){if(item.status!=='draft')return{success:false,code:'ACTION_DENIED',message:'只有草稿可运行沙盒。'};item.sandbox={security:item.metrics.safetyScore>=90,performance:item.metrics.latencyScore>=75,permission:true};item.status=Object.values(item.sandbox).every(Boolean)?'sandbox_passed':'rejected'}else if(input.action==='submit_approval'){if(item.status!=='sandbox_passed')return{success:false,code:'ACTION_DENIED',message:'三项沙盒测试通过后才能送审。'};item.status='pending_approval'}else if(input.action.startsWith('approve_')){if(item.status!=='pending_approval')return{success:false,code:'ACTION_DENIED',message:'只有待审批Skill可会签。'};const kind=input.action.replace('approve_','') as keyof SkillDefinition['approvals'];item.approvals[kind]=true;if(Object.values(item.approvals).every(Boolean))item.status='published'}else{if(!['published','pending_approval'].includes(item.status)||!Object.values(item.approvals).every(Boolean)||!Object.values(item.sandbox).every(Boolean))return{success:false,code:'PRECONDITION_FAILED',message:'Pareto评估前必须完成沙盒与三方会签。'};const elites=store.skills.filter(x=>x.category===item.category&&x.status==='elite'&&x.id!==item.id);const dominatedBy=elites.find(x=>dominates(x.metrics,item.metrics));if(dominatedBy){item.status='rejected';item.eliteDecision=`被 ${dominatedBy.name} 在Pareto维度支配，建议合并经验而非入池。`}else{for(const old of elites.filter(x=>dominates(item.metrics,x.metrics))){old.status='published';old.eliteDecision=`由 ${item.name} 支配，移出精英池但保留版本。`}item.status='elite';item.eliteDecision=elites.length?'未被现有精英支配，且至少在质量维度形成改进，进入Pareto精英池。':'作为首个候选进入精英池。'}}item.version+=1;item.updatedAt=new Date().toISOString();store.idempotency.set(scope,{...item,approvals:{...item.approvals},sandbox:{...item.sandbox},metrics:{...item.metrics}});writeAuditSnapshot({taskId:item.id,actorId:actor.userId,actorRole:actor.role,action:`skill:${input.action}`,outcome:item.status==='rejected'?'rejected':'success',evidenceSummary:`Skill ${item.id} 处理为 ${item.status}；${item.eliteDecision??input.comment.slice(0,100)}`});return{success:true,code:'ACTION_COMPLETED',message:item.eliteDecision??'Skill治理状态已更新。',skill:{...item,approvals:{...item.approvals},sandbox:{...item.sandbox},metrics:{...item.metrics}}}}
export function runEvaluation(actor:ActorContext,input:{suite:string;idempotencyKey:string}){if(!canOperate(actor))return{success:false,code:'ROLE_DENIED',message:'只有AI运维管理员可运行评估。'};const scope=`${actor.userId}:eval:${input.idempotencyKey}`;const replay=store.idempotency.get(scope);if(replay&&'cases'in replay)return{success:true,code:'IDEMPOTENT_REPLAY',message:'评估已运行。',evaluation:{...replay}};const offset=store.evaluations.length%3;const cases=128,passed=122-offset,biasGap=3.4+offset*.4;const evaluation:EvaluationRun={id:`eval-${Date.now()}`,suite:input.suite,model:'deepseek-chat + RAG',cases,passed,accuracy:Number((passed/cases*100).toFixed(1)),hallucinationRate:1.4+offset*.2,biasGap,status:biasGap>5?'blocked':'passed',createdAt:new Date().toISOString()};store.evaluations.unshift(evaluation);store.idempotency.set(scope,{...evaluation});writeAuditSnapshot({taskId:evaluation.id,actorId:actor.userId,actorRole:actor.role,action:'eval:run',outcome:evaluation.status,evidenceSummary:`运行 ${evaluation.suite}，${passed}/${cases} 通过，偏差 ${biasGap}%。`});return{success:true,code:'EVALUATION_COMPLETED',message:evaluation.status==='blocked'?'评估未通过，已阻断发布。':'评估通过。',evaluation:{...evaluation}}}
export function recordModelUsage(model:string,usage:{totalTokens:number},latencyMs:number){const endpoint=store.models.find(x=>x.model===model);if(endpoint){endpoint.requests24h+=1;endpoint.tokens24h+=usage.totalTokens;endpoint.p95LatencyMs=Math.round(endpoint.p95LatencyMs*.9+latencyMs*.1);store.budget.tokensUsed+=usage.totalTokens}store.traces.unshift({id:`trace-${Date.now()}`,requestType:'model_completion',actorRole:'SYSTEM',modelRoute:model,riskLevel:'L0',status:'completed',totalLatencyMs:latencyMs,tokens:usage.totalTokens,estimatedCost:0,steps:[{name:'模型网关',status:'completed',latencyMs}],createdAt:new Date().toISOString()});if(store.traces.length>100)store.traces.length=100}


export type AiControlAction = 'resolve_hitl'|'toggle_guardrail'|'activate_prompt';
export function processAiControlAction(actor:ActorContext,input:{action:AiControlAction;targetId:string;expectedVersion:number;decision?:'approved'|'rejected';comment:string;idempotencyKey:string}){
 if(actor.role!=='AI_OPS')return{success:false,code:'ROLE_DENIED',message:'只有AI运维管理员可执行AI控制平面变更。'};
 const scope=`${actor.userId}:control:${input.idempotencyKey}`;if(store.idempotency.has(scope))return{success:true,code:'IDEMPOTENT_REPLAY',message:'操作已完成，本次返回原结果。'};
 if(input.comment.trim().length<4)return{success:false,code:'COMMENT_REQUIRED',message:'请输入至少4个字的处置依据。'};
 let message='AI控制平面状态已更新';const auditTarget=input.targetId;
 if(input.action==='resolve_hitl'){
  const task=store.hitlTasks.find(x=>x.id===input.targetId);if(!task)return{success:false,code:'NOT_FOUND',message:'人机协同任务不存在。'};if(task.version!==input.expectedVersion)return{success:false,code:'VERSION_CONFLICT',message:'任务已更新，请刷新后重试。'};if(task.assigneeRole!==actor.role)return{success:false,code:'ASSIGNEE_DENIED',message:`该任务应由 ${task.assigneeRole} 岗位处理。`};if(task.status!=='pending')return{success:false,code:'ACTION_DENIED',message:'任务已处理。'};if(input.decision!=='approved'&&input.decision!=='rejected')return{success:false,code:'DECISION_REQUIRED',message:'请选择批准或拒绝。'};task.status=input.decision;task.version+=1;message=`${task.title} 已${input.decision==='approved'?'人工批准':'人工拒绝'}`;store.idempotency.set(scope,{...task});
 }else if(input.action==='toggle_guardrail'){
  const rule=store.guardrails.find(x=>x.id===input.targetId);if(!rule)return{success:false,code:'NOT_FOUND',message:'护栏规则不存在。'};if(rule.version!==input.expectedVersion)return{success:false,code:'VERSION_CONFLICT',message:'护栏规则已更新。'};if(rule.core&&rule.status==='active')return{success:false,code:'CORE_GUARD_PROTECTED',message:'核心安全护栏不能从管理界面关闭。'};rule.status=rule.status==='active'?'disabled':'active';rule.version+=1;message=`${rule.name} 已${rule.status==='active'?'启用':'停用'}`;store.idempotency.set(scope,{...rule});
 }else{
  const prompt=store.prompts.find(x=>x.id===input.targetId);if(!prompt)return{success:false,code:'NOT_FOUND',message:'Prompt模板不存在。'};if(prompt.version!==input.expectedVersion)return{success:false,code:'VERSION_CONFLICT',message:'Prompt模板已更新。'};if(prompt.lastEvaluation<90)return{success:false,code:'EVAL_BLOCKED',message:'评估得分低于90，禁止发布。'};store.prompts.filter(x=>x.scope===prompt.scope&&x.id!==prompt.id).forEach(x=>{if(x.status==='active')x.status='retired'});prompt.status='active';prompt.version+=1;prompt.updatedAt=new Date().toISOString();message=`${prompt.name} ${prompt.versionName} 已人工确认发布`;store.idempotency.set(scope,{...prompt,variables:[...prompt.variables]});
 }
 writeAuditSnapshot({taskId:`ai-control-${Date.now()}`,actorId:actor.userId,actorRole:actor.role,action:`ai_control:${input.action}`,outcome:'success',evidenceSummary:`${message}；对象：${auditTarget}；依据：${input.comment.slice(0,120)}`});return{success:true,code:'ACTION_COMPLETED',message};
}



export function getAiRuntimeAggregate() {
 return {
  agents: { total: store.agents.length, active: store.agents.filter(item=>item.status==='active').length, degraded: store.agents.filter(item=>item.status==='degraded').length, successRate: Number((store.agents.reduce((sum,item)=>sum+item.successRate,0)/store.agents.length).toFixed(1)), executions24h: store.agents.reduce((sum,item)=>sum+item.executions24h,0) },
  skills: { total: store.skills.length, published: store.skills.filter(item=>['published','elite'].includes(item.status)).length, elite: store.skills.filter(item=>item.status==='elite').length },
  models: { configured: store.models.filter(item=>item.configured).length, total: store.models.length, requests24h: store.models.reduce((sum,item)=>sum+item.requests24h,0), tokens24h: store.models.reduce((sum,item)=>sum+item.tokens24h,0) },
  connectors: { healthy: store.connectors.filter(item=>item.status==='healthy').length, total: store.connectors.length, calls24h: store.connectors.reduce((sum,item)=>sum+item.calls24h,0) },
  guardrails: { active: store.guardrails.filter(item=>item.status==='active').length, hits24h: store.guardrails.reduce((sum,item)=>sum+item.hits24h,0) },
  evaluations: { latestAccuracy: store.evaluations[0]?.accuracy??0, blocked: store.evaluations.filter(item=>item.status==='blocked').length },
  budget: { ...store.budget },
 };
}