"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, BadgeCheck, Banknote, Braces, CheckCircle2, FileCheck2, Fingerprint, Landmark, Network, RefreshCw, ServerCog, ShieldCheck, TimerReset } from "lucide-react";
import { EnterprisePageHeader } from "@/components/enterprise/page-header";
import { MetricCard, SectionHeading, StatusPill } from "@/components/enterprise/dashboard";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useHashTab } from "@/hooks/use-hash-tab";

interface BankTask { id:string;assignedTaskId:string;batchId:string;batchNo:string;amount:number;count:number;accountView:string;requiredRole:"BANK";status:"pending_authorization"|"completed";scenarioId:string;applicationId:string;externalActionRoute:string;createdAt:string;completedAt?:string;version:number }
interface Batch { id:string;batchNo:string;project:string;count:number;amount:number;status:string;bankFileHash:string;confirmations:Array<{actorId:string;displayName:string;duty:"maker"|"reviewer";signedAt:string;signature:string}> }
interface Session { id:string;serverName:string;endpoint:string;protocolVersion:string;transport:string;authMode:string;certificateFingerprint:string;allowlist:string[];discoveredTools:string[];status:"connected";openedAt:string;closedAt:string }
interface Call { id:string;sequence:number;method:string;tool?:string;requestId:string;requestDigest:string;responseDigest:string;status:"success";latencyMs:number;requestSummary:string;responseSummary:string;createdAt:string }
interface Receipt { id:string;receiptNo:string;bankTaskId:string;batchId:string;expectedCount:number;actualCount:number;expectedAmount:number;actualAmount:number;failedCount:number;result:"SUCCESS";bankReference:string;sha256:string;receivedAt:string }
interface Reconciliation { id:string;batchNo:string;expectedCount:number;actualCount:number;expectedAmount:number;actualAmount:number;difference:number;failedCount:number;duplicateReceiptCount:number;result:"matched";reason:string;ruleVersion:string;completedAt:string;version:number }
interface Snapshot { scenarioId:string;revision?:number;phase:string;bankTask:BankTask|null;batch:Batch|null;session:Session|null;calls:Call[];receipt:Receipt|null;reconciliation:Reconciliation|null;security:{dataMode:string;externalMoneyMovement:boolean;accountFieldMode:string;directWriteAllowed:boolean;adapter?:string;truthfulness?:string} }
interface Envelope<T>{success:boolean;data?:T;error?:string}
function authHeaders():HeadersInit { const token=window.localStorage.getItem("token"); return token?{Authorization:`Bearer ${token}`}:{ }; }
function money(value:number){return `¥${value.toLocaleString("zh-CN")}`;}
function shortHash(value?:string){if(!value)return "—";return value.length>28?`${value.slice(0,18)}…${value.slice(-8)}`:value;}

export function VideoGrantBankWorkbench({ compact=false }:{compact?:boolean}){
 const [tab,setTab]=useHashTab(["task","mcp","receipt"] as const,"task");
 const [data,setData]=useState<Snapshot|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch("/api/bank/video-grant",{headers:authHeaders(),cache:"no-store"});const body=await response.json() as Envelope<Snapshot>;if(!response.ok||!body.success||!body.data)throw new Error(body.error??"银行任务加载失败");setData(body.data);}catch(reason){setError(reason instanceof Error?reason.message:"银行任务加载失败");}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const phase=useMemo(()=>data?.phase??"not_ready",[data]);
 const completed=data?.bankTask?.status==="completed";
 return <div className="space-y-6">
  {!compact&&<EnterprisePageHeader eyebrow="BANK MCP OPERATIONS" title="银行发放授权与可验证回盘中心" description="承接财务双签批次，以MCP标准完成握手、工具发现、允许列表校验、任务提交、状态查询和回盘拉取。当前为不触达真实资金网络的确定性模拟适配器，但每次调用和状态变化均真实持久化。" icon={Landmark} badge="BANK · 指定银行任务范围" actions={[{label:"刷新运行态",icon:RefreshCw,variant:"outline",onClick:()=>void load(),disabled:loading}]}/>} 
  {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}
  {data&&<>
   <div className="rounded-2xl border border-blue-200 bg-gradient-to-r from-blue-950 via-blue-900 to-cyan-900 p-5 text-white shadow-lg shadow-blue-950/10"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-start gap-4"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-white/10 ring-1 ring-white/20"><Network className="h-6 w-6 text-cyan-300"/></span><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">真实交互边界</p><Badge className="border-emerald-300/30 bg-emerald-400/15 text-emerald-200">模拟数据</Badge><Badge className="border-cyan-300/30 bg-cyan-400/15 text-cyan-100">外部资金移动：关闭</Badge></div><p className="mt-2 max-w-4xl text-xs leading-6 text-blue-100">{data.security.truthfulness??"当前尚未生成银行任务。所有银行外部动作保持关闭。"}</p></div></div><div className="shrink-0 text-right"><p className="font-mono text-[10px] text-cyan-200">{data.scenarioId} · REV {data.revision??"—"}</p><p className="mt-1 text-sm font-semibold">阶段：{phase}</p></div></div></div>
   <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="银行待办" value={data.bankTask?(completed?"已授权":"1"):"0"} detail={data.bankTask?.batchNo??"等待财务批次"} icon={Banknote} tone={completed?"emerald":"amber"}/><MetricCard label="MCP会话" value={data.session?"已连接":"未建立"} detail={data.session?.protocolVersion??"等待银行人工闸门"} icon={ServerCog} tone={data.session?"cyan":"blue"}/><MetricCard label="工具调用" value={String(data.calls.length)} detail="JSON-RPC请求/响应摘要" icon={Braces} tone="violet"/><MetricCard label="回盘结果" value={data.receipt?.result??"等待回盘"} detail={data.receipt?.receiptNo??"未生成"} icon={FileCheck2} tone={data.receipt?"emerald":"blue"}/><MetricCard label="银校对账" value={data.reconciliation?"已平衡":"待执行"} detail={data.reconciliation?.ruleVersion??"grant-reconciliation-v3"} icon={BadgeCheck} tone={data.reconciliation?"emerald":"blue"}/></div>
   <Tabs value={tab} onValueChange={setTab} className="space-y-5"><TabsList className="h-auto flex-wrap rounded-xl border border-slate-200 bg-white p-1"><TabsTrigger value="task">银行授权任务</TabsTrigger><TabsTrigger value="mcp">MCP调用链 ({data.calls.length})</TabsTrigger><TabsTrigger value="receipt">回盘与对账</TabsTrigger></TabsList>
    <TabsContent value="task" className="space-y-4">{data.bankTask&&data.batch?<><Card className="border-blue-200 shadow-sm"><CardHeader><SectionHeading title="财务双签交接批次" description="银行岗位仅获得指定任务和最小必要字段；不能读取学生家庭收入或原始申请材料。"/></CardHeader><CardContent className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="space-y-4"><div className="flex flex-wrap items-center gap-2"><p className="font-mono text-lg font-bold text-slate-900">{data.batch.batchNo}</p><StatusPill status={completed?"healthy":"warning"} label={completed?"银行回盘完成":"待银行人员授权"}/><Badge variant="outline">{data.batch.project}</Badge></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Info label="人数" value={`${data.batch.count}人`}/><Info label="金额" value={money(data.batch.amount)}/><Info label="收款账户" value={data.bankTask.accountView}/><Info label="批次版本" value={`v${data.bankTask.version}`}/></div><div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-slate-400">银行文件 SHA-256</p><p className="mt-2 break-all font-mono text-[10px] leading-5 text-slate-600">{data.batch.bankFileHash}</p></div></div><div className="space-y-3 rounded-xl border border-slate-200 p-4"><p className="text-xs font-semibold text-slate-700">职责分离签名</p>{data.batch.confirmations.map(item=><div key={item.actorId} className="flex items-center gap-3 rounded-lg bg-slate-50 p-3"><Fingerprint className="h-4 w-4 text-blue-600"/><div className="min-w-0 flex-1"><p className="text-xs font-medium text-slate-700">{item.displayName}</p><p className="mt-1 truncate font-mono text-[9px] text-slate-400">{item.signature}</p></div><Badge variant="outline">{item.duty==="maker"?"制单":"复核"}</Badge></div>)}{!completed&&<Button asChild className="w-full"><Link href={data.bankTask.externalActionRoute}><ShieldCheck className="mr-2 h-4 w-4"/>进入银行人工闸门<ArrowRight className="ml-2 h-4 w-4"/></Link></Button>}{completed&&<div className="flex items-center gap-2 rounded-lg bg-emerald-50 p-3 text-xs text-emerald-700"><CheckCircle2 className="h-4 w-4"/>银行授权意见与MCP证据已冻结</div>}</div></CardContent></Card></>:<Empty title="尚未生成银行任务" detail="请先在多Agent协作网络完成财务确定性校验与模拟双人分离复核。"/>}</TabsContent>
    <TabsContent value="mcp" className="space-y-4">{data.session?<><Card className="border-cyan-200 bg-cyan-50/30 shadow-sm"><CardContent className="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-4"><Info label="MCP Server" value={data.session.serverName}/><Info label="协议版本" value={data.session.protocolVersion}/><Info label="传输" value={data.session.transport}/><Info label="认证" value={data.session.authMode}/><div className="md:col-span-2 xl:col-span-4"><p className="text-[10px] text-slate-400">端点 / 证书指纹</p><p className="mt-1 font-mono text-[10px] text-slate-600">{data.session.endpoint} · {data.session.certificateFingerprint}</p></div></CardContent></Card><div className="relative space-y-3 before:absolute before:bottom-5 before:left-[21px] before:top-5 before:w-px before:bg-slate-200">{data.calls.map(call=><Card key={call.id} className="relative ml-0 border-slate-200 shadow-sm"><CardContent className="flex gap-4 p-4"><span className="z-10 flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-blue-600 font-mono text-xs font-bold text-white">{String(call.sequence).padStart(2,"0")}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-mono text-xs font-semibold text-slate-800">{call.tool??call.method}</p><StatusPill status="healthy" label="SUCCESS"/><Badge variant="outline">{call.latencyMs} ms</Badge></div><div className="mt-3 grid gap-3 lg:grid-cols-2"><Trace label="REQUEST" text={call.requestSummary} hash={call.requestDigest}/><Trace label="RESPONSE" text={call.responseSummary} hash={call.responseDigest}/></div><p className="mt-2 font-mono text-[9px] text-slate-400">{call.requestId} · {call.id}</p></div></CardContent></Card>)}</div></>:<Empty title="MCP会话尚未建立" detail="银行人工授权前，系统不会伪造握手、工具发现或回盘调用。"/>}</TabsContent>
    <TabsContent value="receipt" className="grid gap-4 xl:grid-cols-2">{data.receipt?<><Card className="border-emerald-200 shadow-sm"><CardHeader><SectionHeading title="银行可验证回盘" description="回盘原始载荷摘要已冻结，可与调用链和审计证据交叉核验。"/></CardHeader><CardContent className="space-y-4"><div className="flex items-center justify-between"><p className="font-mono text-base font-bold text-slate-900">{data.receipt.receiptNo}</p><StatusPill status="healthy" label={data.receipt.result}/></div><div className="grid grid-cols-2 gap-3"><Info label="应发 / 实发" value={`${data.receipt.expectedCount} / ${data.receipt.actualCount}笔`}/><Info label="应发 / 实发金额" value={`${money(data.receipt.expectedAmount)} / ${money(data.receipt.actualAmount)}`}/><Info label="失败笔数" value={`${data.receipt.failedCount}笔`}/><Info label="银行引用" value={data.receipt.bankReference}/></div><Trace label="RECEIPT SHA-256" text="银行回盘结构化载荷摘要" hash={data.receipt.sha256}/></CardContent></Card>{data.reconciliation?<Card className="border-emerald-200 shadow-sm"><CardHeader><SectionHeading title="银校确定性对账" description="金额、笔数、失败项和重复回盘键全部由程序规则校验。"/></CardHeader><CardContent className="space-y-4"><div className="flex items-center gap-3 rounded-xl bg-emerald-50 p-4 text-emerald-700"><CheckCircle2 className="h-7 w-7"/><div><p className="font-semibold">对账平衡 · 差额 {money(data.reconciliation.difference)}</p><p className="mt-1 text-[11px]">{data.reconciliation.reason}</p></div></div><div className="grid grid-cols-3 gap-3"><Info label="失败项" value={String(data.reconciliation.failedCount)}/><Info label="重复回盘" value={String(data.reconciliation.duplicateReceiptCount)}/><Info label="规则版本" value={data.reconciliation.ruleVersion}/></div></CardContent></Card>:<Empty title="等待财务自动对账" detail="回盘已就绪，下一节点将运行grant-reconciliation Skill并生成到账通知。"/>}</>:<div className="xl:col-span-2"><Empty title="等待银行回盘" detail="必须先由银行岗位确认人工闸门，MCP适配器才会执行受控调用。"/></div>}</TabsContent>
   </Tabs>
  </>}
  {loading&&!data&&<Card className="border-slate-200"><CardContent className="flex h-48 items-center justify-center gap-3 text-sm text-slate-500"><RefreshCw className="h-5 w-5 animate-spin"/>正在读取持久化银行任务…</CardContent></Card>}
 </div>;
}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-slate-50 p-3"><p className="text-[9px] uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 break-all text-xs font-semibold text-slate-700">{value}</p></div>}
function Trace({label,text,hash}:{label:string;text:string;hash:string}){return <div className="rounded-lg border border-slate-200 bg-white p-3"><p className="text-[9px] font-bold tracking-[.16em] text-blue-600">{label}</p><p className="mt-2 text-[11px] leading-5 text-slate-600">{text}</p><p className="mt-2 break-all font-mono text-[9px] text-slate-400">SHA-256 {shortHash(hash)}</p></div>}
function Empty({title,detail}:{title:string;detail:string}){return <Card className="border-dashed border-slate-300"><CardContent className="flex min-h-48 flex-col items-center justify-center p-8 text-center"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-slate-100 text-slate-500"><TimerReset className="h-5 w-5"/></span><p className="mt-4 text-sm font-semibold text-slate-700">{title}</p><p className="mt-2 max-w-lg text-xs leading-6 text-slate-500">{detail}</p></CardContent></Card>}

