"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Bot, Boxes, BrainCircuit, CheckCircle2, CircleDollarSign, Code2, FileCode2, Fingerprint, Gauge, GitPullRequest, Globe2, LockKeyhole, Network, RefreshCw, Route, ShieldCheck, Sparkles, TestTube2, UserCheck, XCircle, Zap } from "lucide-react";
import { useHashTab } from "@/hooks/use-hash-tab";
import { EnterprisePageHeader } from "@/components/enterprise/page-header";
import { MetricCard, SectionHeading, StatusPill } from "@/components/enterprise/dashboard";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
interface PromptTemplate { id: string; name: string; scope: string; versionName: string; variables: string[]; riskLevel: "L0" | "L1" | "L2" | "L3"; status: "draft" | "active" | "retired"; lastEvaluation: number; version: number; updatedAt: string }
interface Guardrail { id: string; name: string; type: string; severity: "critical" | "high" | "medium"; status: "active" | "disabled"; hits24h: number; action: "block" | "redact" | "human_review"; core: boolean; version: number }
interface HitlTask { id: string; title: string; requestedBy: string; assigneeRole: string; riskLevel: "L3" | "L4" | "L5"; tool: string; reason: string; status: "pending" | "approved" | "rejected"; createdAt: string; version: number }
interface Sandbox { id: string; name: string; type: "file_shell" | "browser" | "skill_test"; status: "healthy" | "degraded"; isolation: string; network: string; fileWrite: string; cpuLimit: string; executions24h: number; failures24h: number }
interface Snapshot { prompts: PromptTemplate[]; guardrails: Guardrail[]; hitlTasks: HitlTask[]; sandboxes: Sandbox[]; agents: Array<{ id: string; name: string; status: string; trustScore: number; riskCeiling: string }>; models: Array<{ id: string; provider: string; model: string; expertType: string; status: string; configured: boolean; successRate: number; p95LatencyMs: number }>; budget: { monthlyLimit: number; used: number; tokenLimit: number; tokensUsed: number } }
interface Envelope<T> { success: boolean; data?: T; error?: string; message?: string }
type Pending = { title: string; description: string; confirm: string; body: { action: "resolve_hitl" | "toggle_guardrail" | "activate_prompt"; targetId: string; expectedVersion: number; decision?: "approved" | "rejected" } };
function headers() { const token = localStorage.getItem("token"); return { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }; }
function key() { return `ai-control-${Date.now()}-${crypto.randomUUID()}`; }
export default function AiControlPlanePage() {
 const [tab, setTab] = useHashTab(["hitl", "guardrails", "prompts", "sandbox", "routing"] as const, "hitl");
 const [data, setData] = useState<Snapshot | null>(null); const [loading, setLoading] = useState(true); const [pending, setPending] = useState<Pending | null>(null); const [comment, setComment] = useState(""); const [working, setWorking] = useState(false); const [message, setMessage] = useState<{ type: "ok" | "error"; text: string } | null>(null);
 const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/ai/operations", { headers: headers(), cache: "no-store" }); const body = await response.json() as Envelope<Snapshot>; if (!response.ok || !body.success || !body.data) throw new Error(body.error ?? "AI控制平面加载失败"); setData(body.data); } catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "AI控制平面加载失败" }); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]); const open = (item: Pending) => { setPending(item); setComment(""); };
 const execute = async () => { if (!pending || comment.trim().length < 4) return; setWorking(true); try { const response = await fetch("/api/ai/operations/control/actions", { method: "POST", headers: { ...headers(), "Idempotency-Key": key() }, body: JSON.stringify({ ...pending.body, comment: comment.trim(), humanConfirmed: true }) }); const body = await response.json() as Envelope<unknown>; if (!response.ok || !body.success) throw new Error(body.error ?? "AI治理操作失败"); setMessage({ type: "ok", text: body.message ?? "操作已完成" }); setPending(null); await load(); } catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "AI治理操作失败" }); } finally { setWorking(false); } };
 const stats = useMemo(() => ({ pending: data?.hitlTasks.filter(item => item.status === "pending" && item.assigneeRole === "AI_OPS").length ?? 0, guardHits: data?.guardrails.reduce((sum, item) => sum + item.hits24h, 0) ?? 0, sandboxSuccess: data ? (1 - data.sandboxes.reduce((sum, item) => sum + item.failures24h, 0) / data.sandboxes.reduce((sum, item) => sum + item.executions24h, 0)) * 100 : 0, modelHealth: data?.models.filter(item => item.configured).length ?? 0 }), [data]);
 return <div className="space-y-6"><EnterprisePageHeader eyebrow="AI CONTROL PLANE" title="AI安全、路由与人机协同控制平面" description="把 v6 规划中的意图网关、Prompt工坊、AI护栏、Human-in-the-Loop、沙盒、模型路由和成本控制从概念落实为可查看、可审批、可阻断、可审计的运行模块。" icon={BrainCircuit} badge="AI_OPS · L0-L5治理" actions={[{ label: "刷新控制面", icon: RefreshCw, variant: "outline", onClick: () => void load(), disabled: loading }]} />
 {message && <div className={`rounded-xl border px-4 py-3 text-sm ${message.type === "ok" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-rose-200 bg-rose-50 text-rose-700"}`}>{message.text}</div>}
 {data && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="待人工确认" value={stats.pending.toString()} detail="仅展示当前AI运维岗位可处理任务" icon={UserCheck} tone="amber" /><MetricCard label="24h护栏命中" value={stats.guardHits.toString()} detail="注入、敏感字段、合规和工具风险" icon={ShieldCheck} tone="emerald" /><MetricCard label="沙盒成功率" value={`${stats.sandboxSuccess.toFixed(1)}%`} detail="文件/Shell、浏览器和Skill测试" icon={Boxes} tone="violet" /><MetricCard label="已配置模型专家" value={stats.modelHealth.toString()} detail={`${data.models.length} 个模型端点纳入MoE路由`} icon={Route} tone="blue" /></div>
 <Card className="overflow-hidden border-slate-200 bg-slate-950 text-white shadow-xl"><CardContent className="p-6"><div className="flex flex-col gap-5 xl:flex-row xl:items-center"><div className="xl:w-64"><p className="text-[10px] font-semibold tracking-[.18em] text-cyan-300">INTENT GATEWAY</p><h2 className="mt-2 text-lg font-semibold">总调度室实时路径</h2><p className="mt-2 text-[11px] leading-5 text-slate-400">每步可观测、可阻断，不记录模型内部思维链。</p></div><div className="flex flex-1 flex-wrap items-center gap-2">{[{ name: "统一接入", icon: Globe2 }, { name: "身份与九维权限", icon: Fingerprint }, { name: "意图路由", icon: Route }, { name: "Agent团队", icon: Bot }, { name: "RAG/Skills/MCP", icon: Network }, { name: "模型网关", icon: BrainCircuit }, { name: "输出护栏", icon: ShieldCheck }].map((step, index, list) => { const Icon = step.icon; return <div key={step.name} className="flex items-center gap-2"><span className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.06] px-3 py-2 text-[10px] text-slate-200"><Icon className="h-3.5 w-3.5 text-cyan-300" />{step.name}</span>{index < list.length - 1 && <span className="text-slate-600">→</span>}</div>; })}</div></div></CardContent></Card>
 <Tabs value={tab} onValueChange={setTab} className="space-y-5"><TabsList className="h-auto flex-wrap rounded-xl border border-slate-200 bg-white p-1"><TabsTrigger value="hitl">人机回环队列</TabsTrigger><TabsTrigger value="guardrails">安全护栏</TabsTrigger><TabsTrigger value="prompts">Prompt工坊</TabsTrigger><TabsTrigger value="sandbox">执行沙盒</TabsTrigger><TabsTrigger value="routing">MoE与成本</TabsTrigger></TabsList>
 <TabsContent value="hitl" className="space-y-4">{data.hitlTasks.map(task => <Card key={task.id} className="border-slate-200 shadow-sm"><CardContent className="flex flex-col gap-4 p-5 xl:flex-row xl:items-center"><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${task.riskLevel === "L5" ? "bg-rose-50 text-rose-600" : task.riskLevel === "L4" ? "bg-amber-50 text-amber-600" : "bg-blue-50 text-blue-700"}`}><GitPullRequest className="h-5 w-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-slate-800">{task.title}</p><Badge variant="outline">{task.riskLevel}</Badge><Badge variant="secondary" className="font-mono text-[9px]">{task.tool}</Badge><StatusPill status={task.status === "approved" ? "healthy" : task.status === "rejected" ? "danger" : "warning"} label={task.status === "approved" ? "已批准" : task.status === "rejected" ? "已拒绝" : "待确认"} /></div><p className="mt-2 text-[11px] leading-5 text-slate-600">{task.reason}</p><p className="mt-1 text-[10px] text-slate-400">发起：{task.requestedBy} · 责任岗位：{task.assigneeRole} · {new Date(task.createdAt).toLocaleString("zh-CN")}</p></div>{task.status === "pending" && task.assigneeRole === "AI_OPS" ? <div className="flex gap-2"><Button variant="outline" onClick={() => open({ title: "拒绝AI操作请求", description: "拒绝后任务不会执行，并保留拒绝理由与快照。", confirm: "人工拒绝", body: { action: "resolve_hitl", targetId: task.id, expectedVersion: task.version, decision: "rejected" } })}><XCircle className="mr-2 h-4 w-4" />拒绝</Button><Button onClick={() => open({ title: "批准AI操作请求", description: "批准仅解除本层人工闸门；后续工具权限、护栏和业务前置条件仍会继续校验。", confirm: "人工批准", body: { action: "resolve_hitl", targetId: task.id, expectedVersion: task.version, decision: "approved" } })}><CheckCircle2 className="mr-2 h-4 w-4" />批准</Button></div> : task.status === "pending" ? <Badge variant="outline">等待 {task.assigneeRole} 处理</Badge> : null}</CardContent></Card>)}</TabsContent>
 <TabsContent value="guardrails" className="grid gap-4 xl:grid-cols-2">{data.guardrails.map(rule => <Card key={rule.id} className="border-slate-200 shadow-sm"><CardContent className="p-5"><div className="flex items-start justify-between"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${rule.severity === "critical" ? "bg-rose-50 text-rose-600" : rule.severity === "high" ? "bg-amber-50 text-amber-600" : "bg-blue-50 text-blue-700"}`}><LockKeyhole className="h-4 w-4" /></span><StatusPill status={rule.status === "active" ? "healthy" : "danger"} label={rule.status === "active" ? "运行中" : "已停用"} /></div><div className="mt-4 flex items-center gap-2"><h3 className="text-sm font-semibold text-slate-800">{rule.name}</h3>{rule.core && <Badge className="bg-slate-950 text-white">L0内核</Badge>}</div><p className="mt-1 font-mono text-[9px] text-slate-400">{rule.type} · action={rule.action}</p><div className="mt-4 grid grid-cols-2 gap-2"><Tiny label="24h命中" value={rule.hits24h.toString()} /><Tiny label="严重度" value={rule.severity.toUpperCase()} /></div><Button className="mt-4 w-full" variant="outline" disabled={rule.core && rule.status === "active"} onClick={() => open({ title: rule.status === "active" ? "停用护栏规则" : "启用护栏规则", description: rule.core ? "核心护栏由确定性规则保护，不能从管理界面关闭。" : "变更会立即影响后续AI请求，并写入审计日志。", confirm: "确认变更", body: { action: "toggle_guardrail", targetId: rule.id, expectedVersion: rule.version } })}>{rule.core && rule.status === "active" ? "核心护栏禁止关闭" : rule.status === "active" ? "停用规则" : "启用规则"}</Button></CardContent></Card>)}</TabsContent>
 <TabsContent value="prompts" className="grid gap-4 xl:grid-cols-3">{data.prompts.map(prompt => <Card key={prompt.id} className="border-slate-200 shadow-sm"><CardContent className="p-5"><div className="flex items-start justify-between"><FileCode2 className="h-5 w-5 text-violet-700" /><StatusPill status={prompt.status === "active" ? "healthy" : prompt.status === "draft" ? "warning" : "neutral"} label={prompt.status === "active" ? "生产启用" : prompt.status === "draft" ? "草稿" : "已退役"} /></div><h3 className="mt-4 text-sm font-semibold text-slate-800">{prompt.name}</h3><p className="mt-1 text-[10px] text-slate-400">{prompt.scope} · {prompt.versionName} · 风险 {prompt.riskLevel}</p><div className="mt-3 flex flex-wrap gap-1.5">{prompt.variables.map(variable => <Badge key={variable} variant="secondary" className="font-mono text-[9px]">{`{{${variable}}}`}</Badge>)}</div><div className="mt-4 flex items-center justify-between rounded-xl bg-slate-50 p-3"><span className="text-[10px] text-slate-400">最近评估</span><span className={`text-sm font-bold ${prompt.lastEvaluation >= 90 ? "text-emerald-700" : "text-rose-600"}`}>{prompt.lastEvaluation}</span></div>{prompt.status === "draft" && <Button className="mt-4 w-full" variant="outline" disabled={prompt.lastEvaluation < 90} onClick={() => open({ title: "发布Prompt模板", description: "系统将再次检查评估分数与版本；发布需要人工确认并保留回滚依据。", confirm: "确认发布", body: { action: "activate_prompt", targetId: prompt.id, expectedVersion: prompt.version } })}><Sparkles className="mr-2 h-4 w-4" />人工确认发布</Button>}</CardContent></Card>)}</TabsContent>
 <TabsContent value="sandbox" className="grid gap-4 xl:grid-cols-3">{data.sandboxes.map(sandbox => <Card key={sandbox.id} className="border-slate-200 shadow-sm"><CardContent className="p-5"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-950 text-cyan-300">{sandbox.type === "file_shell" ? <Code2 className="h-4 w-4" /> : sandbox.type === "browser" ? <Globe2 className="h-4 w-4" /> : <TestTube2 className="h-4 w-4" />}</span><StatusPill status={sandbox.status === "healthy" ? "healthy" : "warning"} label={sandbox.status === "healthy" ? "健康" : "降级"} /></div><h3 className="mt-4 text-sm font-semibold text-slate-800">{sandbox.name}</h3><div className="mt-4 space-y-2 text-[10px] text-slate-500"><p><b className="text-slate-700">隔离：</b>{sandbox.isolation}</p><p><b className="text-slate-700">网络：</b>{sandbox.network}</p><p><b className="text-slate-700">文件：</b>{sandbox.fileWrite}</p><p><b className="text-slate-700">资源：</b>{sandbox.cpuLimit}</p></div><div className="mt-4 grid grid-cols-2 gap-2"><Tiny label="24h执行" value={sandbox.executions24h.toString()} /><Tiny label="失败" value={sandbox.failures24h.toString()} /></div></CardContent></Card>)}</TabsContent>
 <TabsContent value="routing" className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><Card className="border-slate-200 shadow-sm"><CardHeader><SectionHeading title="MoE模型专家路由" description="按任务复杂度、数据敏感度、时延与成本自动选择模型" /></CardHeader><CardContent className="space-y-3">{data.models.map(model => <div key={model.id} className="flex items-center gap-4 rounded-xl border border-slate-200 p-4"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-50 text-blue-700"><BrainCircuit className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="text-xs font-semibold text-slate-800">{model.provider} / {model.model}</p><p className="mt-1 text-[10px] text-slate-400">{model.expertType} expert · P95 {model.p95LatencyMs}ms</p></div><div className="text-right"><p className="text-sm font-bold text-slate-800">{model.successRate}%</p><StatusPill status={model.configured ? "healthy" : "danger"} label={model.configured ? model.status : "未配置"} /></div></div>)}</CardContent></Card><Card className="border-slate-200 shadow-sm"><CardHeader><SectionHeading title="成本与Token配额" description="模型网关统一计量与告警" /></CardHeader><CardContent><p className="text-3xl font-bold text-slate-950">¥{data.budget.used.toLocaleString()}</p><p className="mt-1 text-[10px] text-slate-400">月预算 ¥{data.budget.monthlyLimit.toLocaleString()}</p><ProgressBar value={data.budget.used / data.budget.monthlyLimit * 100} /><div className="mt-6 flex items-center justify-between"><span className="text-[11px] text-slate-500">Token消耗</span><span className="text-xs font-semibold text-slate-800">{data.budget.tokensUsed.toLocaleString()} / {data.budget.tokenLimit.toLocaleString()}</span></div><ProgressBar value={data.budget.tokensUsed / data.budget.tokenLimit * 100} /><div className="mt-6 rounded-xl border border-blue-100 bg-blue-50 p-4 text-[11px] leading-5 text-blue-800"><CircleDollarSign className="mr-2 inline h-4 w-4" />轻量任务优先路由本地向量模型与低成本专家；复杂推理按需升级，不允许业务端绕过网关直连模型。</div></CardContent></Card></TabsContent>
 </Tabs></>}
 <AlertDialog open={Boolean(pending)} onOpenChange={value => { if (!value && !working) setPending(null); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{pending?.title}</AlertDialogTitle><AlertDialogDescription>{pending?.description}</AlertDialogDescription></AlertDialogHeader><Textarea value={comment} onChange={event => setComment(event.target.value)} placeholder="请输入人工判断、发布依据或回滚说明（至少4个字）" maxLength={800} /><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction disabled={working || comment.trim().length < 4} onClick={event => { event.preventDefault(); void execute(); }}>{working ? "提交中…" : pending?.confirm}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
function Tiny({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-slate-50 p-2 text-center"><p className="text-xs font-bold text-slate-800">{value}</p><p className="mt-1 text-[9px] text-slate-400">{label}</p></div>; }
function ProgressBar({ value }: { value: number }) { return <div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-blue-600 to-cyan-400" style={{ width: `${Math.min(100, value)}%` }} /></div>; }

