"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, Bot, CheckCircle2, Copy, Database, FileKey2, Fingerprint, GitBranch, LockKeyhole, RefreshCw, ShieldCheck, UserRound } from "lucide-react";
import { EnterprisePageHeader } from "@/components/enterprise/page-header";
import { SectionHeading, StatusPill } from "@/components/enterprise/dashboard";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";

interface AuditRecord { id: string; sequence: number; schemaVersion: string; taskId: string; timestamp: string; actor: { id: string; role: string; type: string; department?: string }; operation: { type: string; category: string; level: string; action: string; targetEntity: string; targetId?: string; fieldsChanged: string[]; details: Record<string, unknown> }; context: Record<string, unknown> & { dataSensitivity: string; workflowState?: string; permissionSnapshot?: Record<string, unknown> }; result: { status: string; errorCode?: string; errorMessage?: string; affectedRows: number }; evidence: { summary: string; snapshotBefore?: Record<string, unknown>; snapshotAfter?: Record<string, unknown>; references: string[]; ai?: Record<string, unknown>; xaiSummary?: string }; retention: { years: number; policy: string; deletionRequiresApproval: boolean }; immutable: true; previousHash: string; recordHash: string }
interface Envelope<T> { success: boolean; data?: T; error?: string }
function authHeaders(): HeadersInit { const token = localStorage.getItem("token"); return token ? { Authorization: `Bearer ${token}` } : {}; }
function JsonBlock({ value, empty = "无记录" }: { value?: unknown; empty?: string }) { if (value === undefined || value === null || (typeof value === "object" && !Object.keys(value as object).length)) return <div className="rounded-xl border border-dashed border-border p-5 text-center text-xs text-muted-foreground">{empty}</div>; return <pre className="max-h-[360px] overflow-auto rounded-xl border border-slate-200 bg-slate-950 p-4 text-[10px] leading-5 text-slate-100 dark:border-slate-800">{JSON.stringify(value, null, 2)}</pre>; }

export default function AuditEventDetailPage() {
  const params = useParams<{ id: string }>(); const id = Array.isArray(params.id) ? params.id[0] : params.id;
  const [data, setData] = useState<AuditRecord | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [copied, setCopied] = useState(false);
  const load = useCallback(async () => { if (!id) return; setLoading(true); setError(""); try { const response = await fetch(`/api/audit-evidence/events/${encodeURIComponent(id)}`, { headers: authHeaders(), cache: "no-store" }); const body = await response.json() as Envelope<AuditRecord>; if (!response.ok || !body.success || !body.data) throw new Error(body.error ?? "审计证据加载失败"); setData(body.data); } catch (reason) { setError(reason instanceof Error ? reason.message : "审计证据加载失败"); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  const copyHash = async () => { if (!data) return; await navigator.clipboard.writeText(data.recordHash); setCopied(true); window.setTimeout(() => setCopied(false), 1600); };
  return <div className="space-y-6">
    <EnterprisePageHeader eyebrow="IMMUTABLE EVIDENCE DETAIL" title="审计事件证据详情" description="独立展示事件主体、业务对象、结果、前后值、九维权限快照、P4最小AI证据、XAI与链式哈希。页面只读，不提供修改或删除入口。" icon={FileKey2} badge={data ? `SEQ ${data.sequence} · ${data.operation.level}` : "READ ONLY"} actions={[{ label: "刷新证据", icon: RefreshCw, variant: "outline", onClick: () => void load(), disabled: loading }]} />
    <Link href="/audit-center/events" className="inline-flex items-center text-xs font-medium text-muted-foreground hover:text-foreground"><ArrowLeft className="mr-1 h-4 w-4" />返回审计事件列表</Link>
    {error && <div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700 dark:border-rose-900 dark:bg-rose-950/30 dark:text-rose-200">{error}</div>}
    {loading && !data && <div className="flex min-h-[400px] items-center justify-center text-sm text-muted-foreground"><RefreshCw className="mr-2 h-5 w-5 animate-spin text-blue-600" />正在验证访问范围并读取只追加证据…</div>}
    {data && <>
      <Card className="border-border shadow-sm"><CardContent className="p-6"><div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between"><div><div className="flex flex-wrap items-center gap-2"><StatusPill status={["SUCCESS", "HUMAN_CONFIRMED"].includes(data.result.status) ? "healthy" : "danger"} label={data.result.status} /><Badge variant="outline">{data.operation.category}</Badge><Badge variant="outline">{data.context.dataSensitivity}</Badge>{data.immutable && <Badge className="bg-slate-950 text-white"><LockKeyhole className="mr-1 h-3 w-3" />IMMUTABLE</Badge>}</div><h2 className="mt-4 text-xl font-bold text-foreground">{data.operation.action}</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-muted-foreground">{data.evidence.summary}</p></div><div className="min-w-[290px] rounded-xl border border-border bg-muted/30 p-4 text-xs"><Info label="审计编号" value={data.id} mono /><Info label="任务编号" value={data.taskId} mono /><Info label="发生时间" value={new Date(data.timestamp).toLocaleString("zh-CN")} /><Info label="数据模式" value={data.schemaVersion} mono /></div></div></CardContent></Card>

      <div className="grid gap-5 xl:grid-cols-3"><SummaryCard icon={UserRound} title="操作主体"><Info label="主体ID" value={data.actor.id} mono /><Info label="角色" value={data.actor.role} /><Info label="主体类型" value={data.actor.type} /><Info label="部门" value={data.actor.department ?? "未登记"} /></SummaryCard><SummaryCard icon={Database} title="业务对象"><Info label="操作类型" value={data.operation.type} /><Info label="目标实体" value={data.operation.targetEntity} /><Info label="目标ID" value={data.operation.targetId ?? "-"} mono /><Info label="流程状态" value={data.context.workflowState ?? "-"} /></SummaryCard><SummaryCard icon={ShieldCheck} title="执行结果"><Info label="结果" value={data.result.status} /><Info label="影响行数" value={String(data.result.affectedRows)} /><Info label="错误码" value={data.result.errorCode ?? "无"} mono /><Info label="保留期限" value={`${data.retention.years} 年`} /></SummaryCard></div>

      <div className="grid gap-5 xl:grid-cols-2"><Card className="border-border shadow-sm"><CardHeader><SectionHeading title="变更前快照" description="UPDATE/审批/流转操作的冻结前值；P4/P5字段按最小必要原则脱敏" /></CardHeader><CardContent><JsonBlock value={data.evidence.snapshotBefore} empty="该事件没有变更前值（可能是创建、读取或被阻断操作）" /></CardContent></Card><Card className="border-border shadow-sm"><CardHeader><SectionHeading title="变更后快照" description={`变更字段：${data.operation.fieldsChanged.length ? data.operation.fieldsChanged.join("、") : "无"}`} /></CardHeader><CardContent><JsonBlock value={data.evidence.snapshotAfter} empty="该事件没有变更后值" /></CardContent></Card></div>

      <Card className="border-border shadow-sm"><CardHeader><SectionHeading title="九维权限与请求上下文" description="记录操作发生当时的确定性权限快照，不以当前权限倒推历史" /></CardHeader><CardContent className="grid gap-5 xl:grid-cols-2"><JsonBlock value={data.context.permissionSnapshot} empty="历史事件未关联独立九维决策编号" /><JsonBlock value={Object.fromEntries(Object.entries(data.context).filter(([key]) => key !== "permissionSnapshot"))} /></CardContent></Card>

      {data.evidence.ai && <Card className="border-violet-200 bg-violet-50/30 shadow-sm dark:border-violet-900 dark:bg-violet-950/10"><CardHeader><SectionHeading title="AI / Agent 最小必要证据" description="不保存完整Prompt、完整Response和RAG全文；仅保存脱敏摘要、摘要哈希、版本、来源类别、工具轨迹与XAI" /></CardHeader><CardContent><div className="mb-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-violet-200 bg-card p-4"><Bot className="h-5 w-5 text-violet-600" /><p className="mt-3 text-[10px] text-muted-foreground">Agent</p><p className="mt-1 text-sm font-semibold text-foreground">{String(data.evidence.ai.agentName ?? data.evidence.ai.agentCode ?? "系统AI")}</p></div><div className="rounded-xl border border-violet-200 bg-card p-4"><GitBranch className="h-5 w-5 text-violet-600" /><p className="mt-3 text-[10px] text-muted-foreground">模型版本</p><p className="mt-1 text-sm font-semibold text-foreground">{String(data.evidence.ai.modelVersion ?? data.evidence.ai.model ?? "已登记")}</p></div><div className="rounded-xl border border-violet-200 bg-card p-4"><CheckCircle2 className="h-5 w-5 text-violet-600" /><p className="mt-3 text-[10px] text-muted-foreground">定位</p><p className="mt-1 text-sm font-semibold text-foreground">{data.evidence.ai.advisoryOnly === true ? "仅辅助建议" : "护栏/系统执行"}</p></div></div><JsonBlock value={data.evidence.ai} />{data.evidence.xaiSummary && <div className="mt-4 rounded-xl border border-blue-200 bg-blue-50 p-4 dark:border-blue-900 dark:bg-blue-950/30"><p className="text-[10px] font-semibold tracking-wider text-blue-700">XAI SUMMARY</p><p className="mt-2 text-xs leading-6 text-foreground">{data.evidence.xaiSummary}</p></div>}</CardContent></Card>}

      <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><Card className="border-border shadow-sm"><CardHeader><SectionHeading title="操作详情与证据引用" description="参数值遵循敏感字段最小化；证据引用可用于案件与业务对象交叉核验" /></CardHeader><CardContent><JsonBlock value={data.operation.details} /><div className="mt-4 flex flex-wrap gap-2">{data.evidence.references.length ? data.evidence.references.map(ref => <Badge key={ref} variant="outline" className="font-mono">{ref}</Badge>) : <span className="text-xs text-muted-foreground">无外部证据引用</span>}</div></CardContent></Card><Card className="border-border shadow-sm"><CardHeader><SectionHeading title="链式哈希凭证" description="当前记录哈希同时绑定上一记录哈希；任意字段变化都会导致完整性校验失败" /></CardHeader><CardContent className="space-y-4"><HashBlock label="PREVIOUS HASH" value={data.previousHash} /><HashBlock label="RECORD HASH" value={data.recordHash} /><Button variant="outline" className="w-full" onClick={() => void copyHash()}><Copy className="mr-2 h-4 w-4" />{copied ? "已复制当前记录哈希" : "复制当前记录哈希"}</Button><Link href="/audit-center/integrity"><Button className="w-full"><Fingerprint className="mr-2 h-4 w-4" />校验完整证据链</Button></Link><p className="text-[10px] leading-5 text-muted-foreground">{data.retention.policy}；{data.retention.deletionRequiresApproval ? "物理销毁需教育主管部门审批并保留审批证据。" : "到期销毁仍需按制度流程执行。"}</p></CardContent></Card></div>
    </>}
  </div>;
}
function Info({ label, value, mono = false }: { label: string; value: string; mono?: boolean }) { return <div className="flex items-start justify-between gap-4 border-b border-border py-2.5 last:border-0"><span className="shrink-0 text-[10px] text-muted-foreground">{label}</span><span className={`break-all text-right text-xs font-medium text-foreground ${mono ? "font-mono" : ""}`}>{value}</span></div>; }
function SummaryCard({ icon: Icon, title, children }: { icon: typeof UserRound; title: string; children: React.ReactNode }) { return <Card className="border-border shadow-sm"><CardHeader><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-50 text-blue-700 dark:bg-blue-950/40 dark:text-blue-300"><Icon className="h-4 w-4" /></span><h2 className="text-sm font-semibold text-foreground">{title}</h2></div></CardHeader><CardContent>{children}</CardContent></Card>; }
function HashBlock({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-border bg-slate-950 p-4"><p className="text-[9px] font-semibold tracking-widest text-slate-400">{label}</p><p className="mt-2 break-all font-mono text-[10px] leading-5 text-emerald-300">{value}</p></div>; }
