import type { ActorContext } from "@/lib/platform/authorization";
import { writeAuditSnapshot } from "@/lib/platform/demo-store";
import { getHardshipVideoLeaderApprovalProjection } from "@/lib/platform/hardship-video-review-store";
export interface DepartmentPerformance { id: string; name: string; applications: number; supported: number; coverageRate: number; budget: number; paid: number; executionRate: number; ciac: number; highRisk: number; overdue: number }
export interface ExceptionCase { id: string; caseNo: string; type: "超标准发放" | "破格认定" | "申诉复核" | "紧急通道" | "资助审批"; title: string; department: string; studentCode: string; requestedAmount: number; standardAmount: number; reason: string; evidence: string[]; aiRisk: "低" | "中" | "高"; aiSuggestion: string; requiredRole: "FUND_LEADER" | "SCHOOL_LEADER"; status: "pending" | "approved" | "rejected"; version: number; submittedAt: string; scenarioId?: string; applicationId?: string; externalActionRoute?: string }
export interface BudgetScenario { id: string; name: string; project: string; deltaAmount: number; baselineCoverage: number; predictedCoverage: number; baselineExecution: number; predictedExecution: number; additionalStudents: number; riskNote: string; createdBy: string; createdAt: string }
export interface PolicyEffect { id: string; policy: string; year: string; target: string; coverageChange: number; completionRate: number; outcomeGain: number; equityChange: number; evidenceLevel: "高" | "中"; recommendation: string }
export interface LeadershipBrief { id: string; title: string; period: string; generatedAt: string; status: "draft" | "reviewed"; sections: string[] }
export interface DecisionSnapshot { departments: DepartmentPerformance[]; exceptions: ExceptionCase[]; scenarios: BudgetScenario[]; policyEffects: PolicyEffect[]; briefs: LeadershipBrief[]; indicators: { supportedStudents: number; coverageRate: number; totalBudget: number; paidAmount: number; executionRate: number; pendingDecisions: number; highRisk: number; ciac: number } }
interface Store extends DecisionSnapshot { idempotency: Map<string, { success: boolean; code: string; message: string }> }
function createStore(): Store { const departments: DepartmentPerformance[] = [
 { id: "dept-agri", name: "农学院", applications: 986, supported: 742, coverageRate: 75.3, budget: 3260000, paid: 2460000, executionRate: 75.5, ciac: .18, highRisk: 7, overdue: 2 },
 { id: "dept-econ", name: "经济管理学院", applications: 1148, supported: 806, coverageRate: 70.2, budget: 3820000, paid: 2780000, executionRate: 72.8, ciac: .24, highRisk: 12, overdue: 5 },
 { id: "dept-it", name: "信息科学与技术学院", applications: 1260, supported: 874, coverageRate: 69.4, budget: 4160000, paid: 2960000, executionRate: 71.2, ciac: .29, highRisk: 18, overdue: 9 },
 { id: "dept-animal", name: "动物科技学院", applications: 842, supported: 638, coverageRate: 75.8, budget: 2840000, paid: 2240000, executionRate: 78.9, ciac: .16, highRisk: 6, overdue: 1 },
 { id: "dept-ocean", name: "海洋学院", applications: 714, supported: 512, coverageRate: 71.7, budget: 2320000, paid: 1680000, executionRate: 72.4, ciac: .21, highRisk: 9, overdue: 4 },
 ]; return { departments,
 exceptions: [
  { id: "exc-001", caseNo: "EX202608-001", type: "超标准发放", title: "突发重大疾病专项补助超标准申请", department: "信息科学与技术学院", studentCode: "信息·24***07", requestedAmount: 12000, standardAmount: 6000, reason: "家庭主要劳动力突发重大疾病，已产生高额自付医疗支出。", evidence: ["医院诊断与费用清单", "家庭经济复核报告", "院系会议纪要"], aiRisk: "中", aiSuggestion: "证据链完整，金额超过常规上限100%；建议核验是否与社会救助重复后提交例外审批。", requiredRole: "FUND_LEADER", status: "pending", version: 2, submittedAt: "2026-08-03 08:36" },
  { id: "exc-002", caseNo: "EX202608-002", type: "破格认定", title: "家庭收入边界学生破格认定", department: "经济管理学院", studentCode: "经管·23***18", requestedAmount: 3000, standardAmount: 3000, reason: "收入略高于阈值，但家庭长期照护支出显著。", evidence: ["收入核验", "照护支出凭证", "民主评议记录"], aiRisk: "低", aiSuggestion: "规则分与民主评议一致，特殊负担证据充分；可在政策例外条款下审议。", requiredRole: "FUND_LEADER", status: "pending", version: 1, submittedAt: "2026-08-03 09:02" },
  { id: "exc-003", caseNo: "EX202608-003", type: "申诉复核", title: "困难等级申诉复核", department: "农学院", studentCode: "农学·24***22", requestedAmount: 4000, standardAmount: 4000, reason: "学生补充提交家庭成员失业证明。", evidence: ["申诉书", "失业证明", "原认定快照"], aiRisk: "中", aiSuggestion: "新证据发生于原认定后，建议重新核验时间有效性并保留原决策快照。", requiredRole: "FUND_LEADER", status: "pending", version: 3, submittedAt: "2026-08-02 16:18" },
  { id: "exc-004", caseNo: "EM202608-001", type: "紧急通道", title: "灾害受损家庭紧急先行救助", department: "海洋学院", studentCode: "海洋·22***26", requestedAmount: 20000, standardAmount: 8000, reason: "家庭所在地遭受洪涝灾害，基本生活与学习中断。", evidence: ["属地灾情证明", "辅导员核实记录", "院系紧急上报"], aiRisk: "高", aiSuggestion: "金额与时效均达到重大事项阈值；建议先行救助不超过8000元，其余部分走校级重大事项终审。", requiredRole: "SCHOOL_LEADER", status: "pending", version: 1, submittedAt: "2026-08-03 09:28" },
  { id: "exc-005", caseNo: "EX202607-026", type: "超标准发放", title: "就业过渡专项补助", department: "动物科技学院", studentCode: "动科·22***09", requestedAmount: 6000, standardAmount: 4000, reason: "基层就业过渡期交通住宿支出。", evidence: ["就业协议", "支出测算", "院系意见"], aiRisk: "低", aiSuggestion: "符合基层就业专项支持方向。", requiredRole: "FUND_LEADER", status: "approved", version: 4, submittedAt: "2026-07-29 14:10" },
 ],
 scenarios: [{ id: "scenario-base", name: "2026年度基线方案", project: "全校资助预算", deltaAmount: 0, baselineCoverage: 71.8, predictedCoverage: 71.8, baselineExecution: 73.4, predictedExecution: 73.4, additionalStudents: 0, riskNote: "按当前政策和申请趋势测算。", createdBy: "系统基线", createdAt: "2026-08-01 00:00" }],
 policyEffects: [
  { id: "effect-001", policy: "国家助学金分档标准优化", year: "2025-2026", target: "困难学生精准覆盖", coverageChange: 3.6, completionRate: 98.2, outcomeGain: 8.4, equityChange: -0.04, evidenceLevel: "高", recommendation: "保留分档机制，进一步统一院系特殊负担证明口径。" },
  { id: "effect-002", policy: "校内勤工助学岗位扩容", year: "2025-2026", target: "发展型资助", coverageChange: 2.1, completionRate: 91.4, outcomeGain: 11.2, equityChange: -0.02, evidenceLevel: "中", recommendation: "增加专业实践型岗位，减少低技能重复岗位。" },
  { id: "effect-003", policy: "临时困难绿色通道", year: "2025-2026", target: "突发困难响应", coverageChange: .8, completionRate: 96.7, outcomeGain: 6.3, equityChange: -0.01, evidenceLevel: "高", recommendation: "维持6小时响应目标，补齐灾害场景标准证据清单。" },
 ],
 briefs: [{ id: "brief-001", title: "2026年春季学期资助工作校长办公会简报", period: "2026春季", generatedAt: "2026-08-02 17:30", status: "draft", sections: ["全校资助覆盖与资金执行", "院系公平性与CIAC", "重大风险和例外事项", "资助育人成效", "下阶段政策建议"] }],
 indicators: { supportedStudents: departments.reduce((sum,item)=>sum+item.supported,0), coverageRate: 71.8, totalBudget: departments.reduce((sum,item)=>sum+item.budget,0), paidAmount: departments.reduce((sum,item)=>sum+item.paid,0), executionRate: 73.4, pendingDecisions: 4, highRisk: departments.reduce((sum,item)=>sum+item.highRisk,0), ciac: .22 }, idempotency: new Map() }; }
type Root = typeof globalThis & { __jhxtDecisionCenter?: Store }; const root = globalThis as Root; const store = root.__jhxtDecisionCenter ?? createStore(); root.__jhxtDecisionCenter = store;
export function getDecisionSnapshot(actor: ActorContext) { if (!["SCHOOL_LEADER", "FUND_LEADER"].includes(actor.role)) return null; const scenario = actor.role === "SCHOOL_LEADER" ? getHardshipVideoLeaderApprovalProjection() : null; const baseExceptions = actor.role === "SCHOOL_LEADER" ? store.exceptions : store.exceptions.filter(item => item.requiredRole === "FUND_LEADER"); const exceptions: ExceptionCase[] = [...(scenario ? [scenario] : []), ...baseExceptions]; return { departments: store.departments.map(item => ({ ...item })), exceptions: exceptions.map(item => ({ ...item, evidence: [...item.evidence] })), scenarios: store.scenarios.map(item => ({ ...item })), policyEffects: store.policyEffects.map(item => ({ ...item })), briefs: store.briefs.map(item => ({ ...item, sections: [...item.sections] })), indicators: { ...store.indicators, pendingDecisions: exceptions.filter(item => item.status === "pending").length } }; }
export type DecisionAction = { action: "decide_exception"; caseId: string; expectedVersion: number; decision: "approved" | "rejected"; comment: string; humanConfirmed: boolean } | { action: "run_budget_scenario"; project: string; deltaAmount: number; comment: string; humanConfirmed: boolean };
export function processDecisionAction(actor: ActorContext, input: DecisionAction, key: string) { if (!["SCHOOL_LEADER", "FUND_LEADER"].includes(actor.role)) return { success: false, code: "ROLE_DENIED", message: "当前岗位无决策中心写权限。" }; if (!key) return { success: false, code: "IDEMPOTENCY_REQUIRED", message: "缺少幂等键。" }; if (!input.humanConfirmed) return { success: false, code: "CONFIRMATION_REQUIRED", message: "决策操作必须由本人明确确认。" }; if (input.comment.trim().length < 4) return { success: false, code: "COMMENT_REQUIRED", message: "请填写至少4个字的决策依据。" }; const scope = `${actor.userId}:${key}`; const replay = store.idempotency.get(scope); if (replay) return replay; let message = "决策状态已更新";
 if (input.action === "decide_exception") { const scenario = getHardshipVideoLeaderApprovalProjection(); if (scenario?.id === input.caseId) return { success: false, code: "SCENARIO_WORKFLOW_REQUIRED", message: "视频场景审批必须在多Agent协作人工闸门中完成，避免决策中心与场景状态分叉。" }; const item = store.exceptions.find(row => row.id === input.caseId); if (!item) return { success: false, code: "NOT_FOUND", message: "例外事项不存在。" }; if (item.requiredRole !== actor.role) return { success: false, code: "ROLE_DENIED", message: `该事项必须由 ${item.requiredRole} 岗位终审。` }; if (item.version !== input.expectedVersion) return { success: false, code: "VERSION_CONFLICT", message: "事项已更新，请刷新后重试。" }; if (item.status !== "pending") return { success: false, code: "ACTION_DENIED", message: "事项已完成裁定。" }; item.status = input.decision; item.version += 1; message = `${item.caseNo} 已${input.decision === "approved" ? "批准" : "驳回"}，原始证据与AI建议快照已冻结`;
 } else { if (actor.role !== "SCHOOL_LEADER") return { success: false, code: "ROLE_DENIED", message: "预算情景模拟仅向校领导开放。" }; if (!Number.isFinite(input.deltaAmount) || Math.abs(input.deltaAmount) > 5000000) return { success: false, code: "VALIDATION_FAILED", message: "单次模拟调整金额必须在±500万元以内。" }; const additionalStudents = Math.round(input.deltaAmount / 3600); const predictedCoverage = Math.max(0, Math.min(100, store.indicators.coverageRate + additionalStudents / 68.42)); const pressure = input.deltaAmount > 0 ? input.deltaAmount / store.indicators.totalBudget * 12 : input.deltaAmount / store.indicators.totalBudget * 4; const scenario: BudgetScenario = { id: `scenario-${Date.now()}`, name: `${input.project}预算调整情景`, project: input.project, deltaAmount: input.deltaAmount, baselineCoverage: store.indicators.coverageRate, predictedCoverage: Number(predictedCoverage.toFixed(1)), baselineExecution: store.indicators.executionRate, predictedExecution: Number(Math.max(0, Math.min(100, store.indicators.executionRate - pressure)).toFixed(1)), additionalStudents, riskNote: input.deltaAmount > 0 ? "覆盖率提升，但需核实资金来源和后续年度可持续性。" : "资金压减可能增加边界困难学生遗漏风险。", createdBy: actor.userId, createdAt: new Date().toLocaleString("zh-CN", { hour12: false }) }; store.scenarios.unshift(scenario); message = `预算情景已完成：预计覆盖学生${additionalStudents >= 0 ? "增加" : "减少"}${Math.abs(additionalStudents)}人，覆盖率变为${scenario.predictedCoverage}%`;
 }
 store.indicators.pendingDecisions = store.exceptions.filter(item => item.status === "pending").length; const result = { success: true, code: "ACTION_COMPLETED", message }; store.idempotency.set(scope, result); writeAuditSnapshot({ taskId: `decision-${Date.now()}`, actorId: actor.userId, actorRole: actor.role, action: `decision:${input.action}`, outcome: "success", evidenceSummary: `${message}；人工依据：${input.comment.slice(0, 120)}` }); return result; }
