import { randomUUID } from "node:crypto";
import type { ActorContext } from "@/lib/platform/authorization";
import { writeAuditSnapshot } from "@/lib/platform/demo-store";
import { getHardshipVideoFinanceTaskProjection } from "@/lib/platform/hardship-video-review-store";
import { getHardshipVideoFinanceProjection, getHardshipVideoFinanceTaskOverlay } from "@/lib/platform/hardship-video-disbursement-store";
export interface BudgetItem { id: string; project: string; budget: number; occupied: number; paid: number; adjustment: number; source: string; executionRate: number; risk: "normal" | "attention" }
export interface FinanceBatch { id: string; batchNo: string; project: string; students: number; amount: number; validAccounts: number; invalidAccounts: number; duplicateRecords: number; status: "draft" | "blocked" | "validated" | "double_confirmed" | "sent" | "partially_failed" | "completed"; confirmations: string[]; bankFileHash?: string; version: number; createdAt: string }
export interface ReconciliationItem { id: string; batchNo: string; expectedCount: number; actualCount: number; expectedAmount: number; actualAmount: number; difference: number; reason: string; status: "matched" | "exception" | "resolved"; version: number }
export interface VoucherItem { id: string; voucherNo: string; batchNo: string; debit: string; credit: string; amount: number; attachments: number; status: "draft" | "reviewed" | "archived"; version: number }
export interface FinanceRisk { id: string; level: "high" | "medium" | "low"; type: string; target: string; description: string; control: string; status: "open" | "controlled" }
export interface FinanceScenarioTask { id:string;title:string;applicationId:string;project:string;studentCode:string;amount:number;requiredRole:"FINANCE";status:"pending"|"completed";dueAt:string;checks:string[];description:string;version:number;completedAt?:string;scenarioId:string;externalActionRoute:string;createdAt:string }
export interface FinanceSnapshot { tasks: FinanceScenarioTask[]; budgets: BudgetItem[]; batches: FinanceBatch[]; reconciliations: ReconciliationItem[]; vouchers: VoucherItem[]; risks: FinanceRisk[]; indicators: { totalBudget: number; occupied: number; paid: number; executionRate: number; pendingAmount: number; exceptionCount: number } }
interface Store extends FinanceSnapshot { idempotency: Map<string, { success: boolean; code: string; message: string }> }
function createStore(): Store { const budgets: BudgetItem[] = [
 { id: "budget-001", project: "国家助学金", budget: 12800000, occupied: 10560000, paid: 7680000, adjustment: 0, source: "中央及省级财政", executionRate: 60, risk: "normal" },
 { id: "budget-002", project: "国家励志奖学金", budget: 4860000, occupied: 4860000, paid: 0, adjustment: 0, source: "中央财政", executionRate: 0, risk: "normal" },
 { id: "budget-003", project: "校内勤工助学", budget: 3200000, occupied: 2780000, paid: 1960000, adjustment: 180000, source: "事业收入提取", executionRate: 61.3, risk: "attention" },
 { id: "budget-004", project: "临时困难补助", budget: 1680000, occupied: 940000, paid: 826000, adjustment: -180000, source: "校内专项", executionRate: 49.2, risk: "normal" },
 ]; return { tasks: [], budgets,
 batches: [
  { id: "batch-001", batchNo: "JF202608-001", project: "国家助学金（春季补发）", students: 386, amount: 772000, validAccounts: 383, invalidAccounts: 3, duplicateRecords: 0, status: "blocked", confirmations: [], version: 2, createdAt: "2026-08-03 08:42" },
  { id: "batch-002", batchNo: "JF202608-002", project: "临时困难补助", students: 84, amount: 252000, validAccounts: 84, invalidAccounts: 0, duplicateRecords: 0, status: "validated", confirmations: [], version: 3, createdAt: "2026-08-03 09:10" },
  { id: "batch-003", batchNo: "JF202607-018", project: "校内勤工助学（7月）", students: 612, amount: 734400, validAccounts: 612, invalidAccounts: 0, duplicateRecords: 0, status: "partially_failed", confirmations: ["demo-finance", "finance-reviewer-002"], bankFileHash: "SHA256:9b77…28af", version: 6, createdAt: "2026-07-31 16:20" },
  { id: "batch-004", batchNo: "JF202607-015", project: "国家助学金", students: 2560, amount: 5120000, validAccounts: 2560, invalidAccounts: 0, duplicateRecords: 0, status: "completed", confirmations: ["demo-finance", "finance-reviewer-002"], bankFileHash: "SHA256:6ca1…09de", version: 8, createdAt: "2026-07-25 14:35" },
 ],
 reconciliations: [
  { id: "rec-001", batchNo: "JF202607-015", expectedCount: 2560, actualCount: 2560, expectedAmount: 5120000, actualAmount: 5120000, difference: 0, reason: "应发与实发一致", status: "matched", version: 2 },
  { id: "rec-002", batchNo: "JF202607-018", expectedCount: 612, actualCount: 607, expectedAmount: 734400, actualAmount: 728400, difference: -6000, reason: "5个账户状态异常，银行退票", status: "exception", version: 3 },
  { id: "rec-003", batchNo: "JF202607-012", expectedCount: 94, actualCount: 94, expectedAmount: 282000, actualAmount: 282000, difference: 0, reason: "差异已核销", status: "resolved", version: 4 },
 ],
 vouchers: [
  { id: "voucher-001", voucherNo: "记-202607-0368", batchNo: "JF202607-015", debit: "学生资助支出/国家助学金", credit: "银行存款", amount: 5120000, attachments: 6, status: "archived", version: 4 },
  { id: "voucher-002", voucherNo: "草稿-202607-0412", batchNo: "JF202607-018", debit: "学生资助支出/勤工助学", credit: "银行存款", amount: 728400, attachments: 4, status: "draft", version: 1 },
 ],
 risks: [
  { id: "risk-f-001", level: "high", type: "发放账户异常", target: "JF202608-001", description: "3个收款账户未通过银行四要素校验。", control: "阻断生成银行文件，退回资助中心补正。", status: "open" },
  { id: "risk-f-002", level: "medium", type: "预算执行偏差", target: "校内勤工助学", description: "执行进度较时间进度偏低8.6个百分点。", control: "核查岗位结算延迟并在月度调度会上说明。", status: "open" },
  { id: "risk-f-003", level: "low", type: "凭证归档", target: "JF202607-018", description: "回盘差异尚未核销，凭证只能保留草稿。", control: "完成失败重发及差异处置后归档。", status: "controlled" },
 ],
 indicators: { totalBudget: budgets.reduce((s, item) => s + item.budget, 0), occupied: budgets.reduce((s, item) => s + item.occupied, 0), paid: budgets.reduce((s, item) => s + item.paid, 0), executionRate: 45.4, pendingAmount: 1024000, exceptionCount: 2 }, idempotency: new Map() }; }
type Root = typeof globalThis & { __jhxtFinance?: Store }; const root = globalThis as Root; const store = root.__jhxtFinance ?? createStore(); root.__jhxtFinance = store;
function canRead(actor: ActorContext) { return ["FINANCE", "FUND_LEADER", "SCHOOL_LEADER", "AUDITOR"].includes(actor.role); }
export function getFinanceSnapshot(actor: ActorContext) {
 if (!canRead(actor)) return null;
 const scenarioTask = getHardshipVideoFinanceTaskProjection();
 const taskOverlay = scenarioTask ? getHardshipVideoFinanceTaskOverlay(scenarioTask.id) : null;
 const scenario = getHardshipVideoFinanceProjection();
 const tasks: FinanceScenarioTask[] = scenarioTask ? [{ ...scenarioTask, ...(taskOverlay ?? {}) } as FinanceScenarioTask] : [];
 const scenarioBatch: FinanceBatch[] = scenario?.batch ? [{ id: scenario.batch.id, batchNo: scenario.batch.batchNo, project: scenario.batch.project, students: scenario.batch.students, amount: scenario.batch.amount, validAccounts: scenario.batch.validAccounts, invalidAccounts: scenario.batch.invalidAccounts, duplicateRecords: scenario.batch.duplicateRecords, status: scenario.batch.status, confirmations: scenario.batch.confirmations.map(item => item.actorId), bankFileHash: scenario.batch.bankFileHash, version: scenario.batch.version, createdAt: scenario.batch.createdAt }] : [];
 const scenarioReconciliation: ReconciliationItem[] = scenario?.reconciliation ? [{ id: scenario.reconciliation.id, batchNo: scenario.reconciliation.batchNo, expectedCount: scenario.reconciliation.expectedCount, actualCount: scenario.reconciliation.actualCount, expectedAmount: scenario.reconciliation.expectedAmount, actualAmount: scenario.reconciliation.actualAmount, difference: scenario.reconciliation.difference, reason: scenario.reconciliation.reason, status: scenario.reconciliation.result, version: scenario.reconciliation.version }] : [];
 const scenarioVoucher: VoucherItem[] = scenario?.voucher ? [{ id: scenario.voucher.id, voucherNo: scenario.voucher.voucherNo, batchNo: scenario.voucher.batchNo, debit: scenario.voucher.debit, credit: scenario.voucher.credit, amount: scenario.voucher.amount, attachments: scenario.voucher.attachments, status: scenario.voucher.status, version: scenario.voucher.version }] : [];
 const scenarioPaid = scenario?.phase === "completed" ? (scenario.batch?.amount ?? 0) : 0;
 const scenarioOccupied = scenario?.batch ? scenario.batch.amount : 0;
 const budgets = store.budgets.map(item => item.id === "budget-004" ? { ...item, occupied: item.occupied + scenarioOccupied, paid: item.paid + scenarioPaid, executionRate: Number(((item.paid + scenarioPaid) / item.budget * 100).toFixed(1)) } : { ...item });
 const paid = budgets.reduce((sum, item) => sum + item.paid, 0);
 return { tasks, budgets, batches: [...scenarioBatch, ...store.batches.map(item => ({ ...item, confirmations: [...item.confirmations] }))], reconciliations: [...scenarioReconciliation, ...store.reconciliations.map(item => ({ ...item }))], vouchers: [...scenarioVoucher, ...store.vouchers.map(item => ({ ...item }))], risks: store.risks.map(item => ({ ...item })), indicators: { ...store.indicators, occupied: budgets.reduce((sum, item) => sum + item.occupied, 0), paid, executionRate: Number((paid / store.indicators.totalBudget * 100).toFixed(1)), pendingAmount: store.indicators.pendingAmount + (scenario?.batch && scenario.phase !== "completed" ? scenario.batch.amount : 0), exceptionCount: store.indicators.exceptionCount + (scenario?.reconciliation && scenario.reconciliation.result !== "matched" ? 1 : 0) } };
}
export type FinanceAction = { action: "validate_batch"; batchId: string; expectedVersion: number; note: string } | { action: "double_confirm_batch"; batchId: string; expectedVersion: number; secondApproverId: string; humanConfirmed: boolean; note: string } | { action: "resolve_reconciliation"; reconciliationId: string; expectedVersion: number; resolution: string; note: string } | { action: "create_voucher"; batchId: string; expectedVersion: number; note: string };
export function processFinanceAction(actor: ActorContext, input: FinanceAction, key: string) { if (actor.role !== "FINANCE") return { success: false, code: "ROLE_DENIED", message: "仅校级财务可执行资金写操作。" }; if (!key) return { success: false, code: "IDEMPOTENCY_REQUIRED", message: "缺少幂等键。" }; if (input.note.trim().length < 4) return { success: false, code: "NOTE_REQUIRED", message: "请填写业务依据。" }; const scope = `${actor.userId}:${key}`; const replay = store.idempotency.get(scope); if (replay) return replay; let message = "财务状态已更新";
 if (input.action === "validate_batch") { const batch = store.batches.find(item => item.id === input.batchId); if (!batch) return { success: false, code: "NOT_FOUND", message: "发放批次不存在。" }; if (batch.version !== input.expectedVersion) return { success: false, code: "VERSION_CONFLICT", message: "批次已更新，请刷新后重试。" }; const valid = batch.invalidAccounts === 0 && batch.duplicateRecords === 0 && batch.validAccounts === batch.students && batch.amount > 0; batch.status = valid ? "validated" : "blocked"; batch.version += 1; message = valid ? `${batch.batchNo} 通过金额、账号与重复记录校验` : `${batch.batchNo} 未通过确定性校验，已保持阻断`;
 } else if (input.action === "double_confirm_batch") { const batch = store.batches.find(item => item.id === input.batchId); if (!batch) return { success: false, code: "NOT_FOUND", message: "发放批次不存在。" }; if (batch.version !== input.expectedVersion) return { success: false, code: "VERSION_CONFLICT", message: "批次已更新，请刷新后重试。" }; if (batch.status !== "validated") return { success: false, code: "PRECONDITION_FAILED", message: "批次必须先通过确定性校验。" }; if (!input.humanConfirmed) return { success: false, code: "CONFIRMATION_REQUIRED", message: "资金发放属于L4操作，必须人工确认。" }; if (!input.secondApproverId || input.secondApproverId === actor.userId) return { success: false, code: "DUAL_CONTROL_REQUIRED", message: "复核人必须与制单人不同。" }; batch.confirmations = [actor.userId, input.secondApproverId]; batch.status = "double_confirmed"; batch.bankFileHash = `SHA256:${randomUUID().replaceAll("-", "").slice(0, 12)}…`; batch.version += 1; message = `${batch.batchNo} 已完成双人复核并生成签名银行文件`;
 } else if (input.action === "resolve_reconciliation") { const item = store.reconciliations.find(row => row.id === input.reconciliationId); if (!item) return { success: false, code: "NOT_FOUND", message: "对账记录不存在。" }; if (item.version !== input.expectedVersion) return { success: false, code: "VERSION_CONFLICT", message: "对账记录已更新，请刷新后重试。" }; if (input.resolution.trim().length < 4) return { success: false, code: "RESOLUTION_REQUIRED", message: "请填写差异处置结果。" }; item.status = "resolved"; item.reason = input.resolution.trim(); item.version += 1; store.indicators.exceptionCount = store.reconciliations.filter(row => row.status === "exception").length; message = `${item.batchNo} 的对账差异已人工核销`;
 } else { const batch = store.batches.find(item => item.id === input.batchId); if (!batch) return { success: false, code: "NOT_FOUND", message: "发放批次不存在。" }; if (batch.version !== input.expectedVersion) return { success: false, code: "VERSION_CONFLICT", message: "批次已更新，请刷新后重试。" }; if (!batch.bankFileHash || !["partially_failed", "completed", "double_confirmed"].includes(batch.status)) return { success: false, code: "PRECONDITION_FAILED", message: "尚未完成双确认或银行回盘，不能生成凭证。" }; if (store.vouchers.some(item => item.batchNo === batch.batchNo)) return { success: false, code: "DUPLICATE_VOUCHER", message: "该批次已存在凭证，禁止重复生成。" }; store.vouchers.unshift({ id: `voucher-${Date.now()}`, voucherNo: `草稿-${new Date().getFullYear()}${String(new Date().getMonth()+1).padStart(2,"0")}-${String(store.vouchers.length+413).padStart(4,"0")}`, batchNo: batch.batchNo, debit: `学生资助支出/${batch.project}`, credit: "银行存款", amount: batch.amount, attachments: 3, status: "draft", version: 1 }); message = `${batch.batchNo} 的会计凭证草稿已生成`;
 }
 const result = { success: true, code: "ACTION_COMPLETED", message }; store.idempotency.set(scope, result); writeAuditSnapshot({ taskId: `finance-${Date.now()}`, actorId: actor.userId, actorRole: actor.role, action: `finance:${input.action}`, outcome: "success", evidenceSummary: `${message}；人工依据：${input.note.slice(0, 120)}` }); return result; }

