import type { ActorContext } from "@/lib/platform/authorization";
import { writeAuditSnapshot } from "@/lib/platform/demo-store";
import { getHardshipVideoCounselorTaskProjection, getHardshipVideoStudentCaseProjection } from "@/lib/platform/hardship-video-business-store";
import { listHardshipVideoReviewTasks } from "@/lib/platform/hardship-video-review-store";
export type FrontlineRole = "FUND_ADMIN" | "DEPT_ADMIN" | "COUNSELOR";
export interface FrontlineTask { id: string; title: string; type: string; assignedRole: FrontlineRole; departmentId?: string; classId?: string; scope: string; studentCount: number; dueAt: string; priority: "high" | "medium" | "normal"; status: "pending" | "processing" | "completed"; description: string; version: number; scenarioId?: string; applicationId?: string; externalActionRoute?: string }
export interface StudentCaseRow { id: string; studentCode: string; college: string; departmentId: string; className: string; classId: string; project: string; materialCompleteness: number; status: string; riskFlags: string[]; lastContact: string; aidHistory: string; followUp: string }
export interface QuotaPlan { id: string; project: string; totalQuota: number; allocatedQuota: number; rows: Array<{ departmentId: string; department: string; applications: number; difficultyStudents: number; currentQuota: number; proposedQuota: number; ciac: number }>; status: "draft" | "published"; version: number }
export interface InterviewRecord { id: string; studentCode: string; classId: string; template: string; summary: string; keyPoints: string[]; followUpDate: string; signature: "pending" | "signed"; status: "draft" | "completed"; version: number }
export interface NotificationBatch { id: string; name: string; assignedRole: FrontlineRole; departmentId?: string; classId?: string; channel: "站内信" | "短信+站内信"; recipients: number; template: string; status: "draft" | "sent"; version: number; sentAt?: string }
export interface ArchiveBatch { id: string; departmentId: string; department: string; period: string; applications: number; evidenceCompleteness: number; signedDocuments: number; totalDocuments: number; status: "preparing" | "ready" | "submitted"; version: number }
export interface FrontlineSnapshot { tasks: FrontlineTask[]; students: StudentCaseRow[]; quotaPlans: QuotaPlan[]; interviews: InterviewRecord[]; notifications: NotificationBatch[]; archives: ArchiveBatch[]; indicators: { pendingTasks: number; students: number; materialIssues: number; highRisk: number; overdue: number; archiveReadiness: number } }
interface Store { tasks: FrontlineTask[]; students: StudentCaseRow[]; quotaPlans: QuotaPlan[]; interviews: InterviewRecord[]; notifications: NotificationBatch[]; archives: ArchiveBatch[]; idempotency: Map<string, { success: boolean; code: string; message: string }> }
function createStore(): Store { return {
 tasks: [
  { id: "task-fa-001", title: "国家助学金校级复审", type: "学校复审", assignedRole: "FUND_ADMIN", scope: "全校", studentCount: 286, dueAt: "2026-08-04 17:00", priority: "high", status: "processing", description: "复核院系提交名单、异常标记与名额边界。", version: 2 },
  { id: "task-fa-002", title: "秋季学期名额分配方案", type: "名额管理", assignedRole: "FUND_ADMIN", scope: "全校", studentCount: 2680, dueAt: "2026-08-06 12:00", priority: "medium", status: "pending", description: "综合申请量、困难生数量与CIAC形成院系名额方案。", version: 1 },
  { id: "task-dept-001", title: "本院材料复核与补正汇总", type: "材料复核", assignedRole: "DEPT_ADMIN", departmentId: "dept-agri", scope: "农学院", studentCount: 38, dueAt: "2026-08-04 12:00", priority: "high", status: "processing", description: "核验材料有效期，汇总需辅导员补正的申请。", version: 3 },
  { id: "task-dept-002", title: "院系公示名单复核", type: "院系公示", assignedRole: "DEPT_ADMIN", departmentId: "dept-agri", scope: "农学院", studentCount: 126, dueAt: "2026-08-05 10:00", priority: "medium", status: "pending", description: "检查公示脱敏字段与异议受理联系方式。", version: 1 },
  { id: "task-co-001", title: "班级申请材料初审", type: "材料初审", assignedRole: "COUNSELOR", departmentId: "dept-agri", classId: "class-agri-01", scope: "农学2401班", studentCount: 12, dueAt: "2026-08-03 18:00", priority: "high", status: "processing", description: "完成材料完整性检查并形成初审意见。", version: 4 },
  { id: "task-co-002", title: "民主评议组织与电子签名", type: "民主评议", assignedRole: "COUNSELOR", departmentId: "dept-agri", classId: "class-agri-01", scope: "农学2401班", studentCount: 8, dueAt: "2026-08-05 17:00", priority: "medium", status: "pending", description: "组织评议、录入结果并完成参评人员电子签名。", version: 2 },
 ],
 students: [
  { id: "stu-case-001", studentCode: "农学·24***01", college: "农学院", departmentId: "dept-agri", className: "农学2401班", classId: "class-agri-01", project: "国家助学金", materialCompleteness: 100, status: "待辅导员初审", riskFlags: [], lastContact: "2026-07-28", aidHistory: "2025年国家助学金", followUp: "学业伙伴计划跟进" },
  { id: "stu-case-002", studentCode: "农学·24***06", college: "农学院", departmentId: "dept-agri", className: "农学2401班", classId: "class-agri-01", project: "临时困难补助", materialCompleteness: 75, status: "待补正", riskFlags: ["收入证明已过期"], lastContact: "2026-08-02", aidHistory: "首次申请", followUp: "8月4日前补交证明" },
  { id: "stu-case-003", studentCode: "农学·24***12", college: "农学院", departmentId: "dept-agri", className: "农学2401班", classId: "class-agri-01", project: "国家助学金", materialCompleteness: 92, status: "待民主评议", riskFlags: ["家庭人口信息待核验"], lastContact: "2026-08-01", aidHistory: "2025年校内补助", followUp: "安排谈心谈话" },
  { id: "stu-case-004", studentCode: "农学·23***28", college: "农学院", departmentId: "dept-agri", className: "农学2302班", classId: "class-agri-02", project: "国家励志奖学金", materialCompleteness: 100, status: "待院系复核", riskFlags: [], lastContact: "2026-07-30", aidHistory: "2024-2025国家助学金", followUp: "核验成绩排名" },
  { id: "stu-case-005", studentCode: "经管·23***18", college: "经济管理学院", departmentId: "dept-econ", className: "金融2301班", classId: "class-finance-01", project: "勤工助学", materialCompleteness: 88, status: "待院系复核", riskFlags: ["岗位工时波动"], lastContact: "2026-08-01", aidHistory: "勤工助学在岗", followUp: "职业发展跟踪" },
 ],
 quotaPlans: [{ id: "quota-001", project: "2026秋季国家助学金", totalQuota: 2680, allocatedQuota: 2680, rows: [
  { departmentId: "dept-agri", department: "农学院", applications: 986, difficultyStudents: 742, currentQuota: 520, proposedQuota: 536, ciac: .18 },
  { departmentId: "dept-econ", department: "经济管理学院", applications: 1148, difficultyStudents: 806, currentQuota: 566, proposedQuota: 584, ciac: .24 },
  { departmentId: "dept-it", department: "信息科学与技术学院", applications: 1260, difficultyStudents: 874, currentQuota: 614, proposedQuota: 630, ciac: .29 },
  { departmentId: "dept-animal", department: "动物科技学院", applications: 842, difficultyStudents: 638, currentQuota: 448, proposedQuota: 460, ciac: .16 },
  { departmentId: "dept-ocean", department: "海洋学院", applications: 714, difficultyStudents: 512, currentQuota: 360, proposedQuota: 470, ciac: .21 },
 ], status: "draft", version: 2 }],
 interviews: [
  { id: "talk-001", studentCode: "农学·24***12", classId: "class-agri-01", template: "困难认定事实核验与支持需求", summary: "学生说明家庭近期新增照护支出，已提示补充材料并说明隐私授权范围。", keyPoints: ["核验照护支出", "关注学业压力", "说明申诉权利"], followUpDate: "2026-08-10", signature: "signed", status: "completed", version: 2 },
  { id: "talk-002", studentCode: "农学·24***06", classId: "class-agri-01", template: "材料补正指导", summary: "", keyPoints: ["说明有效期要求", "确认补正渠道", "核实临时困难"], followUpDate: "2026-08-04", signature: "pending", status: "draft", version: 1 },
 ],
 notifications: [
  { id: "notice-co-001", name: "材料补正提醒", assignedRole: "COUNSELOR", departmentId: "dept-agri", classId: "class-agri-01", channel: "短信+站内信", recipients: 6, template: "请于规定时间内登录系统补充有效证明材料，如有困难请联系辅导员。", status: "draft", version: 1 },
  { id: "notice-dept-001", name: "院系复核进度提醒", assignedRole: "DEPT_ADMIN", departmentId: "dept-agri", channel: "站内信", recipients: 4, template: "请各辅导员核对待补正清单并在截止前完成处理。", status: "sent", version: 2, sentAt: "2026-08-02 16:30" },
 ],
 archives: [
  { id: "archive-agri", departmentId: "dept-agri", department: "农学院", period: "2026春季", applications: 742, evidenceCompleteness: 98.6, signedDocuments: 728, totalDocuments: 742, status: "ready", version: 3 },
  { id: "archive-econ", departmentId: "dept-econ", department: "经济管理学院", period: "2026春季", applications: 806, evidenceCompleteness: 96.8, signedDocuments: 772, totalDocuments: 806, status: "preparing", version: 2 },
 ], idempotency: new Map() }; }
type Root = typeof globalThis & { __jhxtFrontline?: Store }; const root = globalThis as Root; const store = root.__jhxtFrontline ?? createStore(); root.__jhxtFrontline = store;
function isFrontline(actor: ActorContext): actor is ActorContext & { role: FrontlineRole } { return ["FUND_ADMIN", "DEPT_ADMIN", "COUNSELOR"].includes(actor.role); }
function inScope(actor: ActorContext, item: { departmentId?: string; classId?: string }) { if (actor.role === "FUND_ADMIN") return true; if (actor.role === "DEPT_ADMIN") return Boolean(item.departmentId && actor.departmentIds?.includes(item.departmentId)); return Boolean(item.classId && actor.classIds?.includes(item.classId)); }
export function getFrontlineSnapshot(actor: ActorContext): FrontlineSnapshot | null { if (!isFrontline(actor)) return null; const scenarioTask = getHardshipVideoCounselorTaskProjection(); const scenarioStudent = getHardshipVideoStudentCaseProjection(); const reviewTasks = actor.role === "DEPT_ADMIN" || actor.role === "FUND_ADMIN" ? listHardshipVideoReviewTasks(actor.role) : []; const allTasks: FrontlineTask[] = [...(scenarioTask ? [scenarioTask] : []), ...reviewTasks, ...store.tasks]; const allStudents: StudentCaseRow[] = scenarioStudent ? [scenarioStudent, ...store.students] : store.students; const tasks = allTasks.filter(item => item.assignedRole === actor.role && inScope(actor,item)); const students = allStudents.filter(item => inScope(actor,item)); const plans = store.quotaPlans.map(plan => ({ ...plan, rows: plan.rows.filter(row => actor.role === "FUND_ADMIN" || actor.departmentIds?.includes(row.departmentId)).map(row => ({ ...row })) })); const interviews = store.interviews.filter(item => actor.role === "COUNSELOR" && inScope(actor,item)); const notifications = store.notifications.filter(item => item.assignedRole === actor.role && inScope(actor,item)); const archives = store.archives.filter(item => actor.role === "FUND_ADMIN" || actor.departmentIds?.includes(item.departmentId)); return { tasks: tasks.map(item => ({...item})), students: students.map(item => ({...item,riskFlags:[...item.riskFlags]})), quotaPlans: plans, interviews: interviews.map(item => ({...item,keyPoints:[...item.keyPoints]})), notifications: notifications.map(item => ({...item})), archives: archives.map(item => ({...item})), indicators: { pendingTasks: tasks.filter(item=>item.status!=="completed").length, students: students.length, materialIssues: students.filter(item=>item.materialCompleteness<100).length, highRisk: students.filter(item=>item.riskFlags.length>0).length, overdue: tasks.filter(item=>item.priority==="high"&&item.status!=="completed").length, archiveReadiness: archives.length ? Number((archives.reduce((s,item)=>s+item.evidenceCompleteness,0)/archives.length).toFixed(1)) : 0 } }; }
export type FrontlineAction = { action: "complete_task"; taskId: string; expectedVersion: number; note: string; humanConfirmed: boolean } | { action: "publish_quota_plan"; planId: string; expectedVersion: number; note: string; humanConfirmed: boolean } | { action: "complete_interview"; interviewId: string; expectedVersion: number; summary: string; followUpDate: string; note: string; humanConfirmed: boolean } | { action: "send_notification"; notificationId: string; expectedVersion: number; note: string; humanConfirmed: boolean } | { action: "submit_archive"; archiveId: string; expectedVersion: number; note: string; humanConfirmed: boolean };
export function processFrontlineAction(actor: ActorContext, input: FrontlineAction, key: string) { if (!isFrontline(actor)) return { success:false,code:"ROLE_DENIED",message:"当前岗位无一线协同写权限。" }; if(!key)return{success:false,code:"IDEMPOTENCY_REQUIRED",message:"缺少幂等键。"}; if(!input.humanConfirmed)return{success:false,code:"CONFIRMATION_REQUIRED",message:"业务操作需要人工确认。"}; if(input.note.trim().length<4)return{success:false,code:"NOTE_REQUIRED",message:"请填写至少4个字的处理依据。"}; const scope=`${actor.userId}:${key}`;const replay=store.idempotency.get(scope);if(replay)return replay;let message="协同任务已更新";
 if(input.action==="complete_task"){if(input.taskId.startsWith("VIDEO-TASK-"))return{success:false,code:"SCENARIO_WORKFLOW_REQUIRED",message:"视频场景待办必须在多Agent协作人工闸门中处理。"};const item=store.tasks.find(row=>row.id===input.taskId);if(!item)return{success:false,code:"NOT_FOUND",message:"任务不存在。"};if(item.assignedRole!==actor.role||!inScope(actor,item))return{success:false,code:"SCOPE_DENIED",message:"任务不在当前岗位授权范围。"};if(item.version!==input.expectedVersion)return{success:false,code:"VERSION_CONFLICT",message:"任务已更新。"};item.status="completed";item.version+=1;message=`${item.title} 已由当前岗位确认完成`;
 }else if(input.action==="publish_quota_plan"){if(actor.role!=="FUND_ADMIN")return{success:false,code:"ROLE_DENIED",message:"仅校级资助管理员可发布名额方案。"};const item=store.quotaPlans.find(row=>row.id===input.planId);if(!item)return{success:false,code:"NOT_FOUND",message:"名额方案不存在。"};if(item.version!==input.expectedVersion)return{success:false,code:"VERSION_CONFLICT",message:"名额方案已更新。"};const sum=item.rows.reduce((s,row)=>s+row.proposedQuota,0);if(sum!==item.totalQuota)return{success:false,code:"QUOTA_MISMATCH",message:`院系拟分配${sum}个，与总名额${item.totalQuota}不一致。`};item.allocatedQuota=sum;item.status="published";item.version+=1;message=`${item.project} 名额方案已发布，各院系可见`;
 }else if(input.action==="complete_interview"){if(actor.role!=="COUNSELOR")return{success:false,code:"ROLE_DENIED",message:"仅辅导员可完成谈心谈话记录。"};const item=store.interviews.find(row=>row.id===input.interviewId);if(!item)return{success:false,code:"NOT_FOUND",message:"谈话记录不存在。"};if(!inScope(actor,item))return{success:false,code:"SCOPE_DENIED",message:"记录不在当前班级范围。"};if(item.version!==input.expectedVersion)return{success:false,code:"VERSION_CONFLICT",message:"谈话记录已更新。"};if(input.summary.trim().length<10)return{success:false,code:"SUMMARY_REQUIRED",message:"谈话纪要至少10个字。"};item.summary=input.summary.trim();item.followUpDate=input.followUpDate;item.signature="signed";item.status="completed";item.version+=1;message=`${item.studentCode} 的谈话纪要已完成并电子签名`;
 }else if(input.action==="send_notification"){const item=store.notifications.find(row=>row.id===input.notificationId);if(!item)return{success:false,code:"NOT_FOUND",message:"通知批次不存在。"};if(item.assignedRole!==actor.role||!inScope(actor,item))return{success:false,code:"SCOPE_DENIED",message:"通知不在当前岗位范围。"};if(item.version!==input.expectedVersion)return{success:false,code:"VERSION_CONFLICT",message:"通知批次已更新。"};item.status="sent";item.sentAt=new Date().toLocaleString("zh-CN",{hour12:false});item.version+=1;message=`${item.name} 已人工确认发送给${item.recipients}人`;
 }else{if(actor.role!=="DEPT_ADMIN")return{success:false,code:"ROLE_DENIED",message:"仅院系资助管理员可提交院系归档。"};const item=store.archives.find(row=>row.id===input.archiveId);if(!item)return{success:false,code:"NOT_FOUND",message:"归档批次不存在。"};if(!inScope(actor,item))return{success:false,code:"SCOPE_DENIED",message:"归档不在当前院系范围。"};if(item.version!==input.expectedVersion)return{success:false,code:"VERSION_CONFLICT",message:"归档批次已更新。"};if(item.status!=="ready"||item.evidenceCompleteness<98||item.signedDocuments<item.totalDocuments*.98)return{success:false,code:"ARCHIVE_NOT_READY",message:"证据完整度或电子签名未达到归档阈值。"};item.status="submitted";item.version+=1;message=`${item.department}${item.period}资助档案已提交学校`}
 const result={success:true,code:"ACTION_COMPLETED",message};store.idempotency.set(scope,result);writeAuditSnapshot({taskId:`frontline-${Date.now()}`,actorId:actor.userId,actorRole:actor.role,action:`frontline:${input.action}`,outcome:"success",evidenceSummary:`${message}；人工依据：${input.note.slice(0,120)}`});return result; }
