import { copyFileSync, existsSync, mkdirSync, readFileSync, renameSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type { ActorContext } from "./authorization";
import type { RoleCode } from "./roles";

export const HARDSHIP_VIDEO_REVIEW_STAGES = ["counselor", "department", "school", "leader"] as const;
export type HardshipVideoReviewStageId = (typeof HARDSHIP_VIDEO_REVIEW_STAGES)[number];
export type HardshipVideoReviewStatus = "待辅导员初审" | "待院系复核" | "待校级复审" | "待领导审批" | "待发放";
export type HardshipVideoReviewRole = "COUNSELOR" | "DEPT_ADMIN" | "FUND_ADMIN" | "SCHOOL_LEADER";
export interface HardshipVideoReviewContext { scenarioId: string; revision: number; applicationId: string; ticketId: string; projectName: string; precheckId?: string; materialIds: string[]; baselineApplicationVersion: number; baselineTicketVersion: number }
export interface HardshipVideoReviewProjection { id:string;stageId:HardshipVideoReviewStageId;sequence:4|5|6|7;applicationId:string;role:HardshipVideoReviewRole;roleName:string;decision:"approved";opinion:string;previousStatus:HardshipVideoReviewStatus;nextStatus:HardshipVideoReviewStatus;factChecks:string[];evidenceRefs:string[];agentSuggestion:string;xaiSummary:string;humanActorId:string;humanSignature:string;completedAt:string;version:1 }
export interface HardshipVideoReviewTaskProjection { id:string;title:string;type:string;assignedRole:"DEPT_ADMIN"|"FUND_ADMIN";departmentId:string;classId?:string;scope:string;studentCount:number;dueAt:string;priority:"high";status:"pending"|"completed";description:string;version:number;scenarioId:string;applicationId:string;stageId:"department"|"school";externalActionRoute:string;completedAt?:string }
export interface HardshipVideoReviewNoticeProjection { id:string;recipientId:"demo-student";applicationId:string;ticketId:string;type:"progress";title:string;content:string;channels:Array<"in_app"|"wechat_adapter">;deliveryStatus:"delivered";createdAt:string;readAt?:string;actionRoute:string;actionLabel:string;scenarioId:string }
export interface HardshipVideoLeaderApprovalProjection { id:string;caseNo:string;type:"资助审批";title:string;department:string;studentCode:string;requestedAmount:number;standardAmount:number;reason:string;evidence:string[];aiRisk:"中";aiSuggestion:string;requiredRole:"SCHOOL_LEADER";status:"pending"|"approved";version:number;submittedAt:string;scenarioId:string;applicationId:string;externalActionRoute:string }
export interface HardshipVideoFinanceTaskProjection { id:string;title:string;applicationId:string;project:string;studentCode:string;amount:number;requiredRole:"FINANCE";status:"pending";dueAt:string;checks:string[];description:string;version:1;scenarioId:string;externalActionRoute:string;createdAt:string }
export interface HardshipVideoReviewExecutionResult {success:boolean;code:string;message:string;affectedRows:number;outputs:string[]}
interface TimelineProjection {id:string;action:string;title:string;detail:string;actorId:string;actorRole:string;createdAt:string}
interface ReviewEvent {id:string;stageId:HardshipVideoReviewStageId|"reset";actorId:string;actorRole:RoleCode|"SYSTEM";title:string;detail:string;createdAt:string}
interface ReviewState { schemaVersion:1;scenarioId:string;revision:number;applicationId:string;ticketId:string;status:HardshipVideoReviewStatus;applicationVersion:number;ticketVersion:number;lastComment:string;updatedAt:string;handlerRole:"COUNSELOR"|"DEPT_ADMIN"|"FUND_ADMIN"|"SCHOOL_LEADER"|"FINANCE";ticketStatus:"queued"|"forwarded"|"closed";tasks:HardshipVideoReviewTaskProjection[];reviews:HardshipVideoReviewProjection[];notices:HardshipVideoReviewNoticeProjection[];timeline:TimelineProjection[];leaderApproval?:HardshipVideoLeaderApprovalProjection;financeTask?:HardshipVideoFinanceTaskProjection;processedKeys:Array<{scope:string;stageId:HardshipVideoReviewStageId;createdAt:string}>;events:ReviewEvent[] }
type Root=typeof globalThis&{__jhxtHardshipVideoReview?:ReviewState};const root=globalThis as Root;const file=join(process.cwd(),".runtime","hardship-video-review-business.json");
const now=()=>new Date().toISOString();const clone=<T>(v:T):T=>structuredClone(v);const rev=(n:number)=>String(n).padStart(3,"0");const plusDays=(at:string,d:number)=>new Date(new Date(at).getTime()+d*86400000).toISOString();
function initial(context:HardshipVideoReviewContext,actorId="system",at=now()):ReviewState{return{schemaVersion:1,scenarioId:context.scenarioId,revision:context.revision,applicationId:context.applicationId,ticketId:context.ticketId,status:"待辅导员初审",applicationVersion:context.baselineApplicationVersion,ticketVersion:context.baselineTicketVersion,lastComment:"材料预检完成，等待辅导员初审。",updatedAt:at,handlerRole:"COUNSELOR",ticketStatus:"queued",tasks:[],reviews:[],notices:[],timeline:[],processedKeys:[],events:[{id:`VIDEO-REVIEW-EVT-${rev(context.revision)}-RESET`,stageId:"reset",actorId,actorRole:"SYSTEM",title:"四级审核接力已就绪",detail:"辅导员、院系、校级资助中心和校领导审核投影已复位。",createdAt:at}]}}
function persist(state:ReviewState){mkdirSync(dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.tmp`;writeFileSync(tmp,`${JSON.stringify(state,null,2)}\n`,"utf8");try{renameSync(tmp,file)}catch(e){if(!(e instanceof Error)||!("code" in e)||e.code!=="EPERM")throw e;copyFileSync(tmp,file);unlinkSync(tmp)}}
function load(context?:HardshipVideoReviewContext):ReviewState|null{if(root.__jhxtHardshipVideoReview){if(context&&root.__jhxtHardshipVideoReview.revision!==context.revision)return resetHardshipVideoReview(context,"system-revision-sync");return root.__jhxtHardshipVideoReview}let state:ReviewState|null=null;if(existsSync(file))try{const p=JSON.parse(readFileSync(file,"utf8"))as ReviewState;if(p?.schemaVersion===1&&p.scenarioId)state=p}catch{state=null}if(!state&&context)state=initial(context);if(state){root.__jhxtHardshipVideoReview=state;persist(state)}return state}
export function resetHardshipVideoReview(context:HardshipVideoReviewContext,actorId:string,at=now()){const state=initial(context,actorId,at);root.__jhxtHardshipVideoReview=state;persist(state);return clone(state)}
export function clearHardshipVideoReview(actorId:string,scenarioId:string,revision:number,at=now()){const state:ReviewState={schemaVersion:1,scenarioId,revision,applicationId:"",ticketId:"",status:"待辅导员初审",applicationVersion:0,ticketVersion:0,lastComment:"等待学生申请和材料预检。",updatedAt:at,handlerRole:"COUNSELOR",ticketStatus:"queued",tasks:[],reviews:[],notices:[],timeline:[],processedKeys:[],events:[{id:`VIDEO-REVIEW-EVT-${rev(revision)}-RESET`,stageId:"reset",actorId,actorRole:"SYSTEM",title:"四级审核接力已清空",detail:"等待V3-1生成申请与受理工单。",createdAt:at}]};root.__jhxtHardshipVideoReview=state;persist(state)}
const expected:Record<HardshipVideoReviewStageId,HardshipVideoReviewRole>={counselor:"COUNSELOR",department:"DEPT_ADMIN",school:"FUND_ADMIN",leader:"SCHOOL_LEADER"};
const before:Record<HardshipVideoReviewStageId,HardshipVideoReviewStatus>={counselor:"待辅导员初审",department:"待院系复核",school:"待校级复审",leader:"待领导审批"};
const after:Record<HardshipVideoReviewStageId,HardshipVideoReviewStatus>={counselor:"待院系复核",department:"待校级复审",school:"待领导审批",leader:"待发放"};
const roleNames:Record<HardshipVideoReviewStageId,string>={counselor:"辅导员",department:"院系资助管理员",school:"校级资助中心管理员",leader:"校领导 / 管理层"};
function configs(stage:HardshipVideoReviewStageId,state:ReviewState,context:HardshipVideoReviewContext){const common=state.reviews.map(x=>x.id);return{counselor:{checks:["医疗票据原件与结构化摘要一致","突发支出时间与申请陈述一致","已完成关怀核实且未发现事实矛盾"],evidence:[context.precheckId??"",...context.materialIds],suggestion:"建议初审通过并转院系复核；持续关注学生短期生活压力。",xai:"建议基于材料预检、原件核验和谈话事实，最终初审由辅导员本人作出。"},department:{checks:["院系范围与班级归属一致","未发现同类在途重复申请","辅导员意见、材料与金额口径一致"],evidence:common,suggestion:"建议纳入本院临时困难补助上报批次并送校级复审。",xai:"建议基于组织范围、防重规则和证据链一致性，不涉及AI自动认定。"},school:{checks:["符合临时困难补助政策条款","2000元未超过5000元项目上限","三级证据和人工意见链完整"],evidence:["policy-emergency-aid-2026",...common],suggestion:"建议提交校领导审批，金额按2000元执行。",xai:"建议基于政策条款、金额确定性校验和前序人工意见，复审责任由资助中心承担。"},leader:{checks:["审批摘要与原申请金额一致","资金来源为校内临时困难补助专项","前序三岗均已人工签名且无保留意见"],evidence:[state.leaderApproval?.id??"",...common],suggestion:"建议批准并转财务执行；资金动作继续执行双人复核。",xai:"决策参谋仅聚合政策、预算与风险摘要，审批不可由Agent代替。"}}[stage]}
function addNotice(state:ReviewState,stage:HardshipVideoReviewStageId,title:string,content:string,route:string,label:string,at:string){state.notices.unshift({id:`VIDEO-PROGRESS-${stage.toUpperCase()}-${rev(state.revision)}`,recipientId:"demo-student",applicationId:state.applicationId,ticketId:state.ticketId,type:"progress",title,content,channels:["in_app","wechat_adapter"],deliveryStatus:"delivered",createdAt:at,actionRoute:route,actionLabel:label,scenarioId:state.scenarioId})}
function addTimeline(state:ReviewState,stage:HardshipVideoReviewStageId,title:string,detail:string,actor:ActorContext,at:string){state.timeline.unshift({id:`VIDEO-REVIEW-TL-${rev(state.revision)}-${stage.toUpperCase()}`,action:`${stage}_approved`,title,detail,actorId:actor.userId,actorRole:actor.role,createdAt:at});state.ticketVersion+=1}
function completeTask(state:ReviewState,stage:HardshipVideoReviewStageId,at:string){const task=state.tasks.find(x=>x.stageId===stage);if(task){task.status="completed";task.version+=1;task.completedAt=at}}
function makeTask(state:ReviewState,stage:"department"|"school",at:string):HardshipVideoReviewTaskProjection{const route=`/agent/monitor/collaboration?scenario=${state.scenarioId}`;return stage==="department"?{id:`VIDEO-TASK-DEPARTMENT-${rev(state.revision)}`,title:"临时困难补助院系复核与上报",type:"场景业务待办",assignedRole:"DEPT_ADMIN",departmentId:"dept-agri",scope:"农学院 · 单人模拟上报批次",studentCount:1,dueAt:plusDays(at,2),priority:"high",status:"pending",description:`申请${state.applicationId}已通过辅导员初审，请核对重复申请、证据一致性和院系上报口径。`,version:1,scenarioId:state.scenarioId,applicationId:state.applicationId,stageId:stage,externalActionRoute:route}:{id:`VIDEO-TASK-SCHOOL-${rev(state.revision)}`,title:"临时困难补助校级合规复审",type:"场景业务待办",assignedRole:"FUND_ADMIN",departmentId:"dept-agri",scope:"全校 · 农学院上报批次",studentCount:1,dueAt:plusDays(at,2),priority:"high",status:"pending",description:`申请${state.applicationId}已通过院系复核，请执行政策条款、金额边界和跨层级意见一致性检查。`,version:1,scenarioId:state.scenarioId,applicationId:state.applicationId,stageId:stage,externalActionRoute:route}}

export function executeHardshipVideoReviewStage(actor:ActorContext,stageId:HardshipVideoReviewStageId,context:HardshipVideoReviewContext,runId:string,key:string,humanComment:string):HardshipVideoReviewExecutionResult{
 let state=load(context);if(!state)state=resetHardshipVideoReview(context,"system-init");if(state.applicationId!==context.applicationId||state.ticketId!==context.ticketId)state=resetHardshipVideoReview(context,"system-context-sync");
 if(actor.role!==expected[stageId])return{success:false,code:"VIDEO_STAGE_ROLE_DENIED",message:`节点${stageId}必须由${expected[stageId]}执行。`,affectedRows:0,outputs:[]};
 const scope=`${actor.userId}:${runId}:${key}`;if(state.processedKeys.some(x=>x.scope===scope&&x.stageId===stageId))return{success:true,code:"IDEMPOTENT_REPLAY",message:"该审核节点已执行，本次返回持久化结果。",affectedRows:0,outputs:state.reviews.map(x=>x.id)};
 if(state.status!==before[stageId])return{success:false,code:"VIDEO_PRECONDITION_FAILED",message:`申请当前为“${state.status}”，不能执行“${before[stageId]}”节点。`,affectedRows:0,outputs:[]};
 const at=now(),c=configs(stageId,state,context),opinion=humanComment.trim();const review:HardshipVideoReviewProjection={id:`VIDEO-REVIEW-${stageId.toUpperCase()}-${rev(state.revision)}`,stageId,sequence:({counselor:4,department:5,school:6,leader:7}as const)[stageId],applicationId:state.applicationId,role:actor.role as HardshipVideoReviewRole,roleName:roleNames[stageId],decision:"approved",opinion,previousStatus:before[stageId],nextStatus:after[stageId],factChecks:c.checks,evidenceRefs:c.evidence.filter(Boolean),agentSuggestion:c.suggestion,xaiSummary:c.xai,humanActorId:actor.userId,humanSignature:`SIG-${actor.userId}-${rev(state.revision)}`,completedAt:at,version:1};
 state.reviews.push(review);state.status=after[stageId];state.applicationVersion+=1;state.lastComment=`${roleNames[stageId]}人工审核通过：${opinion}`;state.updatedAt=at;completeTask(state,stageId,at);const outputs=[review.id,state.applicationId,state.ticketId];let message="";
 if(stageId==="counselor"){const task=makeTask(state,"department",at);state.tasks.push(task);state.handlerRole="DEPT_ADMIN";state.ticketStatus="forwarded";addTimeline(state,stageId,"辅导员初审通过 → 院系复核",opinion,actor,at);addNotice(state,stageId,"辅导员初审通过，进入院系复核",`辅导员已完成人工核验并签名，申请${state.applicationId}已转农学院资助管理员。`,`/application/detail?id=${state.applicationId}`,"查看审核进度",at);outputs.push(task.id);message="辅导员初审结果已签名，申请与工单已进入院系复核。";
 }else if(stageId==="department"){const task=makeTask(state,"school",at);state.tasks.push(task);state.handlerRole="FUND_ADMIN";addTimeline(state,stageId,"院系复核通过 → 校级复审",opinion,actor,at);addNotice(state,stageId,"院系复核通过，进入校级资助中心复审",`农学院已完成汇总复核并人工签名，申请${state.applicationId}已上报校级资助中心。`,`/application/detail?id=${state.applicationId}`,"查看审核进度",at);outputs.push(task.id);message="院系复核与上报已完成，校级资助中心待办已生成。";
 }else if(stageId==="school"){state.handlerRole="SCHOOL_LEADER";state.leaderApproval={id:`VIDEO-LEADER-APPROVAL-${rev(state.revision)}`,caseNo:`LD${at.slice(0,10).replaceAll("-","")}-${rev(state.revision)}`,type:"资助审批",title:"临时困难补助校领导审批",department:"农学院",studentCode:"农学·24***01",requestedAmount:2000,standardAmount:2000,reason:"家庭成员突发重大疾病造成集中医疗支出，三级人工审核均建议按项目标准给予临时补助。",evidence:Array.from(new Set([...state.reviews.map(x=>x.id),context.precheckId??""])).filter(Boolean),aiRisk:"中",aiSuggestion:"政策条款、金额边界和三级人工意见一致；建议批准并转财务双人复核。AI不得代批。",requiredRole:"SCHOOL_LEADER",status:"pending",version:1,submittedAt:at,scenarioId:state.scenarioId,applicationId:state.applicationId,externalActionRoute:`/agent/monitor/collaboration?scenario=${state.scenarioId}`};addTimeline(state,stageId,"校级复审通过 → 校领导审批",opinion,actor,at);addNotice(state,stageId,"校级复审通过，进入校领导审批",`资助中心已完成政策与金额复审，脱敏审批任务${state.leaderApproval.id}已提交校领导。`,"/decision-center#exceptions","查看审批进度",at);outputs.push(state.leaderApproval.id);message="校级复审通过，脱敏校领导审批任务已生成。";
 }else{if(!state.leaderApproval||state.leaderApproval.status!=="pending")return{success:false,code:"VIDEO_PRECONDITION_FAILED",message:"校领导审批任务尚未生成或已处理。",affectedRows:0,outputs:[]};state.leaderApproval.status="approved";state.leaderApproval.version+=1;state.handlerRole="FINANCE";state.ticketStatus="closed";state.financeTask={id:`VIDEO-FINANCE-TASK-${rev(state.revision)}`,title:"临时困难补助发放准备与双人复核",applicationId:state.applicationId,project:context.projectName,studentCode:"2024****01",amount:2000,requiredRole:"FINANCE",status:"pending",dueAt:plusDays(at,1),checks:["预算占用与可用余额","收款账户最小字段与四要素","同批次重复发放","金额与笔数平衡","双人复核身份分离"],description:"校领导已批准；请财务执行确定性校验、双人确认并生成银行任务。",version:1,scenarioId:state.scenarioId,externalActionRoute:`/agent/monitor/collaboration?scenario=${state.scenarioId}`,createdAt:at};addTimeline(state,stageId,"校领导审批通过 → 财务发放",opinion,actor,at);addNotice(state,stageId,"校领导审批通过，进入财务发放",`校领导已完成人工审批并签名，财务任务${state.financeTask.id}已生成。资金操作仍需财务双人复核。`,"/finance#tasks","查看发放进度",at);outputs.push(state.leaderApproval.id,state.financeTask.id);message="校领导审批已冻结，申请进入待发放并生成财务任务。";}
 state.events.push({id:`VIDEO-REVIEW-EVT-${rev(state.revision)}-${stageId.toUpperCase()}`,stageId,actorId:actor.userId,actorRole:actor.role,title:`${roleNames[stageId]}人工审核通过`,detail:`${review.id}已冻结；${message}`,createdAt:at});state.processedKeys.push({scope,stageId,createdAt:at});state.processedKeys=state.processedKeys.slice(-100);persist(state);return{success:true,code:"VIDEO_BUSINESS_STAGE_COMPLETED",message,affectedRows:outputs.length,outputs};
}
export function getHardshipVideoReviewApplicationOverlay(applicationId:string){const s=load();return s&&s.applicationId===applicationId?{status:s.status,version:s.applicationVersion,updatedAt:s.updatedAt,lastComment:s.lastComment}:null}
export function getHardshipVideoReviewTicketOverlay(ticketId:string){const s=load();return s&&s.ticketId===ticketId?{status:s.ticketStatus,handlerRole:s.handlerRole,version:s.ticketVersion,updatedAt:s.updatedAt,timeline:s.timeline.map(clone)}:null}
export function listHardshipVideoReviewTasks(role?:"DEPT_ADMIN"|"FUND_ADMIN"){const s=load();return s?s.tasks.filter(x=>!role||x.assignedRole===role).map(clone):[]}
export function listHardshipVideoReviewNotices(actor:ActorContext){const s=load();return s&&actor.role==="STUDENT"&&actor.userId==="demo-student"?s.notices.map(clone):[]}
export function markHardshipVideoReviewNoticeRead(actor:ActorContext,id:string){const s=load();if(!s||actor.role!=="STUDENT"||actor.userId!=="demo-student")return null;const n=s.notices.find(x=>x.id===id);if(!n)return null;n.readAt??=now();persist(s);return clone(n)}
export function getHardshipVideoReviewStudentOverlay(applicationId:string){const s=load();if(!s||s.applicationId!==applicationId)return null;const follow:Record<HardshipVideoReviewStatus,string>={"待辅导员初审":"通过场景人工闸门完成初审","待院系复核":"等待院系资助管理员复核并形成上报意见","待校级复审":"等待校级资助中心执行政策与金额一致性复审","待领导审批":"校领导通过脱敏决策摘要完成人工审批","待发放":"等待财务双签、银行回盘与对账"};return{status:s.status,followUp:follow[s.status],lastContact:s.updatedAt.slice(0,10)}}
export function getHardshipVideoReviewProjections(applicationId:string){const s=load();return s&&s.applicationId===applicationId?s.reviews.map(clone):[]}
export function getHardshipVideoLeaderApprovalProjection(){const x=load()?.leaderApproval;return x?clone({...x,evidence:Array.from(new Set(x.evidence))}):null}
export function getHardshipVideoFinanceTaskProjection(){const x=load()?.financeTask;return x?clone(x):null}
export function getHardshipVideoReviewBusinessObjects(context?:HardshipVideoReviewContext){const s=load(context);const r=context?.revision??s?.revision??1;return[{type:"review_chain",id:`VIDEO-REVIEW-CHAIN-${rev(r)}`,label:"四级人工审核证据链",status:`${s?.reviews.length??0}/4级已确认`,route:s?.applicationId?`/application/detail?id=${s.applicationId}`:"/application/all",sensitivity:"P2",syncStatus:(s?.reviews.length===4?"synced":"pending")as"synced"|"pending"},{type:"leadership_approval",id:s?.leaderApproval?.id??"VIDEO-LEADER-PENDING",label:"校领导审批任务",status:s?.leaderApproval?.status??"尚未生成",route:"/decision-center#exceptions",sensitivity:"P1·脱敏摘要",syncStatus:(s?.leaderApproval?.status==="approved"?"synced":"pending")as"synced"|"pending"},{type:"finance_task",id:s?.financeTask?.id??"VIDEO-FINANCE-TASK-PENDING",label:"财务发放交接任务",status:s?.financeTask?.status??"尚未生成",route:"/finance#tasks",sensitivity:"P3·最小必要字段",syncStatus:(s?.financeTask?"synced":"pending")as"synced"|"pending"}]}
export function getHardshipVideoReviewStatus(){const s=load();return s?{revision:s.revision,applicationId:s.applicationId,status:s.status,applicationVersion:s.applicationVersion,ticketVersion:s.ticketVersion,handlerRole:s.handlerRole,ticketStatus:s.ticketStatus,taskIds:s.tasks.map(x=>x.id),reviews:s.reviews.map(x=>x.id),leaderApprovalId:s.leaderApproval?.id,leaderApprovalStatus:s.leaderApproval?.status,financeTaskId:s.financeTask?.id,updatedAt:s.updatedAt}:null}
